force-app/main/default/objects/AutomatedSurvey__c/AutomatedSurvey__c.object-meta.xml
<CustomObject>
    <label>Automated Survey</label>
    <nameField>
        <displayFormat>AS-{000000}</displayFormat>
        <label>Automated Survey</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Automated Surveys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AutomatedSurvey__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Automated Surveys</relationshipLabel>
    <relationshipName>Automated_Surveys</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/AutomatedSurvey__c/fields/DateResponded__c.field-meta.xml
<CustomField>
    <fullName>DateResponded__c</fullName>
    <label>Date Responded</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/SubscriptionLineItem__c.object-meta.xml
<CustomObject>
    <label>Subscription Line Item</label>
    <nameField>
        <label>Subscription Line Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SubscriptionLineItem__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>SubscriptionLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/fields/CalcMRR__c.field-meta.xml
<CustomField>
    <fullName>CalcMRR__c</fullName>
    <formula>Product__r.MRR__c *  Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Calculated MRR (EUR)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>Subscription_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/fields/Status_Active_Device__c.field-meta.xml
<CustomField>
    <fullName>Status_Active_Device__c</fullName>
    <formula>IF(
IsCurrent__c
&amp;&amp; NOT(CONTAINS(Product__r.Model__c,&quot;Discount&quot;))
&amp;&amp; (
Product__r.ProductCategory__r.ProductType__c = &quot;POS Device&quot;
||
Product__r.ProductCategory__r.ProductType__c = &quot;POS Service+Device&quot;
),1,0)</formula>
    <label>Status Active Device</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/fields/Status_Active_Service__c.field-meta.xml
<CustomField>
    <fullName>Status_Active_Service__c</fullName>
    <formula>IF(
IsCurrent__c
&amp;&amp;
NOT(CONTAINS(Product__r.Name,&quot;subsidy&quot;))
&amp;&amp; (
 Product__r.ProductCategory__r.ProductType__c  = &quot;POS Service&quot;
||
 Product__r.ProductCategory__r.ProductType__c  = &quot;POS Service+Device&quot;
),1,0)</formula>
    <label>Status Active Service</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/fields/Status_Future_Customer__c.field-meta.xml
<CustomField>
    <fullName>Status_Future_Customer__c</fullName>
    <formula>IF(EffectiveStartDate__c &gt; TODAY()
&amp;&amp;
Subscription__r.Status__c &lt;&gt; &quot;Expired&quot;
&amp;&amp;
Subscription__r.Status__c &lt;&gt; &quot;Cancelled&quot;
&amp;&amp; (
Product__r.ProductCategory__r.ProductType__c = &quot;POS Service&quot;
||
Product__r.ProductCategory__r.ProductType__c = &quot;POS Device&quot;
||
Product__r.ProductCategory__r.ProductType__c = &quot;POS Service+Device&quot;
),1,0)</formula>
    <label>Status Future Customer</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>Subscription_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CockpitController.cls
public class CockpitController {
    
    @AuraEnabled
    public static List<AutomatedSurvey__c> getNPS(String AccountId) {
        Set<String> EmailSet = new Set<String>();
        for (Contact c : [SELECT Id, Email FROM Contact WHERE AccountId = :AccountId AND Email != null]) {
            if (!c.Email.containsIgnoreCase('orderbird')) EmailSet.add(c.Email);
        }
        system.debug(json.serialize(EmailSet));
        return [
            SELECT Id, Contact__c, NPS__c, Contact__r.Email
            FROM AutomatedSurvey__c 
            WHERE NPS__c != null 
              AND DateResponded__c >= LAST_n_MONTHS:6
              AND Contact__r.Email IN :EmailSet
            ORDER BY DateResponded__c DESC
            LIMIT 3
        ];
    }
    
    @AuraEnabled
    public static List<AggregateResult> getActiveDevices(String AccountId) {
        Set<String> ProdSubSet = new Set<String>();
        List<AggregateResult> ActiveDevices = new List<AggregateResult>();
        List<AggregateResult> ARs = [
            SELECT SUM(Quantity__c) Qty, Product__r.Name Prod, Product__c ProdId, Subscription__r.Name SubName, Subscription__c
            FROM SubscriptionLineItem__c 
            WHERE 
                Subscription__r.Account__c = :AccountId 
                AND (
                    Status_Active_Device__c > 0 
                    OR Status_Active_Service__c > 0
                )
                AND Product__r.Model__c != 'DiscountFixedAmount' 
                AND Product__r.Model__c != 'DiscountPercentage' 
            GROUP BY Product__r.Name, Product__c, Subscription__r.Name, Subscription__c
            ORDER BY SUM(Quantity__c) DESC, Product__r.Name
        ];
        for (AggregateResult AR : ARs) {
            if (!ProdSubSet.contains((String)AR.get('ProdId')+(String)AR.get('SubName'))) {
                ProdSubSet.add((String)AR.get('ProdId')+(String)AR.get('SubName'));
                ActiveDevices.add(AR);
            }
        }
        return ActiveDevices;
    }
    
    @AuraEnabled
    public static Decimal getMRR(String AccountId) {
        AggregateResult[] ARs = [
            SELECT MAX(CalcMRR__c) MRR, Name
            FROM SubscriptionLineItem__c 
            WHERE 
                Subscription__r.Account__c = :AccountId 
                AND (
                    Status_Active_Device__c > 0 
                    OR Status_Active_Service__c > 0 
                    OR Status_Future_Customer__c > 0
                )
            GROUP BY Name
        ];
        Decimal MRR = 0.0;
        for (AggregateResult AR : ARs) {
            MRR += (Decimal)AR.get('MRR');
        }
        return MRR;
    }
    
}