force-app/main/default/objects/AutomatedSurvey__c/AutomatedSurvey__c.object-meta.xml
<CustomObject>
    <label>Automated Survey</label>
    <nameField>
        <displayFormat>AS-{000000}</displayFormat>
        <label>Automated Survey</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Automated Surveys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AutomatedSurvey__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Automated Surveys</relationshipLabel>
    <relationshipName>Automated_Surveys</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/classes/SurveyMonkeyTest.cls
@isTest public class SurveyMonkeyTest {

    static TestMethod void test() {
        Account a = new Account(Name='test');
        insert a;
        Contact c = new Contact(Lastname='test', AccountId=a.Id, Email='bart.collins@orderbird.com');
        insert c;
        AutomatedSurvey__c ausu = new AutomatedSurvey__c(Contact__c = c.Id);
        insert ausu;
    }
    
    static TestMethod void test2() {
        SurveyMonkeyAPI.upsertAnswers('surveyId');
        SurveyMonkeyAPI.createWebhook('CollectorId');
        String s = SurveyMonkeyAPI.getWebhooks();
        s = SurveyMonkeyAPI.getWebhook('webhookId');
        s = SurveyMonkeyAPI.getErrorMessage('errorId');
        s = SurveyMonkeyAPI.getResponse('CollectorId', 'ResponseId');
        s = SurveyMonkeyAPI.getSurveyDetails('SurveyId');
        s = SurveyMonkeyAPI.getResponses('SurveyId');
        SurveyMonkeyAPI.newMonthCollector();
        SurveyMonkeyAPI.getResponse('ResponseId', 'RecipientId', 'CollectorId');
		SurveyMonkeyRestResource.SurveyCallback();
    }
    
    static TestMethod void test3() {
         test.starttest();
         ScheduledNPSNewMonth sNPSnm = new ScheduledNPSNewMonth();   
         String chron = '0 0 23 * * ?';        
         system.schedule('Test Sched', chron, sNPSnm);
         test.stopTest();
    }
}