force-app/main/default/objects/AutomatedSurvey__c/AutomatedSurvey__c.object-meta.xml
<CustomObject>
    <label>Automated Survey</label>
    <nameField>
        <displayFormat>AS-{000000}</displayFormat>
        <label>Automated Survey</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Automated Surveys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AutomatedSurvey__c/fields/DateResponded__c.field-meta.xml
<CustomField>
    <fullName>DateResponded__c</fullName>
    <label>Date Responded</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/SlackNPS_scheduler.cls
global class SlackNPS_scheduler implements Schedulable {
    global void execute(SchedulableContext sc) {
        List<AutomatedSurvey__c> OpenSurveys = [SELECT Id, Locked__c FROM AutomatedSurvey__c WHERE NPS__c != null AND Locked__c = FALSE AND DateResponded__c >= 2020-07-01 AND DateResponded__c < TODAY];
        for (AutomatedSurvey__c OpenSurvey : OpenSurveys) {
            OpenSurvey.Locked__c = TRUE; system.enqueueJob(new SlackNPS(OpenSurvey.Id));
        }
        update OpenSurveys;
        system.enqueueJob(new SlackNPS());
    }
}