force-app/main/default/objects/GlobalStandardRecordType__c/GlobalStandardRecordType__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Global Standard RecordType</label>
</CustomObject>

force-app/main/default/objects/GlobalStandardRecordType__c/fields/RecordTypeDeveloperName__c.field-meta.xml
<CustomField>
    <fullName>RecordTypeDeveloperName__c</fullName>
    <label>RecordType Developer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RedirectToStandardRecordTypeController.cls
public with sharing class RedirectToStandardRecordTypeController {

    @TestVisible private static final Schema.sObjectType globalStandardRecordTypeSetting = GlobalStandardRecordType__c.sObjectType; 
    @TestVisible private static final Schema.sObjectField sObjectNameField = GlobalStandardRecordType__c.Name.getDescribe().getSObjectField(); 
    @TestVisible private static final Schema.sObjectField standardRecordTypeDeveloperNameField = GlobalStandardRecordType__c.RecordTypeDeveloperName__c.getDescribe().getSObjectField(); 

    @TestVisible private static final Schema.sObjectType testSObjectContext = Case.sObjectType; 
    
    private SObject thisRecord; 
    private Schema.sObjectType thisSObject; 
    private Id standardRecordTypeId; 

    public RedirectToStandardRecordTypeController(ApexPages.StandardSetController stdController) {
        thisRecord = stdController.getRecord(); 
        thisSObject = thisRecord.getSObjectType(); 
        initContext(); 
    }
    
    public RedirectToStandardRecordTypeController(ApexPages.StandardController stdController) { 
        thisRecord = stdController.getRecord(); 
        thisSObject = thisRecord.getSObjectType(); 
        initContext(); 
    }   
    
    public void initContext() { 
        SObject[] globalStandardRecordType = Database.query(
            'SELECT ' + 
                 standardRecordTypeDeveloperNameField.getDescribe().getLocalName() + ' ' + 
            'FROM ' + 
                globalStandardRecordTypeSetting.getDescribe().getLocalName() + ' ' + 
            'WHERE ' + 
                sObjectNameField.getDescribe().getLocalName() + ' = \'' + thisSObject.getDescribe().getLocalName() + '\' ' + 
            'ORDER BY ' + standardRecordTypeDeveloperNameField.getDescribe().getLocalName() + ' NULLS FIRST ' + 
            'LIMIT 1 '
            ); 
        System.debug(globalStandardRecordType); 
        if (globalStandardRecordType != null && globalStandardRecordType.size() == 1 && globalStandardRecordType[0].get(standardRecordTypeDeveloperNameField) != null) { 
            String thisSObjectName = thisSObject.getDescribe().getLocalName(); 
            String globalStandardRecordTypeDeveloperName = (String)globalStandardRecordType[0].get(standardRecordTypeDeveloperNameField); 
            RecordType[] recordType = [
                SELECT 
                    Id 
                FROM 
                    RecordType 
                WHERE 
                    sObjectType = :thisSObjectName AND 
                    DeveloperName = :globalStandardRecordTypeDeveloperName AND 
                    IsActive = TRUE 
                LIMIT 1
                ];
            standardRecordTypeId = (recordType != null && recordType.size() == 1) ? recordType[0].Id : null; 
        } 
    }
    
    public PageReference doRedirect() {
            return new PageReference(
                '/' + 
                thisSObject.getDescribe().getKeyPrefix() + 
                '/e' + 
                (standardRecordTypeId != null ? 
                    '?RecordTypeId=' + standardRecordTypeId + '&' : '?'
                ) + 
                'retURL=/' + thisSObject.getDescribe().getKeyPrefix()
            ); 
    }
}