force-app/main/default/objects/InvoicePayment__c/InvoicePayment__c.object-meta.xml
<CustomObject>
    <label>Invoice Payment</label>
    <nameField>
        <displayFormat>InvPmt-{000000}</displayFormat>
        <label>Invoice Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoicePayment__c/fields/IsQualifyingPayment__c.field-meta.xml
<CustomField>
    <fullName>IsQualifyingPayment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsQualifyingPayment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InvoicePayment__c/fields/IsQualifyingPayment_formula__c.field-meta.xml
<CustomField>
    <fullName>IsQualifyingPayment_formula__c</fullName>
    <formula>Payment__r.Status__c = &apos;Processed&apos; &amp;&amp; (Payment__r.Type__c = &apos;External&apos; || (Payment__r.Type__c = &apos;Electronic&apos; &amp;&amp; Payment__r.GatewayState__c = &apos;Settled&apos;)) &amp;&amp;  Payment__r.RefundAmount__c = 0</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IsQualifyingPayment (formula)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/InvoicePayment_Batch.cls
global class InvoicePayment_Batch implements Database.Batchable<sObject>{
    
    global final String Query;
    
    global InvoicePayment_Batch() {
        Query = 'SELECT Id, IsQualifyingPayment__c, IsQualifyingPayment_Formula__c FROM InvoicePayment__c '
            + 'WHERE (IsQualifyingPayment__c = TRUE AND IsQualifyingPayment_Formula__c = FALSE) '
            + 'OR (IsQualifyingPayment__c = FALSE AND IsQualifyingPayment_Formula__c = TRUE)';
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope){
        for (SObject s : scope) {
            s.put('IsQualifyingPayment__c', (Boolean)s.get('IsQualifyingPayment_Formula__c'));
        }
        update scope;
    }
    
    global void finish(Database.BatchableContext BC){
    }
    
}