force-app/main/default/objects/P148Letter__c/P148Letter__c.object-meta.xml
<CustomObject>
    <label>Paragraph 148 Letter</label>
    <nameField>
        <displayFormat>P148L-{000000}</displayFormat>
        <label>P148Letter Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Paragraph 148 Letters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/P148Letter__c/fields/CustomerId__c.field-meta.xml
<CustomField>
    <fullName>CustomerId__c</fullName>
    <formula>Venue__r.Account__r.CustomerID__c</formula>
    <label>Customer ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/P148Letter__c/fields/LegalCompanyName__c.field-meta.xml
<CustomField>
    <fullName>LegalCompanyName__c</fullName>
    <label>Legal Company Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TSE_Bestellbestaetigung_controller.cls
public class TSE_Bestellbestaetigung_controller {
    public String AccountName { get; set; } public String CustomerNumber { get; set; }
    public Boolean ShowPage { get; set; }
    public TSE_Bestellbestaetigung_controller() {
        ShowPage = false;
        String EncPId = ApexPages.currentPage().getParameters().get('param');
        String PId = '';
        try { PId = PortalToken.decryptPlain(EncPId); } catch(exception e) {}
        try {
            P148Letter__c p = [SELECT Id, CustomerId__c, LegalCompanyName__c FROM P148Letter__c WHERE Id = :PId][0];
	        AccountName = p.LegalCompanyName__c; CustomerNumber = p.CustomerId__c; ShowPage = true;
        } catch(exception e) {}
    }
}