force-app/main/default/objects/Aircall_Forwarding_Rule__c/Aircall_Forwarding_Rule__c.object-meta.xml
<CustomObject>
    <label>Aircall Forwarding Rule</label>
    <nameField>
        <label>Aircall Forwarding Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aircall Forwarding Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Aircall_Forwarding_Rule__c/fields/After_Hours__c.field-meta.xml
<CustomField>
    <fullName>After_Hours__c</fullName>
    <defaultValue>false</defaultValue>
    <label>After Hours</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Aircall_Forwarding_Rule__c/fields/Transfer_From_NumberId__c.field-meta.xml
<CustomField>
    <fullName>Transfer_From_NumberId__c</fullName>
    <label>Transfer From NumberId</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AircallWebhook_test.cls
@isTest public class AircallWebhook_test {

    static TestMethod void test() {
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestBody = Blob.valueof('{"event":"x","token":"y","data":{"id":"z","number":{"id":"123","open":true}}}');
        RestContext.request = req;
        RestContext.response = res;
        insert new Aircall_Forwarding_Rule__c(Transfer_From_NumberId__c = 123, After_Hours__c = true);
        insert new Aircall_Forwarding_Rule__c(Transfer_From_NumberId__c = 123, After_Hours__c = false);
        AircallWebhook.call_created();
    }
}