force-app/main/default/objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active Customer</fullName>
                <color>#66FF99</color>
                <label>Active Customer</label>
            </value>
            <value>
                <fullName>Future Customer</fullName>
            </value>
            <value>
                <fullName>Hardware Customer</fullName>
            </value>
            <value>
                <fullName>Incomplete Customer</fullName>
            </value>
            <value>
                <fullName>Legacy NetSuite Customer</fullName>
            </value>
            <value>
                <fullName>Lost Customer</fullName>
                <color>#FF0000</color>
                <label>Lost Customer</label>
            </value>
            <value>
                <fullName>Lost Hardware Customer</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Paused Customer</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
                <color>#DDDDDD</color>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Prospect (Closed Lost)</fullName>
            </value>
            <value>
                <fullName>Prospect (Committed)</fullName>
            </value>
            <value>
                <fullName>Prospect (Introduction / Demo)</fullName>
            </value>
            <value>
                <fullName>Prospect (Potential)</fullName>
            </value>
            <value>
                <fullName>Prospect (Proposal)</fullName>
            </value>
            <value>
                <fullName>Prospect (Qualification)</fullName>
            </value>
            <value>
                <fullName>Product Test Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/VenueCity__c.field-meta.xml
<CustomField>
    <fullName>VenueCity__c</fullName>
    <label>Venue City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/VenueStreet__c.field-meta.xml
<CustomField>
    <fullName>VenueStreet__c</fullName>
    <label>Venue Street</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>This record type is used for customer accounts and the standard Sales process.</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/classes/SecretSearch.cls
public class SecretSearch {
    
    @AuraEnabled
    public static String searchResults(String searchString) {
        return JSON.serialize([
            FIND :searchString
            IN Name Fields
            RETURNING Account(
                Id, Name, Website, Account_Status__c, VenueStreet__c, VenueCity__c
                WHERE 
                	(Account_Status__c LIKE '%Customer%' OR Account_Status__c LIKE '%Prospect%') 
                	AND (NOT Account_Status__c LIKE '%Closed%')
                ORDER BY Name, Account_Status__c
            ) LIMIT 100
        ]);
    }

}