force-app/main/default/objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active Customer</fullName>
                <color>#66FF99</color>
                <label>Active Customer</label>
            </value>
            <value>
                <fullName>Future Customer</fullName>
            </value>
            <value>
                <fullName>Hardware Customer</fullName>
            </value>
            <value>
                <fullName>Incomplete Customer</fullName>
            </value>
            <value>
                <fullName>Legacy NetSuite Customer</fullName>
            </value>
            <value>
                <fullName>Lost Customer</fullName>
                <color>#FF0000</color>
                <label>Lost Customer</label>
            </value>
            <value>
                <fullName>Lost Hardware Customer</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Paused Customer</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
                <color>#DDDDDD</color>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Prospect (Closed Lost)</fullName>
            </value>
            <value>
                <fullName>Prospect (Committed)</fullName>
            </value>
            <value>
                <fullName>Prospect (Introduction / Demo)</fullName>
            </value>
            <value>
                <fullName>Prospect (Potential)</fullName>
            </value>
            <value>
                <fullName>Prospect (Proposal)</fullName>
            </value>
            <value>
                <fullName>Prospect (Qualification)</fullName>
            </value>
            <value>
                <fullName>Product Test Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Privacy_Contact__c.field-meta.xml
<CustomField>
    <fullName>Privacy_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Privacy Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Privacy Contact)</relationshipLabel>
    <relationshipName>Accounts4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <description>This record type should be used for Partner accounts only.</description>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <formula>TEXT(Account.Account_Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/inactiveEmployee__c.field-meta.xml
<CustomField>
    <fullName>inactiveEmployee__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Stakeholder: Sales &amp; Account Management</description>
    <inlineHelpText>Is this person no longer working for this Account? To be checked if the person is no longer with the company.</inlineHelpText>
    <label>inactive employee</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Merge_Into__c.field-meta.xml
<CustomField>
    <fullName>Merge_Into__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Merge Into</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Open_Tasks__c.field-meta.xml
<CustomField>
    <fullName>Open_Tasks__c</fullName>
    <defaultValue>0</defaultValue>
    <description>https://jira.orderbird.com/browse/CDS-1211</description>
    <inlineHelpText>Number of open tasks</inlineHelpText>
    <label>Open Tasks</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/SubscriptionEndDate__c.field-meta.xml
<CustomField>
    <fullName>SubscriptionEndDate__c</fullName>
    <label>Subscription End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ContactPurgeTagger.cls
global class ContactPurgeTagger implements Database.Batchable<sObject>{
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        String Query = 'SELECT Id, Privacy_Contact__c FROM Account '
            + 'WHERE Account_Status__c NOT IN (\'Partner\') '
            + 'AND Id NOT IN (SELECT AccountId FROM Opportunity WHERE CreatedDate = LAST_n_DAYS:365 OR LastActivityDate = LAST_n_DAYS:365 OR Open_Tasks__c > 0) '
            + 'AND Id NOT IN (SELECT Account__c FROM Subscription__c WHERE (SubscriptionEndDate__c = null AND Status__c != \'Expired\') OR SubscriptionEndDate__c > LAST_n_DAYS:365) '
            + 'AND CreatedDate < LAST_n_DAYS:365 AND Privacy_Contact__c = null ';
        return Database.getQueryLocator(Query);
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope){
        List<Contact> insContacts = new List<Contact>();
        Map<Id, Id> contactMap = new Map<Id, Id>();
        for (sObject s : scope) {
            insContacts.add( new Contact(
                AccountId = (String)s.get('Id'), InactiveEmployee__c = true, LastName = 'Deleted Contact'
            ) );
        }
        insert insContacts;
        for (Contact cnct : insContacts) {
            contactMap.put(cnct.AccountId, cnct.Id);
        }
        for (sObject s : scope) {
            s.put('Privacy_Contact__c', contactMap.get((String)s.get('Id')));
        }
        update scope;
        List<Contact> mergeContacts = [
            SELECT Id, AccountId, Merge_Into__c FROM Contact WHERE AccountId IN :contactMap.keySet()
        ];
        for (Contact cnct : mergeContacts) {
            Id mInto = contactMap.get(cnct.AccountId);
            if (mInto != cnct.Id) cnct.Merge_Into__c = mInto;
        }
        update mergeContacts;
    }
    
    global void finish(Database.BatchableContext BC){}
    
}