force-app/main/default/objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active Customer</fullName>
                <color>#66FF99</color>
                <label>Active Customer</label>
            </value>
            <value>
                <fullName>Future Customer</fullName>
            </value>
            <value>
                <fullName>Hardware Customer</fullName>
            </value>
            <value>
                <fullName>Incomplete Customer</fullName>
            </value>
            <value>
                <fullName>Legacy NetSuite Customer</fullName>
            </value>
            <value>
                <fullName>Lost Customer</fullName>
                <color>#FF0000</color>
                <label>Lost Customer</label>
            </value>
            <value>
                <fullName>Lost Hardware Customer</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Paused Customer</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
                <color>#DDDDDD</color>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Prospect (Closed Lost)</fullName>
            </value>
            <value>
                <fullName>Prospect (Committed)</fullName>
            </value>
            <value>
                <fullName>Prospect (Introduction / Demo)</fullName>
            </value>
            <value>
                <fullName>Prospect (Potential)</fullName>
            </value>
            <value>
                <fullName>Prospect (Proposal)</fullName>
            </value>
            <value>
                <fullName>Prospect (Qualification)</fullName>
            </value>
            <value>
                <fullName>Product Test Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/NS_Customer_Internal_ID__c.field-meta.xml
<CustomField>
    <fullName>NS_Customer_Internal_ID__c</fullName>
    <description>Stakeholder: NEST</description>
    <externalId>true</externalId>
    <inlineHelpText>What is the internal ID of this customer account in Netsuite? Updated manually regularly</inlineHelpText>
    <label>NS Customer Internal ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Number_of_active_subscriptions_2__c.field-meta.xml
<CustomField>
    <fullName>Number_of_active_subscriptions_2__c</fullName>
    <description>https://jira.orderbird.com/browse/CDS-511</description>
    <inlineHelpText>How many active subscriptions does this account have?</inlineHelpText>
    <label>Number of active subscriptions</label>
    <summaryFilterItems>
        <field>Subscription__c.Status__c</field>
        <operation>equals</operation>
        <value>Active</value>
    </summaryFilterItems>
    <summaryForeignKey>Subscription__c.Account__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/Product_Test_Participation__c.field-meta.xml
<CustomField>
    <fullName>Product_Test_Participation__c</fullName>
    <label>Product Test Participation</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>orderbird Mini</fullName>
            </value>
            <value>
                <fullName>PRO Field Testing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>This record type is used for customer accounts and the standard Sales process.</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <description>This record type should be used for Partner accounts only.</description>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/SubscriptionLineItem__c.object-meta.xml
<CustomObject>
    <label>Subscription Line Item</label>
    <nameField>
        <label>Subscription Line Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SubscriptionLineItem__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>SubscriptionLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/fields/Status_Active_Device__c.field-meta.xml
<CustomField>
    <fullName>Status_Active_Device__c</fullName>
    <formula>IF(
IsCurrent__c
&amp;&amp; NOT(CONTAINS(Product__r.Model__c,&quot;Discount&quot;))
&amp;&amp; (
Product__r.ProductCategory__r.ProductType__c = &quot;POS Device&quot;
||
Product__r.ProductCategory__r.ProductType__c = &quot;POS Service+Device&quot;
),1,0)</formula>
    <label>Status Active Device</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/fields/Status_Active_Service__c.field-meta.xml
<CustomField>
    <fullName>Status_Active_Service__c</fullName>
    <formula>IF(
IsCurrent__c
&amp;&amp;
NOT(CONTAINS(Product__r.Name,&quot;subsidy&quot;))
&amp;&amp; (
 Product__r.ProductCategory__r.ProductType__c  = &quot;POS Service&quot;
||
 Product__r.ProductCategory__r.ProductType__c  = &quot;POS Service+Device&quot;
),1,0)</formula>
    <label>Status Active Service</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/fields/Status_Future_Customer__c.field-meta.xml
<CustomField>
    <fullName>Status_Future_Customer__c</fullName>
    <formula>IF(EffectiveStartDate__c &gt; TODAY()
&amp;&amp;
Subscription__r.Status__c &lt;&gt; &quot;Expired&quot;
&amp;&amp;
Subscription__r.Status__c &lt;&gt; &quot;Cancelled&quot;
&amp;&amp; (
Product__r.ProductCategory__r.ProductType__c = &quot;POS Service&quot;
||
Product__r.ProductCategory__r.ProductType__c = &quot;POS Device&quot;
||
Product__r.ProductCategory__r.ProductType__c = &quot;POS Service+Device&quot;
),1,0)</formula>
    <label>Status Future Customer</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/fields/Status_Past_Customer__c.field-meta.xml
<CustomField>
    <fullName>Status_Past_Customer__c</fullName>
    <formula>IF(
NOT(CONTAINS(Product__r.Name,&quot;subsidy&quot;))
&amp;&amp;
(EffectiveEndDate__c &lt; TODAY() || (Status__c != &quot;Active&quot; &amp;&amp; EffectiveStartDate__c &lt; TODAY()))
&amp;&amp; (
Product__r.ProductCategory__r.ProductType__c = &quot;POS Service&quot;
||
Product__r.ProductCategory__r.ProductType__c = &quot;POS Device&quot;
||
Product__r.ProductCategory__r.ProductType__c = &quot;POS Service+Device&quot;
),1,0)</formula>
    <label>Status Past Customer</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>Subscription_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AccountStatus_Controller.cls
public class AccountStatus_Controller {
    
    @InvocableMethod(label='Update Account Status' description='Ensures Account Status is still correct')	
    public static void UpdateAccountStatus(List<Id> AccountIds) {
        String Query = 'SELECT Id, RecordType.Name, Account_Status__c, Number_of_Active_Subscriptions_2__c, NS_Customer_Internal_ID__c, Product_Test_Participation__c'
            + ' FROM Account WHERE Id IN :AccountIds';
        ExecuteAccountStatusUpdate(Database.query(Query));
    }
    
    public static void ExecuteAccountStatusUpdate(List<sObject> scope) {
        List<Account> UpdateAccounts = new List<Account>();
        Set<String> SubbedAccts = new Set<String>();
        Map<String, sObject> sObjectMap = new Map<String, sObject>();
        for(sObject s : scope){
            if ((String)s.getSObject('RecordType').get('Name') == 'Customer') {
                sObjectMap.put((String)s.get('Id'), s);
            } else if ((String)s.get('Account_Status__c') != 'Partner') { UpdateAccounts.add(new Account(Id = (String)s.get('Id'),Account_Status__c = 'Partner')); }
        }
        for (AggregateResult ar : [
            SELECT Subscription__r.Account__c AccountId, SUM(Status_Active_Device__c) ActDvc, SUM(Status_Active_Service__c) ActSvc, 
            SUM(Status_Past_Customer__c) CuPast, SUM(Status_Future_Customer__c) CuFutr 
            FROM SubscriptionLineItem__c WHERE Subscription__r.Account__c IN :sObjectMap.keySet() GROUP BY Subscription__r.Account__c
        ]){
            SubbedAccts.add((String)ar.get('AccountId'));
            Boolean ActDvc = (Decimal)ar.get('ActDvc') != 0;
            Boolean ActSvc = (Decimal)ar.get('ActSvc') != 0;
            Boolean CuPast = (Decimal)ar.get('CuPast') != 0;
            Boolean CuFutr = (Decimal)ar.get('CuFutr') != 0;
            Boolean Inactv = (Decimal)(sObjectMap.get((String)ar.get('AccountId')).get('Number_of_Active_Subscriptions_2__c')) == 0;
            Boolean Legacy = (String)(sObjectMap.get((String)ar.get('AccountId')).get('NS_Customer_Internal_ID__c')) != null;
            String Status = 'Hardware Customer';
            if ((ActDvc && ActSvc) || (CuPast && CuFutr)) { Status = 'Active Customer';
            } else if (!ActDvc && ActSvc) { Status = 'Paused Customer';
            } else if (ActDvc && !ActSvc) { Status = 'Incomplete Customer';
            } else if (CuPast) { Status = 'Lost Customer';
            } else if (CuFutr) { Status = 'Future Customer';
			} else if (Inactv) { Status = 'Lost Hardware Customer'; }
            if (Status != (String)(sObjectMap.get((String)ar.get('AccountId')).get('Account_Status__c'))) {
                UpdateAccounts.add(new Account(Id = (String)ar.get('AccountId'),Account_Status__c = Status));
            }
        }
        for (Account acct : [
            SELECT Id, Account_Status__c, NS_Customer_Internal_ID__c, Product_Test_Participation__c, (SELECT Id, StageName FROM Opportunities WHERE StageName != 'Closed Won' ORDER BY CreatedDate DESC LIMIT 1) FROM Account WHERE Id IN :sObjectMap.keySet() AND Id NOT IN :SubbedAccts
        ]) {
            if (acct.Product_Test_Participation__c != null) { UpdateAccounts.add(new Account(Id = acct.Id,Account_Status__c = 'Product Test Only')); } else {
                String AcctStat = 'Prospect';
                if (acct.Opportunities.size() == 1) AcctStat += ' (' + acct.Opportunities[0].StageName + ')';
                if (AcctStat == 'Prospect' && acct.NS_Customer_Internal_ID__c != null) AcctStat = 'Legacy NetSuite Customer';
                if (acct.Account_Status__c != AcctStat) UpdateAccounts.add(new Account(Id = acct.Id,Account_Status__c = AcctStat)); 
            }
        }
        update UpdateAccounts;
    }
}