force-app/main/default/objects/Account/fields/AccountType__c.field-meta.xml
<CustomField>
    <fullName>AccountType__c</fullName>
    <description>Stakeholder: Sales &amp; Partner</description>
    <inlineHelpText>Is this Account related to us as a Partner or Customer? Set on creation.</inlineHelpText>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
                <default>true</default>
                <label>Customer</label>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/PartnerType__c.field-meta.xml
<CustomField>
    <fullName>PartnerType__c</fullName>
    <description>Stakeholder: PaM</description>
    <inlineHelpText>How is our relationship with this partner defined? Referral, Distribution or one of the big strategic partners? Filled in by PaM</inlineHelpText>
    <label>Partner Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>n/a</fullName>
            </value>
            <value>
                <fullName>ConCardis</fullName>
            </value>
            <value>
                <fullName>ETL</fullName>
            </value>
            <value>
                <fullName>METRO</fullName>
            </value>
            <value>
                <fullName>Referral Partner</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Joint Sales</fullName>
            </value>
            <value>
                <fullName>Product Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <description>This record type should be used for Partner accounts only.</description>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/Joint_Sales__c/Joint_Sales__c.object-meta.xml
<CustomObject>
    <label>Joint Sales</label>
    <nameField>
        <displayFormat>JS-{000000}</displayFormat>
        <label>Joint Sales Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Joint Sales</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Joint_Sales__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Joint Sales</relationshipLabel>
    <relationshipName>Joint_Sales1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Joint_Sales__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <label>Partner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.PartnerType__c</field>
            <operation>equals</operation>
            <value>Joint Sales</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Partner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Joint Sales (Partner)</relationshipLabel>
    <relationshipName>Joint_Sales</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/JointSalesExtension_Test.cls
@isTest public class JointSalesExtension_Test {
    
    static testmethod void test() {
        Account a = new Account(name='test');
        insert a;
        Account p = new Account(name='test',AccountType__c='partner',partnertype__c='joint sales');
        insert p;
        insert new Joint_Sales__c(customer__c=a.Id,partner__c=p.Id);
        ApexPages.StandardController sc = new ApexPages.StandardController(a);
        JointSalesExtension jse = new JointSalesExtension(sc);
        PageReference pr = jse.jsSave();
        pr = jse.jsCancel();
    }
}