force-app/main/default/objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active Customer</fullName>
                <color>#66FF99</color>
                <label>Active Customer</label>
            </value>
            <value>
                <fullName>Future Customer</fullName>
            </value>
            <value>
                <fullName>Hardware Customer</fullName>
            </value>
            <value>
                <fullName>Incomplete Customer</fullName>
            </value>
            <value>
                <fullName>Legacy NetSuite Customer</fullName>
            </value>
            <value>
                <fullName>Lost Customer</fullName>
                <color>#FF0000</color>
                <label>Lost Customer</label>
            </value>
            <value>
                <fullName>Lost Hardware Customer</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Paused Customer</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
                <color>#DDDDDD</color>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Prospect (Closed Lost)</fullName>
            </value>
            <value>
                <fullName>Prospect (Committed)</fullName>
            </value>
            <value>
                <fullName>Prospect (Introduction / Demo)</fullName>
            </value>
            <value>
                <fullName>Prospect (Potential)</fullName>
            </value>
            <value>
                <fullName>Prospect (Proposal)</fullName>
            </value>
            <value>
                <fullName>Prospect (Qualification)</fullName>
            </value>
            <value>
                <fullName>Product Test Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Last_Status_Update__c.field-meta.xml
<CustomField>
    <fullName>Last_Status_Update__c</fullName>
    <label>Last Status Update</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountHandler.cls
public class AccountHandler implements ITriggerHandler {
    
    //private AddressSync addressSync;
    private RegionManager regionManager;
    
    public void bulkBefore(){
    	//this.addressSync = new AddressSync(Trigger.new);
    	//this.addressSync.loadRelatedContactAddresses();
        this.regionManager = new RegionManager('Account');
    }

    public void bulkAfter(){}

    public void beforeInsert(SObject so) {
        PhoneNumberCleansing.rewritePhoneNumber(so, 'Phone');
        PhoneNumberCleansing.rewritePhoneNumber(so, 'Fax');
        this.regionManager.setRegionValues(so);
    }
    
    public void beforeUpdate(SObject oldSo, SObject so) {
        //if(AvoidRecursion.isFirstRun()) {
        //    this.addressSync.updateAccountAddresses((Account)so);
        //}
        PhoneNumberCleansing.rewritePhoneNumber(so, 'Phone');
        PhoneNumberCleansing.rewritePhoneNumber(so, 'Fax');
        this.regionManager.updateRegionValues(so, oldSo);
        if ((String)oldSo.get('Account_Status__c') != (String)so.get('Account_Status__c')) so.put('Last_Status_Update__c', DateTime.now());
    }

    public void beforeDelete(SObject so){
        if((String)so.get('ZuoraId__c') != null) so.addError('Accounts with a Zuora link cannot be deleted.');
    }

    public void afterInsert(SObject so) {}

    public void afterUpdate(SObject oldSo, SObject so) {}

    public void afterDelete(SObject so){}

    public void andFinally(){}
}