force-app/main/default/objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active Customer</fullName>
                <color>#66FF99</color>
                <label>Active Customer</label>
            </value>
            <value>
                <fullName>Future Customer</fullName>
            </value>
            <value>
                <fullName>Hardware Customer</fullName>
            </value>
            <value>
                <fullName>Incomplete Customer</fullName>
            </value>
            <value>
                <fullName>Legacy NetSuite Customer</fullName>
            </value>
            <value>
                <fullName>Lost Customer</fullName>
                <color>#FF0000</color>
                <label>Lost Customer</label>
            </value>
            <value>
                <fullName>Lost Hardware Customer</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Paused Customer</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
                <color>#DDDDDD</color>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Prospect (Closed Lost)</fullName>
            </value>
            <value>
                <fullName>Prospect (Committed)</fullName>
            </value>
            <value>
                <fullName>Prospect (Introduction / Demo)</fullName>
            </value>
            <value>
                <fullName>Prospect (Potential)</fullName>
            </value>
            <value>
                <fullName>Prospect (Proposal)</fullName>
            </value>
            <value>
                <fullName>Prospect (Qualification)</fullName>
            </value>
            <value>
                <fullName>Product Test Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/First_POS_Start_Date_2__c.field-meta.xml
<CustomField>
    <fullName>First_POS_Start_Date_2__c</fullName>
    <description>https://jira.orderbird.com/browse/CDS-511</description>
    <inlineHelpText>When did this customer&apos;s first subscription start?</inlineHelpText>
    <label>First Subscription Start Date</label>
    <summarizedField>Subscription__c.SubscriptionStartDate__c</summarizedField>
    <summaryForeignKey>Subscription__c.Account__c</summaryForeignKey>
    <summaryOperation>min</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/Target_Product__c.field-meta.xml
<CustomField>
    <fullName>Target_Product__c</fullName>
    <label>Target Product</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>This record type is used for customer accounts and the standard Sales process.</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/AutomatedSurvey__c/AutomatedSurvey__c.object-meta.xml
<CustomObject>
    <label>Automated Survey</label>
    <nameField>
        <displayFormat>AS-{000000}</displayFormat>
        <label>Automated Survey</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Automated Surveys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AutomatedSurvey__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Automated Surveys</relationshipLabel>
    <relationshipName>Automated_Surveys</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/AutomatedSurvey__c/fields/DateSent__c.field-meta.xml
<CustomField>
    <fullName>DateSent__c</fullName>
    <label>Date Sent</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AutomatedSurvey__c/fields/IsMini__c.field-meta.xml
<CustomField>
    <fullName>IsMini__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Mini</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/AMCategory__c.field-meta.xml
<CustomField>
    <fullName>AMCategory__c</fullName>
    <description>Stakeholder: CS</description>
    <inlineHelpText>What account specific problem does this issue relate to? Filled in by anyone who rises the issue</inlineHelpText>
    <label>AM Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account balance</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>Change bank account information</fullName>
            </value>
            <value>
                <fullName>Change invoice</fullName>
            </value>
            <value>
                <fullName>Credits</fullName>
            </value>
            <value>
                <fullName>Customer referrals</fullName>
            </value>
            <value>
                <fullName>Damage Report</fullName>
            </value>
            <value>
                <fullName>De-escalation</fullName>
            </value>
            <value>
                <fullName>General data</fullName>
            </value>
            <value>
                <fullName>Rescissions</fullName>
            </value>
            <value>
                <fullName>Send out invoice</fullName>
            </value>
            <value>
                <fullName>Tax data</fullName>
            </value>
            <value>
                <fullName>Dunning</fullName>
            </value>
            <value>
                <fullName>Upselling</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Target_Product__c.field-meta.xml
<CustomField>
    <fullName>Target_Product__c</fullName>
    <formula>IF( ISBLANK(Account.Target_Product__c), &apos;PRO&apos;, Account.Target_Product__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Target Product</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <formula>TEXT(Account.Account_Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EmailOptOut__c.field-meta.xml
<CustomField>
    <fullName>EmailOptOut__c</fullName>
    <formula>IF(HasOptedOutOfEmail,1,0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EmailOptOut</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/inactiveEmployee__c.field-meta.xml
<CustomField>
    <fullName>inactiveEmployee__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Stakeholder: Sales &amp; Account Management</description>
    <inlineHelpText>Is this person no longer working for this Account? To be checked if the person is no longer with the company.</inlineHelpText>
    <label>inactive employee</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Last_NPS_Response__c.field-meta.xml
<CustomField>
    <fullName>Last_NPS_Response__c</fullName>
    <label>Last NPS Response</label>
    <summarizedField>AutomatedSurvey__c.DateResponded__c</summarizedField>
    <summaryForeignKey>AutomatedSurvey__c.Contact__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Last_NPS_Send__c.field-meta.xml
<CustomField>
    <fullName>Last_NPS_Send__c</fullName>
    <label>Last NPS Send</label>
    <summarizedField>AutomatedSurvey__c.CreatedDate</summarizedField>
    <summaryForeignKey>AutomatedSurvey__c.Contact__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/NPSScheduler__c/NPSScheduler__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>NPSScheduler</label>
</CustomObject>

force-app/main/default/objects/NPSScheduler__c/fields/Testing__c.field-meta.xml
<CustomField>
    <fullName>Testing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Testing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ScheduledNPS.cls
global class ScheduledNPS implements Schedulable{
    global void execute(SchedulableContext SC) {
        List<AutomatedSurvey__c> insAS = new List<AutomatedSurvey__c>();
        Set<Id> ContactIds = new Set<Id>();
        Map<Id,String> ContactEmailMap = new Map<Id,String>();
        Set<String> MiniEmails = new Set<String>();
        for (
            AggregateResult ar : [
                SELECT Email, MIN(Id) ContactId
                FROM Contact 
                WHERE 
                    Account.First_POS_Start_Date_2__c < LAST_n_DAYS:45 
                    AND Account.First_POS_Start_Date_2__c < LAST_n_DAYS:45 
                    AND Account.First_POS_Start_Date_2__c >= LAST_n_DAYS:75 
                    AND Email != null
                    AND Account.Account_Status__c = 'Active Customer'
                    AND CreatedDate < LAST_n_DAYS:30
                	AND InactiveEmployee__c = FALSE
                    AND AccountId NOT IN (
                        SELECT AccountId 
                        FROM Case 
                        WHERE 
                            AMCategory__c = 'Cancellation' 
                            AND (
                                (NOT Status LIKE '%Closed%') 
                                OR CreatedDate = LAST_n_DAYS:90
                            )
                    ) 
                GROUP BY Email 
                HAVING 
                    (MAX(Last_NPS_Response__c) < last_n_days:180 OR MAX(Last_NPS_Response__c) = null) 
                    AND (MAX(Last_NPS_Send__c) < last_n_days:90 OR MAX(Last_Nps_Send__c) = null)
                    AND (SUM(EmailOptOut__c) = 0)
                	AND MAX(Last_Nps_Send__c) = null
                ORDER BY MAX(Last_NPS_Send__c), MIN(CreatedDate) DESC
                LIMIT 200
            ]
        ){
            ContactIds.add((Id)ar.get('ContactId')); ContactEmailMap.put((Id)ar.get('ContactId'), (String)ar.get('Email'));
        }
        for (AggregateResult ar : [SELECT Email FROM Contact WHERE Email IN :ContactEmailMap.values() AND Account.Target_Product__c = 'MINI' GROUP BY Email]){ MiniEmails.add((String)ar.get('Email')); }
        for (Id ContactId : ContactIds){ insAS.add(new AutomatedSurvey__c(Contact__c = ContactId, IsMini__c = MiniEmails.contains(ContactEmailMap.get(ContactId)), DateSent__c = Date.today())); }
        NPSScheduler__c nps = NPSScheduler__c.getInstance();
        if (!nps.Testing__c) {
            insert insAS;
        } else { for (Contact c : [SELECT Id FROM Contact WHERE LastName = 'NPSTest']) { insert new AutomatedSurvey__c(Contact__c = c.Id); } }
    }
}