force-app/main/default/objects/Account/fields/AccountManager__c.field-meta.xml
<CustomField>
    <fullName>AccountManager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User lookup to specify the Account Manager</description>
    <inlineHelpText>Responsible Account Manager for this Account</inlineHelpText>
    <label>Account Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/AddressBuilder__c.field-meta.xml
<CustomField>
    <fullName>AddressBuilder__c</fullName>
    <defaultValue>&quot;[\&quot;LegalCompanyName__c\&quot;,\&quot;SF_BillTo_Contact__r.Name\&quot;,\&quot;empty\&quot;]&quot;</defaultValue>
    <label>Address Builder (Billing)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Combined_Balance__c.field-meta.xml
<CustomField>
    <fullName>Combined_Balance__c</fullName>
    <formula>Account_Balance_2__c +  Netsuite_Open_Balance__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Combined Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/CustomerIdText__c.field-meta.xml
<CustomField>
    <fullName>CustomerIdText__c</fullName>
    <description>This exists so that code does not have to consume the auto number. We may occassionally have to edit the autonumber field (temporarily changing the field type) and this cannot be done when it is referenced in code.</description>
    <formula>CustomerID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CustomerIdText</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/LegalCompanyName__c.field-meta.xml
<CustomField>
    <fullName>LegalCompanyName__c</fullName>
    <description>Stakeholder: Stakeholders: Sales with Account Management</description>
    <inlineHelpText>What is the company&apos;s legal name for e.g. billing? It is usually in the „about us“/Impressum of websites . If there is an addition such as Gmbh / UG / LDT. / SAS / SL... it’s an operating company. It could however also be a non-incorporated company</inlineHelpText>
    <label>Legal Company Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Netsuite_Open_Balance__c.field-meta.xml
<CustomField>
    <fullName>Netsuite_Open_Balance__c</fullName>
    <description>https://jira.orderbird.com/browse/SAL-1230</description>
    <inlineHelpText>Open Balance migrated from Netsuite. Updated on regular basis by NEST.</inlineHelpText>
    <label>Netsuite Open Balance</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/PrimaryLanguage__c.field-meta.xml
<CustomField>
    <fullName>PrimaryLanguage__c</fullName>
    <defaultValue>&quot;German&quot;</defaultValue>
    <description>Stakeholder: Sales &amp; CS with MKT</description>
    <inlineHelpText>What language do we use to communicate with this venue? Filled in as soon as known. Updated if necessary!</inlineHelpText>
    <label>Primary Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Language</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/SF_BillTo_Contact__c.field-meta.xml
<CustomField>
    <fullName>SF_BillTo_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Stakeholder: Sales &amp; Account Management</description>
    <inlineHelpText>This defines the official billing address.</inlineHelpText>
    <label>Billing Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.ParentId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Zuora BillTo Contact)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PrimaryLanguage__c.field-meta.xml
<CustomField>
    <fullName>PrimaryLanguage__c</fullName>
    <description>Stakeholder: Sales &amp; CS &amp; MKT</description>
    <inlineHelpText>What language do we use to communicate with this venue? Filled in as soon as known. Updated if necessary!</inlineHelpText>
    <label>Primary Language</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>Russian</fullName>
            </value>
            <value>
                <fullName>Italian</fullName>
            </value>
            <value>
                <fullName>Polish</fullName>
            </value>
            <value>
                <fullName>Chinese</fullName>
            </value>
            <value>
                <fullName>Japanese</fullName>
            </value>
            <value>
                <fullName>Swedish</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>2.0</description>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoiceDate__c.field-meta.xml
<CustomField>
    <fullName>InvoiceDate__c</fullName>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <label>Payment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/EffectiveDate__c.field-meta.xml
<CustomField>
    <fullName>EffectiveDate__c</fullName>
    <label>Effective Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Refund__c/Refund__c.object-meta.xml
<CustomObject>
    <label>Refund</label>
    <nameField>
        <label>Refund Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Refunds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Refund__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>Payment__c</referenceTo>
    <relationshipLabel>Refunds</relationshipLabel>
    <relationshipName>Refunds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Refund__c/fields/RefundDate__c.field-meta.xml
<CustomField>
    <fullName>RefundDate__c</fullName>
    <label>Refund Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/globalValueSets/Language.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>German</fullName>
        <default>true</default>
        <label>German</label>
    </customValue>
    <customValue>
        <fullName>English</fullName>
    </customValue>
    <customValue>
        <fullName>French</fullName>
    </customValue>
    <customValue>
        <fullName>Spanish</fullName>
    </customValue>
    <customValue>
        <fullName>Russian</fullName>
    </customValue>
    <customValue>
        <fullName>Italian</fullName>
    </customValue>
    <customValue>
        <fullName>Polish</fullName>
    </customValue>
    <customValue>
        <fullName>Chinese</fullName>
    </customValue>
    <customValue>
        <fullName>Japanese</fullName>
    </customValue>
    <customValue>
        <fullName>Swedish</fullName>
    </customValue>
    <masterLabel>Language</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AccountStatementController.cls
public class AccountStatementController {

    public String acctId { 
        get; 
        set {
            acctId = value;
            init();
        } 
    }
    
    public Account acct { get; set; }
    public List<String> AddressParts { get; set; }
    public List<StatementItem> items { get; set; }
    public Decimal runningBalance { get; set; }
    public String primaryLanguage { get; set; }
    
    public List<Decimal> InvoiceBreakdown { get; set; }
    
    public void init() {
        this.acct = [
            SELECT 
                Id, Name, OwnerId, CustomerIdText__c, CurrencyIsoCode, PrimaryLanguage__c, 
                SF_BillTo_Contact__r.Name, BillingStreet, BillingCity, 
                BillingPostalCode, BillingCountry, BillingCountryCode,
            	SF_BillTo_Contact__r.FirstName, LegalCompanyName__c, 
                AccountManager__r.Name, AccountManager__r.Department, AccountManager__r.Phone, AccountManager__r.Email,
                Netsuite_Open_Balance__c, Combined_Balance__c, AddressBuilder__c,
                (
                    SELECT Id, EffectiveDate__c, Amount__c, Name, CreatedDate
                    FROM Payments__r 
                    WHERE Status__c = 'Processed' OR Status__c = 'Processing'
                ), (
                    SELECT Id, InvoiceDate__c, Amount__c, Name, CreatedDate
                    FROM Invoices__r
                    WHERE Amount__c != 0 AND Status__c = 'Posted'
                ), (
                    SELECT Id, RefundDate__c, Amount__c, Name, CreatedDate
                    FROM Refunds__r
                    WHERE Amount__c != 0 AND Status__c = 'Processed'
                )
            FROM Account 
            WHERE Id= :acctId
            LIMIT 1
        ];
        try {
            AddressParts = (List<String>)JSON.deserialize(acct.AddressBuilder__c, List<String>.class);
        } catch(exception e){}
        Decimal AccountBalance = acct.Combined_Balance__c;
        this.items = new List<StatementItem>();
        items.add(new StatementItem(acct.Netsuite_Open_Balance__c));
        for (Invoice__c inv : acct.Invoices__r) {
            items.add(new StatementItem(inv));
        }
        for (Payment__c pmt : acct.Payments__r) {
            items.add(new StatementItem(pmt));
        }
        for (Refund__c ref : acct.Refunds__r) {
            items.add(new StatementItem(ref));
        }
        items.sort();
        this.InvoiceBreakdown = new List<Decimal>{0, 0, 0, 0, 0};
        runningBalance = 0;
        Double DayConstant = 10.0;
        for (StatementItem item : items) {
            Date dateStamp = Date.today();
            if (item.DateStamp != null) dateStamp = item.DateStamp;
            if (item.Charge != null) {
                runningBalance += item.Charge;
                InvoiceBreakdown[Math.min(4,Math.max(0,(Math.ceil(dateStamp.daysBetween(Date.today())/DayConstant)).intValue()))] += Math.max(0,item.Charge);
            }
            if (item.Payment != null) runningBalance -= item.Payment;
            item.Balance = runningBalance;
        }
        if (items.size() > 1) items[0].DateStamp = items[1].DateStamp;
        /* Decimal offset = runningBalance - AccountBalance;
        if (offset != 0) {
            for (StatementItem item: items) {
                item.Balance -= offset;
            }
        } */
        Decimal BreakdownTotal = AccountBalance;
        for (Integer x=0; x<InvoiceBreakdown.size(); x++) {
            if (InvoiceBreakdown[x] > BreakdownTotal) {
                InvoiceBreakdown[x] = BreakdownTotal;
            }
            BreakdownTotal -= InvoiceBreakdown[x];
        }
        items[0].Charge = null;
        primaryLanguage = LanguageMap.get(acct.PrimaryLanguage__c);
    }
    
    public Static Map<String, String> LanguageMap = new Map<String, String>{'English'=>'en','German'=>'de','Spanish'=>'es','French'=>'fr'};
    
    public class StatementItem implements Comparable{
        public Date DateStamp { get; set; }
        public DateTime TimeStamp { get; set; }
        public String Description { get; set; }
        public String RefNum { get; set; }
        public Decimal Charge { get; set; }
        public Decimal Payment { get; set; }
        public Decimal Balance { get; set; }
        public Integer ItemType { get; set; }
        
        public StatementItem(Decimal nsob) {
            DateStamp = Date.newInstance(2017, 9, 1);
            Description = 'BEGINNING_BALANCE';
            if (nsob != 0 && nsob != null) {
                Charge = nsob;
                Balance = nsob;
            } else {
                Balance = 0;
            }
            ItemType = -1;
        }        
        
        public StatementItem(Invoice__c inv) {
            DateStamp = inv.InvoiceDate__c;
            TimeStamp = inv.CreatedDate;
            Description = 'INVOICE';
            RefNum = inv.Name;
            Charge = inv.Amount__c;
            ItemType = 0;
        }

        public StatementItem(Payment__c pmt) {
            DateStamp = Date.newInstance(pmt.EffectiveDate__c.year(), pmt.EffectiveDate__c.month(), pmt.EffectiveDate__c.day());
            TimeStamp = pmt.CreatedDate;
            Description = 'PAYMENT';
            RefNum = pmt.Name;
            Payment = pmt.Amount__c;
            ItemType = 1;
        }

        public StatementItem(Refund__c ref) {
            DateStamp = ref.RefundDate__c;
            TimeStamp = ref.CreatedDate;
            Description = 'REFUND';
            RefNum = ref.Name;
            Payment = ref.Amount__c * -1;
            ItemType = 2;
        }

        public Integer compareTo(Object compareTo) {
            StatementItem CompareItem = (StatementItem)compareTo;
            if (DateStamp > CompareItem.DateStamp) {
                return 1;
            } else if (DateStamp < CompareItem.DateStamp) {
                return -1;
            } else {
                if (ItemType > CompareItem.ItemType) {
                    return 1;
                } else {
                    return -1;
                }                
            }
        }
    }

}