force-app/main/default/objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active Customer</fullName>
                <color>#66FF99</color>
                <label>Active Customer</label>
            </value>
            <value>
                <fullName>Future Customer</fullName>
            </value>
            <value>
                <fullName>Hardware Customer</fullName>
            </value>
            <value>
                <fullName>Incomplete Customer</fullName>
            </value>
            <value>
                <fullName>Legacy NetSuite Customer</fullName>
            </value>
            <value>
                <fullName>Lost Customer</fullName>
                <color>#FF0000</color>
                <label>Lost Customer</label>
            </value>
            <value>
                <fullName>Lost Hardware Customer</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Paused Customer</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
                <color>#DDDDDD</color>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Prospect (Closed Lost)</fullName>
            </value>
            <value>
                <fullName>Prospect (Committed)</fullName>
            </value>
            <value>
                <fullName>Prospect (Introduction / Demo)</fullName>
            </value>
            <value>
                <fullName>Prospect (Potential)</fullName>
            </value>
            <value>
                <fullName>Prospect (Proposal)</fullName>
            </value>
            <value>
                <fullName>Prospect (Qualification)</fullName>
            </value>
            <value>
                <fullName>Product Test Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/AddressBuilder__c.field-meta.xml
<CustomField>
    <fullName>AddressBuilder__c</fullName>
    <defaultValue>&quot;[\&quot;LegalCompanyName__c\&quot;,\&quot;SF_BillTo_Contact__r.Name\&quot;,\&quot;empty\&quot;]&quot;</defaultValue>
    <label>Address Builder (Billing)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/AddressBuilder_Shipping__c.field-meta.xml
<CustomField>
    <fullName>AddressBuilder_Shipping__c</fullName>
    <defaultValue>&quot;[\&quot;LegalCompanyName__c\&quot;,\&quot;SF_SoldTo_Contact__r.Name\&quot;,\&quot;empty\&quot;]&quot;</defaultValue>
    <label>Address Builder (Shipping)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/AddressBuilder_Venue__c.field-meta.xml
<CustomField>
    <fullName>AddressBuilder_Venue__c</fullName>
    <label>Address Builder (Venue)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CustomerID__c.field-meta.xml
<CustomField>
    <fullName>CustomerID__c</fullName>
    <displayFormat>{000000}</displayFormat>
    <externalId>true</externalId>
    <inlineHelpText>Used for external communication, e.g. on the invoice</inlineHelpText>
    <label>Customer ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Account/fields/LegalCompanyName__c.field-meta.xml
<CustomField>
    <fullName>LegalCompanyName__c</fullName>
    <description>Stakeholder: Stakeholders: Sales with Account Management</description>
    <inlineHelpText>What is the company&apos;s legal name for e.g. billing? It is usually in the „about us“/Impressum of websites . If there is an addition such as Gmbh / UG / LDT. / SAS / SL... it’s an operating company. It could however also be a non-incorporated company</inlineHelpText>
    <label>Legal Company Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/myOrderbirdEmail__c.field-meta.xml
<CustomField>
    <fullName>myOrderbirdEmail__c</fullName>
    <description>Stakeholder: CS</description>
    <inlineHelpText>By which email address is this account officially registered on my.orderbird? Filled in as soon as known. Must be updated if changes occur!</inlineHelpText>
    <label>my.orderbird Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>https://jira.orderbird.com/browse/SFDC-1487</description>
    <inlineHelpText>Primary Contact for all relevant communication. Auto-populated after lead conversion.</inlineHelpText>
    <label>Primary Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Contact.Account.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Account.Id</field>
            <operation>equals</operation>
            <valueField>$Source.ParentId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Primary Contact)</relationshipLabel>
    <relationshipName>PrimaryContactForAcc</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/VATNumber__c.field-meta.xml
<CustomField>
    <fullName>VATNumber__c</fullName>
    <description>Stakeholder: Finance</description>
    <inlineHelpText>What is the venues value added tax (VAT)  number of this venue? Filled in by Sales. Required for most non-German EU customers</inlineHelpText>
    <label>VAT Number (Raw)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <formula>TEXT(Account.Account_Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <formula>Account.Primary_Contact__c = Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/VenueContact__c.field-meta.xml
<CustomField>
    <fullName>VenueContact__c</fullName>
    <formula>Account.SF_Venue_Contact__c = Id</formula>
    <label>Venue Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Zuora_BillTo_Contact__c.field-meta.xml
<CustomField>
    <fullName>Zuora_BillTo_Contact__c</fullName>
    <description>Stakeholder: Account Management &amp; Finance</description>
    <formula>Id  =  Account.SF_BillTo_Contact__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Is this contact the billing contact for its Account? This means that the address in this contact needs to be complete and up to date. Checked automatically, when the contact got selected as billing contact on the Account</inlineHelpText>
    <label>Billing Contact (Zuora)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Zuora_SoldTo_Contact__c.field-meta.xml
<CustomField>
    <fullName>Zuora_SoldTo_Contact__c</fullName>
    <description>Stakeholder: Account Management &amp; Finance</description>
    <formula>Id =  Account.SF_SoldTo_Contact__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Is this contact the shipping contact for its Account? This means that the address in this contact needs to be complete and up to date. Checked automatically, when the contact got selected as shipping contact on the Account</inlineHelpText>
    <label>Shipping Contact (Zuora)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>2.0</description>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MyObVenue__c/MyObVenue__c.object-meta.xml
<CustomObject>
    <label>MyOb Venue</label>
    <nameField>
        <displayFormat>MyOb-{000000}</displayFormat>
        <label>MyOb Venue</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MyOb Venues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MyObVenue__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>MyOrderbird_Log_ons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MyObVenue__c/fields/AssignmentSort__c.field-meta.xml
<CustomField>
    <fullName>AssignmentSort__c</fullName>
    <formula>IF( Inactive__c || ISBLANK( MyOrderbirdId__c ) ,0, 

IF(ISBLANK(Days_Since_Last_Shift_Open__c), 
(CreatedDate - DATETIMEVALUE( &quot;1970-01-01 00:00:00&quot; )),
1000000 + IF (Days_Since_Last_Shift_Open__c = 0, 1000001, 1000000/Days_Since_Last_Shift_Open__c))
)</formula>
    <label>Assignment Sort</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MyObVenue__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>MyOrderbird_Log_ons</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/MyObVenue__c/fields/MyOrderbirdId__c.field-meta.xml
<CustomField>
    <fullName>MyOrderbirdId__c</fullName>
    <externalId>true</externalId>
    <label>MyOrderbird Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/MyObVenue__c/fields/Uncertainty__c.field-meta.xml
<CustomField>
    <fullName>Uncertainty__c</fullName>
    <defaultValue>0</defaultValue>
    <description>This field displays how uncertain we are that this connection is valid.

0 = created by link OR created by BI with all parameters matching
1 = created by BI with one parameter not matching
2 = created by BI with two parameters not matching
9 = created by BI and subsequently confirmed by the customer</description>
    <label>Uncertainty</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AccountLightningController.cls
public class AccountLightningController {
  @AuraEnabled
  public static String matchContacts(String MyObVenueId) {
    return JSON.serialize(new ContactMatchWrapper(MyObVenueId));
  }

  @AuraEnabled
  public static void ReparentMyObVenue(String MyObVenueId, String ContactId) {
    List<Account> DeleteAccounts = new List<Account>();
    MyObVenue__c v = [
      SELECT Id, Contact__c, Contact__r.AccountId, Contact__r.Name
      FROM MyObVenue__c
      WHERE Id = :MyObVenueId
      LIMIT 1
    ];
    if (v.Contact__r.Name == 'MyOrderbird Registrant')
      DeleteAccounts.add(new Account(Id = v.Contact__r.AccountId));
    v.Contact__c = ContactId;
    update v;
    delete DeleteAccounts;
  }

  @AuraEnabled
  public static List<MyObVenue__c> getMyObVenues(String AccountId) {
    return [
      SELECT Id, Contact__c, MyOrderbirdId__c, Uncertainty__c
      FROM MyObVenue__c
      WHERE MyOrderbirdId__c != NULL AND Contact__r.AccountId = :AccountId
      ORDER BY AssignmentSort__c DESC, MyOrderbirdId__c
    ];
  }

  @AuraEnabled
  public static String getObWarning(String AccountId) {
    return JSON.serialize(new ObWarningWrapper(AccountId));
  }

  @AuraEnabled
  public static void confirmObVenue(String MyObVenueId) {
    MyObVenue__c v = [
      SELECT Id, Uncertainty__c
      FROM MyObVenue__c
      WHERE Id = :MyObVenueId
      LIMIT 1
    ];
    v.Uncertainty__c = null;
    update v;
  }

  @AuraEnabled
  public static void sendMyObRegistrationEmail(
    String ContactId,
    String Language
  ) {
    AccountLightningController.sendMyObRegistrationEmail(
      ContactId,
      Language,
      null
    );
  }

  @AuraEnabled
  public static void sendMyObRegistrationEmail(
    String ContactId,
    String Language,
    String EmailAddress
  ) {
    MyObVenue__c v = new MyObVenue__c(Contact__c = ContactId);
    insert v;
    CryptAES cs = new CryptAES('AES256');
    String Token = cs.encrypt(v.Id);
    v.Token__c = Token;
    update v;
    if (!Test.isRunningTest())
      EmailAutomater.AutomatedTemplateEmail(
        new List<EmailAutomater.EmailAutomationRequest>{
          new EmailAutomater.EmailAutomationRequest(
            v.Contact__c,
            v.Id,
            'MyOrderbirdRegistration:' + Language,
            EmailAddress
          )
        }
      );
  }

  @AuraEnabled
  public static String getVATVerify(String VATNumber) {
    return JSON.serialize(VIES.checkVAT(VATNumber));
  }

  @AuraEnabled
  public static Boolean saveVAT(
    String AccountId,
    Boolean UpdateAddress,
    String VIES_json
  ) {
    system.debug(AccountId);
    system.debug(VIES_json);
    system.debug(UpdateAddress);
    VIES.VATCheck VIES = (VIES.VATCheck) JSON.deserialize(
      VIES_json,
      VIES.VATCheck.class
    );
    Account a = [
      SELECT
        Id,
        VATNumber__c,
        LegalCompanyName__c,
        BillingStreet,
        BillingCity,
        BillingPostalCode,
        BillingCountryCode
      FROM Account
      WHERE Id = :AccountId
      LIMIT 1
    ];
    try {
      a.VATNumber__c = VIES.vatID;
      a.LegalCompanyName__c = VIES.name;
      update a;
      if (UpdateAddress) {
        AddressWrapper addr = new AddressWrapper(VIES.address, VIES.vatID);
        a.BillingStreet = addr.Street;
        a.BillingCity = addr.City;
        a.BillingPostalCode = addr.PostalCode;
        a.BillingCountryCode = addr.CountryCode;
        update a;
      }
    } catch (exception e) {
      system.debug(e.getMessage());
      system.debug(String.valueOf(e.getLineNumber()));
      return false;
    }
    return true;
  }

  @AuraEnabled
  public static void updateAddressBuilder(
    String AccountId,
    String AddressType,
    String AddressBuilder
  ) {
    Account a = [
      SELECT
        Id,
        AddressBuilder__c,
        AddressBuilder_Shipping__c,
        AddressBuilder_Venue__c
      FROM Account
      WHERE Id = :AccountId
      LIMIT 1
    ];
    String BuilderField = 'AddressBuilder_' + AddressType + '__c';
    a.put(BuilderField.replace('_Billing', ''), AddressBuilder);
    update a;
  }

  @AuraEnabled
  public static String getAddressBuilder(String AccountId, String AddressType) {
    Account a = [
      SELECT
        Id,
        AddressBuilder__c,
        AddressBuilder_Shipping__c,
        AddressBuilder_Venue__c
      FROM Account
      WHERE Id = :AccountId
      LIMIT 1
    ];
    String BuilderField = 'AddressBuilder_' + AddressType + '__c';
    return (String) a.get(BuilderField.replace('_Billing', ''));
  }

  @AuraEnabled
  public static String getAccountContacts(String AccountId) {
    return json.serialize(
      [
        SELECT Id, Name, Email, Phone, MobilePhone
        FROM Contact
        WHERE AccountId = :AccountId
        ORDER BY
          Primary_Contact__c DESC,
          Zuora_SoldTo_Contact__c DESC,
          Zuora_BillTo_Contact__c DESC,
          VenueContact__c DESC,
          LastName,
          FirstName
      ]
    );
  }

  @AuraEnabled
  public static String getRelatedDocuments(String AccountId) {
    return JSON.serialize(new RelDocWrapper(AccountId));
  }

  @AuraEnabled
  public static void replaceBamboraRegId(String VenueId) {
    system.enqueueJob(new BamboraOnboard(VenueId));
  }

  public class ContactMatchWrapper {
    public Contact TargetContact { get; set; }
    public List<Contact> MatchContacts { get; set; }
    public ContactMatchWrapper(String MyObVenueId) {
      TargetContact = [
        SELECT
          Id,
          Email,
          Account.BillingCity,
          Account.BillingCountry,
          Account.Name,
          Account.MyOrderbirdEmail__c
        FROM Contact
        WHERE
          Id IN (SELECT Contact__c FROM MyObVenue__c WHERE Id = :MyObVenueId)
        LIMIT 1
      ];
      MatchContacts = [
        SELECT
          Id,
          Name,
          Email,
          Account.BillingCity,
          Account.BillingCountry,
          Account.Name,
          Account.Account_Status__c,
          Primary_Contact__c,
          Account.CustomerId__c
        FROM Contact
        WHERE
          Id != :TargetContact.Id
          AND (Email = :TargetContact.Email
          OR (Primary_Contact__c = TRUE
          AND Account.Name = :TargetContact.Account.Name)
          OR (Primary_Contact__c = TRUE
          AND Account.MyOrderbirdEmail__c = :TargetContact.Email))
        LIMIT 20
      ];
    }
  }

  public class ObWarningWrapper {
    public Boolean NoWarning { get; set; }
    public Boolean SentEmail { get; set; }
    public String PrimaryContactId { get; set; }
    public String PrimaryContactEmail { get; set; }
    public ObWarningWrapper(String AccountId) {
      NoWarning =
        [
          SELECT Id
          FROM MyObVenue__c
          WHERE MyOrderbirdId__c != NULL AND Contact__r.AccountId = :AccountId
        ]
        .size() > 0;
      if (!NoWarning) {
        SentEmail =
          [SELECT Id FROM MyObVenue__c WHERE Contact__r.AccountId = :AccountId]
          .size() > 0;
        Account a = [
          SELECT Id, Primary_Contact__c, Primary_Contact__r.Email
          FROM Account
          WHERE Id = :AccountId
          LIMIT 1
        ];
        PrimaryContactId = a.Primary_Contact__c;
        PrimaryContactEmail = a.Primary_Contact__r.Email;
      }
    }
  }

  public class RelDocWrapper {
    public List<RelatedDoc> InvoiceDocs { get; set; }
    public List<RelatedDoc> QuoteDocs { get; set; }
    public RelDocWrapper(String AccountId) {
      InvoiceDocs = new List<RelatedDoc>();
      QuoteDocs = new List<RelatedDoc>();
      Map<Id, Invoice__c> InvoiceMap = new Map<Id, Invoice__c>(
        [SELECT Id, Name FROM Invoice__c WHERE Account__c = :AccountId]
      );
      Map<Id, EmailMessage> EmailMessageMap = new Map<Id, EmailMessage>(
        [
          SELECT Id, RelatedToId
          FROM EmailMessage
          WHERE RelatedToId IN :InvoiceMap.keySet()
        ]
      );
      Set<Id> EmailMessageIdSet = EmailMessageMap.keySet();
      if (EmailMessageIdSet.size() > 0) {
        for (ContentDocumentLink CDL : [
          SELECT
            Id,
            LinkedEntityId,
            ContentDocumentId,
            ContentDocument.Title,
            ContentDocument.CreatedDate
          FROM ContentDocumentLink
          WHERE LinkedEntityId IN :EmailMessageIdSet
          ORDER BY ContentDocument.CreatedDate DESC
        ]) {
          InvoiceDocs.add(
            new RelatedDoc(
              CDL.ContentDocumentId,
              CDL.ContentDocument.Title,
              EmailMessageMap.get(CDL.LinkedEntityId).RelatedToId,
              InvoiceMap.get(
                  EmailMessageMap.get(CDL.LinkedEntityId).RelatedToId
                )
                .Name,
              CDL.ContentDocument.CreatedDate
            )
          );
        }
      }
      Map<Id, Quote> QuoteMap = new Map<Id, Quote>(
        [SELECT Id, QuoteNumber FROM Quote WHERE AccountId = :AccountId]
      );
      Set<Id> QuoteIdSet = QuoteMap.keySet();
      if (QuoteIdSet.size() > 0) {
        for (ContentDocumentLink CDL : [
          SELECT
            Id,
            LinkedEntityId,
            ContentDocumentId,
            ContentDocument.Title,
            ContentDocument.CreatedDate
          FROM ContentDocumentLink
          WHERE LinkedEntityId IN :QuoteIdSet
          ORDER BY ContentDocument.CreatedDate DESC
        ]) {
          QuoteDocs.add(
            new RelatedDoc(
              CDL.ContentDocumentId,
              CDL.ContentDocument.Title,
              CDL.LinkedEntityId,
              QuoteMap.get(CDL.LinkedEntityId).QuoteNumber,
              CDL.ContentDocument.CreatedDate
            )
          );
        }
      }
    }
  }

  public class RelatedDoc {
    public String Id { get; set; }
    public String Name { get; set; }
    public String RelatedId { get; set; }
    public String RelatedName { get; set; }
    public DateTime Stamp { get; set; }
    public RelatedDoc(
      String iId,
      String iName,
      String iRelatedId,
      String iRelatedName,
      DateTime iStamp
    ) {
      Id = iId;
      Name = iName;
      RelatedId = iRelatedId;
      RelatedName = iRelatedName;
      Stamp = iStamp;
    }
  }

  public class AddressWrapper {
    public String Street { get; set; }
    public String City { get; set; }
    public String PostalCode { get; set; }
    public String CountryCode { get; set; }
    public AddressWrapper(String rawAddress, String VATId) {
      CountryCode = VATId.substring(0, 2);
      system.debug(VATId + '|' + CountryCode);
      List<String> AddressParts = rawAddress.split('[\n]');
      Street = AddressParts[0];
      for (Integer x = 1; AddressParts.size() > x + 1; x++) {
        Street += '\n' + AddressParts[x];
      }
      List<String> LastLineParts = AddressParts[AddressParts.size() - 1]
        .split(' ', 2);
      City = LastLineParts[1];
      PostalCode = LastLineParts[0];
      if (PostalCode.contains('-'))
        PostalCode = PostalCode.split('-')[1];
    }
  }
}