force-app/main/default/objects/Account/fields/AddressSyncType__c.field-meta.xml
<CustomField>
    <fullName>AddressSyncType__c</fullName>
    <label>Address Sync Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ALL</fullName>
                <default>true</default>
                <label>ALL</label>
            </value>
            <value>
                <fullName>SHIP-VENUE</fullName>
            </value>
            <value>
                <fullName>BILL-SHIP</fullName>
            </value>
            <value>
                <fullName>BILL-VENUE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/VenueCity__c.field-meta.xml
<CustomField>
    <fullName>VenueCity__c</fullName>
    <label>Venue City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/VenueCountry__c.field-meta.xml
<CustomField>
    <fullName>VenueCountry__c</fullName>
    <label>Venue Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/VenuePostalCode__c.field-meta.xml
<CustomField>
    <fullName>VenuePostalCode__c</fullName>
    <label>Venue Postal Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/VenueStreet__c.field-meta.xml
<CustomField>
    <fullName>VenueStreet__c</fullName>
    <label>Venue Street</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/MyObVenue__c/MyObVenue__c.object-meta.xml
<CustomObject>
    <label>MyOb Venue</label>
    <nameField>
        <displayFormat>MyOb-{000000}</displayFormat>
        <label>MyOb Venue</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MyOb Venues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MyObVenue__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>MyOrderbird_Log_ons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MyObVenue__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>MyOrderbird_Log_ons</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/MyObVenue__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created only for Customers that buy a MINI in Shopify</description>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>MyOb Venues</relationshipLabel>
    <relationshipName>MyOb_Venues</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Germany</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Switzerland</fullName>
    </customValue>
    <customValue>
        <fullName>France</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Bulgaria</fullName>
    </customValue>
    <customValue>
        <fullName>China</fullName>
    </customValue>
    <customValue>
        <fullName>Costa Rica</fullName>
    </customValue>
    <customValue>
        <fullName>Cyprus</fullName>
    </customValue>
    <customValue>
        <fullName>Czech Republic</fullName>
    </customValue>
    <customValue>
        <fullName>Denmark</fullName>
    </customValue>
    <customValue>
        <fullName>Dominican Republic</fullName>
    </customValue>
    <customValue>
        <fullName>Egypt</fullName>
    </customValue>
    <customValue>
        <fullName>Estonia</fullName>
    </customValue>
    <customValue>
        <fullName>Finland</fullName>
    </customValue>
    <customValue>
        <fullName>Gambia</fullName>
    </customValue>
    <customValue>
        <fullName>Ghana</fullName>
    </customValue>
    <customValue>
        <fullName>Greece</fullName>
    </customValue>
    <customValue>
        <fullName>Grenada</fullName>
    </customValue>
    <customValue>
        <fullName>Guadeloupe</fullName>
    </customValue>
    <customValue>
        <fullName>Hungary</fullName>
    </customValue>
    <customValue>
        <fullName>Iceland</fullName>
    </customValue>
    <customValue>
        <fullName>India</fullName>
    </customValue>
    <customValue>
        <fullName>Ireland</fullName>
    </customValue>
    <customValue>
        <fullName>Italy</fullName>
    </customValue>
    <customValue>
        <fullName>Liechtenstein</fullName>
    </customValue>
    <customValue>
        <fullName>Luxembourg</fullName>
    </customValue>
    <masterLabel>Countries</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/MiniOnboarding.cls
public class MiniOnboarding {
  public static void sendMyObRegistrationEmailLead(String LeadId) {
    Id ContactId = [SELECT id FROM Contact WHERE Name = 'Shopify Buyer' LIMIT 1]
    .Id;
    MyObVenue__c v = new MyObVenue__c(Contact__c = ContactId, Lead__c = LeadId);
    insert v;
    CryptAES cs = new CryptAES('AES256');
    String Token = cs.encrypt(v.Id);
    v.Token__c = Token;
    update v;

    try {
      EmailAutomater.AutomatedTemplateEmail(
        new List<EmailAutomater.EmailAutomationRequest>{
          new EmailAutomater.EmailAutomationRequest(
            v.Lead__c,
            v.Id,
            'MyOrderbirdRegistration:German', // Known Issue: It only allows the use of German Template
            'supportmini@orderbird.com'
          )
        }
      );
    } catch (Exception e) {
      System.debug('Exception type caught: ' + e.getTypeName());
    }
  }

  public static void updateLeadInfo(MyObVenue__c v, MyOBWrapper payload) {
    //update Lead fields
    v.lead__r.Company = payload.CustomerName != null
      ? payload.CustomerName
      : v.lead__r.Company;
    v.lead__r.city = payload.City != null ? payload.City : v.lead__r.city;
    v.lead__r.CountryCode = payload.CountryCode != null
      ? payload.CountryCode
      : v.lead__r.CountryCode;
    v.lead__r.email = payload.Email != null ? payload.Email : v.lead__r.email;

    update v.lead__r;
  }

  public static void updateAccConInfo(MyObVenue__c v, MyOBWrapper payload) {
    // Update Account and Contact Info related to the Venue object
    v.account__r.Name = payload.CustomerName != null
      ? payload.CustomerName
      : v.account__r.Name;
    v.account__r.VenueStreet__c = payload.Address != null
      ? payload.Address
      : v.account__r.VenueStreet__c;
    v.account__r.VenuePostalCode__c	 = payload.PostalCode != null
      ? payload.PostalCode
      : v.account__r.VenuePostalCode__c	;
    v.account__r.VenueCity__c = payload.City != null
      ? payload.City
      : v.account__r.VenueCity__c;
    v.account__r.VenueCountry__c = payload.Country != null
      ? payload.Country
      : v.account__r.VenueCountry__c;
    v.contact__r.email = payload.Email != null
      ? payload.Email
      : v.contact__r.email;
    v.contact__r.firstName = payload.FirstName != null
      ? payload.FirstName
      : v.contact__r.firstName;
    v.contact__r.lastName = payload.LastName != null
      ? payload.LastName
      : v.contact__r.lastName;
    v.contact__r.phone = payload.Phone != null
      ? payload.Phone
      : v.contact__r.phone;

    // Assign value BILL-SHIP to display the Venue Address in the AddressBuilderNew_Account.cmp in the account record
    if (v.account__r.VenueStreet__c != v.account__r.BillingStreet || v.account__r.VenueStreet__c != v.account__r.ShippingStreet){
      if(v.account__r.ShippingStreet != v.account__r.BillingStreet){
        v.account__r.AddressSyncType__c = null;
      }else{
        v.account__r.AddressSyncType__c = 'BILL-SHIP';
      }
    }

    update v.account__r;
    update v.contact__r;
  }
}