force-app/main/default/objects/Account/fields/AddressBuilder_Shipping__c.field-meta.xml
<CustomField>
    <fullName>AddressBuilder_Shipping__c</fullName>
    <defaultValue>&quot;[\&quot;LegalCompanyName__c\&quot;,\&quot;SF_SoldTo_Contact__r.Name\&quot;,\&quot;empty\&quot;]&quot;</defaultValue>
    <label>Address Builder (Shipping)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/LegalCompanyName__c.field-meta.xml
<CustomField>
    <fullName>LegalCompanyName__c</fullName>
    <description>Stakeholder: Stakeholders: Sales with Account Management</description>
    <inlineHelpText>What is the company&apos;s legal name for e.g. billing? It is usually in the „about us“/Impressum of websites . If there is an addition such as Gmbh / UG / LDT. / SAS / SL... it’s an operating company. It could however also be a non-incorporated company</inlineHelpText>
    <label>Legal Company Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/NetsuiteAddr1__c.field-meta.xml
<CustomField>
    <fullName>NetsuiteAddr1__c</fullName>
    <label>Netsuite Address Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/NetsuiteAddr2__c.field-meta.xml
<CustomField>
    <fullName>NetsuiteAddr2__c</fullName>
    <label>Netsuite Address Line 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SF_BillTo_Contact__c.field-meta.xml
<CustomField>
    <fullName>SF_BillTo_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Stakeholder: Sales &amp; Account Management</description>
    <inlineHelpText>This defines the official billing address.</inlineHelpText>
    <label>Billing Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.ParentId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Zuora BillTo Contact)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/SF_SoldTo_Contact__c.field-meta.xml
<CustomField>
    <fullName>SF_SoldTo_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Stakeholder: Sales &amp; Account Management</description>
    <inlineHelpText>This contact defines the official shipping address.</inlineHelpText>
    <label>Shipping Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.ParentId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/classes/NetsuiteAddressCopier.cls
/*
 * this is intended to be temporary (fingers crossed)
 * it is intended to fill the NetSuite Address Fields for the report entitled
 * "Recently Updated Accounts LAST STATUS UP"
 * 
 */

global class NetsuiteAddressCopier  implements Database.Batchable<sObject>{
    
    global String Query;
    
    global NetsuiteAddressCopier() {
        Query = 'SELECT Id, AddressBuilder_Shipping__c, Name, LegalCompanyName__c, NetsuiteAddr1__c, NetsuiteAddr2__c, '
            + 'SF_SoldTo_Contact__r.Name, SF_SoldTo_Contact__r.FirstName, SF_BillTo_Contact__r.Name, SF_BillTo_Contact__r.FirstName '
            + 'FROM Account ';
        if (!test.isRunningTest()) Query += 'WHERE Id IN (SELECT AccountId FROM AccountHistory WHERE CreatedDate >= YESTERDAY AND Field IN (\'Name\',\'LegalCompanyName__c\',\'AddressBuilder_Shipping__c\'))';
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope){
        for(sObject a : scope){
            system.debug(json.serialize(a));
            Contact c = (Contact)a.getSObject('SF_SoldTo_Contact__r');
            if ((String)a.get('AddressBuilder_Shipping__c') == null) {
                a.put('NetsuiteAddr1__c', (String)a.get('LegalCompanyName__c'));
                a.put('NetsuiteAddr2__c', c.FirstName == '[not provided]' ? null : c.Name);
            } else {
                String abs = ((String)a.get('AddressBuilder_Shipping__c')).replace('\\"','"');
                List<String> Blocks = (List<String>)JSON.deserialize(
                    abs,
                    List<String>.class
                );
                try{a.put('NetsuiteAddr1__c', getAddressLine(a, Blocks[0].split('\\.')));}catch(exception e){ a.put('NetsuiteAddr1__c', null); }
                try{a.put('NetsuiteAddr2__c', getAddressLine(a, Blocks[1].split('\\.')));}catch(exception e){ a.put('NetsuiteAddr2__c', null); }
            }
            if ((String)a.get('NetsuiteAddr1__c') == 'empty' || (String)a.get('NetsuiteAddr1__c') == 'null') a.put('NetsuiteAddr1__c', null);
            if ((String)a.get('NetsuiteAddr2__c') == 'empty' || (String)a.get('NetsuiteAddr2__c') == 'null') a.put('NetsuiteAddr2__c', null);
        }
        update scope;
    }
    
    global String getAddressLine(sObject a, List<String> Fields) {
        try {
            if (Fields.size() == 1) {
                return (String)a.get(Fields[0]);
            }
            return (String)a.getSObject(Fields[0]).get(Fields[1]); 
        } catch(exception e){ return Fields[0]; }
    }
    
    global void finish(Database.BatchableContext BC){
    }
    
}