force-app/main/default/objects/Account/fields/AddressBuilder__c.field-meta.xml
<CustomField>
    <fullName>AddressBuilder__c</fullName>
    <defaultValue>&quot;[\&quot;LegalCompanyName__c\&quot;,\&quot;SF_BillTo_Contact__r.Name\&quot;,\&quot;empty\&quot;]&quot;</defaultValue>
    <label>Address Builder (Billing)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/AddressBuilder_Shipping__c.field-meta.xml
<CustomField>
    <fullName>AddressBuilder_Shipping__c</fullName>
    <defaultValue>&quot;[\&quot;LegalCompanyName__c\&quot;,\&quot;SF_SoldTo_Contact__r.Name\&quot;,\&quot;empty\&quot;]&quot;</defaultValue>
    <label>Address Builder (Shipping)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/AddressSyncType__c.field-meta.xml
<CustomField>
    <fullName>AddressSyncType__c</fullName>
    <label>Address Sync Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ALL</fullName>
                <default>true</default>
                <label>ALL</label>
            </value>
            <value>
                <fullName>SHIP-VENUE</fullName>
            </value>
            <value>
                <fullName>BILL-SHIP</fullName>
            </value>
            <value>
                <fullName>BILL-VENUE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/VenueCity__c.field-meta.xml
<CustomField>
    <fullName>VenueCity__c</fullName>
    <label>Venue City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/VenueCountry__c.field-meta.xml
<CustomField>
    <fullName>VenueCountry__c</fullName>
    <label>Venue Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/VenueCountryCode__c.field-meta.xml
<CustomField>
    <fullName>VenueCountryCode__c</fullName>
    <formula>CASE( TEXT(VenueCountry__c) ,
&quot;Albania&quot;,&quot;AL&quot;,
&quot;Australia&quot;,&quot;AU&quot;,
&quot;Austria&quot;,&quot;AT&quot;,
&quot;Belarus&quot;,&quot;BY&quot;,
&quot;Bulgaria&quot;,&quot;BG&quot;,
&quot;China&quot;,&quot;CN&quot;,
&quot;Costa Rica&quot;,&quot;CR&quot;,
&quot;Cyprus&quot;,&quot;CY&quot;,
&quot;Czech Republic&quot;,&quot;CZ&quot;,
&quot;Denmark&quot;,&quot;DK&quot;,
&quot;Dominican Republic&quot;,&quot;DO&quot;,
&quot;Egypt&quot;,&quot;EG&quot;,
&quot;Estonia&quot;,&quot;EE&quot;,
&quot;Finland&quot;,&quot;FI&quot;,
&quot;France&quot;,&quot;FR&quot;,
&quot;Gambia&quot;,&quot;GM&quot;,
&quot;Germany&quot;,&quot;DE&quot;,
&quot;Ghana&quot;,&quot;GH&quot;,
&quot;Greece&quot;,&quot;GR&quot;,
&quot;Grenada&quot;,&quot;GD&quot;,
&quot;Guadeloupe&quot;,&quot;GP&quot;,
&quot;Hungary&quot;,&quot;HU&quot;,
&quot;Iceland&quot;,&quot;IS&quot;,
&quot;India&quot;,&quot;IN&quot;,
&quot;Ireland&quot;,&quot;IE&quot;,
&quot;Italy&quot;,&quot;IT&quot;,
&quot;Liechtenstein&quot;,&quot;LI&quot;,
&quot;Luxembourg&quot;,&quot;LU&quot;,
&quot;Malaysia&quot;,&quot;MY&quot;,
&quot;Malta&quot;,&quot;MT&quot;,
&quot;Mexico&quot;,&quot;MX&quot;,
&quot;Montenegro&quot;,&quot;ME&quot;,
&quot;Netherlands&quot;,&quot;NL&quot;,
&quot;Norway&quot;,&quot;NO&quot;,
&quot;Peru&quot;,&quot;PE&quot;,
&quot;Philippines&quot;,&quot;PH&quot;,
&quot;Poland&quot;,&quot;PL&quot;,
&quot;Romania&quot;,&quot;RO&quot;,
&quot;Russian Federation&quot;,&quot;RU&quot;,
&quot;Singapore&quot;,&quot;SG&quot;,
&quot;Spain&quot;,&quot;ES&quot;,
&quot;Sri Lanka&quot;,&quot;LK&quot;,
&quot;Swaziland&quot;,&quot;SZ&quot;,
&quot;Sweden&quot;,&quot;SE&quot;,
&quot;Switzerland&quot;,&quot;CH&quot;,
&quot;Tanzania, United Republic of&quot;,&quot;TZ&quot;,
&quot;Thailand&quot;,&quot;TH&quot;,
&quot;Turkey&quot;,&quot;TR&quot;,
&quot;Ukraine&quot;,&quot;UA&quot;,
&quot;United Arab Emirates&quot;,&quot;AE&quot;,
&quot;United Kingdom&quot;,&quot;GB&quot;,
&quot;United States&quot;,&quot;US&quot;,
&quot;Virgin Islands, British&quot;,&quot;VG&quot;,
&quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Venue Country Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/VenuePostalCode__c.field-meta.xml
<CustomField>
    <fullName>VenuePostalCode__c</fullName>
    <label>Venue Postal Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/VenueStreet__c.field-meta.xml
<CustomField>
    <fullName>VenueStreet__c</fullName>
    <label>Venue Street</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/globalValueSets/Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Germany</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Switzerland</fullName>
    </customValue>
    <customValue>
        <fullName>France</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Bulgaria</fullName>
    </customValue>
    <customValue>
        <fullName>China</fullName>
    </customValue>
    <customValue>
        <fullName>Costa Rica</fullName>
    </customValue>
    <customValue>
        <fullName>Cyprus</fullName>
    </customValue>
    <customValue>
        <fullName>Czech Republic</fullName>
    </customValue>
    <customValue>
        <fullName>Denmark</fullName>
    </customValue>
    <customValue>
        <fullName>Dominican Republic</fullName>
    </customValue>
    <customValue>
        <fullName>Egypt</fullName>
    </customValue>
    <customValue>
        <fullName>Estonia</fullName>
    </customValue>
    <customValue>
        <fullName>Finland</fullName>
    </customValue>
    <customValue>
        <fullName>Gambia</fullName>
    </customValue>
    <customValue>
        <fullName>Ghana</fullName>
    </customValue>
    <customValue>
        <fullName>Greece</fullName>
    </customValue>
    <customValue>
        <fullName>Grenada</fullName>
    </customValue>
    <customValue>
        <fullName>Guadeloupe</fullName>
    </customValue>
    <customValue>
        <fullName>Hungary</fullName>
    </customValue>
    <customValue>
        <fullName>Iceland</fullName>
    </customValue>
    <customValue>
        <fullName>India</fullName>
    </customValue>
    <customValue>
        <fullName>Ireland</fullName>
    </customValue>
    <customValue>
        <fullName>Italy</fullName>
    </customValue>
    <customValue>
        <fullName>Liechtenstein</fullName>
    </customValue>
    <customValue>
        <fullName>Luxembourg</fullName>
    </customValue>
    <masterLabel>Countries</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AddressBuilderController.cls
public class AddressBuilderController {
    
    @AuraEnabled
    public Static String getTaskAccountId(String TaskId) {
        Task t = [SELECT Id, Account__c FROM Task WHERE Id = :TaskId LIMIT 1];
        if (t != null) { return t.Account__c; } else { return null; }
    }
    
    @AuraEnabled
    public Static Boolean SyncAddress(String AccountId, String AddressBuilder, String Type) {
        Map<String, String> Prefix = new Map<String, String>{'BILL'=>'Billing', 'SHIP'=>'Shipping', 'VENUE'=>'Venue'};
            Map<String, String> Suffix = new Map<String, String>{'BILL'=>'', 'SHIP'=>'', 'VENUE'=>'__c'};
                List<String> Fields = new List<String>{'Street', 'PostalCode', 'City', 'Country'};
                    Account a = [
                        SELECT Id, AddressSyncType__c, AddressBuilder__c, AddressBuilder_Shipping__c,
                        BillingStreet, BillingPostalCode, BillingCity, BillingCountryCode, BillingCountry,
                        ShippingStreet, ShippingPostalCode, ShippingCity, ShippingCountryCode, ShippingCountry,
                        VenueStreet__c, VenuePostalCode__c, VenueCity__c, VenueCountryCode__c, VenueCountry__c
                        FROM Account
                        WHERE Id = :AccountId
                    ];
        if (Type == 'SHIP') {
            a.AddressBuilder_Shipping__c = AddressBuilder;
        } else if (Type == 'BILL') {
            a.AddressBuilder__c = AddressBuilder;
            if (a.AddressSyncType__c == 'ALL' || a.AddressSyncType__c == 'BILL-SHIP') a.AddressBuilder_Shipping__c = AddressBuilder;
        }
        if (a.AddressSyncType__c != null) {
            Map<String, String> SyncMap = new Map<String, String>();
            if (a.AddressSyncType__c == 'ALL') {
                SyncMap = new Map<String, String>{'VENUE' => 'BILL', 'SHIP' => 'BILL'};
                    } else {
                        SyncMap.put(a.AddressSyncType__c.split('-')[1], a.AddressSyncType__c.split('-')[0]);
                    }
            for (String SyncTo : SyncMap.keySet()) {
                for (String Field : Fields) {
                    a.put(
                        (Prefix.get(SyncTo) + Field + Suffix.get(SyncTo)), 
                        a.get(Prefix.get(SyncMap.get(SyncTo)) + Field + Suffix.get(SyncMap.get(SyncTo)))
                    );
                }
            }
        }
        update a;
        return true;
    }
    
    @AuraEnabled
    public Static void ChangeSyncType(String AccountId, String SyncType, String Winner, String Losers) {
        Map<String, String> Prefix = new Map<String, String>{'BILL'=>'Billing', 'SHIP'=>'Shipping', 'VENUE'=>'Venue'};
            Map<String, String> Suffix = new Map<String, String>{'BILL'=>'', 'SHIP'=>'', 'VENUE'=>'__c'};
                List<String> Fields = new List<String>{'Street', 'PostalCode', 'City', 'Country'};
                    Account a = [
                        SELECT Id, AddressSyncType__c,
                        BillingStreet, BillingPostalCode, BillingCity, BillingCountryCode, BillingCountry,
                        ShippingStreet, ShippingPostalCode, ShippingCity, ShippingCountryCode, ShippingCountry,
                        VenueStreet__c, VenuePostalCode__c, VenueCity__c, VenueCountryCode__c, VenueCountry__c
                        FROM Account
                        WHERE Id = :AccountId
                    ];
        if (Winner != null) {
            for (String Loser : (List<String>)json.deserialize(Losers, List<String>.class)) {
                for (String Field : Fields) {
                    a.put(
                        (Prefix.get(Loser) + Field + Suffix.get(Loser)), 
                        a.get(Prefix.get(Winner) + Field + Suffix.get(Winner))
                    );
                }
            }
        }
        a.AddressSyncType__c = SyncType;
        update a;
    }
}