force-app/main/default/objects/Account/fields/AddressBuilder__c.field-meta.xml
<CustomField>
    <fullName>AddressBuilder__c</fullName>
    <defaultValue>&quot;[\&quot;LegalCompanyName__c\&quot;,\&quot;SF_BillTo_Contact__r.Name\&quot;,\&quot;empty\&quot;]&quot;</defaultValue>
    <label>Address Builder (Billing)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/AddressBuilder_Shipping__c.field-meta.xml
<CustomField>
    <fullName>AddressBuilder_Shipping__c</fullName>
    <defaultValue>&quot;[\&quot;LegalCompanyName__c\&quot;,\&quot;SF_SoldTo_Contact__r.Name\&quot;,\&quot;empty\&quot;]&quot;</defaultValue>
    <label>Address Builder (Shipping)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CustomerID__c.field-meta.xml
<CustomField>
    <fullName>CustomerID__c</fullName>
    <displayFormat>{000000}</displayFormat>
    <externalId>true</externalId>
    <inlineHelpText>Used for external communication, e.g. on the invoice</inlineHelpText>
    <label>Customer ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Account/fields/LegalCompanyName__c.field-meta.xml
<CustomField>
    <fullName>LegalCompanyName__c</fullName>
    <description>Stakeholder: Stakeholders: Sales with Account Management</description>
    <inlineHelpText>What is the company&apos;s legal name for e.g. billing? It is usually in the „about us“/Impressum of websites . If there is an addition such as Gmbh / UG / LDT. / SAS / SL... it’s an operating company. It could however also be a non-incorporated company</inlineHelpText>
    <label>Legal Company Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/PrimaryLanguage__c.field-meta.xml
<CustomField>
    <fullName>PrimaryLanguage__c</fullName>
    <defaultValue>&quot;German&quot;</defaultValue>
    <description>Stakeholder: Sales &amp; CS with MKT</description>
    <inlineHelpText>What language do we use to communicate with this venue? Filled in as soon as known. Updated if necessary!</inlineHelpText>
    <label>Primary Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Language</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/SF_BillTo_Contact__c.field-meta.xml
<CustomField>
    <fullName>SF_BillTo_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Stakeholder: Sales &amp; Account Management</description>
    <inlineHelpText>This defines the official billing address.</inlineHelpText>
    <label>Billing Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.ParentId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Zuora BillTo Contact)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/SF_SoldTo_Contact__c.field-meta.xml
<CustomField>
    <fullName>SF_SoldTo_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Stakeholder: Sales &amp; Account Management</description>
    <inlineHelpText>This contact defines the official shipping address.</inlineHelpText>
    <label>Shipping Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.ParentId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BundleAssignment__c/BundleAssignment__c.object-meta.xml
<CustomObject>
    <label>Product Bundle Assignment</label>
    <nameField>
        <displayFormat>PBAssn-{0000}</displayFormat>
        <label>Product Bundle Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Bundle Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BundleAssignment__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Bundle Assignments</relationshipLabel>
    <relationshipName>Product_Bundle_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BundleAssignment__c/fields/ProductBundle__c.field-meta.xml
<CustomField>
    <fullName>ProductBundle__c</fullName>
    <label>Product Bundle</label>
    <referenceTo>ProductBundle__c</referenceTo>
    <relationshipLabel>Product Bundle Assignments</relationshipLabel>
    <relationshipName>Product_Bundle_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PrimaryLanguage__c.field-meta.xml
<CustomField>
    <fullName>PrimaryLanguage__c</fullName>
    <description>Stakeholder: Sales &amp; CS &amp; MKT</description>
    <inlineHelpText>What language do we use to communicate with this venue? Filled in as soon as known. Updated if necessary!</inlineHelpText>
    <label>Primary Language</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>Russian</fullName>
            </value>
            <value>
                <fullName>Italian</fullName>
            </value>
            <value>
                <fullName>Polish</fullName>
            </value>
            <value>
                <fullName>Chinese</fullName>
            </value>
            <value>
                <fullName>Japanese</fullName>
            </value>
            <value>
                <fullName>Swedish</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Name_DE__c.field-meta.xml
<CustomField>
    <fullName>Product_Name_DE__c</fullName>
    <label>Product Name de-DE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Name_FR__c.field-meta.xml
<CustomField>
    <fullName>Product_Name_FR__c</fullName>
    <label>Product Name fr-FR</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductCategory__c.field-meta.xml
<CustomField>
    <fullName>ProductCategory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Category</label>
    <referenceTo>ProductCategory__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductBundle__c/ProductBundle__c.object-meta.xml
<CustomObject>
    <label>Product Bundle</label>
    <nameField>
        <label>Product Bundle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Bundles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductBundle__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <label>Model</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FlatFee</fullName>
                <default>true</default>
                <label>FlatFee</label>
            </value>
            <value>
                <fullName>PerUnit</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductBundle__c/fields/Name_DE__c.field-meta.xml
<CustomField>
    <fullName>Name_DE__c</fullName>
    <label>Name DE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductBundle__c/fields/Name_FR__c.field-meta.xml
<CustomField>
    <fullName>Name_FR__c</fullName>
    <label>Name FR</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductBundle__c/fields/ProductCategory__c.field-meta.xml
<CustomField>
    <fullName>ProductCategory__c</fullName>
    <label>Product Category</label>
    <referenceTo>ProductCategory__c</referenceTo>
    <relationshipLabel>Product Bundles</relationshipLabel>
    <relationshipName>Product_Bundles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote/fields/InvoiceDate__c.field-meta.xml
<CustomField>
    <fullName>InvoiceDate__c</fullName>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Pay_by_Instalment__c.field-meta.xml
<CustomField>
    <fullName>Pay_by_Instalment__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Does the customer request to pay by three monthly instalments? This automatically adds the instalment fee to the quote. Only available with Bank transfer</inlineHelpText>
    <label>Pay by Instalment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/PaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethod__c</fullName>
    <inlineHelpText>How is the customer going to pay recurring fees? Bank transfer (orderbird charges, SEPA Mandate / Direct Debit) or Wire transfer (customer wires money)?</inlineHelpText>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bank Transfer</fullName>
                <default>true</default>
                <label>Bank Transfer</label>
            </value>
            <value>
                <fullName>Wire Transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/PayPalLink__c.field-meta.xml
<CustomField>
    <fullName>PayPalLink__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PayPal Link</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/PDF_PaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>PDF_PaymentMethod__c</fullName>
    <description>Shows the Payment Method for the related Account, considering the current Billing Process.
This value is rendered in the pdf of the quote.</description>
    <formula>Account_for_Related_List__r.Batch_Payment_Method__c</formula>
    <label>PDF Payment Method</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/VAT_TaxLabel__c.field-meta.xml
<CustomField>
    <fullName>VAT_TaxLabel__c</fullName>
    <formula>CASE( Account_for_Related_List__r.BillingCountry__c  ,
&apos;Germany&apos;,&apos;19%&apos;,
&apos;Austria&apos;, &apos;20% AT&apos;,
&apos;France&apos;, &apos;20% FR&apos;,
&apos;Spain&apos;, &apos;21% ES&apos;,
&apos;Luxembourg&apos;, &apos;17% LX&apos;,
&apos;Netherlands&apos;, &apos;21% NL&apos;,
&apos;0%&apos;)</formula>
    <label>VAT TaxLabel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DiscountProduct__c.field-meta.xml
<CustomField>
    <fullName>DiscountProduct__c</fullName>
    <formula>CONTAINS(Product2.Model__c, &quot;Discount&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Discount Product</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/NonDiscountPriceBundle__c.field-meta.xml
<CustomField>
    <fullName>NonDiscountPriceBundle__c</fullName>
    <formula>IF(
NOT(ISBLANK( ProductBundle__c ))
&amp;&amp;
Quantity &gt; 0
&amp;&amp;
NOT( DiscountProduct__c ),
UnitPrice * Quantity ,
0)</formula>
    <label>Non-Discount Price for Bundle</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/NonDiscountUnitPriceBundle__c.field-meta.xml
<CustomField>
    <fullName>NonDiscountUnitPriceBundle__c</fullName>
    <formula>IF(
NOT(ISBLANK( ProductBundle__c ))
&amp;&amp;
Quantity &gt; 0
&amp;&amp;
NOT( DiscountProduct__c ),
UnitPrice ,
0)</formula>
    <label>Non-Discount Unit Price for Bundle</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ProductBundle__c.field-meta.xml
<CustomField>
    <fullName>ProductBundle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Bundle</label>
    <referenceTo>ProductBundle__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Language.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>German</fullName>
        <default>true</default>
        <label>German</label>
    </customValue>
    <customValue>
        <fullName>English</fullName>
    </customValue>
    <customValue>
        <fullName>French</fullName>
    </customValue>
    <customValue>
        <fullName>Spanish</fullName>
    </customValue>
    <customValue>
        <fullName>Russian</fullName>
    </customValue>
    <customValue>
        <fullName>Italian</fullName>
    </customValue>
    <customValue>
        <fullName>Polish</fullName>
    </customValue>
    <customValue>
        <fullName>Chinese</fullName>
    </customValue>
    <customValue>
        <fullName>Japanese</fullName>
    </customValue>
    <customValue>
        <fullName>Swedish</fullName>
    </customValue>
    <masterLabel>Language</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/QuotePdfController.cls
public class QuotePdfController {
    public String qId {
        get; 
        set {
            qId = value;
            init();
        } 
    }
    public Account Account { get; set; }
    public Boolean UseDiscountTotal { get; set; }
    public Decimal DiscountTotal { get; set; }
    public Decimal NonDiscountTotal { get; set; }
    public Decimal RestartTotal { get; set; }
    public String primaryLanguage { get; set; }
    public String Country { get; set; }
    public List<LineItemWrapper> LineItems { get; set; }
    public List<String> AddressParts { get; set; }
    public List<String> AddressPartsShip { get; set; }
    public Map<Id, ProductBundle__c> BundleMap { get; set; }
    public Quote Quote { get; set; }
    public Boolean VATNewEULaw {get; set;}
    public Boolean Has_GM {get; set;}
    
    public void init() {
        Quote = [
            SELECT 
                Id, AccountId, SubTotal, Tax, TotalPrice, GrandTotal, Owner.Name, Owner.Email, Owner.Phone,
                Opportunity.Owner.Name, Opportunity.Owner.Email, Opportunity.Owner.Phone, Account.CustomerID__c,
                QuoteNumber, ExpirationDate, PaymentMethod__c, Pay_by_Instalment__c, Account.CurrencyIsoCode,
                PayPalLink__c, PDF_PaymentMethod__c, Opportunity.Owner.Profile.Name, VAT_TaxLabel__c, InvoiceDate__c	
            FROM Quote 
            WHERE Id=:qId 
            LIMIT 1
        ];
        
        
        //Defines the date when VAT changes in the Tax Lable applies 
        //for the countries outside of Germany 
        //
        Datetime VATLawStart = date.newInstance(2021, 7, 1); 
        if (quote.invoicedate__c >= VATLawStart){VATNewEULaw = true;}
        else {VATNewEULaw = false;}
        
        //Check if the Quote includes Guest Management Product checking by the Product Category
        //If yes set a boolean as true
        List<QuoteLineItem> GM_Items = [SELECT Id, Product2Id FROM QuoteLineItem
            WHERE QuoteId = :Quote.Id 
            AND Product2.ProductCategory__r.name ='7 F5 Guest Management']; 
       	if (GM_Items.size() > 0) Has_GM = true;
        
        //Wrapping QLI items that do not belong to a bundle
        LineItems = new List<LineItemWrapper>();
        for (QuoteLineItem QLI : [
            SELECT Id, Product2.Name, Product2.ProductCategory__r.Name, Product2.Model__c,
                Product2.Product_Name_DE__c, Product2.Product_Name_FR__c, 
                Quantity, UnitPrice, TotalPrice
            FROM QuoteLineItem
            WHERE QuoteId = :Quote.Id AND ProductBundle__c = null
        ]) {
            LineItems.add(new LineItemWrapper(QLI));
        }
        
        Decimal multiplier = [SELECT ConversionRate FROM CurrencyType WHERE IsoCode = :Quote.Account.CurrencyIsoCode LIMIT 1].ConversionRate;
        
        for (AggregateResult AR : [
            SELECT 
                ProductBundle__r.Name nameEN, 
                ProductBundle__r.Name_DE__c nameDE, 
                ProductBundle__r.Name_FR__c nameFR, 
                ProductBundle__r.ProductCategory__r.Name sorter, 
                ProductBundle__c pbid,
                MAX(Quantity) qty, 
                SUM(UnitPrice) uprice, 
                SUM(TotalPrice) tprice,
                SUM(NonDiscountUnitPriceBundle__c) nduprice,
                SUM(NonDiscountPriceBundle__c) ndprice
            FROM QuoteLineItem
            WHERE QuoteId = :Quote.Id AND ProductBundle__c != null
            GROUP BY ProductBundle__r.Name, ProductBundle__r.ProductCategory__r.Name, 
                ProductBundle__r.Name_DE__c, ProductBundle__r.Name_FR__c, ProductBundle__c
        ]) {
            LineItems.add(new LineItemWrapper(AR, multiplier));
        }

        LineItems.sort();
       
        BundleMap = new Map<Id,ProductBundle__c>([
            SELECT Id, (
                SELECT Product__r.Name, Product__r.Product_Name_DE__c, Product__r.Product_Name_FR__c
                FROM Product_Bundle_Assignments__r
                ORDER BY Product__r.Model__c DESC, Product__r.ProductCategory__r.Name ASC
            )
            FROM ProductBundle__c
        ]);
        
        Account = [
            SELECT Id, Name, OwnerId, CurrencyIsoCode, PrimaryLanguage__c, AddressBuilder__c, AddressBuilder_Shipping__c, LegalCompanyName__c,
                SF_BillTo_Contact__r.Name, BillingStreet, BillingCity, 
                BillingPostalCode, BillingCountry, BillingCountryCode,
                SF_BillTo_Contact__r.FirstName,
                SF_SoldTo_Contact__r.Name, ShippingStreet, ShippingCity, 
                ShippingPostalCode, ShippingCountry, ShippingCountryCode,
                SF_SoldTo_Contact__r.FirstName
            FROM Account 
            WHERE Id = :Quote.AccountId 
            LIMIT 1
        ];
        
        Country = Account.BillingCountry;

        try {
            AddressParts = (List<String>)JSON.deserialize(Account.AddressBuilder__c, List<String>.class);
        } catch(exception e){}

        try {
            AddressPartsShip = (List<String>)JSON.deserialize(Account.AddressBuilder_Shipping__c, List<String>.class);
        } catch(exception e){}

        DiscountTotal = 0;
        NonDiscountTotal = 0;
        RestartTotal = 0;
        for (QuoteLineItem QLI : [
            SELECT 
                Id, DiscountProduct__c, TotalPrice, Product2.Type__c, Product2.Model__c
            FROM QuoteLineItem 
            WHERE QuoteId = :Quote.Id
        ]) {
            if (QLI.DiscountProduct__c) {
                DiscountTotal += QLI.TotalPrice;
            } else {
                NonDiscountTotal += QLI.TotalPrice;
            }
            if (QLI.Product2.Type__c != 'Recurring' || (QLI.Product2.Model__c != 'PerUnit' && QLI.Product2.Model__c != 'FlatFee')) RestartTotal += QLI.TotalPrice;
        }
        UseDiscountTotal = (
            Math.abs(Quote.Subtotal - DiscountTotal - NonDiscountTotal) < 0.01
            && DiscountTotal != 0
        );

        primaryLanguage = LanguageMap.get(Account.PrimaryLanguage__c);

    }

    public Static Map<String, String> LanguageMap = new Map<String, String>{'English'=>'en','German'=>'de',null=>'de','French'=>'fr'};

    public class LineItemWrapper implements Comparable {
        public QuoteLineItem QLI { get; set; }
        public AggregateResult AR { get; set; }
        public Decimal UnitPrice { get; set; }
        public Decimal TotalPrice { get; set; }
        public Decimal StrikeoutUnitPrice { get; set; }
        public Decimal StrikeoutPrice { get; set; }
        public Boolean IsBundle { get; set; }
        public String SortItemOneASC { get; set; }
        public String SortItemTwoDSC { get; set; }
        public LineItemWrapper(QuoteLineItem iQLI) {
            QLI = iQLI;
            IsBundle = false;
            SortItemOneASC = QLI.Product2.ProductCategory__r.Name;
            SortItemTwoDSC = QLI.Product2.Model__c;
        }
        public LineItemWrapper(AggregateResult iAR, Decimal multiplier) {
            AR = iAR;
            UnitPrice = (multiplier * (Decimal)AR.get('uprice')).setScale(2, System.RoundingMode.HALF_UP);
            TotalPrice = (multiplier * (Decimal)AR.get('tprice')).setScale(2, System.RoundingMode.HALF_UP);
            StrikeoutUnitPrice = (multiplier * (Decimal)AR.get('nduprice')).setScale(2, System.RoundingMode.HALF_UP);
            StrikeoutPrice = (multiplier * (Decimal)AR.get('ndprice')).setScale(2, System.RoundingMode.HALF_UP);
            if (StrikeoutUnitPrice == 0 || StrikeoutUnitPrice == UnitPrice) StrikeoutUnitPrice = null;
            if (StrikeoutPrice == 0 || StrikeoutPrice == TotalPrice) StrikeoutPrice = null;
            IsBundle = true;
            SortItemOneASC = (String)AR.get('sorter');
            SortItemTwoDSC = '0';
        }
        public Integer compareTo(Object compareTo) {
            LineItemWrapper compareToLIW = (LineItemWrapper)compareTo;
            if (SortItemOneASC == compareToLIW.SortItemOneASC) {
                if (SortItemTwoDSC > compareToLIW.SortItemTwoDSC) return -1;
                if (SortItemTwoDSC == compareToLIW.SortItemTwoDSC) return 0;
                return 1;
            }
            if (SortItemOneASC > compareToLIW.SortItemOneASC) return 1;
            return -1;
        }
    }

}