force-app/main/default/objects/Account/fields/AddressSyncType__c.field-meta.xml
<CustomField>
    <fullName>AddressSyncType__c</fullName>
    <label>Address Sync Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ALL</fullName>
                <default>true</default>
                <label>ALL</label>
            </value>
            <value>
                <fullName>SHIP-VENUE</fullName>
            </value>
            <value>
                <fullName>BILL-SHIP</fullName>
            </value>
            <value>
                <fullName>BILL-VENUE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CustomerIdText__c.field-meta.xml
<CustomField>
    <fullName>CustomerIdText__c</fullName>
    <description>This exists so that code does not have to consume the auto number. We may occassionally have to edit the autonumber field (temporarily changing the field type) and this cannot be done when it is referenced in code.</description>
    <formula>CustomerID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CustomerIdText</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>https://jira.orderbird.com/browse/SFDC-1487</description>
    <inlineHelpText>Primary Contact for all relevant communication. Auto-populated after lead conversion.</inlineHelpText>
    <label>Primary Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Contact.Account.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Account.Id</field>
            <operation>equals</operation>
            <valueField>$Source.ParentId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Primary Contact)</relationshipLabel>
    <relationshipName>PrimaryContactForAcc</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/SF_BillTo_Contact__c.field-meta.xml
<CustomField>
    <fullName>SF_BillTo_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Stakeholder: Sales &amp; Account Management</description>
    <inlineHelpText>This defines the official billing address.</inlineHelpText>
    <label>Billing Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.ParentId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Zuora BillTo Contact)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/SF_SoldTo_Contact__c.field-meta.xml
<CustomField>
    <fullName>SF_SoldTo_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Stakeholder: Sales &amp; Account Management</description>
    <inlineHelpText>This contact defines the official shipping address.</inlineHelpText>
    <label>Shipping Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.ParentId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Target_Product__c.field-meta.xml
<CustomField>
    <fullName>Target_Product__c</fullName>
    <label>Target Product</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/VenueCity__c.field-meta.xml
<CustomField>
    <fullName>VenueCity__c</fullName>
    <label>Venue City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/VenueCountry__c.field-meta.xml
<CustomField>
    <fullName>VenueCountry__c</fullName>
    <label>Venue Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/VenueCountryCode__c.field-meta.xml
<CustomField>
    <fullName>VenueCountryCode__c</fullName>
    <formula>CASE( TEXT(VenueCountry__c) ,
&quot;Albania&quot;,&quot;AL&quot;,
&quot;Australia&quot;,&quot;AU&quot;,
&quot;Austria&quot;,&quot;AT&quot;,
&quot;Belarus&quot;,&quot;BY&quot;,
&quot;Bulgaria&quot;,&quot;BG&quot;,
&quot;China&quot;,&quot;CN&quot;,
&quot;Costa Rica&quot;,&quot;CR&quot;,
&quot;Cyprus&quot;,&quot;CY&quot;,
&quot;Czech Republic&quot;,&quot;CZ&quot;,
&quot;Denmark&quot;,&quot;DK&quot;,
&quot;Dominican Republic&quot;,&quot;DO&quot;,
&quot;Egypt&quot;,&quot;EG&quot;,
&quot;Estonia&quot;,&quot;EE&quot;,
&quot;Finland&quot;,&quot;FI&quot;,
&quot;France&quot;,&quot;FR&quot;,
&quot;Gambia&quot;,&quot;GM&quot;,
&quot;Germany&quot;,&quot;DE&quot;,
&quot;Ghana&quot;,&quot;GH&quot;,
&quot;Greece&quot;,&quot;GR&quot;,
&quot;Grenada&quot;,&quot;GD&quot;,
&quot;Guadeloupe&quot;,&quot;GP&quot;,
&quot;Hungary&quot;,&quot;HU&quot;,
&quot;Iceland&quot;,&quot;IS&quot;,
&quot;India&quot;,&quot;IN&quot;,
&quot;Ireland&quot;,&quot;IE&quot;,
&quot;Italy&quot;,&quot;IT&quot;,
&quot;Liechtenstein&quot;,&quot;LI&quot;,
&quot;Luxembourg&quot;,&quot;LU&quot;,
&quot;Malaysia&quot;,&quot;MY&quot;,
&quot;Malta&quot;,&quot;MT&quot;,
&quot;Mexico&quot;,&quot;MX&quot;,
&quot;Montenegro&quot;,&quot;ME&quot;,
&quot;Netherlands&quot;,&quot;NL&quot;,
&quot;Norway&quot;,&quot;NO&quot;,
&quot;Peru&quot;,&quot;PE&quot;,
&quot;Philippines&quot;,&quot;PH&quot;,
&quot;Poland&quot;,&quot;PL&quot;,
&quot;Romania&quot;,&quot;RO&quot;,
&quot;Russian Federation&quot;,&quot;RU&quot;,
&quot;Singapore&quot;,&quot;SG&quot;,
&quot;Spain&quot;,&quot;ES&quot;,
&quot;Sri Lanka&quot;,&quot;LK&quot;,
&quot;Swaziland&quot;,&quot;SZ&quot;,
&quot;Sweden&quot;,&quot;SE&quot;,
&quot;Switzerland&quot;,&quot;CH&quot;,
&quot;Tanzania, United Republic of&quot;,&quot;TZ&quot;,
&quot;Thailand&quot;,&quot;TH&quot;,
&quot;Turkey&quot;,&quot;TR&quot;,
&quot;Ukraine&quot;,&quot;UA&quot;,
&quot;United Arab Emirates&quot;,&quot;AE&quot;,
&quot;United Kingdom&quot;,&quot;GB&quot;,
&quot;United States&quot;,&quot;US&quot;,
&quot;Virgin Islands, British&quot;,&quot;VG&quot;,
&quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Venue Country Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/VenuePostalCode__c.field-meta.xml
<CustomField>
    <fullName>VenuePostalCode__c</fullName>
    <label>Venue Postal Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/VenueStreet__c.field-meta.xml
<CustomField>
    <fullName>VenueStreet__c</fullName>
    <label>Venue Street</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>This record type is used for customer accounts and the standard Sales process.</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <formula>Account.Primary_Contact__c = Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Lead/fields/Target_Product__c.field-meta.xml
<CustomField>
    <fullName>Target_Product__c</fullName>
    <formula>IF( OR(LAC_ID__c = &quot;180&quot;,LAC_ID__c = &quot;181&quot;), &quot;MINI&quot;, &quot;PRO&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Target Product</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <businessProcess>Lead Process for Sales</businessProcess>
    <description>to create a new lead for a potential customer</description>
    <label>Customer Lead</label>
</RecordType>

force-app/main/default/objects/MyObVenue__c/MyObVenue__c.object-meta.xml
<CustomObject>
    <label>MyOb Venue</label>
    <nameField>
        <displayFormat>MyOb-{000000}</displayFormat>
        <label>MyOb Venue</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MyOb Venues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MyObVenue__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>MyOrderbird_Log_ons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MyObVenue__c/fields/BamboraId__c.field-meta.xml
<CustomField>
    <fullName>BamboraId__c</fullName>
    <label>Bambora Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MyObVenue__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>MyOrderbird_Log_ons</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/MyObVenue__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created only for Customers that buy a MINI in Shopify</description>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>MyOb Venues</relationshipLabel>
    <relationshipName>MyOb_Venues</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MyObVenue__c/fields/MyOrderbirdId__c.field-meta.xml
<CustomField>
    <fullName>MyOrderbirdId__c</fullName>
    <externalId>true</externalId>
    <label>MyOrderbird Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/MyObVenue__c/fields/Target_Product__c.field-meta.xml
<CustomField>
    <fullName>Target_Product__c</fullName>
    <formula>Account__r.Target_Product__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Target Product</label>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Germany</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Switzerland</fullName>
    </customValue>
    <customValue>
        <fullName>France</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Bulgaria</fullName>
    </customValue>
    <customValue>
        <fullName>China</fullName>
    </customValue>
    <customValue>
        <fullName>Costa Rica</fullName>
    </customValue>
    <customValue>
        <fullName>Cyprus</fullName>
    </customValue>
    <customValue>
        <fullName>Czech Republic</fullName>
    </customValue>
    <customValue>
        <fullName>Denmark</fullName>
    </customValue>
    <customValue>
        <fullName>Dominican Republic</fullName>
    </customValue>
    <customValue>
        <fullName>Egypt</fullName>
    </customValue>
    <customValue>
        <fullName>Estonia</fullName>
    </customValue>
    <customValue>
        <fullName>Finland</fullName>
    </customValue>
    <customValue>
        <fullName>Gambia</fullName>
    </customValue>
    <customValue>
        <fullName>Ghana</fullName>
    </customValue>
    <customValue>
        <fullName>Greece</fullName>
    </customValue>
    <customValue>
        <fullName>Grenada</fullName>
    </customValue>
    <customValue>
        <fullName>Guadeloupe</fullName>
    </customValue>
    <customValue>
        <fullName>Hungary</fullName>
    </customValue>
    <customValue>
        <fullName>Iceland</fullName>
    </customValue>
    <customValue>
        <fullName>India</fullName>
    </customValue>
    <customValue>
        <fullName>Ireland</fullName>
    </customValue>
    <customValue>
        <fullName>Italy</fullName>
    </customValue>
    <customValue>
        <fullName>Liechtenstein</fullName>
    </customValue>
    <customValue>
        <fullName>Luxembourg</fullName>
    </customValue>
    <masterLabel>Countries</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CustomerDataAPI.cls
@RestResource(urlMapping='/customerdata')
global class CustomerDataAPI {
@HttpPut
  global static void updateCustomerData() {
    // define Payload
    RestRequest req = System.RestContext.request;
		System.debug(req.requestBody.size());
      System.debug(req.requestBody.toString());
    MyOBWrapper payload = (MyOBWrapper) JSON.deserialize(
      req.requestBody.toString(),
      MyOBWrapper.class
    );
	System.debug(payload);
    // No authentication for the call

    // Find customer
    Id keyId = payload.applicationId;
    MyObVenue__c MyObVenue = QueryVenue(keyId);
    
    try {
      MiniOnboarding.updateAccConInfo(MyObVenue, payload);
    } catch (DmlException e) {
      System.RestContext.response.responseBody = Blob.valueOf(BadSave());
      throw e;
    }

    String CustomerId = MyObVenue.account__r.customeridtext__c;
	
    //send Bambora/Worldline Onboarding email to MINI customers
      if (!Test.isRunningTest()&&
        MyObVenue.BamboraId__c == null &&
        MyObVenue.account__r.Target_Product__c == 'MINI')
        System.enqueueJob(new BamboraOnboard(MyObVenue.Id));
      
    System.RestContext.response.responseBody = Blob.valueOf(
      JSON.serialize(new ResponseWrapper(CustomerId, MyObVenue, keyId))
    );
  }

@HttpPost
  global static void registerMyObVenue() {
    String CustomerId;
    CryptAES cs = new CryptAES('AES256');
    RestRequest req = System.RestContext.request;
    MyOBWrapper payload = (MyOBWrapper) JSON.deserialize(
      req.requestBody.toString(),
      MyOBWrapper.class
    );

    Map<String, Object> reqMap = (Map<String, Object>) JSON.deserializeUntyped(
      req.requestBody.toString()
    );
    system.debug(json.serialize(reqMap));

    //authenticate
    try {
      List<String> AuthHeader = req.headers.get('Auth').split(' ');
      String accessToken;
      if (AuthHeader.size() == 2 && AuthHeader[0] == 'bearer')
        accessToken = AuthHeader[1];
      if (cs.decrypt(accessToken) != 'My.Orderbird')
        System.RestContext.response.responseBody = Blob.valueOf(BadToken());
    } catch (exception e) {
      System.RestContext.response.responseBody = Blob.valueOf(BadToken());
    }

    //find customer
    String keyToken = payload.keyToken;
    String myObId = payload.venueId;
    String keyId = null;
    if (myObId == null)
      System.RestContext.response.responseBody = Blob.valueOf(MissingMyObId());
    /*
    //OUTDATED Process that enabled customers to register without using a Token
    //This must not be possible anymore.

    if (keyToken == null) {
      Contact c = new Contact(
        firstname = 'MyOrderbird',
        lastname = 'Registrant',
        email = (String) reqMap.get('email')
      );
      insert c;
      Account a = new Account(
        name = (String) reqMap.get('name'),
        primary_contact__c = c.id,
        sf_billto_contact__c = c.id,
        sf_soldto_contact__c = c.id,
        Venuecountry__c = (String) reqMap.get('country'),
        Venuecity__c = (String) reqMap.get('city')
      );
      try {
        insert a;
      } catch (exception e) {
        a.VenueCountry__c = null;
        insert a;
      }
      c.AccountId = a.Id;
      update c;
      MyObVenue__c m = new MyObVenue__c(Contact__c = c.Id);
      insert m;
      keyId = m.Id;
    }
    */

    if (keyId == null) {
      keyId = cs.decrypt(keyToken);
    }

    MyObVenue__c MyObVenue = QueryVenue(keyId);
	    
    if (MyObVenue.MyOrderbirdId__c != null) {
      System.RestContext.response.responseBody = Blob.valueOf(BadSave());
    } else {
      MyObVenue.MyOrderbirdId__c = myObId;
      if (MyObVenue.Lead__c != null) {
        CustomerId = null;
        MiniOnboarding.updateLeadInfo(MyObVenue, payload);
        System.enqueueJob(new MiniConverter(MyObVenue.Lead__c));
      } else {
        CustomerId = MyObVenue.account__r.customeridtext__c;
        // MiniOnboarding.updateAccConInfo(MyObVenue, payload);
      	
        //send Bambora/Worldline Onboarding email to PRO customers
        if (!Test.isRunningTest())
        System.enqueueJob(new BamboraOnboard(MyObVenue.Id));
      }
      update MyObVenue;
      

      System.RestContext.response.responseBody = Blob.valueOf(
        JSON.serialize(new ResponseWrapper(CustomerId, MyObVenue, keyId))
      );
    }
  }

  @HttpGet
  global static void getCustomerInfo() {
    CryptAES cs = new CryptAES('AES256');
    RestRequest req = System.RestContext.request;

    //authenticate
    try {
      List<String> AuthHeader = req.headers.get('Auth').split(' ');
      String accessToken;
      if (AuthHeader.size() == 2 && AuthHeader[0] == 'bearer')
        accessToken = AuthHeader[1];
      if (cs.decrypt(accessToken) != 'My.Orderbird')
        System.RestContext.response.responseBody = Blob.valueOf(BadToken());
    } catch (exception e) {
      System.RestContext.response.responseBody = Blob.valueOf(BadToken());
    }

    //find customer
    String keyToken = req.params.get('keyToken');
    if (keyToken == null)
      System.RestContext.response.responseBody = Blob.valueOf(MissingKey());
    else {
      String keyId = cs.decrypt(keyToken);
      MyObVenue__c MyObVenue = QueryVenue(keyId);
      System.debug(MyObVenue);
     
      if (MyObVenue.MyOrderbirdId__c == null) {
        System.RestContext.response.responseBody = Blob.valueOf(
          JSON.serialize(new ResponseWrapper(MyObVenue))
        );
      } else {
        System.RestContext.response.responseBody = Blob.valueOf(BadSave());
      }
    }
  }

  public class ResponseWrapper {
    public String CustomerId { get; set; }
    public String ApplicationId { get; set; }
    public String CustomerName { get; set; }
    public String FirstName { get; set; }
    public String LastName { get; set; }
    public String Address { get; set; }
    public String PostalCode { get; set; }
    public String City { get; set; }
    public String CountryCode { get; set; }
    public String Phone { get; set; }
    public String Email { get; set; }
    public String VenueId { get; set; }
    public List<String> Products { get; set; }

    public ResponseWrapper(String custId, MyObVenue__c v, String vId) {
      CustomerId = custId;
      ApplicationId = vId;
      VenueId = v.MyOrderbirdId__c;
    }

    public ResponseWrapper(MyObVenue__c v) {
      //condition for all Venues that are connected with Placeholder Account for Shopify Device Buyers
      if (v.Account__r.Name == 'Shopify') {
        CustomerId = null;
        ApplicationId = v.Id != null ? v.id : null;
        CustomerName = v.lead__r.company != null ? v.lead__r.company : null;
        FirstName = v.lead__r.firstName != null ? v.lead__r.firstname : null;
        LastName = v.lead__r.lastName != null ? v.lead__r.lastName : null;
        City = v.lead__r.city != null ? v.lead__r.city : null;
        CountryCode = v.lead__r.CountryCode != null
          ? v.lead__r.countrycode
          : null;
        Email = v.lead__r.Email != null ? v.lead__r.email : null;
        Address = v.lead__r.street != null ? v.lead__r.street : null;
        PostalCode = v.lead__r.postalcode != null ? v.lead__r.postalcode : null;
        Phone = v.lead__r.phone != null ? v.lead__r.phone : null;
        Products = new List<String>{ 'MINI' };
        //condition for all the other Venues
      } else {
        CustomerId = v.Account__r.CustomerIdText__c != null
          ? v.account__r.customeridtext__c
          : null;
        ApplicationId = v.Id;
        CustomerName = v.Account__r.Name != null ? v.account__r.name : null;
        FirstName = v.contact__r.firstName != null
          ? v.contact__r.firstname
          : null;
        LastName = v.contact__r.lastName != null ? v.contact__r.lastname : null;
        City = v.Account__r.Venuecity__c != null
          ? v.account__r.Venuecity__c
          : null;
        CountryCode = v.Account__r.VenueCountryCode__c != null
          ? v.account__r.VenueCountryCode__c
          : null;
        Email = v.Contact__r.Email != null ? v.contact__r.Email : null;
        Address = v.Account__r.VenueStreet__c != null
          ? v.account__r.VenueStreet__c
          : null;
        PostalCode = v.Account__r.VenuePostalCode__c != null
          ? v.account__r.VenuePostalCode__c
          : null;
        Phone = v.Contact__r.phone != null ? v.contact__r.phone : null;
        Products = v.Account__r.Target_Product__c == null
          ? new List<String>{ 'PRO' }
          : v.Account__r.Target_Product__c.replace(' ', '').split(';');
      }
    }
  }

  private static MyObVenue__c QueryVenue(Id venueId) {
    MyObVenue__c Venue;
    try {
      Venue = [
        SELECT
          id,
          myorderbirdid__c,
          BamboraId__c,
          account__c,
          account__r.Name,
          account__r.CustomerIdText__c,
          account__r.Target_Product__c,
          account__r.VenueCity__c,
          account__r.VenueCountry__c,
          account__r.VenueCountryCode__c,
          account__r.Venuepostalcode__c,
          account__r.Venuestreet__c,
          account__r.BillingStreet,
          account__r.ShippingStreet,
          account__r.AddressSyncType__c,
          contact__c,
          contact__r.Email,
          contact__r.FirstName,
          contact__r.lastname,
          contact__r.phone,
          lead__c,
          lead__r.firstName,
          lead__r.lastname,
          lead__r.company,
          lead__r.Email,
          lead__r.street,
          lead__r.city,
          lead__r.postalcode,
          lead__r.countrycode,
          lead__r.phone
        FROM MyObVenue__c
        WHERE Id = :venueId
        LIMIT 1
      ];
    } catch (Exception e) {
      System.RestContext.response.responseBody = Blob.valueOf(NoSuchKey());
      throw e;
    }
    return Venue;
  }

  public static String BadToken() {
    RestContext.response.statusCode = 401;
    return '{"Error":"Could not authenticate. Bad or missing Authentication header."}';
  }

  public static String NoSuchKey() {
    RestContext.response.statusCode = 404;
    return '{"Error":"Key Token not found in Server."}';
  }

  public static String MissingKey() {
    RestContext.response.statusCode = 400;
    return '{"Error":"Key Token not provided."}';
  }

  public static String MissingMyObId() {
    RestContext.response.statusCode = 400;
    return '{"Error":"Venue Id not provided."}';
  }

  public static String BadSave() {
    RestContext.response.statusCode = 500;
    return '{"Error":"Internal Server Error."}';
  }
}