force-app/main/default/objects/Account/fields/Address_Error__c.field-meta.xml
<CustomField>
    <fullName>Address_Error__c</fullName>
    <formula>( TEXT(AddressSyncType__c) = &apos;ALL&apos; || TEXT(AddressSyncType__c) = &apos;BILL-VENUE&apos;)
&amp;&amp; (
(BillingStreet &lt;&gt; VenueStreet__c )
||(BillingCity &lt;&gt; VenueCity__c )
||(BillingPostalCode &lt;&gt; VenuePostalCode__c )
||(BillingCountry &lt;&gt; text(VenueCountry__c) )
)
&amp;&amp;  !(CONTAINS( SF_BillTo_Contact__r.FirstName , &quot;MyOrderbird&quot;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Address Error</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/AddressBuilder__c.field-meta.xml
<CustomField>
    <fullName>AddressBuilder__c</fullName>
    <defaultValue>&quot;[\&quot;LegalCompanyName__c\&quot;,\&quot;SF_BillTo_Contact__r.Name\&quot;,\&quot;empty\&quot;]&quot;</defaultValue>
    <label>Address Builder (Billing)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/AddressBuilder_Shipping__c.field-meta.xml
<CustomField>
    <fullName>AddressBuilder_Shipping__c</fullName>
    <defaultValue>&quot;[\&quot;LegalCompanyName__c\&quot;,\&quot;SF_SoldTo_Contact__r.Name\&quot;,\&quot;empty\&quot;]&quot;</defaultValue>
    <label>Address Builder (Shipping)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/AddressBuilderMatch__c.field-meta.xml
<CustomField>
    <fullName>AddressBuilderMatch__c</fullName>
    <formula>SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(AddressBuilder__c,&quot;Bill&quot;,&quot;Sold&quot;),&quot;,null&quot;,&quot;&quot;),&quot;,\&quot;empty\&quot;&quot;,&quot;&quot;) = 
SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(AddressBuilder_Shipping__c,&quot;Bill&quot;,&quot;Sold&quot;),&quot;,null&quot;,&quot;&quot;),&quot;,\&quot;empty\&quot;&quot;,&quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>AddressBuilderMatch</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/AddressSyncType__c.field-meta.xml
<CustomField>
    <fullName>AddressSyncType__c</fullName>
    <label>Address Sync Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ALL</fullName>
                <default>true</default>
                <label>ALL</label>
            </value>
            <value>
                <fullName>SHIP-VENUE</fullName>
            </value>
            <value>
                <fullName>BILL-SHIP</fullName>
            </value>
            <value>
                <fullName>BILL-VENUE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/SF_BillTo_Contact__c.field-meta.xml
<CustomField>
    <fullName>SF_BillTo_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Stakeholder: Sales &amp; Account Management</description>
    <inlineHelpText>This defines the official billing address.</inlineHelpText>
    <label>Billing Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.ParentId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Zuora BillTo Contact)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/SF_SoldTo_Contact__c.field-meta.xml
<CustomField>
    <fullName>SF_SoldTo_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Stakeholder: Sales &amp; Account Management</description>
    <inlineHelpText>This contact defines the official shipping address.</inlineHelpText>
    <label>Shipping Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.ParentId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/SF_Venue_Contact__c.field-meta.xml
<CustomField>
    <fullName>SF_Venue_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This contact defines the physical address of the venue.</inlineHelpText>
    <label>Venue Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.ParentId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Venue Contact)</relationshipLabel>
    <relationshipName>Accounts3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/VenueCity__c.field-meta.xml
<CustomField>
    <fullName>VenueCity__c</fullName>
    <label>Venue City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/VenueCountry__c.field-meta.xml
<CustomField>
    <fullName>VenueCountry__c</fullName>
    <label>Venue Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/VenuePostalCode__c.field-meta.xml
<CustomField>
    <fullName>VenuePostalCode__c</fullName>
    <label>Venue Postal Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/VenueStreet__c.field-meta.xml
<CustomField>
    <fullName>VenueStreet__c</fullName>
    <label>Venue Street</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Addressee__c.field-meta.xml
<CustomField>
    <fullName>Addressee__c</fullName>
    <inlineHelpText>This field can be selected within Address Builder</inlineHelpText>
    <label>OUTDATED Addressee</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Attention__c.field-meta.xml
<CustomField>
    <fullName>Attention__c</fullName>
    <inlineHelpText>This field can be selected within Address Builder</inlineHelpText>
    <label>OUTDATED Attention</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/globalValueSets/Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Germany</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Switzerland</fullName>
    </customValue>
    <customValue>
        <fullName>France</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Bulgaria</fullName>
    </customValue>
    <customValue>
        <fullName>China</fullName>
    </customValue>
    <customValue>
        <fullName>Costa Rica</fullName>
    </customValue>
    <customValue>
        <fullName>Cyprus</fullName>
    </customValue>
    <customValue>
        <fullName>Czech Republic</fullName>
    </customValue>
    <customValue>
        <fullName>Denmark</fullName>
    </customValue>
    <customValue>
        <fullName>Dominican Republic</fullName>
    </customValue>
    <customValue>
        <fullName>Egypt</fullName>
    </customValue>
    <customValue>
        <fullName>Estonia</fullName>
    </customValue>
    <customValue>
        <fullName>Finland</fullName>
    </customValue>
    <customValue>
        <fullName>Gambia</fullName>
    </customValue>
    <customValue>
        <fullName>Ghana</fullName>
    </customValue>
    <customValue>
        <fullName>Greece</fullName>
    </customValue>
    <customValue>
        <fullName>Grenada</fullName>
    </customValue>
    <customValue>
        <fullName>Guadeloupe</fullName>
    </customValue>
    <customValue>
        <fullName>Hungary</fullName>
    </customValue>
    <customValue>
        <fullName>Iceland</fullName>
    </customValue>
    <customValue>
        <fullName>India</fullName>
    </customValue>
    <customValue>
        <fullName>Ireland</fullName>
    </customValue>
    <customValue>
        <fullName>Italy</fullName>
    </customValue>
    <customValue>
        <fullName>Liechtenstein</fullName>
    </customValue>
    <customValue>
        <fullName>Luxembourg</fullName>
    </customValue>
    <masterLabel>Countries</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AddressMigration.cls
global class AddressMigration implements Database.Batchable<sObject>{
    
    global String Filter;
    
    global AddressMigration() {
        Filter = '';
    }
    
    global AddressMigration(String f) {
        Filter = f;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        String Query = 'SELECT Id, '
            + 'BillingStreet, BillingCity, BillingPostalCode, BillingCountry, '
            + 'ShippingStreet, ShippingCity, ShippingPostalCode, ShippingCountry, '
            + 'VenueStreet__c, VenueCity__c, VenuePostalCode__c, VenueCountry__c, '
            + 'SF_BillTo_Contact__c, SF_SoldTo_Contact__c, SF_Venue_Contact__c, '
            + 'SF_BillTo_Contact__r.MailingStreet, SF_BillTo_Contact__r.MailingCity, SF_BillTo_Contact__r.MailingPostalCode, SF_BillTo_Contact__r.MailingCountry, '
            + 'SF_SoldTo_Contact__r.MailingStreet, SF_SoldTo_Contact__r.MailingCity, SF_SoldTo_Contact__r.MailingPostalCode, SF_SoldTo_Contact__r.MailingCountry, '
            + 'SF_Venue_Contact__r.MailingStreet, SF_Venue_Contact__r.MailingCity, SF_Venue_Contact__r.MailingPostalCode, SF_Venue_Contact__r.MailingCountry, '
            + 'AddressSyncType__c, AddressBuilder__c, AddressBuilder_Shipping__c, AddressBuilderMatch__c, SF_BillTo_Contact__r.FirstName, SF_SoldTo_Contact__r.FirstName, '
            + 'SF_BillTo_Contact__r.Attention__c, SF_BillTo_Contact__r.Addressee__c, SF_SoldTo_Contact__r.Attention__c, SF_SoldTo_Contact__r.Addressee__c '
            + 'FROM Account WHERE Address_Error__c = true';
        Query += Filter;
        return Database.getQueryLocator(Query);
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope){
        /*Map<String, String> AddressMap = new Map<String, String>{'Billing' => 'SF_BillTo_Contact__r', 'Shipping' => 'SF_SoldTo_Contact__r', 'Venue' => 'SF_Venue_Contact__r'};
        List<String> AddressTypes = new List<String>{'Street', 'City', 'PostalCode', 'Country'};
        Map<String, String> ContactTypes = new Map<String, String>{'SF_BillTo_Contact__r' => 'AddressBuilder__c', 'SF_SoldTo_Contact__r' => 'AddressBuilder_Shipping__c'};
        for (sObject s : scope) {
            for (String addr : AddressMap.keySet()) {
                for (String type : AddressTypes) {
                    String Field = addr + type;
                    if (addr == 'Venue') Field += '__c';
                    if (s.getSObject(AddressMap.get(addr)) != null) {
                        s.put(Field, (String)s.getSObject(AddressMap.get(addr)).get('Mailing' + type));
                    } else {
                        s.put(Field, null);
                    }
                }
            }
            for (String ct : ContactTypes.keySet()) {
                String AddressBuilder = (String)s.get(ContactTypes.get(ct));
                if (s.getSObject(ct) != null) {
                    if (AddressBuilder == null && (String)s.getSObject(ct).get('FirstName') == '[not provided]') AddressBuilder = '["'+ct+'.Addressee__c","'+ct+'.Attention__c","empty"]';
                    if (AddressBuilder != null && ((String)s.getSObject(ct).get('Attention__c')) != null) AddressBuilder = AddressBuilder.replace((ct+'.Attention__c'), ((String)s.getSObject(ct).get('Attention__c')));
                    if (AddressBuilder != null && ((String)s.getSObject(ct).get('Addressee__c')) != null) AddressBuilder = AddressBuilder.replace((ct+'.Addressee__c'), ((String)s.getSObject(ct).get('Addressee__c')));
                }
                s.put(ContactTypes.get(ct), AddressBuilder);
            }
            Boolean MatchBS = (String)s.get('SF_BillTo_Contact__c') == (String)s.get('SF_SoldTo_Contact__c') && (Boolean)s.get('AddressBuilderMatch__c');
            Boolean MatchBV = (String)s.get('SF_BillTo_Contact__c') == (String)s.get('SF_Venue_Contact__c') || (String)s.get('SF_Venue_Contact__c') == null;
            Boolean MatchSV = (String)s.get('SF_SoldTo_Contact__c') == (String)s.get('SF_Venue_Contact__c') || (String)s.get('SF_Venue_Contact__c') == null;
            if (MatchBS) s.put('AddressSyncType__c', 'BILL-SHIP');
            if (MatchSV) s.put('AddressSyncType__c', 'SHIP-VENUE');
            if (MatchBV) s.put('AddressSyncType__c', 'BILL-VENUE');
            if (MatchBS && MatchBV) s.put('AddressSyncType__c', 'ALL');
        }*/
        for (sObject s : scope) {
            s.put('VenueStreet__c', (String)s.get('BillingStreet'));
            s.put('VenueCity__c', (String)s.get('BillingCity'));
            s.put('VenuePostalCode__c', (String)s.get('BillingPostalCode'));
            s.put('VenueCountry__c', (String)s.get('BillingCountry'));
        }
        update scope;
    }
    
    global void finish(Database.BatchableContext BC){}
    
}