force-app/main/default/objects/Account/fields/Batch7_Age__c.field-meta.xml
<CustomField>
    <fullName>Batch7_Age__c</fullName>
    <label>Batch7 Age</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Batch__c.field-meta.xml
<CustomField>
    <fullName>Batch__c</fullName>
    <label>Billing Batch</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Closed_Contract_Date__c.field-meta.xml
<CustomField>
    <fullName>Closed_Contract_Date__c</fullName>
    <formula>if( text(AccountType__c) = &quot;Partner&quot; , null ,
IF(and(isnull(
if(BillingAmount__c&gt;0,CCD_Zu__c,null)),isnull(CCD_NetSuite__c),isnull(CCD_IO2__c)),null,
TODAY()-max(
if(isnull(TODAY()-
if(BillingAmount__c&gt;0,CCD_Zu__c,null)),0,TODAY()-
if(BillingAmount__c&gt;0,CCD_Zu__c,null)),
if(isnull(TODAY()-CCD_IO2__c),0,TODAY()-CCD_IO2__c),
if(isnull(TODAY()-CCD_NetSuite__c),0,TODAY()-CCD_NetSuite__c))))</formula>
    <label>Closed Contract Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>2.0</description>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/CustomerAccount__c.field-meta.xml
<CustomField>
    <fullName>CustomerAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices (Customer Account)</relationshipLabel>
    <relationshipName>Invoices1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/AcceptedDate__c.field-meta.xml
<CustomField>
    <fullName>AcceptedDate__c</fullName>
    <description>Date, when Quote got Status Accepted.</description>
    <label>Accepted Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/UpfrontPaymentFollowUp.cls
global class UpfrontPaymentFollowUp implements Database.Batchable<sObject>{

    global String Query;
    global Boolean ResetBatch;
    
    // things that make clock stop: Batch isn't 7, CCD isn't null, or there's an invoice
    
    global UpfrontPaymentFollowUp(Integer iBatchNo) {
        ResetBatch = iBatchNo != 0;
        Query = 'SELECT Id, Batch7_Age__c ';
        Query += 'FROM Account ';
        if (iBatchNo == 1) {
            Query += 'WHERE Batch7_Age__c != null ';
            Query += 'AND Id IN (SELECT CustomerAccount__c FROM Invoice__c) ';
        } else if (iBatchNo == 2) {
            Query += 'WHERE Batch7_Age__c != null ';
            Query += 'AND Id NOT IN (SELECT CustomerAccount__c FROM Invoice__c) AND (';
            Query += 'Closed_Contract_Date__c != NULL ';
            Query += 'OR (Batch__c != \'Batch7\' AND Batch__c != \'Batch4\')) ';
        } else {
            Query += 'WHERE Id IN (SELECT Account__c FROM Subscription__c WHERE Status__c = \'Active\') ';
            Query += 'AND Id NOT IN (SELECT CustomerAccount__c FROM Invoice__c) ';
            Query += 'AND Closed_Contract_Date__c = NULL ';
            Query += 'AND (Batch__c = \'Batch7\' OR Batch__c = \'Batch4\') ';
        }
    }

    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(Query);
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope){
        Set<Id> AcctIds = new Set<Id>(); Map<Id, Date> DateMap = new Map<Id, Date>();
        for (sObject s : scope) { AcctIds.add((Id)s.get('Id')); }
        for (AggregateResult ar : [SELECT AccountId, MIN(AcceptedDate__c) AccDate FROM Quote WHERE AcceptedDate__c != NULL AND AccountId IN :AcctIds GROUP BY AccountId]) {DateMap.put((Id)ar.get('AccountId'), (Date)ar.get('AccDate'));}
        for (sObject s : scope) { s.put('Batch7_Age__c', ResetBatch ? null : Math.abs(Date.today().daysBetween(DateMap.get((Id)s.get('Id'))))); } update scope;
    }        

    global void finish(Database.BatchableContext BC){}

}