force-app/main/default/objects/Account/fields/Batch__c.field-meta.xml
<CustomField>
    <fullName>Batch__c</fullName>
    <label>Billing Batch</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/PaymentTerm__c.field-meta.xml
<CustomField>
    <fullName>PaymentTerm__c</fullName>
    <label>Payment Term</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Target_Batch__c.field-meta.xml
<CustomField>
    <fullName>Target_Batch__c</fullName>
    <formula>IF(isblank(OldBatch__c),
IF(
Batch__c=&quot;Batch1&quot; || Batch__c=&quot;Batch2&quot; || AND(
Batch__c=&quot;Batch7&quot;,NOT(ISBLANK(FirstInvoiceDate__c))
|| AND(
Batch__c=&quot;Batch7&quot;,NOT(ISBLANK(Closed_Contract_Paid_Date__c))
)
),
IF(
AND(Batch__c=&quot;Batch7&quot;,NOT(ISBLANK(Closed_Contract_Paid_Date__c))),
&quot;Batch3&quot;,
IF(
NOT(ISBLANK(DefaultPaymentMethod__r.BankTransferAccountNumberMask__c))
&amp;&amp; DefaultPaymentMethod__r.BankTransferType__c = &quot;SEPA&quot;,
&quot;Batch5&quot;,
IF(
Count_Wire_Transfers__c&gt;1
||AND(Batch__c=&quot;Batch2&quot;,Last_Payment_Rollup__c),
&quot;Batch3&quot;,
IF(
Batch__c&lt;&gt;&quot;Batch2&quot;,
&quot;Batch2&quot;,
IF(
PaymentTerm__c=&quot;Due Upon Receipt&quot;
|| ISBLANK(FirstInvoiceDate__c),
&quot;&quot;,
Batch__c
)
)
)
)
),
IF(
Batch__c =&quot;Batch8&quot; || Batch__c =&quot;Batch9&quot;,
IF(
OR(Last_Payment_Rollup__c, Account_Balance_2__c &lt; 1,
AND(Account_Balance_2__c &lt; 39,  DAY(TODAY()) = 10)),
&quot;Batch5&quot;,
&quot;&quot;
),
IF(
PaymentTerm__c=&quot;Due Upon Receipt&quot; || ISBLANK(FirstInvoiceDate__c),
&quot;&quot;,
Batch__c
)
)
),
if(
begins(OldBatch__c,&quot;x&quot;),&quot;Batch25&quot;,OldBatch__c
))</formula>
    <label>Target Batch</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BillingBatchUpdater.cls
global class BillingBatchUpdater implements Database.Batchable<sObject>, Database.AllowsCallouts{
    
    global String Query;
    
    global BillingBatchUpdater() {
        Query  = 'SELECT Id, Batch__c, Target_Batch__c, ZuoraId__c FROM Account WHERE Target_Batch__c != NULL';
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(Query);
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope){
        List<ZObj.BatchChange> BatchChanges = new List<ZObj.BatchChange>();
        Map<String,String> zMap = new Map<String,String>();
        List<Account> UpsertAccounts = new List<Account>();
        for (sObject s : scope) {
            zMap.put((String)s.get('ZuoraId__c'), (String)s.get('Target_Batch__c'));
            BatchChanges.add(new ZObj.BatchChange((String)s.get('ZuoraId__c'), (String)s.get('Target_Batch__c')));
        }
        for (ZObj.SuccessId zs : ZuoraSyncController.UpdateBillingBatches(BatchChanges)) {
            if (zs.Success) UpsertAccounts.add(new Account(ZuoraId__c = zs.Id, Batch__c = zMap.get(zs.Id), PaymentTerm__c = 'Due Upon Receipt' ));
        }
        upsert UpsertAccounts ZuoraId__c;
    }
    
    global void finish(Database.BatchableContext BC){
    }

}