force-app/main/default/objects/Account/fields/Batch__c.field-meta.xml
<CustomField>
    <fullName>Batch__c</fullName>
    <label>Billing Batch</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <label>Payment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/ServiceActivationDate__c.field-meta.xml
<CustomField>
    <fullName>ServiceActivationDate__c</fullName>
    <label>Service Activation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/BillRunForPrepayers_Test.cls
@isTest public class BillRunForPrepayers_Test {
    
    static TestMethod void test1() {
        Account a = new Account(name='test', Batch__c='Batch7', ZuoraId__c='t');
        insert a;
        insert new Subscription__c(Account__c=a.Id, ServiceActivationDate__c=Date.today(), ZuoraId__c='t');
        insert new Payment__c(Account__c=a.Id, ZuoraId__c='t');
        BillRunForPrepayers b = new BillRunForPrepayers(); 
        database.executebatch(b, 50);
    }
    
    static TestMethod void test2() {
        String jobId = System.schedule('test', '0 0 0 3 9 ? 2022', new BillRunForPrepayers_Scheduler());
    }
    
}