force-app/main/default/objects/Account/fields/Batch__c.field-meta.xml
<CustomField>
    <fullName>Batch__c</fullName>
    <label>Billing Batch</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Dunning_0_Date__c.field-meta.xml
<CustomField>
    <fullName>Dunning_0_Date__c</fullName>
    <label>Dunning 0 Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Target_Product__c.field-meta.xml
<CustomField>
    <fullName>Target_Product__c</fullName>
    <label>Target Product</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>2.0</description>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/HasFullBalance__c.field-meta.xml
<CustomField>
    <fullName>HasFullBalance__c</fullName>
    <formula>Balance__c = Amount__c &amp;&amp; Amount__c &gt; 0</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Has Full Balance</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>Zuora Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/InvoiceLineItem__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>ILI-{0000000}</displayFormat>
        <label>Invoice Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceLineItem__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/fields/ServiceStartDate__c.field-meta.xml
<CustomField>
    <fullName>ServiceStartDate__c</fullName>
    <label>Service Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/fields/SubscriptionLineItem__c.field-meta.xml
<CustomField>
    <fullName>SubscriptionLineItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription Line Item</label>
    <referenceTo>SubscriptionLineItem__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/MyObVenue__c/MyObVenue__c.object-meta.xml
<CustomObject>
    <label>MyOb Venue</label>
    <nameField>
        <displayFormat>MyOb-{000000}</displayFormat>
        <label>MyOb Venue</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MyOb Venues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MyObVenue__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>MyOrderbird_Log_ons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MyObVenue__c/fields/ChurnPrediction__c.field-meta.xml
<CustomField>
    <fullName>ChurnPrediction__c</fullName>
    <label>Churn Prediction</label>
    <precision>18</precision>
    <scale>17</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MyObVenue__c/fields/Days_Since_Last_Shift_Open__c.field-meta.xml
<CustomField>
    <fullName>Days_Since_Last_Shift_Open__c</fullName>
    <formula>if(isblank(LastOpenShiftTimestamp__c),null,
today() - datevalue( LastOpenShiftTimestamp__c ))</formula>
    <label>Days Since Last Shift Open</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MyObVenue__c/fields/Target_Product__c.field-meta.xml
<CustomField>
    <fullName>Target_Product__c</fullName>
    <formula>Account__r.Target_Product__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Target Product</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <label>Payment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/CreatedDate__c.field-meta.xml
<CustomField>
    <fullName>CreatedDate__c</fullName>
    <label>Payment Created Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/evaluation__c.field-meta.xml
<CustomField>
    <fullName>evaluation__c</fullName>
    <description>Stakeholder Finance https://jira.orderbird.com/browse/CDS-1019
Summarises Type, GatewayState, Amount and Refund in one field to provide an easier overview in Related Lists</description>
    <formula>IF(AND(Type__c = &apos;Electronic&apos;, GatewayState__c = &apos;Settled&apos;,  Amount__c -  RefundAmount__c != 0), &apos;SEPA settled&apos;,
 IF(AND(Type__c = &apos;Electronic&apos;, GatewayState__c = &apos;Settled&apos;,  Amount__c -  RefundAmount__c = 0), &apos;SEPA refunded&apos;,
  IF(AND(Type__c = &apos;Electronic&apos;, GatewayState__c = &apos;Submitted&apos;,  Amount__c -  RefundAmount__c != 0), &apos;SEPA pending&apos;,
   IF(AND(Type__c = &apos;Electronic&apos;, OR(GatewayState__c = &apos;FailedToSettle&apos;,GatewayState__c = &apos;Submitted&apos;),  Amount__c -  RefundAmount__c = 0), &apos;SEPA failed&apos;,
    IF(AND(Type__c = &apos;Electronic&apos;, GatewayState__c = &apos;NotSubmitted&apos;,  Amount__c -  RefundAmount__c != 0), &apos;SEPA aborted&apos;,
     IF(AND(Type__c = &apos;External&apos;, GatewayState__c = &apos;NotSubmitted&apos;,  Amount__c -  RefundAmount__c != 0), &apos;Manually settled&apos;,
      IF(AND(Type__c = &apos;External&apos;, GatewayState__c = &apos;NotSubmitted&apos;,  Amount__c -  RefundAmount__c = 0), &apos;Manually refunded&apos;,
&apos;undefined&apos;)))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Evaluation</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/PaymentMethod__c.object-meta.xml
<CustomObject>
    <label>Payment Method</label>
    <nameField>
        <label>Payment Method Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentMethod__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payment Methods</relationshipLabel>
    <relationshipName>Payment_Methods</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <externalId>true</externalId>
    <label>Key</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <externalId>true</externalId>
    <label>Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/DownshiftsTo__c.field-meta.xml
<CustomField>
    <fullName>DownshiftsTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Downshifts To</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Products (Downshifts To)</relationshipLabel>
    <relationshipName>DSProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/SubscriptionLineItem__c.field-meta.xml
<CustomField>
    <fullName>SubscriptionLineItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription Line Item</label>
    <referenceTo>SubscriptionLineItem__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Refund__c/Refund__c.object-meta.xml
<CustomObject>
    <label>Refund</label>
    <nameField>
        <label>Refund Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Refunds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Refund__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>Payment__c</referenceTo>
    <relationshipLabel>Refunds</relationshipLabel>
    <relationshipName>Refunds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/SubscriptionLineItem__c.object-meta.xml
<CustomObject>
    <label>Subscription Line Item</label>
    <nameField>
        <label>Subscription Line Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SubscriptionLineItem__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>SubscriptionLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <formula>IF( Product__r.BillingPeriod__c &lt;&gt; &apos;Specific_Months&apos;, 
CASE(Product__r.BillingPeriod__c,
&quot;Annual&quot;, &quot;Year&quot;,
&quot;Three_Years&quot;, &quot;Three_Year&quot;,
Product__r.BillingPeriod__c
),
CASE( Product__r.SpecificBillingPeriod__c,
&quot;1&quot;, &apos;Month&apos;,
&quot;3&quot;, &apos;Quarter&apos;,
&quot;12&quot;, &apos;Year&apos;,
&quot;36&quot;, &apos;Three_Year&apos;,
&quot;120&quot;, &apos;Ten_Year&apos;,
&apos;Unknown&apos;
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Frequency</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>Subscription_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/FailedPaymentBatch.cls
global class FailedPaymentBatch implements Database.Batchable<sObject>, Database.AllowsCallouts{
    
    global FailedPaymentBatch() {
        SetQuery(true);
    }
    
    global void SetQuery(Boolean IsInitial) {
        Query  = 'SELECT Id, ZuoraId__c, Target_Product__c,';
        Query += '  ( ';
        Query += '    SELECT Id, Days_Since_Last_Shift_Open__c, ChurnPrediction__c ';
        Query += '    FROM MyOrderbird_Log_ons__r ';
        Query += '    WHERE Days_Since_Last_Shift_Open__c != NULL ';
        Query += '    	AND Days_Since_Last_Shift_Open__c < 20 ';
        Query += '    ORDER BY ChurnPrediction__c ';
        Query += '    LIMIT 1 ';
        Query += '  ), ';
        Query += '  ( ';
        Query += '    SELECT Id ';
        Query += '    FROM Invoices__r ';
        Query += '    WHERE HasFullBalance__c = TRUE ';
        Query += '  ), ';
        Query += '  ( ';
        Query += '    SELECT Id, Evaluation__c ';
        Query += '    FROM Payments__r ';
        Query += '    WHERE Evaluation__c IN (\'Sepa Failed\', \'Sepa Refunded\', \'Sepa Aborted\') ';
        Query += '      AND CreatedDate__c = LAST_n_DAYS:27 ';
        Query += '  ) ';
        Query += 'FROM Account ';
        if (IsInitial) {
            Query += 'WHERE Id IN (SELECT Account__c FROM Refund__c WHERE CreatedDate = TODAY) ';
        } 
        /* The account with 'SEPA Aborted' are excluded from Smart Collections
         * because of CDS-3175
         * else {
            Query += 'WHERE Id IN (SELECT Account__c FROM Payment__c WHERE CreatedDate = TODAY AND Evaluation__c = \'Sepa Aborted\') ';
            Query += 'AND Id NOT IN :AllAccounts ';
        }*/
        Query += '  AND Dunning_0_Date__c = NULL ';
        if (test.isRunningTest()) Query += '  AND Name = \'isRunning Test Account\' ';
        Query += '  LIMIT 200 ';
        // First = true;
    }
    
    global String Query;
    global Map<Id, Invoice__c> InvoiceMap;
    //global Boolean First;
    global Map<String, sObject> BatchMap = new Map<String, sObject>();
    global Map<String, Date> DateMap = new Map<String, Date>();
    global List<ZObj.BatchChange> BatchChanges = new List<ZObj.BatchChange>();
    global List<InvoiceLineItem__c> DownshiftILIs = new List<InvoiceLineItem__c>();
    
    global Map<String, Integer> FreqOrder = new Map<String, Integer>{'Ten_Year'=>120,'Three_Year'=>36,'Year'=>12,'Quarter'=>3,'Month'=>1};
        
        global Database.QueryLocator start(Database.BatchableContext BC){
            return Database.getQueryLocator(Query);
        }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope){
        Set<String> AllAccounts = new Set<String>();
        List<String> BatchChange = new List<String>();
        List<String> Downshift = new List<String>();
        for (sObject s : scope) {
            AllAccounts.add((String)s.get('Id'));
        }
        /* if (First) {
            SetQuery(false);
            List<sObject> scope_append = Database.query(Query);
            for (sObject s : scope_append) {
                AllAccounts.add((String)s.get('Id'));
            }
            scope.addAll(scope_append);
            First = false;
        } */
        InvoiceMap = new Map<Id, Invoice__c>([
            SELECT Id, (
                SELECT Id, SubscriptionLineItem__c, SubscriptionLineItem__r.Name, SubscriptionLineItem__r.Frequency__c, ServiceStartDate__c 
                FROM Invoice_Line_Items__r 
                WHERE SubscriptionLineItem__r.Product__r.DownshiftsTo__c != NULL 
                  AND ServiceStartDate__c = LAST_n_DAYS:30
            )
            FROM Invoice__c
            WHERE Account__c IN :AllAccounts AND HasFullBalance__c = TRUE
        ]);
        for (sObject s : scope) {
            if (!IsVenueActive(s)) {
                BatchChange(s);
            } else if (HasMultipleFailures(s) || IsLikelyChurner(s)){
                if (CanDownshift(s)) {
                    Downshift(s);
                } else {
                    BatchChange(s);
                }
            }
        }
        doBatchUpdates();
        doDownshifting();
    }
    
    global static Boolean IsVenueActive(sObject s) {
        try{ return ((List<MyObVenue__c>)(s.getSObjects('MyOrderbird_Log_ons__r'))).size() > 0; }catch(exception e){ return false; }
    }
    
    global static Boolean IsLikelyChurner(sObject s) {
        MyObVenue__c venue = (MyObVenue__c)(s.getSObjects('MyOrderbird_Log_ons__r'))[0];
        return venue.ChurnPrediction__c != null && venue.ChurnPrediction__c > 0.5 ;
    }
    
    global static Boolean HasMultipleFailures(sObject s) {
        try{
            List<Payment__c> Payments = (List<Payment__c>)s.getSObjects('Payments__r');
            return (Payments.size() > 1 || Payments[0].Evaluation__c == 'Sepa Refunded' || Payments[0].Evaluation__c == 'Sepa Aborted');
        }catch(exception e){ return false; }
    }
    
    global Boolean CanDownshift(sObject s) {
        try{ 
            for (Invoice__c Inv : (List<Invoice__c>)(s.getSObjects('Invoices__r'))) {
                if (InvoiceMap.get(Inv.Id).Invoice_Line_Items__r.size() > 0) return true; 
            }
        } catch(exception e){}
        return false;
    }
    
    global void BatchChange(sObject s) {
        String Collection_Batch;
        if((String)s.get('Target_Product__c')=='MINI')
            Collection_Batch = 'Batch9';
        else
        	Collection_Batch = 'Batch8';
        s.put('Batch__c', Collection_Batch);
        BatchMap.put((String)s.get('ZuoraId__c'), s);
        BatchChanges.add(new ZObj.BatchChange((String)s.get('ZuoraId__c'), Collection_Batch));
    }
    
    global void Downshift(sObject s) {
        List<InvoiceLineItem__c> ILIs = new List<InvoiceLineItem__c>();
        for (Invoice__c Inv : (List<Invoice__c>)(s.getSObjects('Invoices__r'))) {
            for (InvoiceLineItem__c ILI : InvoiceMap.get(Inv.Id).Invoice_Line_Items__r) {
                DateMap.put(ILI.SubscriptionLineItem__r.Name, ILI.ServiceStartDate__c);
                if (ILIs.size()==0) {
                    ILIs.add(ILI);
                } else if (ILIs[0].SubscriptionLineItem__r.Frequency__c == ILI.SubscriptionLineItem__r.Frequency__c) {
                    ILIs.add(ILI);
                } else if (FreqOrder.get(ILI.SubscriptionLineItem__r.Frequency__c) > FreqOrder.get(ILIs[0].SubscriptionLineItem__r.Frequency__c)) {
                    ILIs = new List<InvoiceLineItem__c>();
                    ILIs.add(ILI);
                }
            }
        }
        DownshiftILIs.addAll(ILIs);
    }
    
    global void doDownshifting() {
        Set<String> SLIIds = new Set<String>();
        List<PricebookEntry> pbes = [
            SELECT Id, Key__c, Name, Pricebook2Id, Product2Id, CurrencyIsoCode, 
              UnitPrice, IsActive, UseStandardPrice 
            FROM PricebookEntry
        ];
        Map<String, PricebookEntry> pbeMap = new Map<String, PricebookEntry>();
        for (PricebookEntry pbe : pbes) { pbeMap.put(pbe.Key__c, pbe); }
        for (InvoiceLineItem__c ILI : DownshiftILIs) { SLIIds.add(ILI.SubscriptionLineItem__r.Name); }
        List<SubscriptionLineItem__c> SLIs = [
            SELECT Id, Name, Subscription__r.Account__r.CurrencyIsoCode, Subscription__r.Account__c, Product__c, 
                Product__r.ZuoraId__c, Product__r.DownshiftsTo__r.ZuoraId__c, CurrencyIsoCode, 
                Product__r.DownshiftsTo__c, Quantity__c, EffectiveStartDate__c, Frequency__c
            FROM SubscriptionLineItem__c 
            WHERE Subscription__r.Status__c = 'Active'
            	AND Name IN :SLIIds
        ];
        List<Opportunity> newOpps = new List<Opportunity>();
        List<Quote> newQuotes = new List<Quote>();
        List<QuoteLineItem> newQLIs = new List<QuoteLineItem>();
        for (SubscriptionLineItem__c sli : SLIs) {
            for (Integer i=0; i<2; i++) {
                newOpps.add(new Opportunity(
                    CurrencyIsoCode = sli.Subscription__r.Account__r.CurrencyIsoCode,
                    AccountId = sli.Subscription__r.Account__c,
                    Name = 'Downshift Auto-Opportunity',
                    StageName = 'Potential',
                    CloseDate = Date.today().addDays(14),
                    OppCategory__c = 'Account Management',
                    Opportunity_Type_1__c = 'Downshift Autochange'
                ));
            }
        }
        insert newOpps;
        //////////
        Integer x = 0;
        for (Integer i=0; i<2; i++) {
            for (SubscriptionLineItem__c sli : SLIs) {
                newQuotes.add(new Quote(
                    name='Downshift Auto-Quote',
                    Pricebook2Id = [SELECT Id From Pricebook2 WHERE Key__c = 'Main' LIMIT 1].Id,
                    Tax = 0,
                    ContractEffectiveDate__c = DateMap.get(sli.Name),
                    InvoiceDate__c = Date.today(),
                    InvoiceTargetDate__c = Date.today(),
                    POS_Start_Date__c = DateMap.get(sli.Name),
                    ExpirationDate = Date.today().addDays(30),
                    Pay_by_Instalment__c = false,
                    PaymentMethod__c = 'Bank Transfer',
                    WireFirstPayment__c = false,
                    PayPalLink__c = false,
                    InvoiceOwner__c = sli.Subscription__r.Account__c,
                    Contains_Recurring_Items__c = true,
                    CurrencyIsoCode = sli.CurrencyIsoCode,
                    AutoAcceptPriority__c = 1,
                    OpportunityId = newOpps[x].Id
                ));
                x++;
            }
        }
        insert newQuotes;
        x = 0;
        for (SubscriptionLineItem__c sli : SLIs) {
            newQLIs.add(new QuoteLineItem(
                QuoteId = newQuotes[x].id,
                Product2Id = sli.Product__c,
                SubscriptionLineItem__c = sli.Id,
                Quantity = sli.Quantity__c * -1,
                PricebookEntryId = pbeMap.get(sli.Subscription__r.Account__r.CurrencyIsoCode + ':' + sli.Product__r.ZuoraId__c).Id,
                UnitPrice = pbeMap.get(sli.Subscription__r.Account__r.CurrencyIsoCode + ':' + sli.Product__r.ZuoraId__c).UnitPrice
            ));
            x++;
            newQLIs.add(new QuoteLineItem(
                QuoteId = newQuotes[x].id,
                Product2Id = sli.Product__r.DownshiftsTo__c,
                Quantity = sli.Quantity__c,
                PricebookEntryId = pbeMap.get(sli.Subscription__r.Account__r.CurrencyIsoCode + ':' + sli.Product__r.DownshiftsTo__r.ZuoraId__c).Id,
                UnitPrice = pbeMap.get(sli.Subscription__r.Account__r.CurrencyIsoCode + ':' + sli.Product__r.DownshiftsTo__r.ZuoraId__c).UnitPrice
            ));
            x++;
        }
        insert newQLIs;
    }
    
    global void doBatchUpdates() {
        if (BatchChanges.size() > 0) {
            for (ZObj.SuccessId zs : ZuoraSyncController.UpdateBillingBatches(BatchChanges)) {
                if (!zs.Success) BatchMap.remove(zs.Id);
            }
            update BatchMap.values();
        }
    }
    
    global void finish(Database.BatchableContext BC){
        if (!test.isRunningTest()) System.enqueueJob(new EnqueueAQA());
    }
    
}