force-app/main/default/objects/Account/fields/Batch__c.field-meta.xml
<CustomField>
    <fullName>Batch__c</fullName>
    <label>Billing Batch</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DefaultPaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>DefaultPaymentMethod__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Default Payment Method</label>
    <referenceTo>PaymentMethod__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>2.0</description>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/CustomerAccount__c.field-meta.xml
<CustomField>
    <fullName>CustomerAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices (Customer Account)</relationshipLabel>
    <relationshipName>Invoices1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>Zuora Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <label>Payment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentMethod__c/PaymentMethod__c.object-meta.xml
<CustomObject>
    <label>Payment Method</label>
    <nameField>
        <label>Payment Method Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentMethod__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payment Methods</relationshipLabel>
    <relationshipName>Payment_Methods</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/BankTransferAccountNumberMask__c.field-meta.xml
<CustomField>
    <fullName>BankTransferAccountNumberMask__c</fullName>
    <label>Bank Transfer Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/BankTransferType__c.field-meta.xml
<CustomField>
    <fullName>BankTransferType__c</fullName>
    <label>Bank Transfer Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/PaymentMethodStatus__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethodStatus__c</fullName>
    <label>Payment Method Status</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/ServiceActivationDate__c.field-meta.xml
<CustomField>
    <fullName>ServiceActivationDate__c</fullName>
    <label>Service Activation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/Instalment_test.cls
@isTest public class Instalment_test {

    static TestMethod void test1() {
        Account a = new Account(name='test', Batch__c='Batch4', ZuoraId__c='t');
        insert a;
        insert new Invoice__c(Account__c=a.Id,CustomerAccount__c=a.Id,Status__c='Posted');
        insert new Subscription__c(Account__c=a.Id, ServiceActivationDate__c=Date.today(), ZuoraId__c='t');
        insert new Payment__c(Account__c=a.Id, ZuoraId__c='t');
        InstalmentBillRun b = new InstalmentBillRun(); 
        database.executebatch(b, 50);
    }
    
    static TestMethod void test1a() {
        Account a = new Account(name='test', Batch__c='Batch4', ZuoraId__c='t');
        insert a;
        PaymentMethod__c pm = new PaymentMethod__c(Name='t',BankTransferAccountNumberMask__c='t',Account__c = a.Id, BankTransferType__c = 'SEPA', PaymentMethodStatus__c = 'Active', ZuoraId__c = 't');
        insert pm;
        a.DefaultPaymentMethod__c = pm.Id;
        update a;
        insert new Subscription__c(Account__c=a.Id, ServiceActivationDate__c=Date.today(), ZuoraId__c='t');
        insert new Invoice__c(Account__c=a.Id, ZuoraId__c='t', Balance__c=10, Status__c='Posted');
        InstalmentPaymentRun b = new InstalmentPaymentRun(); 
        database.executebatch(b, 50);
    }
    
    static TestMethod void test2() {
        System.schedule('test', '0 0 0 3 9 ? 2022', new InstalmentBillRun_scheduler());
        System.schedule('test2', '0 0 0 3 9 ? 2022', new InstalmentPaymentRun_scheduler());
    }

}