force-app/main/default/objects/Account/fields/Batch__c.field-meta.xml
<CustomField>
    <fullName>Batch__c</fullName>
    <label>Billing Batch</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>2.0</description>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/CustomerAccount__c.field-meta.xml
<CustomField>
    <fullName>CustomerAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices (Customer Account)</relationshipLabel>
    <relationshipName>Invoices1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>Zuora Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <label>Payment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote/fields/ContractEffectiveDate__c.field-meta.xml
<CustomField>
    <fullName>ContractEffectiveDate__c</fullName>
    <inlineHelpText>Relevant date for Hardware shipment (if payments are confirmed) and date printed on the invoice.</inlineHelpText>
    <label>Contract Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Is_Missing_Documents__c.field-meta.xml
<CustomField>
    <fullName>Is_Missing_Documents__c</fullName>
    <formula>Opportunity.Account.BillingCountryCode__c = &quot;DE&quot; &amp;&amp;
Opportunity.NewBusiness__c &amp;&amp;

(
ISBLANK( Opportunity.Account.Registration_certificate_chk__c )

||

(Pay_by_Instalment__c &amp;&amp; (
ISBLANK( Opportunity.Account.Instalment_Contract_chk__c ) ||
ISBLANK( Opportunity.Account.Credit_Check_chk__c ) ||
ISBLANK( Opportunity.Account.Id_Card_chk__c ) 
))

||

( (  (NOT(WireFirstPayment__c) &amp;&amp; TEXT(PaymentMethod__c) = &quot;Bank Transfer&quot;) || Contains_Recurring_Items__c) &amp;&amp; ISBLANK(  Opportunity.Account.SEPA_Mandate_chk__c  ))

)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Missing Documents</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/SpecialRestart__c.field-meta.xml
<CustomField>
    <fullName>SpecialRestart__c</fullName>
    <label>Special Restart</label>
    <summaryFilterItems>
        <field>QuoteLineItem.RestartDiscount__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/ContractEffectiveDate__c.field-meta.xml
<CustomField>
    <fullName>ContractEffectiveDate__c</fullName>
    <label>Contract Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/ServiceActivationDate__c.field-meta.xml
<CustomField>
    <fullName>ServiceActivationDate__c</fullName>
    <label>Service Activation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/BillRunForPrepayers.cls
global class BillRunForPrepayers implements Database.Batchable<sObject>, Database.AllowsCallouts{
    
    global String Query;
    
    global BillRunForPrepayers() {
        Query  = 'SELECT Id, ZuoraId__c, (SELECT ContractEffectiveDate__c, ServiceActivationDate__c FROM Subscriptions__r ORDER BY ServiceActivationDate__c DESC LIMIT 1) FROM Account';
        Query += ' WHERE (Batch__c = \'Batch7\' OR Batch__c = \'Batch4\') AND ZuoraId__c != NULL AND Id NOT IN (SELECT CustomerAccount__c FROM Invoice__c)';
        Query += ' AND Id IN (SELECT Account__c FROM Payment__c)';
    }

//  AND Id NOT IN (SELECT AccountId FROM Quote WHERE Status = \'Accepted\' AND Is_Missing_Documents__c = TRUE)    
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(Query);
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope){
        List<ZObj.CreateBillRun> BillRuns = new List<ZObj.CreateBillRun>();
        Set<String> AccountIds = new Set<String>();
        Set<String> ExcludeZIds = new Set<String>();
        Set<String> RestartZIds = new Set<String>();
        for (sObject s : scope) { AccountIds.add((String)s.get('Id')); }
        for (Account a : [SELECT Id, ZuoraId__c FROM Account WHERE Id IN (SELECT AccountId FROM Quote WHERE Status = 'Accepted' AND Is_Missing_Documents__c = TRUE)]) {
            ExcludeZIds.add(a.ZuoraId__c);
        }
        for (Account a : [SELECT Id, ZuoraId__c FROM Account WHERE Id IN (SELECT AccountId FROM Quote WHERE Status = 'Accepted' AND SpecialRestart__c > 0)]) {
            RestartZIds.add(a.ZuoraId__c);
        }
        for (sObject s : scope) {
            if (!ExcludeZIds.contains((String)s.get('ZuoraId__c'))) {
                List<sObject> Subscriptions = s.getSObjects('Subscriptions__r');
                if (Subscriptions != null) {
                    BillRuns.add(new ZObj.CreateBillRun((String)s.get('ZuoraId__c'), RestartZIds.contains((String)s.get('ZuoraId__c')) ? (Date)Subscriptions[0].get('ContractEffectiveDate__c') : (Date)Subscriptions[0].get('ServiceActivationDate__c')));
                }
            }
        }
        ZuoraSyncController.CreateBillRunsForPrepayers(BillRuns);
    }
    
    global void finish(Database.BatchableContext BC){
    }
    
}