force-app/main/default/objects/Account/fields/Batch__c.field-meta.xml
<CustomField>
    <fullName>Batch__c</fullName>
    <label>Billing Batch</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DefaultPaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>DefaultPaymentMethod__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Default Payment Method</label>
    <referenceTo>PaymentMethod__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>2.0</description>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <formula>TODAY()-InvoiceDate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>Zuora Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/InvoiceLineItem__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>ILI-{0000000}</displayFormat>
        <label>Invoice Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceLineItem__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/fields/SubscriptionLineItem__c.field-meta.xml
<CustomField>
    <fullName>SubscriptionLineItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription Line Item</label>
    <referenceTo>SubscriptionLineItem__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/PaymentMethod__c.object-meta.xml
<CustomObject>
    <label>Payment Method</label>
    <nameField>
        <label>Payment Method Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SubscriptionLineItem__c/SubscriptionLineItem__c.object-meta.xml
<CustomObject>
    <label>Subscription Line Item</label>
    <nameField>
        <label>Subscription Line Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/InstalmentPaymentRun.cls
global class InstalmentPaymentRun implements Database.Batchable<sObject>, Database.AllowsCallouts{
    
    global String Query;
    
    global InstalmentPaymentRun() {
        Query  = 'SELECT Id, Age__c, Balance__c, Amount__c, ZuoraId__c, Account__r.ZuoraId__c, Account__r.DefaultPaymentMethod__r.ZuoraId__c, ';
        Query += '  (SELECT Id FROM Invoice_Line_Items__r WHERE SubscriptionLineItem__r.Product__r.Name LIKE \'%Instalment%\') ';
        Query += 'FROM Invoice__c ';
        Query += 'WHERE Balance__c > 0 AND Status__c = \'Posted\' ';
        Query += '  AND Account__r.Batch__c = \'Batch4\' ';
        Query += '  AND Account__r.DefaultPaymentMethod__r.BankTransferType__c = \'SEPA\' ';
        Query += '  AND Account__r.DefaultPaymentMethod__r.PaymentMethodStatus__c = \'Active\' ';
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(Query);
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope){
        List<ZObj.CreatePayment> CreatePayments = new List<ZObj.CreatePayment>();
        for (sObject s : scope) {
            if ((s.getSObjects('Invoice_Line_Items__r')) == null) {
                // Non-instalment Payment
                CreatePayments.add(new ZObj.CreatePayment(
                    (String)s.getSObject('Account__r').get('ZuoraId__c'),
                    (String)s.get('ZuoraId__c'),
                    (String)s.getSObject('Account__r').getSObject('DefaultPaymentMethod__r').get('ZuoraId__c'),
                    (Decimal)s.get('Balance__c')
                ));              
            } else if ((Decimal)s.get('Age__c') > 29 && (Decimal)s.get('Age__c') < 54 && (Decimal)s.get('Balance__c') > 5 + ((Decimal)s.get('Amount__c') / 3)) {
                // Instalment Payment
                CreatePayments.add(new ZObj.CreatePayment(
                    (String)s.getSObject('Account__r').get('ZuoraId__c'),
                    (String)s.get('ZuoraId__c'),
                    (String)s.getSObject('Account__r').getSObject('DefaultPaymentMethod__r').get('ZuoraId__c'),
                    ((Decimal)s.get('Balance__c') - ((Decimal)s.get('Amount__c') / 3)).setScale(2)
                ));
            }
        }
        ZuoraSyncController.InstalmentPaymentRun(CreatePayments);
    }
    
    global void finish(Database.BatchableContext BC){
    }
    
}