force-app/main/default/objects/Account/fields/Batch__c.field-meta.xml
<CustomField>
    <fullName>Batch__c</fullName>
    <label>Billing Batch</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>2.0</description>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <formula>TODAY()-InvoiceDate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/CustomerAccount__c.field-meta.xml
<CustomField>
    <fullName>CustomerAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices (Customer Account)</relationshipLabel>
    <relationshipName>Invoices1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>Zuora Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/InvoiceLineItem__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>ILI-{0000000}</displayFormat>
        <label>Invoice Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceLineItem__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/fields/SubscriptionLineItem__c.field-meta.xml
<CustomField>
    <fullName>SubscriptionLineItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription Line Item</label>
    <referenceTo>SubscriptionLineItem__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/SubscriptionLineItem__c.object-meta.xml
<CustomObject>
    <label>Subscription Line Item</label>
    <nameField>
        <label>Subscription Line Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SubscriptionLineItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>Subscription_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>Subscription__r.Status__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/InstalmentBillRun.cls
global class InstalmentBillRun implements Database.Batchable<sObject>, Database.AllowsCallouts{
    
    global String Query;
    
    global InstalmentBillRun() {
        Query  = 'SELECT Id, ZuoraId__c, (';
        Query += '  SELECT Id FROM Invoices__r ';
        Query += '  WHERE Age__c < 60 AND Status__c = \'Posted\' AND Balance__c > 0 AND Id IN (';
        Query += '    SELECT Invoice__c FROM InvoiceLineItem__c ';
        Query += '    WHERE SubscriptionLineItem__r.Product__r.Name LIKE \'%Instalment%\'';
        Query += '  )';
        Query += ') FROM Account ';
        Query += 'WHERE Batch__c = \'Batch4\' AND Id IN (SELECT CustomerAccount__c FROM Invoice__c WHERE Status__c = \'Posted\')';
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(Query);
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope){
        Set<String> IdSet = new Set<String>();
        List<ZObj.BatchChange> BatchChanges = new List<ZObj.BatchChange>();
        Map<String,String> zMap = new Map<String,String>();
        List<Account> UpsertAccounts = new List<Account>();
        List<ZObj.CreateBillRun> BillRuns = new List<ZObj.CreateBillRun>();
        for (sObject s : scope) {
            if ((s.getSObjects('Invoices__r')) == null) {
                zMap.put((String)s.get('ZuoraId__c'), 'Batch2');
                BatchChanges.add(new ZObj.BatchChange((String)s.get('ZuoraId__c'), 'Batch2'));
            } else {
            	BillRuns.add(new ZObj.CreateBillRun((String)s.get('ZuoraId__c'), Date.today()));
            }
        }
        ZuoraSyncController.CreateBillRunsForPrepayers(BillRuns);
        if(BatchChanges != null) {for (ZObj.SuccessId zs : ZuoraSyncController.UpdateBillingBatches(BatchChanges)) {
            if (zs.Success) UpsertAccounts.add(new Account(ZuoraId__c = zs.Id, Batch__c = zMap.get(zs.Id) ));
        }}
        upsert UpsertAccounts ZuoraId__c;
    }
    
    global void finish(Database.BatchableContext BC){
    }
    
}