force-app/main/default/objects/Account/fields/Caller_Contact__c.field-meta.xml
<CustomField>
    <fullName>Caller_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>https://jira.orderbird.com/browse/SFDC-1365</description>
    <label>Caller Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Caller Contact)</relationshipLabel>
    <relationshipName>Accounts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Caller_Contact__c.field-meta.xml
<CustomField>
    <fullName>Caller_Contact__c</fullName>
    <formula>Account.Caller_Contact__c = Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Caller Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Joint_Sales__c/Joint_Sales__c.object-meta.xml
<CustomObject>
    <label>Joint Sales</label>
    <nameField>
        <displayFormat>JS-{000000}</displayFormat>
        <label>Joint Sales Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Joint Sales</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Joint_Sales__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Joint Sales</relationshipLabel>
    <relationshipName>Joint_Sales1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Joint_Sales__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <label>Partner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.PartnerType__c</field>
            <operation>equals</operation>
            <value>Joint Sales</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Partner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Joint Sales (Partner)</relationshipLabel>
    <relationshipName>Joint_Sales</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/JointSalesEmbedExtension.cls
public class JointSalesEmbedExtension {

    public Account acct { get; set; }
    public Boolean renderError { get; set; }
    public String errorMsg { get; set; }
    public Boolean gotoRedirect { get; set; }

    public JointSalesEmbedExtension(ApexPages.StandardController stdController) {
        gotoRedirect = false;
        this.acct = [
            SELECT 
                Id, Name, Caller_Contact__c, Caller_Contact__r.Email, Caller_Contact__r.Phone, 
                Caller_Contact__r.MailingStreet, Caller_Contact__r.MailingCity, 
            	Caller_Contact__r.MailingPostalCode, Caller_Contact__r.MailingCountry, 
            (SELECT Id, Partner__r.Name FROM Joint_Sales1__r ORDER BY Partner__r.Name)
            FROM Account 
            WHERE Id=:((Account)stdController.getRecord()).Id 
            LIMIT 1
        ];
        if (acct.Caller_Contact__c == null) {
            renderError = true;
            errorMsg = 'This account requires a Caller Contact to refer Joint Sales.';
        } else if (acct.Caller_Contact__r.Email == null || (acct.Caller_Contact__r.Phone == null && acct.Caller_Contact__r.MobilePhone == null)) {
            renderError = true;
            errorMsg = 'Before referring Joint Sales, this Account\'s Caller Contact must have a valid Phone and Email.';
        } else {
            renderError = false;
        }
    }
    
    public void redirect() {
        gotoRedirect = true;
    }
    
}