force-app/main/default/objects/Account/fields/Caller_Contact__c.field-meta.xml
<CustomField>
    <fullName>Caller_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>https://jira.orderbird.com/browse/SFDC-1365</description>
    <label>Caller Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Caller Contact)</relationshipLabel>
    <relationshipName>Accounts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>https://jira.orderbird.com/browse/SFDC-1487</description>
    <inlineHelpText>Primary Contact for all relevant communication. Auto-populated after lead conversion.</inlineHelpText>
    <label>Primary Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Contact.Account.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Account.Id</field>
            <operation>equals</operation>
            <valueField>$Source.ParentId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Primary Contact)</relationshipLabel>
    <relationshipName>PrimaryContactForAcc</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/SF_BillTo_Contact__c.field-meta.xml
<CustomField>
    <fullName>SF_BillTo_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Stakeholder: Sales &amp; Account Management</description>
    <inlineHelpText>This defines the official billing address.</inlineHelpText>
    <label>Billing Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.ParentId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Zuora BillTo Contact)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/SF_SoldTo_Contact__c.field-meta.xml
<CustomField>
    <fullName>SF_SoldTo_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Stakeholder: Sales &amp; Account Management</description>
    <inlineHelpText>This contact defines the official shipping address.</inlineHelpText>
    <label>Shipping Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.ParentId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Has_Complete_Contact_Info__c.field-meta.xml
<CustomField>
    <fullName>Has_Complete_Contact_Info__c</fullName>
    <description>Formula to check if all contact information are filled in</description>
    <formula>AND( 
FirstName != &apos;&apos;,
Street != &apos;&apos;,
City != &apos;&apos;,
PostalCode != &apos;&apos;,
Country != &apos;&apos;,
Phone != &apos;&apos;,
Email!=&apos;&apos;,
Company!=&apos;&apos;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Has Complete Contact Info</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ContactAutoPopulator.cls
/**
 * author:  Bart
 * desc:    Sets Primary, ZBilling, and ZShipping Contacts on Lead Conversion and sets corresponding Address/Email/Phone fields
 * 
 */
public class ContactAutoPopulator {

    public List<Account> AccountsToUpdate;
    public Map<Id, SObject> AccountMap;
    
    // Instantiate class and create map to determine if lead is converting into new account
    public ContactAutoPopulator(List<Lead> leads) {
        AccountsToUpdate = new List<Account>();
        Set<Id> AccountIds = new Set<Id>();
        for (Lead l : leads) { AccountIds.add(l.ConvertedAccountId); }
        AccountMap = new Map<Id, SObject>([SELECT Id, (SELECT Id From Contacts) FROM Account WHERE Id IN :AccountIds]);
    }
    
    public void updateContactLookups(SObject so, SObject oldSo) {
        
        // Set lead converted into new account as Primary, ZBill, and ZShip Contacts
        if(
            (Boolean)so.get('IsConverted') 
            && !(Boolean)oldSo.get('IsConverted')
            && AccountMap.get((Id)so.get('ConvertedAccountId')).getSObjects('Contacts').size() == 1
        ) {
            Id CallerContactId = (Id)so.get('ConvertedContactId');
            if (!(Boolean)so.get('Has_Complete_Contact_Info__c')) CallerContactId = null;
            AccountsToUpdate.add(
                new Account(
                    Id = (Id)so.get('ConvertedAccountId'),
                    Primary_Contact__c = (Id)so.get('ConvertedContactId'),
                    SF_BillTo_Contact__c = (Id)so.get('ConvertedContactId'),
                    SF_SoldTo_Contact__c = (Id)so.get('ConvertedContactId'),
                    Caller_Contact__c = CallerContactId
                )
            );
        }
    }
    
    
    public void updateAccounts() {
        
        // Set Address/Email/Phone after conversion -- trigger will not do this because of recursion check
        AddressSync addressSync = new AddressSync(AccountsToUpdate);
        addressSync.loadRelatedContactAddresses();
        for (Account a : AccountsToUpdate) addressSync.updateAccountAddresses(a);
        
        // Finally: Commit changes
        update AccountsToUpdate;
    }
    
}