force-app/main/default/objects/Account/fields/Caller_Contact__c.field-meta.xml
<CustomField>
    <fullName>Caller_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>https://jira.orderbird.com/browse/SFDC-1365</description>
    <label>Caller Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Caller Contact)</relationshipLabel>
    <relationshipName>Accounts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/PartnerType__c.field-meta.xml
<CustomField>
    <fullName>PartnerType__c</fullName>
    <description>Stakeholder: PaM</description>
    <inlineHelpText>How is our relationship with this partner defined? Referral, Distribution or one of the big strategic partners? Filled in by PaM</inlineHelpText>
    <label>Partner Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>n/a</fullName>
            </value>
            <value>
                <fullName>ConCardis</fullName>
            </value>
            <value>
                <fullName>ETL</fullName>
            </value>
            <value>
                <fullName>METRO</fullName>
            </value>
            <value>
                <fullName>Referral Partner</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Joint Sales</fullName>
            </value>
            <value>
                <fullName>Product Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <description>This record type should be used for Partner accounts only.</description>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/Joint_Sales__c/Joint_Sales__c.object-meta.xml
<CustomObject>
    <label>Joint Sales</label>
    <nameField>
        <displayFormat>JS-{000000}</displayFormat>
        <label>Joint Sales Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Joint Sales</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Joint_Sales__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Joint Sales</relationshipLabel>
    <relationshipName>Joint_Sales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Joint_Sales__c/fields/Created_By__c.field-meta.xml
<CustomField>
    <fullName>Created_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Referred By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Joint_Sales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Joint_Sales__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Joint Sales</relationshipLabel>
    <relationshipName>Joint_Sales1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Joint_Sales__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <label>Partner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.PartnerType__c</field>
            <operation>equals</operation>
            <value>Joint Sales</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Partner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Joint Sales (Partner)</relationshipLabel>
    <relationshipName>Joint_Sales</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/JointSalesExtension.cls
public class JointSalesExtension {
    
    public list<PartnerWrapper> Partners { get; set; }
    public Set<Id> JSIds { get; set; }
    public Account acct { get; set; }
    public String comment { get; set; }

    public JointSalesExtension(ApexPages.StandardController stdController) {
		Partners = new List<PartnerWrapper>();
        JSIds = new Set<Id>();
        acct = [
            SELECT 
                Id, Name, Caller_Contact__c,
            	(SELECT Id, Partner__c, Partner__r.Name FROM Joint_Sales1__r ORDER BY Partner__r.Name)
            FROM Account 
            WHERE Id=:((Account)stdController.getRecord()).Id
            LIMIT 1
        ];
        if (acct.getSObjects('Joint_Sales1__r') != null) {
            for (sObject o : (List<sObject>)acct.getSObjects('Joint_Sales1__r')) {
                JSIds.add((Id)o.get('Partner__c'));
            }
        }
        for (Account jsAcct : [
            SELECT Id, Name 
            FROM Account 
            WHERE RecordType.Name = 'Partner' AND PartnerType__c = 'Joint Sales'
            ORDER BY Name
        ]) {
            Partners.add(new PartnerWrapper(jsAcct, JSIds));
        }
    }
    
    public class PartnerWrapper {
        public String Id { get; set; }
        public String Name { get; set; }
        public Boolean Disabled { get; set; }
        public Boolean Selected { get; set; }
        
        public PartnerWrapper(Account pAcct, set<Id> idSet) {
            Id = pAcct.Id;
            Name = pAcct.Name;
            Disabled = idSet.contains(Id);
            Selected = idSet.contains(Id);
        }
    }
    
    public PageReference jsSave() {
        CryptAES crypt = new CryptAES('AES256');
        List<Joint_Sales__c> inserts = new List<Joint_Sales__c>();
        for (PartnerWrapper pw : Partners) {
            if (pw.Selected && !pw.Disabled) inserts.add(new Joint_Sales__c(
                Partner__c = pw.Id,
                Customer__c = acct.Id,
                Contact__c = acct.Caller_Contact__c,
                Comment__c = comment,
                Created_By__c = UserInfo.getUserId()
            ));
        }
        insert inserts;
        for (Joint_Sales__c js : inserts) {
            js.Token__c = crypt.encrypt(js.Id);
        }
        update inserts;
        return new PageReference('/' + acct.Id);
    }

    public PageReference jsCancel() {
        return new PageReference('/' + acct.Id);
    }

}