force-app/main/default/objects/Account/fields/CCD_IO__c.field-meta.xml
<CustomField>
    <fullName>CCD_IO__c</fullName>
    <label>CCD IO</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Closed_Contract_Paid_Date__c.field-meta.xml
<CustomField>
    <fullName>Closed_Contract_Paid_Date__c</fullName>
    <description>https://jira.orderbird.com/browse/CDS-8</description>
    <inlineHelpText>When was the first payment settled for this customer? Filled automatically</inlineHelpText>
    <label>Closed Contract Paid Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Set_CCPD_manually__c.field-meta.xml
<CustomField>
    <fullName>Set_CCPD_manually__c</fullName>
    <defaultValue>false</defaultValue>
    <description>https://jira.orderbird.com/browse/CDS-8</description>
    <inlineHelpText>Should the Closed Contract Paid Date for this account be managed manually? (And not by the automatism)</inlineHelpText>
    <label>Manual CCPD</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CreditBalanceAdjustment__c/CreditBalanceAdjustment__c.object-meta.xml
<CustomObject>
    <label>Credit Balance Adjustment</label>
    <nameField>
        <label>Credit Balance Adjustment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credit Balance Adjustments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CreditBalanceAdjustment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Credit Balance Adjustments</relationshipLabel>
    <relationshipName>Credit_Balance_Adjustments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CreditBalanceAdjustment__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Credit Balance Adjustments</relationshipLabel>
    <relationshipName>Credit_Balance_Adjustments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CreditBalanceAdjustment__c/fields/SourceTransactionType__c.field-meta.xml
<CustomField>
    <fullName>SourceTransactionType__c</fullName>
    <label>Source Transaction Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CreditBalanceAdjustment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>2.0</description>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/CreditBalanceAdjustmentAmount__c.field-meta.xml
<CustomField>
    <fullName>CreditBalanceAdjustmentAmount__c</fullName>
    <label>Credit Balance Adjustment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/CustomerAccount__c.field-meta.xml
<CustomField>
    <fullName>CustomerAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices (Customer Account)</relationshipLabel>
    <relationshipName>Invoices1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InstalmentCharges__c.field-meta.xml
<CustomField>
    <fullName>InstalmentCharges__c</fullName>
    <label>Instalment Charges</label>
    <summaryFilterItems>
        <field>InvoiceLineItem__c.ChargeName__c</field>
        <operation>equals</operation>
        <value>Payment by Instalments Setup Fee</value>
    </summaryFilterItems>
    <summaryForeignKey>InvoiceLineItem__c.Invoice__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoiceDate__c.field-meta.xml
<CustomField>
    <fullName>InvoiceDate__c</fullName>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/InvoicePayment__c/InvoicePayment__c.object-meta.xml
<CustomObject>
    <label>Invoice Payment</label>
    <nameField>
        <displayFormat>InvPmt-{000000}</displayFormat>
        <label>Invoice Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoicePayment__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Payments</relationshipLabel>
    <relationshipName>Invoice_Payments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoicePayment__c/fields/IsQualifyingPayment_formula__c.field-meta.xml
<CustomField>
    <fullName>IsQualifyingPayment_formula__c</fullName>
    <formula>Payment__r.Status__c = &apos;Processed&apos; &amp;&amp; (Payment__r.Type__c = &apos;External&apos; || (Payment__r.Type__c = &apos;Electronic&apos; &amp;&amp; Payment__r.GatewayState__c = &apos;Settled&apos;)) &amp;&amp;  Payment__r.RefundAmount__c = 0</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IsQualifyingPayment (formula)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InvoicePayment__c/fields/PaidDate__c.field-meta.xml
<CustomField>
    <fullName>PaidDate__c</fullName>
    <formula>IF(Payment__r.GatewayState__c==&quot;Settled&quot;,Payment__r.SettledOn__c,Payment__r.EffectiveDate__c)</formula>
    <label>Paid Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CCPD_Calculator.cls
global class CCPD_Calculator implements Database.Batchable<sObject>{
    
    global final String Query;
    
    global CCPD_Calculator() {
        Query = 'SELECT Id, CCD_IO__c, Closed_Contract_Paid_Date__c, '
            + '(SELECT Id FROM Invoices1__r WHERE Status__c = \'Posted\' ORDER BY Name LIMIT 4),('
            + '   SELECT Id, AdjustmentDate__c FROM Credit_Balance_Adjustments__r '
            + '   WHERE SourceTransactionType__c = \'Payment\' AND Type__c = \'Increase\' '
            + '   ORDER BY Name DESC LIMIT 1'
            + ') '
            + 'FROM Account '
            + 'WHERE Id IN (SELECT Account__c FROM Subscription__c) '
            + ' AND (Closed_Contract_Paid_Date__c = null OR Closed_Contract_Paid_Date__c >= LAST_n_DAYS:15) '
            + ' AND Id IN (SELECT CustomerAccount__c FROM Invoice__c WHERE Status__c = \'Posted\' AND (InvoiceDate__c >= 2018-01-01 OR InstalmentCharges__c > 0)) '
            + ' AND Set_CCPD_manually__c = false';
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope){
        List<Id> InvoiceIds = new List<Id>();
        for(sObject s : scope){
            for(sObject ss : (List<sObject>)s.getSObjects('Invoices1__r')){
                InvoiceIds.add((Id)ss.get('Id'));
            }
        }
        List<sObject> InvoiceList = [
            SELECT Id, CustomerAccount__c, Balance__c, CreditBalanceAdjustmentAmount__c, InstalmentCharges__c, Amount__c, (
                SELECT Id, PaidDate__c
                FROM Invoice_Payments__r 
                WHERE IsQualifyingPayment_formula__c = TRUE
                ORDER BY PaidDate__c DESC 
                LIMIT 1
            )
            FROM Invoice__c 
            WHERE Id IN :InvoiceIds
            ORDER BY Name
        ];
        Map<Id,List<sObject>> InvoiceMap = new Map<Id,List<sObject>>();
        for (sObject inv : InvoiceList){
            if(InvoiceMap.get((Id)inv.get('CustomerAccount__c'))==null) InvoiceMap.put((Id)inv.get('CustomerAccount__c'), new List<sObject>());
            InvoiceMap.get((Id)inv.get('CustomerAccount__c')).add(inv);
        }
        for(sObject s : scope){
            sObject RelevantInvoice = null;
            for (sObject ss : InvoiceMap.get((Id)s.get('Id'))){
                if (RelevantInvoice == null){
                    if(
                        (Decimal)ss.get('Balance__c') > 0 || (List<sObject>)ss.getSObjects('Invoice_Payments__r')!=null || (Decimal)ss.get('CreditBalanceAdjustmentAmount__c') < 0
                    ) RelevantInvoice = ss;
                }
            }
            if (RelevantInvoice == null) {
                s.put('Closed_Contract_Paid_Date__c', null);
            }else if (
                ((Decimal)RelevantInvoice.get('InstalmentCharges__c') > 0
                &&
                (Decimal)RelevantInvoice.get('Balance__c') > (Decimal)RelevantInvoice.get('Amount__c') * (18.0/25.0)) // 18/25 replaces 2/3 per Peter Helf CDS-1485
                ||
                ((Decimal)RelevantInvoice.get('InstalmentCharges__c') < 1
                &&
                (Decimal)RelevantInvoice.get('Balance__c') != 0)
                ||
                ((List<sObject>)RelevantInvoice.getSObjects('Invoice_Payments__r')==null 
                && 
                (List<sObject>)s.getSObjects('Credit_Balance_Adjustments__r')==null)
            ){
                s.put('Closed_Contract_Paid_Date__c', null);
            } else {
                Date CreBalDate; try{CreBalDate = (Date)(s.getSObjects('Credit_Balance_Adjustments__r')[0].get('AdjustmentDate__c'));}catch(exception e){}
                DateTime InvPmtDT; try{InvPmtDT = (DateTime)(RelevantInvoice.getSObjects('Invoice_Payments__r')[0].get('PaidDate__c'));}catch(exception e){}
                Date InvPmtDate = ConvertDateTime(InvPmtDT, (Date)s.get('CCD_IO__c'));

                if (CreBalDate != null && s.get('Closed_Contract_Paid_Date__c') == null) { s.put('Closed_Contract_Paid_Date__c', CreBalDate);
                } else if (CreBalDate == null){ s.put('Closed_Contract_Paid_Date__c', InvPmtDate);
                }
            }
        }
        update scope;
    }
    
    global Date ConvertDateTime(DateTime dt, Date d2){
        if (dt==null) return null;
        Date d1 = Date.newInstance(dt.year(), dt.month(), dt.day());
        if (d2 == null) return d1;
        if (d1 < d2) {
            return d1;
        } else {
            return d2;
        }
    }
    
    global void finish(Database.BatchableContext BC){
    }
    
}