force-app/main/default/objects/Account/fields/Closed_Contract_Date__c.field-meta.xml
<CustomField>
    <fullName>Closed_Contract_Date__c</fullName>
    <formula>if( text(AccountType__c) = &quot;Partner&quot; , null ,
IF(and(isnull(
if(BillingAmount__c&gt;0,CCD_Zu__c,null)),isnull(CCD_NetSuite__c),isnull(CCD_IO2__c)),null,
TODAY()-max(
if(isnull(TODAY()-
if(BillingAmount__c&gt;0,CCD_Zu__c,null)),0,TODAY()-
if(BillingAmount__c&gt;0,CCD_Zu__c,null)),
if(isnull(TODAY()-CCD_IO2__c),0,TODAY()-CCD_IO2__c),
if(isnull(TODAY()-CCD_NetSuite__c),0,TODAY()-CCD_NetSuite__c))))</formula>
    <label>Closed Contract Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CSVReport__c/CSVReport__c.object-meta.xml
<CustomObject>
    <label>CSV Report</label>
    <nameField>
        <label>CSV Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSV Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CSVReport__c/fields/EmailTo__c.field-meta.xml
<CustomField>
    <fullName>EmailTo__c</fullName>
    <label>Scheduled Email Recipient(s)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CSVReportField__c/CSVReportField__c.object-meta.xml
<CustomObject>
    <label>CSV Report Field</label>
    <nameField>
        <label>Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSV Report Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CSVReportField__c/fields/Aggregation__c.field-meta.xml
<CustomField>
    <fullName>Aggregation__c</fullName>
    <label>Aggregation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GROUP BY</fullName>
                <default>true</default>
                <label>GROUP BY</label>
            </value>
            <value>
                <fullName>SUM</fullName>
            </value>
            <value>
                <fullName>COUNT</fullName>
            </value>
            <value>
                <fullName>COUNT_DISTINCT</fullName>
            </value>
            <value>
                <fullName>AVG</fullName>
            </value>
            <value>
                <fullName>MIN</fullName>
            </value>
            <value>
                <fullName>MAX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CSVReportField__c/fields/CSVReport__c.field-meta.xml
<CustomField>
    <fullName>CSVReport__c</fullName>
    <label>CSV Report</label>
    <referenceTo>CSVReport__c</referenceTo>
    <relationshipLabel>CSV Report Fields</relationshipLabel>
    <relationshipName>CSV_Report_Fields</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CSVReportField__c/fields/Header__c.field-meta.xml
<CustomField>
    <fullName>Header__c</fullName>
    <label>CSV Column Header</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CSVReportField__c/fields/IsDate__c.field-meta.xml
<CustomField>
    <fullName>IsDate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Date Field</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CSVReportEngine_test.cls
@isTest public class CSVReportEngine_test {

    static TestMethod void test() {
        CSVReport__c csvr = new CSVReport__c(name='test',object__c='Account',filter__c='CreatedDate=today',emailto__c='test@test.com');
        insert csvr;
        insert new CSVReportField__c(CSVReport__c=csvr.Id, name='Name', Header__c='Name', Aggregation__c='GROUP BY');
        insert new CSVReportField__c(CSVReport__c=csvr.Id, name='Closed_Contract_Date__c', Header__c='CCD', Aggregation__c='MAX', isdate__c =true);
        apexpages.currentpage().getparameters().put('id',csvr.Id);
        CSVReportEngine csvre = new CSVReportEngine();
		String filename = csvre.getFileName();        
        String columnheaders = csvre.getColumnHeaders();
        system.debug(json.serialize(csvre.getFields()));
        system.debug(json.serialize(csvre.getReportData()));
        system.debug(json.serialize(csvre.getNewLine()));
        String jobId = System.schedule('test', '0 0 0 3 9 ? 2022', new CSVReportScheduler());
        List<CSVReportEmailer.CSVRequest> csvrs = new List<CSVReportEmailer.CSVRequest>();
        CSVReportEmailer.CSVRequest csvrr = new CSVReportEmailer.CSVRequest();
        csvrr.UserId = userInfo.getUserId();
        csvrr.CSVReportIds = csvr.id;
        csvrs.add(csvrr);
        CSVReportEmailer.CSVInvocableEmail(csvrs);
    }
    
}