force-app/main/default/objects/Account/fields/Closed_Contract_Paid_Date__c.field-meta.xml
<CustomField>
    <fullName>Closed_Contract_Paid_Date__c</fullName>
    <description>https://jira.orderbird.com/browse/CDS-8</description>
    <inlineHelpText>When was the first payment settled for this customer? Filled automatically</inlineHelpText>
    <label>Closed Contract Paid Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Dunning_0_Date__c.field-meta.xml
<CustomField>
    <fullName>Dunning_0_Date__c</fullName>
    <label>Dunning 0 Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Dunning_1_Date__c.field-meta.xml
<CustomField>
    <fullName>Dunning_1_Date__c</fullName>
    <label>Dunning 1 Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Dunning_2_Date__c.field-meta.xml
<CustomField>
    <fullName>Dunning_2_Date__c</fullName>
    <label>Dunning 2 Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/PrimaryLanguage__c.field-meta.xml
<CustomField>
    <fullName>PrimaryLanguage__c</fullName>
    <defaultValue>&quot;German&quot;</defaultValue>
    <description>Stakeholder: Sales &amp; CS with MKT</description>
    <inlineHelpText>What language do we use to communicate with this venue? Filled in as soon as known. Updated if necessary!</inlineHelpText>
    <label>Primary Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Language</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/SF_BillTo_Contact__c.field-meta.xml
<CustomField>
    <fullName>SF_BillTo_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Stakeholder: Sales &amp; Account Management</description>
    <inlineHelpText>This defines the official billing address.</inlineHelpText>
    <label>Billing Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.ParentId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Zuora BillTo Contact)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/SuccessfulTasks__c.field-meta.xml
<CustomField>
    <fullName>SuccessfulTasks__c</fullName>
    <description>Stakeholder: UNKNOWN - who wanted this field? BI, Sales? // processes begin this seem to be not setup yet!</description>
    <inlineHelpText>Who many successful tasks have we had with this venue? Filled automatically</inlineHelpText>
    <label>Successful Tasks</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Target_Product__c.field-meta.xml
<CustomField>
    <fullName>Target_Product__c</fullName>
    <label>Target Product</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>This record type is used for customer accounts and the standard Sales process.</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Contact/fields/PrimaryLanguage__c.field-meta.xml
<CustomField>
    <fullName>PrimaryLanguage__c</fullName>
    <description>Stakeholder: Sales &amp; CS &amp; MKT</description>
    <inlineHelpText>What language do we use to communicate with this venue? Filled in as soon as known. Updated if necessary!</inlineHelpText>
    <label>Primary Language</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>Russian</fullName>
            </value>
            <value>
                <fullName>Italian</fullName>
            </value>
            <value>
                <fullName>Polish</fullName>
            </value>
            <value>
                <fullName>Chinese</fullName>
            </value>
            <value>
                <fullName>Japanese</fullName>
            </value>
            <value>
                <fullName>Swedish</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>2.0</description>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Language.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>German</fullName>
        <default>true</default>
        <label>German</label>
    </customValue>
    <customValue>
        <fullName>English</fullName>
    </customValue>
    <customValue>
        <fullName>French</fullName>
    </customValue>
    <customValue>
        <fullName>Spanish</fullName>
    </customValue>
    <customValue>
        <fullName>Russian</fullName>
    </customValue>
    <customValue>
        <fullName>Italian</fullName>
    </customValue>
    <customValue>
        <fullName>Polish</fullName>
    </customValue>
    <customValue>
        <fullName>Chinese</fullName>
    </customValue>
    <customValue>
        <fullName>Japanese</fullName>
    </customValue>
    <customValue>
        <fullName>Swedish</fullName>
    </customValue>
    <masterLabel>Language</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Dunning_Test.cls
@isTest
public class Dunning_Test {

    static testMethod void dunningMessages() {
        List<Account> insAccts = new List<Account>();
        insAccts.add( new Account(
            name='English Test',
            PrimaryLanguage__c = 'English'
        ));
        insAccts.add( new Account(
            name='German Test',
            PrimaryLanguage__c = 'German'
        ));
        insAccts.add( new Account(
            name='French Test',
            PrimaryLanguage__c = 'French'
        ));
        insert insAccts;
        dunningMessageController dmc = new dunningMessageController();
        for (Account a : insAccts) {
            dmc.acctId = a.Id;
        }
    }

    static testMethod void batchTest() {
        Id RTId = [SELECT Id FROM RecordType WHERE SObjectType = 'Account' AND Name = 'Customer' LIMIT 1].Id;
        List<Account> insAccts = new List<Account>();
        List<Account> updAccts = new List<Account>();
        List<Contact> insCons = new List<Contact>();
        List<Invoice__c> insInvs = new List<Invoice__c>();
        for (Integer xx=0; xx<4; xx++) {
            insAccts.add( new Account(
                name='English Test',
                PrimaryLanguage__c = 'English',
                RecordTypeId = RTId,
                Dunning_0_Date__c = Date.newInstance(2011,1,1),
                SuccessfulTasks__c = xx
            ));
            insAccts.add( new Account(
                name='German MINITest',
                PrimaryLanguage__c = 'German',
                RecordTypeId = RTId,
                Dunning_0_Date__c = Date.newInstance(2011,1,1),
                Dunning_1_Date__c = Date.newInstance(2011,1,1),
                Target_Product__c = 'MINI',
                SuccessfulTasks__c = xx
            ));
            insAccts.add( new Account(
                name='German PROTest',
                PrimaryLanguage__c = 'German',
                RecordTypeId = RTId,
                Dunning_0_Date__c = Date.newInstance(2011,1,1),
                Dunning_1_Date__c = Date.newInstance(2011,1,1),
                Closed_Contract_Paid_Date__c = Date.newInstance(2011,1,1),
                SuccessfulTasks__c = xx
            ));
            insAccts.add( new Account(
                name='German Test2',
                PrimaryLanguage__c = 'German',
                RecordTypeId = RTId,
                Dunning_0_Date__c = Date.newInstance(2011,1,1),
                Dunning_1_Date__c = Date.newInstance(2011,1,1),
                Dunning_2_Date__c = Date.newInstance(2011,1,1),
                SuccessfulTasks__c = xx
            ));
            insAccts.add( new Account(
                name='French Test',
                PrimaryLanguage__c = 'French',
                RecordTypeId = RTId,
                Target_Product__c = 'PRO',
                SuccessfulTasks__c = xx
            ));
        }
        insert insAccts;
        for (Account a : insAccts) {
            insInvs.add(new Invoice__c(
            	Account__c = a.Id,
                Balance__c = 11,
                Status__c = 'Posted',
                DueDate__c = Date.today().addDays(Integer.valueOf(-10 * a.SuccessfulTasks__c - 2))
            ));
            insCons.add(new Contact(
            	Lastname = 'test',
                AccountId = a.Id,
                Email = 'noreply@orderbird.com'
            ));
        }
        insert insInvs;
        insert insCons;
        for (Contact c : insCons) {
            updAccts.add(new Account(
            	Id = c.AccountId,
                SF_BillTo_Contact__c = c.Id
            ));
        }
        update updAccts;
        for (Integer x=0; x<4; x++) {
            database.executeBatch(new DunningBatch(x), 20);
            system.debug(x);
        }
    }
    
    static testMethod void testScheduler() {
        test.startTest();
 		DunningBatch_Scheduler dbs = new DunningBatch_Scheduler();
        String sch = '0 0 23 * * ?';
        system.schedule('Test check', sch, dbs);
        test.stopTest();
    }

}