force-app/main/default/objects/Account/fields/CustomerID__c.field-meta.xml
<CustomField>
    <fullName>CustomerID__c</fullName>
    <displayFormat>{000000}</displayFormat>
    <externalId>true</externalId>
    <inlineHelpText>Used for external communication, e.g. on the invoice</inlineHelpText>
    <label>Customer ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Account/fields/Target_Product__c.field-meta.xml
<CustomField>
    <fullName>Target_Product__c</fullName>
    <label>Target Product</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <description>This record type should be used for Partner accounts only.</description>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/BamboraOnboarding__c/BamboraOnboarding__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Bambora Onboarding</label>
</CustomObject>

force-app/main/default/objects/MyObVenue__c/MyObVenue__c.object-meta.xml
<CustomObject>
    <label>MyOb Venue</label>
    <nameField>
        <displayFormat>MyOb-{000000}</displayFormat>
        <label>MyOb Venue</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MyOb Venues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MyObVenue__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>MyOrderbird_Log_ons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MyObVenue__c/fields/BamboraId__c.field-meta.xml
<CustomField>
    <fullName>BamboraId__c</fullName>
    <label>Bambora Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MyObVenue__c/fields/Target_Product__c.field-meta.xml
<CustomField>
    <fullName>Target_Product__c</fullName>
    <formula>Account__r.Target_Product__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Target Product</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BamboraOnboard.cls
public class BamboraOnboard implements Queueable, Database.AllowsCallouts {
    
    public Final Id MyObVenueId;
    
    public BamboraOnboard(Id iMyObVenueId) {
        MyObVenueId = iMyObVenueId;
    }
    
    public void execute(QueueableContext context) {
        MyObVenue__c v = [SELECT Id, BamboraId__c, Account__r.Target_Product__c, Account__r.CustomerId__c FROM MyObVenue__c WHERE Id = :MyObVenueId LIMIT 1];
        if (v.Account__r.Target_Product__c == 'MINI') {
            system.debug(v.Account__r.CustomerId__c);
            v.BamboraId__c = getBamboraId(String.valueOf(v.Account__r.CustomerId__c));
            update v;
        }
    }
    
    public static String getBamboraId(String CustId) {
        Http h = new Http();
        HttpRequest req = new HttpRequest();
        req.setEndpoint(BamboraOnboarding__c.getAll().get('MINI').API_URL__c);
        req.setMethod('POST');
        req.setHeader('Content-Type', 'application/json');
        req.setBody(json.serialize(new BamboraMINIOnboard(CustId)).replace('_x',''));
        system.debug(req.getBody());
        HttpResponse res;
        if (test.isRunningTest()) { res = new HttpResponse(); res.setBody('{"id":"abc123"}'); } else { res = h.send(req); }
        return ((BamboraResponse)JSON.deserialize(res.getBody(), BamboraResponse.class)).Id;
    }
    
    public class BamboraMINIOnboard {
        public BoardingWrap Boarding;
        public PackageWrap Package_x;
        public PriceWrap Price;
        public PartnerWrap Partner;
        public BamboraMINIOnboard(String CustId) {
            Boarding = new BoardingWrap();
            Package_x = new PackageWrap();
            Price = new PriceWrap();
            Partner = new PartnerWrap(CustId);
        }
    }
    
    public class BoardingWrap {
		public String CultureCode = 'de-DE';
		public String CountryIso3Code = 'DEU';
		public String BackofficeVersion = 'Bambora';
    }
    
    public class PackageWrap {
		public String Code = 'ACCEPTANCE_POS';
		public String TerminalModel = 'PAX A920';
		public String PaymentServiceProvider = 'Payworks';
    }
    
    public class PriceWrap {
		//public String PricePlanName = 'CONNECT_LIGHT';
		public String PricePlanName = 'CONNECT_LIGHT_MINI';
    }
    
    public class PartnerWrap {
        public String Code;
        public String Source;
        public String ReferenceId;
        public String ReferenceEmail;
        public String ExternalReference;
        public PartnerWrap(String CustId) {
            Code = 'A00252810';
            Source = 'Orderbird';
            ReferenceId = '0051p00000AtuSDAAZ';
            ReferenceEmail = 'valeria.meissner@orderbird.com';
            ExternalReference = CustId;
        }
    }
    
    public class BamboraResponse {
        public String Id;
    }
    
}