force-app/main/default/objects/Account/fields/CustomerID__c.field-meta.xml
<CustomField>
    <fullName>CustomerID__c</fullName>
    <displayFormat>{000000}</displayFormat>
    <externalId>true</externalId>
    <inlineHelpText>Used for external communication, e.g. on the invoice</inlineHelpText>
    <label>Customer ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Account/fields/Interwega_Status__c.field-meta.xml
<CustomField>
    <fullName>Interwega_Status__c</fullName>
    <label>Interwega Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Interwega_Import__c/Interwega_Import__c.object-meta.xml
<CustomObject>
    <label>Interwega Import</label>
    <nameField>
        <displayFormat>IWImp-{00000000}</displayFormat>
        <label>Interwega Import Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interwega Imports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Interwega_Import__c/fields/Interwega_Status__c.field-meta.xml
<CustomField>
    <fullName>Interwega_Status__c</fullName>
    <label>Interwega Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/InterwegaController_Test.cls
@isTest public class InterwegaController_Test {
    static TestMethod void test1() {
        insert new Account(name='test',Interwega_Status__c='test');
        Integer i = InterwegaController.CountInterwega();
        String s = InterwegaController.ClearInterwega();
        system.assertEquals(1, i);
        system.assertEquals('OK', s);
    }
    
    static TestMethod void test2() {
        Account a = new Account(name='test');
        insert a;
        String custId = [SELECT Id, CustomerId__c FROM Account WHERE Id=:a.Id LIMIT 1].CustomerId__c;
        insert new Interwega_Import__c(CustomerId__c=custId, Interwega_Status__c='test');
    }

    static TestMethod void test3() {
        insert new Account(name='test',Interwega_Status__c='test');
        Database.executeBatch(new InterwegaBatch());
    }
}