force-app/main/default/objects/Account/fields/Dunning_0_Date__c.field-meta.xml
<CustomField>
    <fullName>Dunning_0_Date__c</fullName>
    <label>Dunning 0 Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Dunning_1_Date__c.field-meta.xml
<CustomField>
    <fullName>Dunning_1_Date__c</fullName>
    <label>Dunning 1 Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Dunning_2_Date__c.field-meta.xml
<CustomField>
    <fullName>Dunning_2_Date__c</fullName>
    <label>Dunning 2 Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Dunning_X_Date__c.field-meta.xml
<CustomField>
    <fullName>Dunning_X_Date__c</fullName>
    <label>Dunning X Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Exclude_Account_Name_on_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Exclude_Account_Name_on_Invoice__c</fullName>
    <label>Exclude Account Name on Invoice</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <default>true</default>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Exclude_Contact_Name_on_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Exclude_Contact_Name_on_Invoice__c</fullName>
    <label>Exclude Contact Name on Invoice</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/LegalCompanyName__c.field-meta.xml
<CustomField>
    <fullName>LegalCompanyName__c</fullName>
    <description>Stakeholder: Stakeholders: Sales with Account Management</description>
    <inlineHelpText>What is the company&apos;s legal name for e.g. billing? It is usually in the „about us“/Impressum of websites . If there is an addition such as Gmbh / UG / LDT. / SAS / SL... it’s an operating company. It could however also be a non-incorporated company</inlineHelpText>
    <label>Legal Company Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/myOrderbirdEmail__c.field-meta.xml
<CustomField>
    <fullName>myOrderbirdEmail__c</fullName>
    <description>Stakeholder: CS</description>
    <inlineHelpText>By which email address is this account officially registered on my.orderbird? Filled in as soon as known. Must be updated if changes occur!</inlineHelpText>
    <label>my.orderbird Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/NS_Customer_Internal_ID__c.field-meta.xml
<CustomField>
    <fullName>NS_Customer_Internal_ID__c</fullName>
    <description>Stakeholder: NEST</description>
    <externalId>true</externalId>
    <inlineHelpText>What is the internal ID of this customer account in Netsuite? Updated manually regularly</inlineHelpText>
    <label>NS Customer Internal ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SF_BillTo_Contact__c.field-meta.xml
<CustomField>
    <fullName>SF_BillTo_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Stakeholder: Sales &amp; Account Management</description>
    <inlineHelpText>This defines the official billing address.</inlineHelpText>
    <label>Billing Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.ParentId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Zuora BillTo Contact)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/SF_SoldTo_Contact__c.field-meta.xml
<CustomField>
    <fullName>SF_SoldTo_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Stakeholder: Sales &amp; Account Management</description>
    <inlineHelpText>This contact defines the official shipping address.</inlineHelpText>
    <label>Shipping Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.ParentId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tax_Exempt_Reason__c.field-meta.xml
<CustomField>
    <fullName>Tax_Exempt_Reason__c</fullName>
    <description>https://jira.orderbird.com/browse/SAL-1185</description>
    <label>Tax Exempt Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Non Tax Exempt</fullName>
            </value>
            <value>
                <fullName>EU reverse charge mechanism</fullName>
            </value>
            <value>
                <fullName>Third country jurisdictions</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/taxExempted__c.field-meta.xml
<CustomField>
    <fullName>taxExempted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>tax exempted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/VATNumber__c.field-meta.xml
<CustomField>
    <fullName>VATNumber__c</fullName>
    <description>Stakeholder: Finance</description>
    <inlineHelpText>What is the venues value added tax (VAT)  number of this venue? Filled in by Sales. Required for most non-German EU customers</inlineHelpText>
    <label>VAT Number (Raw)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/classes/ZuoraAccountUpdateUtil.cls
/**
 * @author keylight
 */
public with sharing class ZuoraAccountUpdateUtil {/*
    public static List<ZuoraAccountUpdate> getZuoraAccountUpdates(
        Account oldAccount,
        Account newAccount,
        List<Zuora__CustomerAccount__c> billingAccounts
        ) {
        List<ZuoraAccountUpdate> accountUpdates = new List<ZuoraAccountUpdate>();
        if (ZuoraAccountUpdateUtil.accountNeedsUpdate(oldAccount, newAccount)) {
            for (Zuora__CustomerAccount__c billingAccount : billingAccounts) {
                if (billingAccount.Zuora__Account__c == newAccount.Id) {
                    accountUpdates.add(new ZuoraAccountUpdate(newAccount, billingAccount.Zuora__Zuora_Id__c));
                }
            }    
        }
        return accountUpdates;
    }

    public static List<ZuoraContactUpdate> getZuoraContactUpdates(
        Account oldAccount,
        Account newAccount,
        List<Contact> contacts,
        List<Zuora__CustomerAccount__c> billingAccounts
        ) {
        List<ZuoraContactUpdate> contactUpdates = new List<ZuoraContactUpdate>();
        if (ZuoraAccountUpdateUtil.billToNeedsUpdate(oldAccount, newAccount)) {
            for (Contact contact : contacts) {
                if (contact.Id == newAccount.SF_BillTo_Contact__c) {
                    for (Zuora__CustomerAccount__c billingAccount : billingAccounts) {
                        if (billingAccount.Zuora__Account__c == newAccount.Id) {
                            contactUpdates.add(new ZuoraContactUpdate(contact, billingAccount.Zuora__BillToId__c));
                        }
                    }    
                }
            }
        }
        if (ZuoraAccountUpdateUtil.soldToNeedsUpdate(oldAccount, newAccount)) {
            for (Contact contact : contacts) {
                if (contact.Id == newAccount.SF_SoldTo_Contact__c) {
                    for (Zuora__CustomerAccount__c billingAccount : billingAccounts) {
                        if (billingAccount.Zuora__Account__c == newAccount.Id) {
                            contactUpdates.add(new ZuoraContactUpdate(contact, billingAccount.Zuora__SoldToId__c));
                        }
                    }    
                }
            }
        }
        return contactUpdates;
    }

    private static Boolean billToNeedsUpdate(Account a1, Account a2) {
        return a1.SF_BillTo_Contact__c != a2.SF_BillTo_Contact__c;
    }

    private static Boolean soldToNeedsUpdate(Account a1, Account a2) {
        return a1.SF_SoldTo_Contact__c != a2.SF_SoldTo_Contact__c;
    } 
            
    @TestVisible
    private static Boolean accountNeedsUpdate(Account a1, Account a2) {
        for (String field : accountFields) {
            if (a1.get(field) != a2.get(field)) return true;
        }
        return false;
    }

    private static List<String> accountFields = new List<String>{
            'myOrderbirdEmail__c',
            'LegalCompanyName__c',
            'NS_Customer_Internal_ID__c',
            'SF_BillTo_Contact__c',
            'SF_SoldTo_Contact__c',
            'taxExempted__c',
            'VATNumber__c',
            'Tax_Exempt_Reason__c',
            'Exclude_Contact_Name_on_Invoice__c',
            'Exclude_Account_Name_on_Invoice__c',
         /**   'Dunning_0_Date__c',
            'Dunning_1_Date__c',
            'Dunning_2_Date__c',
            'Dunning_X_Date__c', *
            'Name'
    };*/
}