force-app/main/default/objects/Account/fields/Dunning_Status__c.field-meta.xml
<CustomField>
    <fullName>Dunning_Status__c</fullName>
    <formula>IF(
    NOT(ISBLANK(Dunning_X_Date__c)),
    &quot;Closed&quot;,
    IF(
        NOT(ISBLANK(Dunning_2_Date__c)),
        &quot;2nd Dunning&quot;,
        IF(
            NOT(ISBLANK(Dunning_1_Date__c)),
            &quot;1st Dunning&quot;,
            IF(
                NOT(ISBLANK(Dunning_0_Date__c)),
                &quot;Friendly Reminder&quot;,
                &quot;Not in Dunning&quot;
            )
        )
    )
)</formula>
    <label>Dunning Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Exclude_Account_Name_on_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Exclude_Account_Name_on_Invoice__c</fullName>
    <label>Exclude Account Name on Invoice</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <default>true</default>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Exclude_Contact_Name_on_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Exclude_Contact_Name_on_Invoice__c</fullName>
    <label>Exclude Contact Name on Invoice</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/LegalCompanyName__c.field-meta.xml
<CustomField>
    <fullName>LegalCompanyName__c</fullName>
    <description>Stakeholder: Stakeholders: Sales with Account Management</description>
    <inlineHelpText>What is the company&apos;s legal name for e.g. billing? It is usually in the „about us“/Impressum of websites . If there is an addition such as Gmbh / UG / LDT. / SAS / SL... it’s an operating company. It could however also be a non-incorporated company</inlineHelpText>
    <label>Legal Company Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/myOrderbirdEmail__c.field-meta.xml
<CustomField>
    <fullName>myOrderbirdEmail__c</fullName>
    <description>Stakeholder: CS</description>
    <inlineHelpText>By which email address is this account officially registered on my.orderbird? Filled in as soon as known. Must be updated if changes occur!</inlineHelpText>
    <label>my.orderbird Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/NS_Customer_Internal_ID__c.field-meta.xml
<CustomField>
    <fullName>NS_Customer_Internal_ID__c</fullName>
    <description>Stakeholder: NEST</description>
    <externalId>true</externalId>
    <inlineHelpText>What is the internal ID of this customer account in Netsuite? Updated manually regularly</inlineHelpText>
    <label>NS Customer Internal ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tax_Exempt_Reason__c.field-meta.xml
<CustomField>
    <fullName>Tax_Exempt_Reason__c</fullName>
    <description>https://jira.orderbird.com/browse/SAL-1185</description>
    <label>Tax Exempt Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Non Tax Exempt</fullName>
            </value>
            <value>
                <fullName>EU reverse charge mechanism</fullName>
            </value>
            <value>
                <fullName>Third country jurisdictions</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/taxExempted__c.field-meta.xml
<CustomField>
    <fullName>taxExempted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>tax exempted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/VATNumber__c.field-meta.xml
<CustomField>
    <fullName>VATNumber__c</fullName>
    <description>Stakeholder: Finance</description>
    <inlineHelpText>What is the venues value added tax (VAT)  number of this venue? Filled in by Sales. Required for most non-German EU customers</inlineHelpText>
    <label>VAT Number (Raw)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ZuoraAccountUpdate.cls
/**
 * @author keylight
 */
global class ZuoraAccountUpdate {
    public Account account;
    public String zuoraId;

    global ZuoraAccountUpdate(Account account, String zuoraId) {
        this.account = account;
        this.zuoraId = zuoraId;
    }

    @TestVisible
    private String toJson() {
        JSONGenerator gen = JSON.createGenerator(true);
        gen.writeStartObject();
        if (this.account.LegalCompanyName__c != null) gen.writeStringField('LegalCompanyName__c', this.account.LegalCompanyName__c);
        if (this.account.NS_Customer_Internal_ID__c != null) gen.writeStringField('NS_Customer_Internal_ID__c', this.account.NS_Customer_Internal_ID__c);
        if (this.account.myOrderbirdEmail__c != null) gen.writeStringField('myOrderbirdEmail__c', this.account.myOrderbirdEmail__c);
        if (this.account.Exclude_Account_Name_on_Invoice__c != null) gen.writeStringField('Exclude_Account_Name_on_Invoice__c', this.account.Exclude_Account_Name_on_Invoice__c);
        if (this.account.Tax_Exempt_Reason__c != null) gen.writeStringField('Tax_Exempt_Reason__c', this.account.Tax_Exempt_Reason__c);
        if (this.account.Name != null) gen.writeStringField('name', this.account.Name);
        if (this.account.Exclude_Contact_Name_on_Invoice__c != null) gen.writeStringField('Exclude_Contact_Name_on_Invoice__c', this.account.Exclude_Contact_Name_on_Invoice__c);
        if (this.account.Dunning_Status__c != null) gen.writeStringField('Dunning_Status__c', this.account.Dunning_Status__c);
        ZuoraAccountTaxInfo taxInfo = new ZuoraAccountTaxInfo(this.account.VATNumber__c, this.account.taxExempted__c);
        gen.writeObjectField('taxInfo', taxInfo);
        gen.writeEndObject();
        return gen.getAsString();
    }

    global String send() {
        String data = this.toJson();
        String path = 'accounts/' + this.zuoraId;
        String res = ZuoraManager.callZuoraAPI(path, 'PUT', data);
        return res;
    }

    public class ZuoraAccountTaxInfo {
        public String VATId;
        public String exemptStatus;

        public ZuoraAccountTaxInfo(String vatId, Boolean taxExempt) {
            if(vatId == null) {
                this.VATId = '';
            } else {
                this.VATId = vatId;
            }
            if(taxExempt){
                this.exemptStatus = 'Yes';
            } else {
                this.exemptStatus = 'No';
            }
        }

    }
}