force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <inlineHelpText>Read-Only field that was used for data migration. Please use the contact(s) to store contact related information.</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>https://jira.orderbird.com/browse/SFDC-1487</description>
    <inlineHelpText>Primary Contact for all relevant communication. Auto-populated after lead conversion.</inlineHelpText>
    <label>Primary Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Contact.Account.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Account.Id</field>
            <operation>equals</operation>
            <valueField>$Source.ParentId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Primary Contact)</relationshipLabel>
    <relationshipName>PrimaryContactForAcc</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/SF_BillTo_Contact__c.field-meta.xml
<CustomField>
    <fullName>SF_BillTo_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Stakeholder: Sales &amp; Account Management</description>
    <inlineHelpText>This defines the official billing address.</inlineHelpText>
    <label>Billing Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.ParentId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Zuora BillTo Contact)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/SF_SoldTo_Contact__c.field-meta.xml
<CustomField>
    <fullName>SF_SoldTo_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Stakeholder: Sales &amp; Account Management</description>
    <inlineHelpText>This contact defines the official shipping address.</inlineHelpText>
    <label>Shipping Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.ParentId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/VenueCity__c.field-meta.xml
<CustomField>
    <fullName>VenueCity__c</fullName>
    <label>Venue City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/VenueCountry__c.field-meta.xml
<CustomField>
    <fullName>VenueCountry__c</fullName>
    <label>Venue Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/VenuePostalCode__c.field-meta.xml
<CustomField>
    <fullName>VenuePostalCode__c</fullName>
    <label>Venue Postal Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/VenueStreet__c.field-meta.xml
<CustomField>
    <fullName>VenueStreet__c</fullName>
    <label>Venue Street</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <formula>Account.Primary_Contact__c = Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/globalValueSets/Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Germany</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Switzerland</fullName>
    </customValue>
    <customValue>
        <fullName>France</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Bulgaria</fullName>
    </customValue>
    <customValue>
        <fullName>China</fullName>
    </customValue>
    <customValue>
        <fullName>Costa Rica</fullName>
    </customValue>
    <customValue>
        <fullName>Cyprus</fullName>
    </customValue>
    <customValue>
        <fullName>Czech Republic</fullName>
    </customValue>
    <customValue>
        <fullName>Denmark</fullName>
    </customValue>
    <customValue>
        <fullName>Dominican Republic</fullName>
    </customValue>
    <customValue>
        <fullName>Egypt</fullName>
    </customValue>
    <customValue>
        <fullName>Estonia</fullName>
    </customValue>
    <customValue>
        <fullName>Finland</fullName>
    </customValue>
    <customValue>
        <fullName>Gambia</fullName>
    </customValue>
    <customValue>
        <fullName>Ghana</fullName>
    </customValue>
    <customValue>
        <fullName>Greece</fullName>
    </customValue>
    <customValue>
        <fullName>Grenada</fullName>
    </customValue>
    <customValue>
        <fullName>Guadeloupe</fullName>
    </customValue>
    <customValue>
        <fullName>Hungary</fullName>
    </customValue>
    <customValue>
        <fullName>Iceland</fullName>
    </customValue>
    <customValue>
        <fullName>India</fullName>
    </customValue>
    <customValue>
        <fullName>Ireland</fullName>
    </customValue>
    <customValue>
        <fullName>Italy</fullName>
    </customValue>
    <customValue>
        <fullName>Liechtenstein</fullName>
    </customValue>
    <customValue>
        <fullName>Luxembourg</fullName>
    </customValue>
    <masterLabel>Countries</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AddressSync.cls
/**
 * @author joern
 * @description Sync address data from related (zuora billing/soldTo lookups) contacts
 * to billing and shipping address fields on account object
 * 
 * added email/phone sync (( contact ==> account only )) 
 * @modified by Bart
 * 
 */
public class AddressSync {
	@TestVisible private List<SObject> objList;
	@TestVisible private Map<ID, Account> relatedAccounts;
	@TestVisible private Map<ID, Contact> relatedContacts;

	public AddressSync(SObject[] objList) {
		this.objList = objList;
	}

	/**
	 * @description Used in account trigger (beforeUpdate)
	 * @param acc Account
	 */
	public void updateAccountAddresses(Account acc) {
		//unsetAccountAddresses(acc);
        setShipAndVenueAccountAddresses(acc);
        /*
		if (relatedContacts != null) {
			Contact billingContact = relatedContacts.get(acc.SF_BillTo_Contact__c);
			if (billingContact != null) {
				setBillingAccountAddress(acc, billingContact);
			}
			Contact shippingContact = relatedContacts.get(acc.SF_SoldTo_Contact__c);
			if (shippingContact != null) {
				setShippingAccountAddress(acc, shippingContact);
			}
		}*/
	}

	/**
	 * @description Used in contact trigger (afterUpdate). Updates account if BillTo and/or SoldTo contact changed
	 * @param cont Contact
	 * @return Account
	 */
	public Account updateAccountAddresses(Contact cont) {
		Account acc = relatedAccounts.get(cont.AccountId);
		if (acc == null) {
			return null;
		} else {
			setShipAndVenueAccountAddresses(acc);
            if (acc.Primary_Contact__c == cont.Id) {
                setPhoneAndEmail(acc, cont);
            }
			return acc;
		}
	}

	public void loadRelatedAccountAddresses() {
		Set<ID> accountIDs = findAccountIDs();
		this.relatedAccounts = new Map<ID, Account>([
				SELECT
						Phone, Email__c,			
            			SF_BillTo_Contact__c, SF_SoldTo_Contact__c, Primary_Contact__c,
						BillingStreet, BillingCity, BillingState, BillingCountry, BillingCountryCode, BillingPostalCode,
						VenueStreet__c, VenueCity__c, VenueCountry__c, VenuePostalCode__c,
						ShippingStreet, ShippingCity, ShippingState, ShippingCountry, ShippingCountryCode, ShippingPostalCode
				FROM Account
				WHERE Id IN :accountIDs
		]);
	}

	public void loadRelatedContactAddresses() {
		Set<ID> contactIDs = findContactIDs();
		relatedContacts = new Map<ID, Contact>([
				SELECT
						MailingStreet, MailingCity, MailingState, MailingCountry, MailingCountryCode, MailingPostalCode,
            			Phone, Email
				FROM Contact
				WHERE Id IN :contactIDs
		]);
	}

	@TestVisible
	private Set<ID> findContactIDs() {
		Set<ID> contactIDs = new Set<ID>();
		if (objList != null) {
			for (Account acc : (List<Account>) objList) {
				contactIDs.add(acc.SF_BillTo_Contact__c);
				contactIDs.add(acc.SF_SoldTo_Contact__c);
                contactIDs.add(acc.Primary_Contact__c);
			}
		}
		return contactIDs;
	}

	@TestVisible
	private Set<ID> findAccountIDs() {
		Set<ID> accountIDs = new Set<ID>();
		if (objList != null) {
			for (Contact cont : (List<Contact>) objList) {
				accountIDs.add(cont.AccountId);
			}
		}
		return accountIDs;
	}

	/*private void unsetAccountAddresses(Account acc) {
		acc.BillingStreet = null;
		acc.BillingCity = null;
		acc.BillingState = null;
		acc.BillingCountry = null;
		acc.BillingCountryCode = null;
		acc.BillingPostalCode = null;
		acc.ShippingStreet = null;
		acc.ShippingCity = null;
		acc.ShippingState = null;
		acc.ShippingCountry = null;
		acc.ShippingCountryCode = null;
		acc.ShippingPostalCode = null;
	}*/

	/*private void setBillingAccountAddress(Account acc, Contact cont) {
		acc.BillingStreet = cont.MailingStreet;
		acc.BillingCity = cont.MailingCity;
		acc.BillingState = cont.MailingState;
		acc.BillingCountry = cont.MailingCountry;
		acc.BillingCountryCode = cont.MailingCountryCode;
		acc.BillingPostalCode = cont.MailingPostalCode;
	}

	private void setShippingAccountAddress(Account acc, Contact cont) {
		acc.ShippingStreet = cont.MailingStreet;
		acc.ShippingCity = cont.MailingCity;
		acc.ShippingState = cont.MailingState;
		acc.ShippingCountry = cont.MailingCountry;
		acc.ShippingCountryCode = cont.MailingCountryCode;
		acc.ShippingPostalCode = cont.MailingPostalCode;
	}*/
    
    private void setShipAndVenueAccountAddresses(Account acc) {
		acc.ShippingStreet = acc.BillingStreet;
		acc.ShippingCity = acc.BillingCity;
		acc.ShippingCountry = acc.BillingCountry;
		acc.ShippingCountryCode = acc.BillingCountryCode;
		acc.ShippingPostalCode = acc.BillingPostalCode;
		acc.VenueStreet__c = acc.BillingStreet;
		acc.VenueCity__c = acc.BillingCity;
		acc.VenueCountry__c = acc.BillingCountry;
		acc.VenuePostalCode__c = acc.BillingPostalCode;
    }
    
    private void setPhoneAndEmail(Account acc, Contact cont) {
        acc.Phone = cont.Phone;
        acc.Email__c = cont.Email;
    }
}