force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <inlineHelpText>Read-Only field that was used for data migration. Please use the contact(s) to store contact related information.</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/PrimaryLanguage__c.field-meta.xml
<CustomField>
    <fullName>PrimaryLanguage__c</fullName>
    <defaultValue>&quot;German&quot;</defaultValue>
    <description>Stakeholder: Sales &amp; CS with MKT</description>
    <inlineHelpText>What language do we use to communicate with this venue? Filled in as soon as known. Updated if necessary!</inlineHelpText>
    <label>Primary Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Language</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/SF_BillTo_Contact__c.field-meta.xml
<CustomField>
    <fullName>SF_BillTo_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Stakeholder: Sales &amp; Account Management</description>
    <inlineHelpText>This defines the official billing address.</inlineHelpText>
    <label>Billing Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.ParentId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Zuora BillTo Contact)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Template_Branding__c.field-meta.xml
<CustomField>
    <fullName>Template_Branding__c</fullName>
    <description>https://jira.orderbird.com/browse/CDS-3198</description>
    <formula>IF(Target_Product__c = &apos;MINI&apos;,&apos;MINI&apos;, &apos;PRO&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Template Branding</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/IsInvoice__c.field-meta.xml
<CustomField>
    <fullName>IsInvoice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsInvoice</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InvoiceSending__c/InvoiceSending__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>InvoiceSending</label>
</CustomObject>

force-app/main/default/objects/InvoiceSending__c/fields/BatchSize__c.field-meta.xml
<CustomField>
    <fullName>BatchSize__c</fullName>
    <label>BatchSize</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OBInvoice__c/OBInvoice__c.object-meta.xml
<CustomObject>
    <label>OB Invoice</label>
    <nameField>
        <label>Invoice (New) Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OB Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OBInvoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Invoices_New</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OBInvoice__c/fields/Base64Pdf__c.field-meta.xml
<CustomField>
    <fullName>Base64Pdf__c</fullName>
    <label>Base64Pdf</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/OBInvoice__c/fields/Correction_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Correction_Invoice__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Stakeholder: CDS https://jira.orderbird.com/browse/CDS-2990</description>
    <label>Correction Invoice</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OBInvoice__c/fields/Credit_Memo_Amount__c.field-meta.xml
<CustomField>
    <fullName>Credit_Memo_Amount__c</fullName>
    <formula>IF( Transaction_Type__c = &apos;Credit Memo&apos; &amp;&amp; Amount__c &lt; 0, Amount__c * -1, Amount__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Credit Memo Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OBInvoice__c/fields/HasBeenEmailed__c.field-meta.xml
<CustomField>
    <fullName>HasBeenEmailed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Been Emailed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OBInvoice__c/fields/MismatchTotal__c.field-meta.xml
<CustomField>
    <fullName>MismatchTotal__c</fullName>
    <formula>ABS(Amount__c - AmountRollup__c) &gt; 0.009</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mismatch Total</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OBInvoice__c/fields/Template_Branding__c.field-meta.xml
<CustomField>
    <fullName>Template_Branding__c</fullName>
    <description>https://jira.orderbird.com/browse/CDS-3198</description>
    <formula>&apos;MINI&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Template Branding</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OBInvoice__c/fields/Transaction_Label__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Label__c</fullName>
    <description>For Templates and such
Language as a condition not added yet</description>
    <formula>IF( Transaction_Type__c = &quot;Credit Memo&quot;, &quot;Gutschrift&quot;, &quot;Rechnung&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Transaction Label</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SendTemplate__c/SendTemplate__c.object-meta.xml
<CustomObject>
    <label>Send Template</label>
    <nameField>
        <label>Send Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Send Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SendTemplate__c/fields/Default__c.field-meta.xml
<CustomField>
    <fullName>Default__c</fullName>
    <label>Default</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SendTemplate__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/SendTemplate__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Case</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>MyObVenue</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>BigDataAlert__c</fullName>
            </value>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>Joint_Sales__c</fullName>
            </value>
            <value>
                <fullName>HardwareFulfilment__c</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>OBInvoice</fullName>
            </value>
            <value>
                <fullName>P148Letter__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Language.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>German</fullName>
        <default>true</default>
        <label>German</label>
    </customValue>
    <customValue>
        <fullName>English</fullName>
    </customValue>
    <customValue>
        <fullName>French</fullName>
    </customValue>
    <customValue>
        <fullName>Spanish</fullName>
    </customValue>
    <customValue>
        <fullName>Russian</fullName>
    </customValue>
    <customValue>
        <fullName>Italian</fullName>
    </customValue>
    <customValue>
        <fullName>Polish</fullName>
    </customValue>
    <customValue>
        <fullName>Chinese</fullName>
    </customValue>
    <customValue>
        <fullName>Japanese</fullName>
    </customValue>
    <customValue>
        <fullName>Swedish</fullName>
    </customValue>
    <masterLabel>Language</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OBInvoiceSender.cls
global class OBInvoiceSender implements Database.Batchable<sObject>{
    
    global String Query;
    global OrgWideEmailAddress[] owea;
    global Map<String,String> TemplateMap;
    global Map<String,SendTemplate__c> SendTemplateMap;
    global List<ContentVersion> insertCVs;
    global List<Messaging.Email> Emails;

    global OBInvoiceSender() {
        Id SysAdminId = [SELECT Id FROM Profile where Name = 'System Administrator' LIMIT 1].Id;
        String BatchLimit = InvoiceSending__c.getInstance(SysAdminId).BatchSize__c;
        if (test.isRunningTest()) BatchLimit = '10';
        Query = 'SELECT Id, Name, Template_Branding__c, HasBeenEmailed__c, InvoiceDate__c, Amount__c, Transaction_Label__c, Credit_Memo_Amount__c, Email__c, CurrencyIsoCode, Addressee__c, Correction_Invoice__c  '
            +   'FROM OBInvoice__c '
            +   'WHERE '
            +   '   HasBeenEmailed__c = FALSE '
            +   '   AND (Email__c != NULL OR (Account__r.SF_BillTo_Contact__c != NULL '
            +   '   AND Account__r.SF_BillTo_Contact__r.Email != NULL '
            +   '   AND Account__r.SF_BillTo_Contact__r.IsEmailBounced = FALSE)) '
            +   '   AND MismatchTotal__c = FALSE '
            +   'LIMIT ' + BatchLimit;
        setParams();
    }

    global void setParams() {

        owea = [select Id from OrgWideEmailAddress where Address = 'noreply@orderbird.com'];

        TemplateMap = new Map<String, String>();
        for (StaticResource TSR : [
            SELECT Id, Name, Body 
            FROM StaticResource 
            WHERE Name LIKE 'ReplacementTemplate%'
            ORDER BY Name DESC
        ]) {
            TemplateMap.put(TSR.Name, TSR.Body.toString());
        }

        SendTemplateMap = new Map<String, SendTemplate__c>();
        for (SendTemplate__c ST : [
            SELECT Id, Message__c, Default__c, Subject__c 
            FROM SendTemplate__c 
            WHERE Object__c = 'OBInvoice' AND Default__c != null
        ]) {
            SendTemplateMap.put(ST.Default__c, ST);
        }

        insertCVs = new List<ContentVersion>();
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(Query);
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope){
        
        Set<String> EmailAddresses = new Set<String>();
        Map<String,String> MessageMap = new Map<String,String>();
        Map<String,String> DocumentMap = new Map<String,String>();
        Map<String,String> TitleMap = new Map<String,String>();
        List<String> ContentDocumentIds = new List<String>();
        
        // create list of emails to send at the end of the process
        Emails = new List<Messaging.Email>();
        
        // iterate through queried accounts
        for (SObject s : scope) {

            /*String Language = (String)s.getSObject('Account__r').get('PrimaryLanguage__c');
            if (Language != 'German' && Language != 'English' && Language != 'French') {
                if ((String)s.getSObject('Account__r').get('BillingCountry') == 'France') {
                    Language = 'French';
                } else {
                    Language = 'German';
                }
            }*/
            String Language = 'German';
            
            String TemplateBrand = 'PRO';
            try { 
                TemplateBrand = (String)s.get('Template_Branding__c');
                if (TemplateBrand == null) TemplateBrand = '';
            } catch(exception e){}

            Messaging.Emailfileattachment efa = new Messaging.Emailfileattachment();
            List<Messaging.Emailfileattachment> fileAttachments = new List<Messaging.Emailfileattachment>();
            efa.setFileName('Invoice.pdf');
            PageReference pageRef = new PageReference('/apex/OBInvoiceAttachment');
            pageRef.getParameters().put('id', (String)s.get('Id') );
            Blob pdfBlob;
            if(!test.isRunningTest()) pdfBlob = pageRef.getContent();
            efa.setBody(pdfBlob);
            fileAttachments.add(efa);

            insertCVs.add(new ContentVersion(
                ContentLocation = 'S',
                IsInvoice__c = true,
                VersionData = pdfBlob,
                Title = 'orderbird Invoice : ' + (String)s.get('Name') + ' : sent ' + String.valueOf(DateTime.now()),
                PathOnClient = '/Invoice.pdf'
            ));

            List<String> args = new String[]{'0','number','###,###,##0.00'};
                
            String EmailText = SendTemplateMap.get(Language).Message__c.replace('%%!Account__r.Name%%',(String)s.get('Addressee__c'))
                .replace('%%!Name%%',(String)s.get('Name'))
                .replace('%%!Transaction_Label__c%%',(String)s.get('Transaction_Label__c'))
                .replace('%%!InvoiceDate__c:Date%%',((Date)s.get('InvoiceDate__c')).format())
                .replace('%%!Amount__c:Currency%%',String.format((((Decimal)s.get('Amount__c')).setScale(2)).format(), args))
                .replace('%%!Credit_Memo_Amount__c:Currency%%',String.format((((Decimal)s.get('Credit_Memo_Amount__c')).setScale(2)).format(), args))
                .replace('%%!CurrencyIsoCode%%',(String)s.get('CurrencyIsoCode'));
        
            String TextBody = EmailText;
            TextBody = TextBody.replace('<p>','').replace('</p>','\n').replace('<br>','\n').replace('<br/>','\n');
            //TextBody = EncodingUtil.URLDecode(TextBody, 'UTF-8');
            
            EmailText = TemplateMap.get('ReplacementTemplate' + TemplateBrand + Language).replace('<!--%%REPLACE%%-->',EmailText);
            
            system.debug(json.serialize(s));
            
            String emailSubject = SendTemplateMap.get(Language).Subject__c.replace('%%!Name%%',(String)s.get('Name')).replace('%%!Transaction_Label__c%%',(String)s.get('Transaction_Label__c'));
            if ((Boolean)s.get('Correction_Invoice__c')) emailSubject = emailSubject.replace('Rechnung','Rechnungsberichtigung');
            TextBody = TextBody.replace('<!--%%SUBJECTLINE%%-->',emailSubject);
            
            Messaging.SingleEmailMessage em = new Messaging.SingleEmailMessage();
            em.setTreatBodiesAsTemplate(true);
            em.setHtmlBody(EmailText);
            em.setPlainTextBody(TextBody);
            em.setSubject(emailSubject);
            em.setWhatId((String)s.get('Id'));
            em.setSaveAsActivity(true);
            em.setToAddresses(new List<String> {(String)s.get('Email__c')});
            //em.setTargetObjectID((Id)s.getSObject('Account__r').get('SF_BillTo_Contact__c'));
            //em.setCCAddresses( new List<String>{} );
            em.setOrgWideEmailAddressId(owea.get(0).Id);
            em.setFileAttachments(fileAttachments);
            Emails.add(em);

            if (!test.isRunningTest()) s.put('Base64Pdf__c', EncodingUtil.base64Encode(pdfBlob));
            s.put('HasBeenEmailed__c', true);
            EmailAddresses.add((String)s.get('Email__c'));
            TitleMap.put(
                (String)s.get('Name'),
                (String)s.get('Id')
            );
        }
        
        if (!test.isRunningTest()) Messaging.sendEmail( Emails );
        
        for(EmailMessageRelation emr : [
            SELECT EmailMessageId, EmailMessage.RelatedToId
            FROM EmailMessageRelation 
            WHERE RelationAddress IN :EmailAddresses
            ORDER BY CreatedDate DESC
            LIMIT :Emails.size()
        ]) {
            MessageMap.put(emr.EmailMessage.RelatedToId, emr.EmailMessageId);
        }        
        update scope;
        if (!test.isRunningTest()) insert insertCVs;
        
        Set<Id> CVIdSet = new Set<Id>();
        for (ContentVersion CV : insertCVs) {
            CVIdSet.add(CV.Id);
        }

        for (ContentVersion newCV : [SELECT Title, ContentDocumentId FROM ContentVersion WHERE Id IN :CVIdSet]) {
            ContentDocumentIds.add(newCV.ContentDocumentId);
            DocumentMap.put(newCV.ContentDocumentId, newCV.Title.split(':')[1].replace(' ',''));
        }

        List<ContentDocumentLink> CDLs = new List<ContentDocumentLink>();
        for (String CDId : ContentDocumentIds) {
            CDLs.add(new ContentDocumentLink(
                ShareType = 'v',
                LinkedEntityId = MessageMap.get(TitleMap.get(DocumentMap.get(CDId))),
                ContentDocumentId = CDId
            ));
        }
        if (!test.isRunningTest()) insert CDLs;
        
    }

    global void finish(Database.BatchableContext BC){}
    
}