force-app/main/default/objects/Account/fields/Interwega_Business_Area__c.field-meta.xml
<CustomField>
    <fullName>Interwega_Business_Area__c</fullName>
    <label>Interwega Business Area</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Interwega_Debt_Collection_Id__c.field-meta.xml
<CustomField>
    <fullName>Interwega_Debt_Collection_Id__c</fullName>
    <label>Interwega Debt Collection Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Interwega_Open_Balance__c.field-meta.xml
<CustomField>
    <fullName>Interwega_Open_Balance__c</fullName>
    <label>Interwega Open Balance (incl fees) (EUR)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Interwega_Open_Balance_wo_fees__c.field-meta.xml
<CustomField>
    <fullName>Interwega_Open_Balance_wo_fees__c</fullName>
    <label>Interwega Open Balance (excl fees) (EUR)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Interwega_Reference_Date__c.field-meta.xml
<CustomField>
    <fullName>Interwega_Reference_Date__c</fullName>
    <label>Interwega Reference Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Interwega_Status__c.field-meta.xml
<CustomField>
    <fullName>Interwega_Status__c</fullName>
    <label>Interwega Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/InterwegaController.cls
public class InterwegaController {
    
    @AuraEnabled
    public static Integer CountInterwega() {
        return [SELECT Id FROM Account WHERE Interwega_Status__c != null].size();
    }
    
    @AuraEnabled
    public static String ClearInterwega() {
        if (CountInterwega() < 201) {
            try {
                List<Account> Accounts = [
                    SELECT 
                    Id, Interwega_Business_Area__c, Interwega_Open_Balance__c, Interwega_Debt_Collection_Id__c,
                    Interwega_Open_Balance_wo_fees__c, Interwega_Reference_Date__c, Interwega_Status__c 
                    FROM Account
                    WHERE Interwega_Status__c != null
                ];
                for (Account a : Accounts) {
                    a.Interwega_Business_Area__c = null;
                    a.Interwega_Open_Balance__c = null;
                    a.Interwega_Open_Balance_wo_fees__c = null;
                    a.Interwega_Reference_Date__c = null;
                    a.Interwega_Status__c = null;
                    a.Interwega_Debt_Collection_Id__c = null;
                }
                update Accounts;
            } catch(exception e) {
                return e.getMessage();
            }
            return 'OK';
        } else {
            Database.executeBatch(new InterwegaBatch());
            return 'Process started. Wait until count goes to -0- before importing.';
        }
    }
    
}