force-app/main/default/objects/Account/fields/Invoice_Count__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Count__c</fullName>
    <formula>Cleared_Invoice_Count__c + Not_Cleared_Invoice_Count__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Invoice Count</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CreditBalanceAdjustment__c/CreditBalanceAdjustment__c.object-meta.xml
<CustomObject>
    <label>Credit Balance Adjustment</label>
    <nameField>
        <label>Credit Balance Adjustment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credit Balance Adjustments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CreditBalanceAdjustment__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Credit Balance Adjustments</relationshipLabel>
    <relationshipName>Credit_Balance_Adjustments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CreditBalanceAdjustment__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>Payment__c</referenceTo>
    <relationshipLabel>Credit Balance Adjustments</relationshipLabel>
    <relationshipName>Credit_Balance_Adjustments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CreditBalanceAdjustment__c/fields/Refund__c.field-meta.xml
<CustomField>
    <fullName>Refund__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Refund</label>
    <referenceTo>Refund__c</referenceTo>
    <relationshipLabel>Credit Balance Adjustments</relationshipLabel>
    <relationshipName>Credit_Balance_Adjustments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CreditBalanceAdjustment__c/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>32</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>2.0</description>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>Zuora Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/InvoiceLineItem__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>ILI-{0000000}</displayFormat>
        <label>Invoice Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceLineItem__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/fields/SubscriptionLineItem__c.field-meta.xml
<CustomField>
    <fullName>SubscriptionLineItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription Line Item</label>
    <referenceTo>SubscriptionLineItem__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/InvoicePayment__c/InvoicePayment__c.object-meta.xml
<CustomObject>
    <label>Invoice Payment</label>
    <nameField>
        <displayFormat>InvPmt-{000000}</displayFormat>
        <label>Invoice Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoicePayment__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Payments</relationshipLabel>
    <relationshipName>Invoice_Payments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoicePayment__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <label>Payment</label>
    <referenceTo>Payment__c</referenceTo>
    <relationshipLabel>Invoice Payments</relationshipLabel>
    <relationshipName>Invoice_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoiceRefund__c/InvoiceRefund__c.object-meta.xml
<CustomObject>
    <label>Invoice Refund</label>
    <nameField>
        <displayFormat>InvRef-{000000}</displayFormat>
        <label>Invoice Refund Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Refunds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceRefund__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Refunds</relationshipLabel>
    <relationshipName>Invoice_Refunds</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoiceRefund__c/fields/Refund__c.field-meta.xml
<CustomField>
    <fullName>Refund__c</fullName>
    <label>Refund</label>
    <referenceTo>Refund__c</referenceTo>
    <relationshipLabel>Invoice Refunds</relationshipLabel>
    <relationshipName>Invoice_Refunds</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoiceRefund__c/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <label>Payment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentMethod__c/PaymentMethod__c.object-meta.xml
<CustomObject>
    <label>Payment Method</label>
    <nameField>
        <label>Payment Method Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Refund__c/Refund__c.object-meta.xml
<CustomObject>
    <label>Refund</label>
    <nameField>
        <label>Refund Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Refunds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Refund__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>Payment__c</referenceTo>
    <relationshipLabel>Refunds</relationshipLabel>
    <relationshipName>Refunds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SLIMap__c/SLIMap__c.object-meta.xml
<CustomObject>
    <label>SLI Mapping</label>
    <nameField>
        <displayFormat>SLIM-{000000}</displayFormat>
        <label>SLI Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SLI Map</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/SubscriptionLineItem__c.object-meta.xml
<CustomObject>
    <label>Subscription Line Item</label>
    <nameField>
        <label>Subscription Line Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SubscriptionLineItem__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>Subscription_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ZuoraFetchQueue.cls
public class ZuoraFetchQueue implements Queueable, Database.AllowsCallouts {
    
    public Final String FetchType;
    
    public ZuoraFetchQueue(String iFetchType) {
        FetchType = iFetchType;
    }
    
    public void execute(QueueableContext context) {
        
        if (FetchType == 'ProductCatalog') {
            if (!test.isRunningTest()) System.enqueueJob(new ProdCatUpsert(0, JSON.serialize(ZuoraSyncController.FetchCatalog())));
        }
        
        if (FetchType == 'Account') {
            if (!test.isRunningTest()) ZuoraSyncController.AccountCollectionUpsert(ZuoraSyncController.FetchAccountCollection(Date.today().addDays(-2)));
        }
        
        if (FetchType == 'Subscription__c') {
            if (!test.isRunningTest()) ZuoraSyncController.SubscriptionCollectionUpsert(ZuoraSyncController.FetchSubscriptionCollection(Date.today().addDays(-2)));
        }
        
        if (FetchType == 'SLIMap__c') {
            if (!test.isRunningTest()) ZuoraSyncController.SLIMapCollectionUpsert(ZuoraSyncController.FetchSLIMapCollection(Date.today().addDays(-2)));
        }
        
        if (FetchType == 'SubscriptionLineItem__c:0') {
            if (!test.isRunningTest()) ZuoraSyncController.SubItemCollectionUpsert(ZuoraSyncController.FetchSubItemCollection(Date.today().addDays(-2), 0), 0);
        }
        
        if (FetchType == 'SubscriptionLineItem__c:1') {
            if (!test.isRunningTest()) ZuoraSyncController.SubItemCollectionUpsert(ZuoraSyncController.FetchSubItemCollection(Date.today().addDays(-2), 1), 1);
        }
        
        if (FetchType == 'SubscriptionLineItem__c:2') {
            if (!test.isRunningTest()) ZuoraSyncController.SubItemCollectionUpsert(ZuoraSyncController.FetchSubItemCollection(Date.today().addDays(-2), 2), 2);
        }
        
        if (FetchType == 'Invoice__c') {
            if (!test.isRunningTest()) ZuoraSyncController.InvoiceCollectionUpsert(ZuoraSyncController.FetchInvoiceCollection(Date.today().addDays(-2)));
        }
        
        if (FetchType == 'LargeAccount_Invoice__c') {
            List<String> AcctIds = new List<String>();
            for (Account a : [SELECT Id, ZuoraId__c FROM Account WHERE Invoice_Count__c > 200]) { AcctIds.add(a.ZuoraId__c); }
            if (!test.isRunningTest()) ZuoraSyncController.InvoiceCollectionUpsert(ZuoraSyncController.FetchInvoiceCollection(AcctIds, Date.today().addDays(-2)),true,true);
        }

        if (FetchType == 'InvoiceLineItem__c') {
            if (!test.isRunningTest()) ZuoraSyncController.InvItemCollectionUpsert(ZuoraSyncController.FetchInvItemCollection(Date.today().addDays(-2)));
        }
        
        if (FetchType == 'Payment__c') {
            if (!test.isRunningTest()) ZuoraSyncController.PaymentCollectionUpsert(ZuoraSyncController.FetchPaymentCollection(Date.today().addDays(-2)));
        }
        
        if (FetchType == 'Refund__c') {
            if (!test.isRunningTest()) ZuoraSyncController.RefundCollectionUpsert(ZuoraSyncController.FetchRefundCollection(Date.today().addDays(-2)));
        }
        
        if (FetchType == 'InvoicePayment__c') {
            if (!test.isRunningTest()) ZuoraSyncController.InvPmtCollectionUpsert(ZuoraSyncController.FetchInvPmtCollection(Date.today().addDays(-2)));
        }
        
        if (FetchType == 'InvoiceRefund__c') {
            if (!test.isRunningTest()) ZuoraSyncController.InvRefCollectionUpsert(ZuoraSyncController.FetchInvRefCollection(Date.today().addDays(-2)));
        }
        
        if (FetchType == 'PaymentMethod__c') {
            if (!test.isRunningTest()) ZuoraSyncController.PmtMtdCollectionUpsert(ZuoraSyncController.FetchPmtMtdCollection(Date.today().addDays(-2)));
        }
        
        if (FetchType == 'Amendment__c') {
            if (!test.isRunningTest()) ZuoraSyncController.AmendmentCollectionUpsert(ZuoraSyncController.FetchAmendmentCollection(Date.today().addDays(-2)));
        }
        
        if (FetchType == 'CreditBalanceAdjustment__c') {
            if (!test.isRunningTest()) ZuoraSyncController.CBACollectionUpsert(ZuoraSyncController.FetchCBACollection(Date.today().addDays(-2)));
        }
        
    }
}