force-app/main/default/objects/Account/fields/LegalCompanyName__c.field-meta.xml
<CustomField>
    <fullName>LegalCompanyName__c</fullName>
    <description>Stakeholder: Stakeholders: Sales with Account Management</description>
    <inlineHelpText>What is the company&apos;s legal name for e.g. billing? It is usually in the „about us“/Impressum of websites . If there is an addition such as Gmbh / UG / LDT. / SAS / SL... it’s an operating company. It could however also be a non-incorporated company</inlineHelpText>
    <label>Legal Company Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/PrimaryLanguage__c.field-meta.xml
<CustomField>
    <fullName>PrimaryLanguage__c</fullName>
    <defaultValue>&quot;German&quot;</defaultValue>
    <description>Stakeholder: Sales &amp; CS with MKT</description>
    <inlineHelpText>What language do we use to communicate with this venue? Filled in as soon as known. Updated if necessary!</inlineHelpText>
    <label>Primary Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Language</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/SF_BillTo_Contact__c.field-meta.xml
<CustomField>
    <fullName>SF_BillTo_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Stakeholder: Sales &amp; Account Management</description>
    <inlineHelpText>This defines the official billing address.</inlineHelpText>
    <label>Billing Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.ParentId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Zuora BillTo Contact)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/SF_SoldTo_Contact__c.field-meta.xml
<CustomField>
    <fullName>SF_SoldTo_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Stakeholder: Sales &amp; Account Management</description>
    <inlineHelpText>This contact defines the official shipping address.</inlineHelpText>
    <label>Shipping Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.ParentId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tax_Exempt_Reason__c.field-meta.xml
<CustomField>
    <fullName>Tax_Exempt_Reason__c</fullName>
    <description>https://jira.orderbird.com/browse/SAL-1185</description>
    <label>Tax Exempt Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Non Tax Exempt</fullName>
            </value>
            <value>
                <fullName>EU reverse charge mechanism</fullName>
            </value>
            <value>
                <fullName>Third country jurisdictions</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/PrimaryLanguage__c.field-meta.xml
<CustomField>
    <fullName>PrimaryLanguage__c</fullName>
    <description>Stakeholder: Sales &amp; CS &amp; MKT</description>
    <inlineHelpText>What language do we use to communicate with this venue? Filled in as soon as known. Updated if necessary!</inlineHelpText>
    <label>Primary Language</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>Russian</fullName>
            </value>
            <value>
                <fullName>Italian</fullName>
            </value>
            <value>
                <fullName>Polish</fullName>
            </value>
            <value>
                <fullName>Chinese</fullName>
            </value>
            <value>
                <fullName>Japanese</fullName>
            </value>
            <value>
                <fullName>Swedish</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/LAC_Shorthand__c.field-meta.xml
<CustomField>
    <fullName>LAC_Shorthand__c</fullName>
    <description>Stakeholder: CDS, BI, MKT, Sales https://jira.orderbird.com/browse/CDS-138</description>
    <inlineHelpText>Select the relevant Lead Attribution Combo. If it is not on the list use the field LAC ID</inlineHelpText>
    <label>LAC Shorthand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LAC_Shorthands</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/LAC_Shorthands.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Walk-In</fullName>
    </customValue>
    <customValue>
        <fullName>Hotline</fullName>
    </customValue>
    <customValue>
        <fullName>Personal Network</fullName>
    </customValue>
    <customValue>
        <fullName>E-mail</fullName>
    </customValue>
    <customValue>
        <fullName>CRC - Referral of successor</fullName>
    </customValue>
    <customValue>
        <fullName>CRC - E-mail</fullName>
    </customValue>
    <customValue>
        <fullName>CRC - Hotline</fullName>
    </customValue>
    <customValue>
        <fullName>CRC - Webform</fullName>
    </customValue>
    <customValue>
        <fullName>Referral by Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Research - Public Register</fullName>
    </customValue>
    <customValue>
        <fullName>Research - Other</fullName>
    </customValue>
    <customValue>
        <fullName>Chat</fullName>
    </customValue>
    <customValue>
        <fullName>Facebook</fullName>
    </customValue>
    <customValue>
        <fullName>Twitter</fullName>
    </customValue>
    <customValue>
        <fullName>Instagram</fullName>
    </customValue>
    <customValue>
        <fullName>Kassensystemevergleich.de</fullName>
    </customValue>
    <customValue>
        <fullName>Kassen-Vergleich.com</fullName>
    </customValue>
    <customValue>
        <fullName>Companeo</fullName>
    </customValue>
    <customValue>
        <fullName>Facebook Scraper</fullName>
    </customValue>
    <customValue>
        <fullName>Toques de restauration</fullName>
    </customValue>
    <customValue>
        <fullName>Chardasso</fullName>
    </customValue>
    <customValue>
        <fullName>Trade Register Scraper</fullName>
    </customValue>
    <customValue>
        <fullName>TradingTwins</fullName>
    </customValue>
    <customValue>
        <fullName>Outbound Texting</fullName>
    </customValue>
    <customValue>
        <fullName>my.ob Reg</fullName>
    </customValue>
    <customValue>
        <fullName>Neugeschaeft</fullName>
    </customValue>
    <customValue>
        <fullName>ETL-Print</fullName>
    </customValue>
    <customValue>
        <fullName>Cold Call</fullName>
    </customValue>
    <customValue>
        <fullName>Preorder</fullName>
    </customValue>
    <customValue>
        <fullName>Postcard 2020</fullName>
        <isActive>false</isActive>
        <label>Postcard 2020</label>
    </customValue>
    <description>For the convenient use of Lead Attributes: Users can use Keywords instead of IDs</description>
    <masterLabel>LAC Shorthands</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Language.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>German</fullName>
        <default>true</default>
        <label>German</label>
    </customValue>
    <customValue>
        <fullName>English</fullName>
    </customValue>
    <customValue>
        <fullName>French</fullName>
    </customValue>
    <customValue>
        <fullName>Spanish</fullName>
    </customValue>
    <customValue>
        <fullName>Russian</fullName>
    </customValue>
    <customValue>
        <fullName>Italian</fullName>
    </customValue>
    <customValue>
        <fullName>Polish</fullName>
    </customValue>
    <customValue>
        <fullName>Chinese</fullName>
    </customValue>
    <customValue>
        <fullName>Japanese</fullName>
    </customValue>
    <customValue>
        <fullName>Swedish</fullName>
    </customValue>
    <masterLabel>Language</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/QuoteAttachmentMandatoryTest.cls
/**
 * @author martin
 */
@IsTest
public class QuoteAttachmentMandatoryTest {
/*
    private static User createUser() {
        Profile p = [SELECT Id FROM Profile WHERE Name = 'Sales'];
        User u = new User(Alias = 'dUser', Email = 'deploymentuser@orderbird.com',
                EmailEncodingKey = 'UTF-8', LastName = 'Deploy', LanguageLocaleKey = 'en_US',
                LocaleSidKey = 'en_US', ProfileId = p.Id,
                TimeZoneSidKey = 'America/Los_Angeles', UserName = 'deploymentuser@orderbird.com');
        return u;
    }

    static testMethod void quote_insert_should_fail() {

        // Setup test data
        User u = createUser();
        // This code runs as the deploying user

        System.runAs(u) {
            // This runs as the created user u
            // Insert fail
            Contact c = new Contact(FirstName = 'Hi', LastName = 'krass', PrimaryLanguage__c = 'German', Email = 'bla@bla.de', MailingCity = 'lul', MailingStreet = 'lul', MailingPostalCode = '12345', MailingCountry = 'Germany');
            insert c;
            Account a = new Account(Name = 'LULACCOUNT', BillingCity = 'a', BillingCountry = 'Germany', LegalCompanyName__c = 'krasscompany', BillingStreet = 'e', BillingPostalCode = '12345', ShippingCity = 'a', ShippingCountry = 'Germany', ShippingStreet = 'e', ShippingPostalCode = '12345', SF_BillTo_Contact__c = c.Id, SF_SoldTo_Contact__c = c.Id, CurrencyISOCode = 'EUR', Tax_Exempt_Reason__c = 'Non Tax Exempt');
            insert a;
            Opportunity o = new Opportunity(Name = 'LULOPP', StageName = 'Potential', CloseDate = System.Today(), AccountId = a.Id, LAC_Shorthand__c = 'Walk-In');
            insert o;
            zqu__Quote__c q = new zqu__Quote__c(Name = 'Deployment Quote', zqu__BillToContact__c = c.Id, zqu__Account__c = a.Id, zqu__Opportunity__c = o.Id, Quote_is_ready__c = true, zqu__Currency__c = 'EUR');

            Test.startTest();
            try {
                insert q;
                System.assertEquals(true, false);
            } catch (Exception e) {
                System.Assert(e.getMessage().contains('Please attach the customers response to the Quote before marking it as ready!'));
            }
            Test.stopTest();
        }

    }

    static testMethod void quote_update_should_fail() {

        // Setup test data
        User u = createUser();
        // This code runs as the deploying user

        System.runAs(u) {
            // Update Fail
            Contact c2 = new Contact(FirstName = 'Hi', LastName = 'krass', PrimaryLanguage__c = 'German', Email = 'bla@bla.de', MailingCity = 'lul', MailingStreet = 'lul', MailingPostalCode = '12345', MailingCountry = 'Germany');
            insert c2;
            Account a2 = new Account(Name = 'LULACCOUNT', BillingCity = 'a', BillingCountry = 'Germany', LegalCompanyName__c = 'krasscompany', BillingStreet = 'e', BillingPostalCode = '12345', ShippingCity = 'a', ShippingCountry = 'Germany', ShippingStreet = 'e', ShippingPostalCode = '12345', SF_BillTo_Contact__c = c2.Id, SF_SoldTo_Contact__c = c2.Id, Tax_Exempt_Reason__c = 'Non Tax Exempt');
            insert a2;
            Opportunity o2 = new Opportunity(Name = 'LULOPP', StageName = 'Potential', CloseDate = System.Today(), AccountId = a2.Id, LAC_Shorthand__c = 'Walk-In');
            insert o2;
            zqu__Quote__c q2 = new zqu__Quote__c(Name = 'Deployment Quote', zqu__BillToContact__c = c2.Id, zqu__Account__c = a2.Id, zqu__Opportunity__c = o2.Id);
            insert q2;

            q2.Quote_is_ready__c = true;

            Test.startTest();
            try {
                update q2;
                System.assertEquals(true, false);
            } catch (Exception e) {
                System.Assert(e.getMessage().contains('Please attach the customers response to the Quote before marking it as ready!'));
            }
            Test.stopTest();
        }

    }

    static testMethod void quote_update_should_not_fail() {

        // Setup test data
        User u = createUser();
        // This code runs as the deploying user

        System.runAs(u) {

            // No Error

            Contact c3 = new Contact(FirstName = 'Hi', LastName = 'krass', PrimaryLanguage__c = 'German', Email = 'bla@bla.de', MailingCity = 'lul', MailingStreet = 'lul', MailingPostalCode = '12345', MailingCountry = 'Germany');
            insert c3;
            Account a3 = new Account(Name = 'LULACCOUNT', BillingCity = 'a', BillingCountry = 'Germany', LegalCompanyName__c = 'krasscompany', BillingStreet = 'e', BillingPostalCode = '12345', ShippingCity = 'a', ShippingCountry = 'Germany', ShippingStreet = 'e', ShippingPostalCode = '12345', SF_BillTo_Contact__c = c3.Id, SF_SoldTo_Contact__c = c3.Id, Tax_Exempt_Reason__c = 'Non Tax Exempt');
            insert a3;
            Opportunity o3 = new Opportunity(Name = 'LULOPP', StageName = 'Potential', CloseDate = System.Today(), AccountId = a3.Id, LAC_Shorthand__c = 'Walk-In');
            insert o3;
            zqu__Quote__c q3 = new zqu__Quote__c(Name = 'Deployment Quote', zqu__BillToContact__c = c3.Id, zqu__Account__c = a3.Id, zqu__Opportunity__c = o3.Id);
            insert q3;
            Attachment att = new Attachment(Name = 'Test attachment', body = Blob.valueOf('Testbody of bodyness'), ParentId = q3.Id);
            insert att;

            Test.startTest();
            q3.Quote_is_ready__c = true;
            update q3;
            Test.stopTest();
        }
    }*/
}