force-app/main/default/objects/Account/fields/LegalCompanyName__c.field-meta.xml
<CustomField>
    <fullName>LegalCompanyName__c</fullName>
    <description>Stakeholder: Stakeholders: Sales with Account Management</description>
    <inlineHelpText>What is the company&apos;s legal name for e.g. billing? It is usually in the „about us“/Impressum of websites . If there is an addition such as Gmbh / UG / LDT. / SAS / SL... it’s an operating company. It could however also be a non-incorporated company</inlineHelpText>
    <label>Legal Company Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/myOrderbirdEmail__c.field-meta.xml
<CustomField>
    <fullName>myOrderbirdEmail__c</fullName>
    <description>Stakeholder: CS</description>
    <inlineHelpText>By which email address is this account officially registered on my.orderbird? Filled in as soon as known. Must be updated if changes occur!</inlineHelpText>
    <label>my.orderbird Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/NS_Customer_Internal_ID__c.field-meta.xml
<CustomField>
    <fullName>NS_Customer_Internal_ID__c</fullName>
    <description>Stakeholder: NEST</description>
    <externalId>true</externalId>
    <inlineHelpText>What is the internal ID of this customer account in Netsuite? Updated manually regularly</inlineHelpText>
    <label>NS Customer Internal ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tax_Exempt_Reason__c.field-meta.xml
<CustomField>
    <fullName>Tax_Exempt_Reason__c</fullName>
    <description>https://jira.orderbird.com/browse/SAL-1185</description>
    <label>Tax Exempt Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Non Tax Exempt</fullName>
            </value>
            <value>
                <fullName>EU reverse charge mechanism</fullName>
            </value>
            <value>
                <fullName>Third country jurisdictions</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/taxExempted__c.field-meta.xml
<CustomField>
    <fullName>taxExempted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>tax exempted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/VATNumber__c.field-meta.xml
<CustomField>
    <fullName>VATNumber__c</fullName>
    <description>Stakeholder: Finance</description>
    <inlineHelpText>What is the venues value added tax (VAT)  number of this venue? Filled in by Sales. Required for most non-German EU customers</inlineHelpText>
    <label>VAT Number (Raw)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ZuoraAccountUpdateTest.cls
/**
 * @author keylight
 */
@IsTest
private class ZuoraAccountUpdateTest {
	@isTest static void constructer_test() {
		Account a = new Account();
		String zId = 'test';
		ZuoraAccountUpdate au = new ZuoraAccountUpdate(a, zId);
        System.assertEquals(a, au.account);
        System.assertEquals(zId, au.zuoraId);
    }

    @isTest static void should_return_json() {
		Account a = new Account(
				Name='AccountName',
				LegalCompanyName__c='Test',
				NS_Customer_Internal_ID__c='Test2',
				myOrderbirdEmail__c='email',
				taxExempted__c=true,
				VATNumber__c='111',
				Tax_Exempt_Reason__c='EU reverse charge mechanism');
		String zId = 'test';
		ZuoraAccountUpdate au = new ZuoraAccountUpdate(a, zId);
		String json = au.toJson();
        System.assertEquals('{"LegalCompanyName__c":"Test","NS_Customer_Internal_ID__c":"Test2","myOrderbirdEmail__c":"email","Tax_Exempt_Reason__c":"EUreversechargemechanism","name":"AccountName","taxInfo":{"VATId":"111","exemptStatus":"Yes"}}', json.deleteWhitespace());
    }

     @isTest static void run_send() {
     	Test.setMock(HttpCalloutMock.class, new ZuoraHttpCalloutMock());
		Account a = new Account(Name='Test', LegalCompanyName__c='Test', NS_Customer_Internal_ID__c='Test2', myOrderbirdEmail__c='email');
		String zId = 'test';
		ZuoraAccountUpdate au = new ZuoraAccountUpdate(a, zId);
		au.send();
    }
}