force-app/main/default/objects/Account/fields/myOrderbirdEmail__c.field-meta.xml
<CustomField>
    <fullName>myOrderbirdEmail__c</fullName>
    <description>Stakeholder: CS</description>
    <inlineHelpText>By which email address is this account officially registered on my.orderbird? Filled in as soon as known. Must be updated if changes occur!</inlineHelpText>
    <label>my.orderbird Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/MyObVenue__c/MyObVenue__c.object-meta.xml
<CustomObject>
    <label>MyOb Venue</label>
    <nameField>
        <displayFormat>MyOb-{000000}</displayFormat>
        <label>MyOb Venue</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MyOb Venues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MyObVenue__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>MyOrderbird_Log_ons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MyObVenue__c/fields/LastOpenShiftTimestamp__c.field-meta.xml
<CustomField>
    <fullName>LastOpenShiftTimestamp__c</fullName>
    <label>Last Open Shift Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MyObVenue__c/fields/Login__c.field-meta.xml
<CustomField>
    <fullName>Login__c</fullName>
    <externalId>true</externalId>
    <label>MyOrderbird Login</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/MyOrderbirdEmailGenerator.cls
global class MyOrderbirdEmailGenerator implements Schedulable{
    global void execute(SchedulableContext SC) {
        List<Account> NeedsMyObEmail = [SELECT Id, MyOrderbirdEmail__c FROM Account WHERE MyOrderbirdEmail__c = null AND Id IN (SELECT Account__c FROM MyObvenue__c WHERE Login__c != null) LIMIT 200];
        Set<Id> AccountIds = new Set<Id>();
        for (Account a : NeedsMyObEmail) { AccountIds.add(a.Id); }
        Map<Id, String> EmailMap = new Map<Id, String>();
        for (MyObVenue__c v : [SELECT Id, Login__c, Account__c FROM MyObVenue__c WHERE Account__c IN :AccountIds AND Login__c != null ORDER BY LastOpenShiftTimestamp__c]) {
            EmailMap.put(v.Account__c, v.Login__c);
        }
        for (Account a : NeedsMyObEmail) { a.MyOrderbirdEmail__c = EmailMap.get(a.Id); }
        update NeedsMyObEmail;
    }
}