force-app/main/default/objects/Account/fields/NPS__c.field-meta.xml
<CustomField>
    <fullName>NPS__c</fullName>
    <label>NPS (old)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AutomatedSurvey__c/AutomatedSurvey__c.object-meta.xml
<CustomObject>
    <label>Automated Survey</label>
    <nameField>
        <displayFormat>AS-{000000}</displayFormat>
        <label>Automated Survey</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Automated Surveys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AutomatedSurvey__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Automated Surveys</relationshipLabel>
    <relationshipName>Automated_Surveys</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/classes/SurveyControllerTest.cls
@isTest(SeeAllData=true) public class SurveyControllerTest {

    static TestMethod void test() {
        Account a = new Account(Name='test');
        insert a;
        Contact c = new Contact(Lastname='test', AccountId=a.Id, Email='bart.collins@orderbird.com');
        insert c;
        AutomatedSurvey__c ausu = new AutomatedSurvey__c(Contact__c = c.Id);
        insert ausu;
        system.assert(!SurveyController.InitSurvey(PortalToken.encryptPlain('other'),'5'));
        system.assert(!SurveyController.SubmitSurvey(PortalToken.encryptPlain('other'),'{}'));
        system.assert(SurveyController.InitSurvey(PortalToken.encryptPlain(ausu.Id),'5'));
        system.assertEquals([SELECT Id, Nps__c FROM AutomatedSurvey__c WHERE Id = :ausu.Id LIMIT 1].Nps__c, 5);
        system.assert(SurveyController.SubmitSurvey(PortalToken.encryptPlain(ausu.Id),'{"NPS":6}'));
        system.assertEquals([SELECT Id, Nps__c FROM AutomatedSurvey__c WHERE Id = :ausu.Id LIMIT 1].Nps__c, 6);
        system.assert([SELECT Id, Locked__c FROM AutomatedSurvey__c WHERE Id = :ausu.Id LIMIT 1].Locked__c);
    }
}