force-app/main/default/objects/Account/fields/Onboard_Status__c.field-meta.xml
<CustomField>
    <fullName>Onboard_Status__c</fullName>
    <label>Onboarding Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No Onboarding</fullName>
                <default>true</default>
                <label>No Onboarding</label>
            </value>
            <value>
                <fullName>Awaiting Case</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Waiting for Customer Reply</fullName>
            </value>
            <value>
                <fullName>Re-Open</fullName>
            </value>
            <value>
                <fullName>Escalated</fullName>
            </value>
            <value>
                <fullName>Postponed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Closed/Uncompleted</fullName>
            </value>
            <value>
                <fullName>Awaiting Subscription (New)</fullName>
            </value>
            <value>
                <fullName>Awaiting Subscription (Open)</fullName>
            </value>
            <value>
                <fullName>Awaiting Subscription (On Hold)</fullName>
            </value>
            <value>
                <fullName>Awaiting Subscription (Waiting for Customer Reply)</fullName>
            </value>
            <value>
                <fullName>Awaiting Subscription (Re-Open)</fullName>
            </value>
            <value>
                <fullName>Awaiting Subscription (Escalated)</fullName>
            </value>
            <value>
                <fullName>Awaiting Subscription (Postponed)</fullName>
            </value>
            <value>
                <fullName>Awaiting Subscription (Completed)</fullName>
            </value>
            <value>
                <fullName>Awaiting Subscription (Closed/Uncompleted)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/OnboardingClosedDate__c.field-meta.xml
<CustomField>
    <fullName>OnboardingClosedDate__c</fullName>
    <label>Onboarding Closed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Onboarding_Status_Relevant__c.field-meta.xml
<CustomField>
    <fullName>Onboarding_Status_Relevant__c</fullName>
    <description>Used in scirpt to update Onboarding Status on Account https://jira.orderbird.com/browse/CDS-2745</description>
    <formula>IF( ISPICKVAL(Onboarding_Type__c, &quot;Onboarding Basic&quot;), TRUE, FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Onboarding Status Relevant</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/SubscriptionLineItem__c.object-meta.xml
<CustomObject>
    <label>Subscription Line Item</label>
    <nameField>
        <label>Subscription Line Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SubscriptionLineItem__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>SubscriptionLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>Subscription_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AccountOnboardingStatus.cls
/**
 * @author Bart
 */
public class AccountOnboardingStatus {
    
    // Updates Accounts if Onboarding Status should change
    public static void process(Set<Id> AccountIds, List<Account> UpdateAccounts) {

        // Query map of related onboarding cases and subscriptions
        Map<Id, SObject> AccountMap = new Map<Id, SObject>([
            SELECT Id, (
                SELECT Id, Status, CreatedDate, ClosedDate
                FROM Cases 
                WHERE 
                    Onboarding_Status_Relevant__c = True
                	//RecordType.Name = 'Case: Onboarding'
                    AND Status != 'Closed as Duplicate'
                ORDER BY CreatedDate DESC 
            ), (
                SELECT Id 
                FROM SubscriptionLineItems__r
                WHERE Product__r.Onboarding_Status_Relevant__c = True
            )
            FROM Account
            WHERE Id IN :AccountIds
        ]);
        
        // Iterate through accounts to determine correct Onboarding Status and only update for changes
        for (Integer x = UpdateAccounts.size()-1 ; x >= 0 ; x--) {
            
            // Get list of related subscriptions (if any)
            List<SObject> RelatedSubscriptions = AccountMap.get(UpdateAccounts[x].Id).getSObjects('SubscriptionLineItems__r');
            
            // Get list of related cases (if any)
            List<SObject> RelatedCases = AccountMap.get(UpdateAccounts[x].Id).getSObjects('Cases');
            
            // Determine if related subscriptions or cases exist
            Boolean HasCase = RelatedCases != null;
            Boolean HasSubscription = RelatedSubscriptions != null;
            
            // Check to see if Case pre-dates Go-live
            if (HasCase && !HasSubscription) {
                DateTime FirstCaseDateTime = (DateTime)(RelatedCases[RelatedCases.size()-1].get('CreatedDate'));
                DateTime CutOffDateTime = DateTime.newInstance(2017, 9, 4);
                if (FirstCaseDateTime < CutOffDateTime) HasSubscription = true;
            }
            
            // Determine correct onboarding message 
            String OnboardingMessage = Label.ONBOARDSTATUS_NOSUB;
            Date OnboardingClosedDate = null;
            if (HasSubscription) {
                if (HasCase) {
                    OnboardingMessage = getStatusMessage((String)RelatedCases[0].get('Status'));
                    try{
                        DateTime cd = (DateTime)RelatedCases[0].get('ClosedDate');
                        OnboardingClosedDate = Date.newInstance(cd.year(), cd.month(), cd.day());
                    }catch(exception e){}
                } else {
                    OnboardingMessage = Label.ONBOARDSTATUS_NOCASE;
                }
            } else if (HasCase) {
                OnboardingMessage = Label.ONBOARDSTATUS_CASENOSUB + ' (' + getStatusMessage((String)RelatedCases[0].get('Status')) + ')';
                try{
                    DateTime cd = (DateTime)RelatedCases[0].get('ClosedDate');
                    OnboardingClosedDate = Date.newInstance(cd.year(), cd.month(), cd.day());
                }catch(exception e){}
            }
            
            // If there is a difference between database and determined value, replace value. Otherwise, remove from list.
            if (OnboardingMessage != UpdateAccounts[x].Onboard_Status__c) {
                UpdateAccounts[x].Onboard_Status__c = OnboardingMessage;
                if (UpdateAccounts[x].OnboardingClosedDate__c == null) UpdateAccounts[x].OnboardingClosedDate__c = OnboardingClosedDate;
            } else {
                UpdateAccounts.remove(x);
            }
            
        }
        
        // Make database update to commit correct status
        update UpdateAccounts;
        
    }
    
    // Used by triggers
    public static void process(Set<Id> AccountIds) {
        
        // Query accounts
        List<Account> UpdateAccounts = [SELECT Id, Onboard_Status__c FROM Account WHERE Id IN :AccountIds];
        
        process(AccountIds, UpdateAccounts);
        
    }
    
    // Used by batch jobs
    public static void process(List<Account> UpdateAccounts) {
        
        // Create set of Account Ids
        Set<Id> AccountIds = new Set<Id>();
        for (Account UpdateAccount : UpdateAccounts) {
            AccountIds.add(UpdateAccount.Id);
        }
        
        process(AccountIds, UpdateAccounts);
        
    }
    
    // Replace Case Statuses with User-friendly Onboarding Statuses as appropriate
    public static Map<String, String> MessageMap = new Map<String, String>{
        'Closed' => 'Completed',
        'Closed - Not Solved' => 'Closed/Uncompleted'
    };
    
    // Only Return User-friendly Onboarding Status where one is mapped, otherwise display Case Status
    public static String getStatusMessage(String Status) {
        String Message = MessageMap.get(Status);
        if (Message == null) { return Status; } else { return Message; }
    }
    
}