force-app/main/default/objects/Account/fields/Onboard_Status__c.field-meta.xml
<CustomField>
    <fullName>Onboard_Status__c</fullName>
    <label>Onboarding Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No Onboarding</fullName>
                <default>true</default>
                <label>No Onboarding</label>
            </value>
            <value>
                <fullName>Awaiting Case</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Waiting for Customer Reply</fullName>
            </value>
            <value>
                <fullName>Re-Open</fullName>
            </value>
            <value>
                <fullName>Escalated</fullName>
            </value>
            <value>
                <fullName>Postponed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Closed/Uncompleted</fullName>
            </value>
            <value>
                <fullName>Awaiting Subscription (New)</fullName>
            </value>
            <value>
                <fullName>Awaiting Subscription (Open)</fullName>
            </value>
            <value>
                <fullName>Awaiting Subscription (On Hold)</fullName>
            </value>
            <value>
                <fullName>Awaiting Subscription (Waiting for Customer Reply)</fullName>
            </value>
            <value>
                <fullName>Awaiting Subscription (Re-Open)</fullName>
            </value>
            <value>
                <fullName>Awaiting Subscription (Escalated)</fullName>
            </value>
            <value>
                <fullName>Awaiting Subscription (Postponed)</fullName>
            </value>
            <value>
                <fullName>Awaiting Subscription (Completed)</fullName>
            </value>
            <value>
                <fullName>Awaiting Subscription (Closed/Uncompleted)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/taxExempted__c.field-meta.xml
<CustomField>
    <fullName>taxExempted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>tax exempted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Reaction_Time__c.field-meta.xml
<CustomField>
    <fullName>Reaction_Time__c</fullName>
    <label>Reaction Time (in sec)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Response_Time__c.field-meta.xml
<CustomField>
    <fullName>Response_Time__c</fullName>
    <label>Response Time (in sec)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/First_Activity_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>First_Activity_Date_Time__c</fullName>
    <label>First Activity Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/First_Successful_Activity_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>First_Successful_Activity_Date_Time__c</fullName>
    <label>First Successful Activity Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lead_Created_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Lead_Created_Date_Time__c</fullName>
    <formula>Converted_Lead__r.CreatedDate</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lead Created Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Reaction_Time__c.field-meta.xml
<CustomField>
    <fullName>Reaction_Time__c</fullName>
    <label>Reaction Time (in Sec)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Response_Time__c.field-meta.xml
<CustomField>
    <fullName>Response_Time__c</fullName>
    <label>Response Time (in Sec)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BatchUtilTest.cls
@isTest public class BatchUtilTest {

    @testSetup
    public static void setupTestData() {
        List<Account> TestAccounts = new List<Account>();
        List<Lead> TestLeads = new List<Lead>();
        for (Integer x=0; x<3; x++) {
            TestAccounts.add(new Account(Name = 'TestAccount_' + x));
            TestLeads.add(new Lead(LastName='test_' + x, Company='test'));
        }
        insert TestAccounts;
        insert TestLeads;
    }
    


    @isTest static void batchProcess() {
        Test.startTest();
        
        List<Account> Accounts = [SELECT Id, Onboard_Status__c FROM Account];
        
        // corrupt data by deleting Onboarding Status
        for (Account Acct : Accounts) {
            Acct.Onboard_Status__c = null;
        }
        update Accounts;
        
        // before process, a selected account should have null onboarding status
        system.assertEquals(null, [SELECT Id, Onboard_Status__c FROM Account][2].Onboard_Status__c);
        
        // after process, a selected account should not have null onboarding status
        Database.executeBatch(
            new BatchUtil(
                'AccountOnboardingStatus',
                'SELECT Id, Onboard_Status__c FROM Account'
            )
        );
        Test.stopTest();
        system.assertNotEquals(null, [SELECT Id, Onboard_Status__c FROM Account][2].Onboard_Status__c);
        
    }
    
    // Testing method for batch without method parameter
    @isTest static void batchProcess2() {
        Test.startTest();
        
        List<Account> Accounts = [SELECT Id, Onboard_Status__c FROM Account];
        //system.assertEquals(0, [SELECT Id FROM Account WHERE Onboard_Status__c = null].size());
        
        String s = null;
        
        Database.executeBatch(
            new BatchUtil(
                'SELECT Id, Onboard_Status__c FROM Account',
                'Onboard_Status__c',
                s
            )
        );
        Test.stopTest();
        
        //system.assertEquals(3, [SELECT Id FROM Account WHERE Onboard_Status__c = null].size());
        
    }
    
    // Testing method for batch without method parameter
    @isTest static void batchProcess2a() {
        Test.startTest();
        
        List<Account> Accounts = [SELECT Id, Onboard_Status__c FROM Account];
        //system.assertEquals(0, [SELECT Id FROM Account WHERE Onboard_Status__c = null].size());
        
        Database.executeBatch(
            new BatchUtil(
                'SELECT Id, taxexempted__c FROM Account',
                'taxexempted__c',
                true
            )
        );
        Test.stopTest();
        
        
    }
    
    @isTest static void testLeadTimeCalculator() {
        Database.executeBatch(
            new BatchUtil(
                'LeadTimeCalculator',
                'SELECT Id, First_Activity_Date_Time__c, First_Successful_Activity_Date_Time__c, '
                +'Lead_Created_Date_Time__c, Response_Time__c, Reaction_Time__c FROM Opportunity'
            )
        );
    }

}