force-app/main/default/objects/Account/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>https://jira.orderbird.com/browse/SFDC-1487</description>
    <inlineHelpText>Primary Contact for all relevant communication. Auto-populated after lead conversion.</inlineHelpText>
    <label>Primary Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Contact.Account.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Account.Id</field>
            <operation>equals</operation>
            <valueField>$Source.ParentId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Primary Contact)</relationshipLabel>
    <relationshipName>PrimaryContactForAcc</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/PrimaryLanguage__c.field-meta.xml
<CustomField>
    <fullName>PrimaryLanguage__c</fullName>
    <defaultValue>&quot;German&quot;</defaultValue>
    <description>Stakeholder: Sales &amp; CS with MKT</description>
    <inlineHelpText>What language do we use to communicate with this venue? Filled in as soon as known. Updated if necessary!</inlineHelpText>
    <label>Primary Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Language</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/DataInsight__c/DataInsight__c.object-meta.xml
<CustomObject>
    <label>Data Insight</label>
    <nameField>
        <displayFormat>DI-{00000000}</displayFormat>
        <label>Data Insight Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Insights</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DataInsight__c/fields/Venue_SFId__c.field-meta.xml
<CustomField>
    <fullName>Venue_SFId__c</fullName>
    <label>MyOb Venue</label>
    <referenceTo>MyObVenue__c</referenceTo>
    <relationshipLabel>Data Insights</relationshipLabel>
    <relationshipName>Data_Insights</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MyObVenue__c/MyObVenue__c.object-meta.xml
<CustomObject>
    <label>MyOb Venue</label>
    <nameField>
        <displayFormat>MyOb-{000000}</displayFormat>
        <label>MyOb Venue</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MyOb Venues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MyObVenue__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>MyOrderbird_Log_ons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MyObVenue__c/fields/InsightsEligible__c.field-meta.xml
<CustomField>
    <fullName>InsightsEligible__c</fullName>
    <formula>ISBLANK(InsightsEmail__c)
 &amp;&amp;
Account__r.Target_Product__c = &quot;MINI&quot;
 &amp;&amp;
ISBLANK(Account__r.Dunning_0_Date__c)
 &amp;&amp;
(
  CONTAINS(Channel__c, &quot;Food&quot;) 
   || 
  CONTAINS(Channel__c, &quot;Cafe&quot;) 
   || 
  CONTAINS(Channel__c, &quot;Drinks&quot;) 
   || 
  CONTAINS(Channel__c, &quot;Big Night Out&quot;)
)
 &amp;&amp;
(
  TEXT(Account__r.Account_Status__c) = &quot;Active Customer&quot;
   ||
  TEXT(Account__r.Account_Status__c) = &quot;Future Customer&quot;
)
 &amp;&amp;
(
  ISBLANK(TEXT(Account__r.PrimaryLanguage__c))
   ||
  TEXT(Account__r.PrimaryLanguage__c) = &quot;German&quot;
   ||
  TEXT(Account__r.PrimaryLanguage__c) = &quot;English&quot;
)</formula>
    <label>Insights Eligible</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MyObVenue__c/fields/InsightsEmail__c.field-meta.xml
<CustomField>
    <fullName>InsightsEmail__c</fullName>
    <label>Insights Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/MyObVenue__c/fields/InsightsUnsubbed__c.field-meta.xml
<CustomField>
    <fullName>InsightsUnsubbed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Insights Unsubscribed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MyObVenue__c/fields/InsightsVersion__c.field-meta.xml
<CustomField>
    <fullName>InsightsVersion__c</fullName>
    <defaultValue>&quot;2&quot;</defaultValue>
    <label>Insights Version</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Language.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>German</fullName>
        <default>true</default>
        <label>German</label>
    </customValue>
    <customValue>
        <fullName>English</fullName>
    </customValue>
    <customValue>
        <fullName>French</fullName>
    </customValue>
    <customValue>
        <fullName>Spanish</fullName>
    </customValue>
    <customValue>
        <fullName>Russian</fullName>
    </customValue>
    <customValue>
        <fullName>Italian</fullName>
    </customValue>
    <customValue>
        <fullName>Polish</fullName>
    </customValue>
    <customValue>
        <fullName>Chinese</fullName>
    </customValue>
    <customValue>
        <fullName>Japanese</fullName>
    </customValue>
    <customValue>
        <fullName>Swedish</fullName>
    </customValue>
    <masterLabel>Language</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/InsightsSubscription.cls
global class InsightsSubscription implements Schedulable, Database.AllowsCallouts {
    global void execute(SchedulableContext SC) {
        futureExecute();
    }
    
    @future(callout=true)
    global static void futureExecute() {
        
        //subscribe venues to Insights (limit 200)
        
        List<MyObVenue__c> SubscribeVenues = [
        	SELECT Id, InsightsEmail__c, InsightsVersion__c, Account__r.PrimaryLanguage__c, Account__r.Primary_Contact__r.Email
            FROM MyObVenue__c
            WHERE Id IN (SELECT Venue_SFId__c from DataInsight__c) AND InsightsEligible__c = TRUE
            LIMIT 200
        ];
        
		List<SendGrid.PersonalizationWrapper> PWs = new List<SendGrid.PersonalizationWrapper>();       
        
        for (MyObVenue__c v : SubscribeVenues) {
            v.InsightsEmail__c = v.Account__r.Primary_Contact__r.Email;
            v.InsightsVersion__c = '2';
            PWs.add(new SendGrid.PersonalizationWrapper(v.InsightsEmail__c, (Map<String, Object>)JSON.deserializeUntyped ('{"isEnglish":' + String.valueOf(v.Account__r.PrimaryLanguage__c == 'English') + '}')));
        }
                
        SendGrid.SendEmail(new SendGrid.EmailWrapper(
            'd-ab85a9551dc0422181279d0748c96e7a', 	//templateId
            new List<String>{'insights_presend'},	//categories
            PWs,									//personalizations
            20248									//asm (unsubscribe group)
        ));
        
        ////////////
        // retrieve globally unsubscribed email addresses
        
        HttpRequest globalUnsubReq = new HttpRequest();
        globalUnsubReq.setMethod('GET');
        globalUnsubReq.setEndpoint('https://api.sendgrid.com/v3/suppression/unsubscribes?start_time=' + String.valueOf(Date.newInstance(1970,1,4).daysBetween(Date.today())*86400));
        globalUnsubReq.setHeader('content-type', 'application/json');
        globalUnsubReq.setHeader('Authorization', 'Bearer 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');
        Http globalUnsubHttp = new Http();
        HTTPResponse globalUnsubRes;
        if (!test.isRunningTest()) globalUnsubRes = globalUnsubHttp.send(globalUnsubReq);

        List<Object> GlobalUnsubs;
        try {
            GlobalUnsubs = (List<Object>)json.deserializeUntyped(globalUnsubRes.getBody());
        }catch(exception e){
            GlobalUnsubs = new List<Object>();
        }
        
        ////////////
        // retrieve group unsubscribed email addresses
        
        HttpRequest groupUnsubReq = new HttpRequest();
        groupUnsubReq.setMethod('GET');
        groupUnsubReq.setEndpoint('https://api.sendgrid.com/v3/asm/groups/20248/suppressions');
        groupUnsubReq.setHeader('content-type', 'application/json');
        groupUnsubReq.setHeader('Authorization', 'Bearer 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');
        Http groupUnsubHttp = new Http();
        HTTPResponse groupUnsubRes;
        if (!test.isRunningTest()) groupUnsubRes = groupUnsubHttp.send(groupUnsubReq);
        Set<String> UnsubbedEmails;
        try {
            UnsubbedEmails = (Set<String>)json.deserialize(groupUnsubRes.getBody(), Set<String>.class);
        }catch(exception e){
            UnsubbedEmails = new Set<String>();
        }
        for (Object o : GlobalUnsubs) {
            Map<String,Object> GlobalUnsubMap = (Map<String,Object>)o;
            UnsubbedEmails.add((String)GlobalUnsubMap.get('email'));
        }
        List<MyObVenue__c> VenuesToUnsub = [SELECT Id, InsightsUnsubbed__c FROM MyObVenue__c WHERE InsightsEmail__c != null AND InsightsEmail__c IN :UnsubbedEmails];
        for (MyObVenue__c v : VenuesToUnsub) {
            v.InsightsUnsubbed__c = true;
        }
        update VenuesToUnsub;
        update SubscribeVenues;

    }
}