force-app/main/default/objects/Account/fields/PrimaryLanguage__c.field-meta.xml
<CustomField>
    <fullName>PrimaryLanguage__c</fullName>
    <defaultValue>&quot;German&quot;</defaultValue>
    <description>Stakeholder: Sales &amp; CS with MKT</description>
    <inlineHelpText>What language do we use to communicate with this venue? Filled in as soon as known. Updated if necessary!</inlineHelpText>
    <label>Primary Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Language</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CaseSolution__c/CaseSolution__c.object-meta.xml
<CustomObject>
    <label>Case Solution</label>
    <nameField>
        <label>Case Solution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Solutions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CaseSolution__c/fields/NameDE__c.field-meta.xml
<CustomField>
    <fullName>NameDE__c</fullName>
    <label>Name (German)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CaseSolution__c/fields/NameFR__c.field-meta.xml
<CustomField>
    <fullName>NameFR__c</fullName>
    <label>Name (French)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CaseSolutionJunction__c/CaseSolutionJunction__c.object-meta.xml
<CustomObject>
    <label>Case Solution Junction</label>
    <nameField>
        <displayFormat>CSJ-{00000000}</displayFormat>
        <label>Case Solution Junction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Solution Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CaseSolutionJunction__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Solution Junctions</relationshipLabel>
    <relationshipName>Case_Solution_Junctions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CaseSolutionJunction__c/fields/CaseSolution__c.field-meta.xml
<CustomField>
    <fullName>CaseSolution__c</fullName>
    <label>Case Solution</label>
    <referenceTo>CaseSolution__c</referenceTo>
    <relationshipLabel>Case Solution Junctions</relationshipLabel>
    <relationshipName>Case_Solution_Junctions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CaseSolutionTranslation__c/CaseSolutionTranslation__c.object-meta.xml
<CustomObject>
    <label>Case Solution Translation</label>
    <nameField>
        <label>Case Solution Translation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Solution Translations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CaseSolutionTranslation__c/fields/CaseSolution__c.field-meta.xml
<CustomField>
    <fullName>CaseSolution__c</fullName>
    <label>Case Solution</label>
    <referenceTo>CaseSolution__c</referenceTo>
    <relationshipLabel>Case Solution Translations</relationshipLabel>
    <relationshipName>Case_Solution_Translations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CaseSolutionTranslation__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EN</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/PrimaryLanguage__c.field-meta.xml
<CustomField>
    <fullName>PrimaryLanguage__c</fullName>
    <description>Stakeholder: Sales &amp; CS &amp; MKT</description>
    <inlineHelpText>What language do we use to communicate with this venue? Filled in as soon as known. Updated if necessary!</inlineHelpText>
    <label>Primary Language</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>Russian</fullName>
            </value>
            <value>
                <fullName>Italian</fullName>
            </value>
            <value>
                <fullName>Polish</fullName>
            </value>
            <value>
                <fullName>Chinese</fullName>
            </value>
            <value>
                <fullName>Japanese</fullName>
            </value>
            <value>
                <fullName>Swedish</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/globalValueSets/Language.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>German</fullName>
        <default>true</default>
        <label>German</label>
    </customValue>
    <customValue>
        <fullName>English</fullName>
    </customValue>
    <customValue>
        <fullName>French</fullName>
    </customValue>
    <customValue>
        <fullName>Spanish</fullName>
    </customValue>
    <customValue>
        <fullName>Russian</fullName>
    </customValue>
    <customValue>
        <fullName>Italian</fullName>
    </customValue>
    <customValue>
        <fullName>Polish</fullName>
    </customValue>
    <customValue>
        <fullName>Chinese</fullName>
    </customValue>
    <customValue>
        <fullName>Japanese</fullName>
    </customValue>
    <customValue>
        <fullName>Swedish</fullName>
    </customValue>
    <masterLabel>Language</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CaseSolutionController.cls
public class CaseSolutionController {
    
    @AuraEnabled
    public static String getCaseSolutions(String CaseId) {
        return json.serialize([SELECT Id, CaseSolution__r.Name FROM CaseSolutionJunction__c WHERE Case__c = :CaseId]);
    }
    
    @AuraEnabled
    public static void newCaseSolution(String CaseId, String CaseSolutionId, Boolean UpdateSubject) {
        insert new CaseSolutionJunction__c(Case__c = CaseId, CaseSolution__c = CaseSolutionId);
        if (UpdateSubject) {
            Case c = [SELECT Id, Contact.PrimaryLanguage__c, Account.PrimaryLanguage__c, Subject FROM Case WHERE Id = :CaseId LIMIT 1];
            CaseSolution__c cs = [SELECT Id, Name, NameDE__c, NameFR__c FROM CaseSolution__c WHERE Id = :CaseSolutionId LIMIT 1];
            String Subject = cs.NameDE__c;
            if (
                c.Contact.PrimaryLanguage__c == 'English' || (
                    c.Contact.PrimaryLanguage__c == null 
                    && c.Account.PrimaryLanguage__c == 'English'
                )
            ) {
                Subject = cs.Name;
            }
            if (
                c.Contact.PrimaryLanguage__c == 'French' || (
                    c.Contact.PrimaryLanguage__c == null 
                    && c.Account.PrimaryLanguage__c == 'French'
                )
            ) {
                Subject = cs.NameFR__c;
            }
            c.Subject = Subject;
            update c;
        }
    }
    
    @AuraEnabled
    public static void delCaseSolution(String CaseId, String CaseSolutionIds) {
        List<String> CSIds = (List<String>)json.deserialize(CaseSolutionIds, List<String>.class);
        delete [SELECT Id FROM CaseSolutionJunction__c WHERE Case__c = :CaseId AND CaseSolution__c NOT IN :CSIds];
    }
    
    @AuraEnabled(cacheable=true)
    public static List<LookupSearchResult> search(String searchTerm, List<String> selectedIds) {
        // Prepare query paramters
        searchTerm += '*';
        
        // Execute search query
        List<List<SObject>> searchResults = [
            FIND :searchTerm IN ALL FIELDS RETURNING
            CaseSolutionTranslation__c (Name, Language__c, CaseSolution__c, CaseSolution__r.Name, CaseSolution__r.Description__c WHERE CaseSolution__c NOT IN :selectedIds)
            LIMIT 20
        ];
        
        // Prepare results
        List<LookupSearchResult> results = new List<LookupSearchResult>();
        
        String solnIcon = 'custom:custom94';
        CaseSolutionTranslation__c [] CSTs = ((List<CaseSolutionTranslation__c>) searchResults[0]);
        for (CaseSolutionTranslation__c CST : CSTs) {
            if (CST.Language__c == 'EN') results.add(new LookupSearchResult(CST.CaseSolution__c, 'CaseSolutionTranslation__c', solnIcon, '🇬🇧 ' + CST.Name, CST.CaseSolution__r.Description__c, CST.CaseSolution__r.Name));
            if (CST.Language__c == 'DE') results.add(new LookupSearchResult(CST.CaseSolution__c, 'CaseSolutionTranslation__c', solnIcon, '🇩🇪 ' + CST.Name, CST.CaseSolution__r.Description__c, CST.CaseSolution__r.Name));
            if (CST.Language__c == 'FR') results.add(new LookupSearchResult(CST.CaseSolution__c, 'CaseSolutionTranslation__c', solnIcon, '🇫🇷 ' + CST.Name, CST.CaseSolution__r.Description__c, CST.CaseSolution__r.Name));
        }
        return results;
    }
}