force-app/main/default/objects/Account/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>https://jira.orderbird.com/browse/SFDC-1487</description>
    <inlineHelpText>Primary Contact for all relevant communication. Auto-populated after lead conversion.</inlineHelpText>
    <label>Primary Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Contact.Account.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Account.Id</field>
            <operation>equals</operation>
            <valueField>$Source.ParentId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Primary Contact)</relationshipLabel>
    <relationshipName>PrimaryContactForAcc</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/SF_BillTo_Contact__c.field-meta.xml
<CustomField>
    <fullName>SF_BillTo_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Stakeholder: Sales &amp; Account Management</description>
    <inlineHelpText>This defines the official billing address.</inlineHelpText>
    <label>Billing Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.ParentId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Zuora BillTo Contact)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/SF_SoldTo_Contact__c.field-meta.xml
<CustomField>
    <fullName>SF_SoldTo_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Stakeholder: Sales &amp; Account Management</description>
    <inlineHelpText>This contact defines the official shipping address.</inlineHelpText>
    <label>Shipping Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.ParentId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <formula>Account.Primary_Contact__c = Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/classes/ContactAutoPopulatorTest.cls
@isTest
public class ContactAutoPopulatorTest {

    static testMethod void insertLeads() {
        
        Lead l = new Lead(LastName = 'test', Company = 'test');
        insert l;
        
        Database.LeadConvert lc = new Database.LeadConvert();
        lc.setLeadId(l.Id);
        lc.setConvertedStatus('Qualified');
        Database.LeadConvertResult lcr = Database.convertLead(lc);
        
        system.assert(lcr.isSuccess());
        
        Lead updL = [SELECT ConvertedAccountId, ConvertedContactId FROM Lead WHERE Id=:l.Id LIMIT 1];

        system.assertEquals(
            [SELECT Primary_Contact__c FROM Account WHERE Id=:updL.ConvertedAccountId LIMIT 1].Primary_Contact__c,
            updL.ConvertedContactId
        );

        system.assertEquals(
            [SELECT SF_SoldTo_Contact__c FROM Account WHERE Id=:updL.ConvertedAccountId LIMIT 1].SF_SoldTo_Contact__c,
            updL.ConvertedContactId
        );

        system.assertEquals(
            [SELECT SF_BillTo_Contact__c FROM Account WHERE Id=:updL.ConvertedAccountId LIMIT 1].SF_BillTo_Contact__c,
            updL.ConvertedContactId
        );
        
        Lead l2 = new Lead(LastName = 'test2', Company = 'test');
        insert l2;
        
        Database.LeadConvert lc2 = new Database.LeadConvert();
        lc2.setLeadId(l2.Id);
        lc2.setAccountId(updL.ConvertedAccountId);
        lc2.setConvertedStatus('Additional Contact');
        Database.LeadConvertResult lcr2 = Database.convertLead(lc2);
        
        system.assert(lcr2.isSuccess());

        Lead updL2 = [SELECT ConvertedAccountId, ConvertedContactId FROM Lead WHERE Id=:l2.Id LIMIT 1];

        system.assertEquals(
            [SELECT Primary_Contact__c FROM Account WHERE Id=:updL.ConvertedAccountId LIMIT 1].Primary_Contact__c,
            updL.ConvertedContactId
        );

        system.assertNotEquals(
            [SELECT Primary_Contact__c FROM Account WHERE Id=:updL2.ConvertedAccountId LIMIT 1].Primary_Contact__c,
            updL2.ConvertedContactId
        );

    }
}