force-app/main/default/objects/Account/fields/PrimaryLanguage__c.field-meta.xml
<CustomField>
    <fullName>PrimaryLanguage__c</fullName>
    <defaultValue>&quot;German&quot;</defaultValue>
    <description>Stakeholder: Sales &amp; CS with MKT</description>
    <inlineHelpText>What language do we use to communicate with this venue? Filled in as soon as known. Updated if necessary!</inlineHelpText>
    <label>Primary Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Language</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Related_MINI_Account__c.field-meta.xml
<CustomField>
    <fullName>Related_MINI_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related MINI Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Related MINI Account)</relationshipLabel>
    <relationshipName>PROAccount</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Related_PRO_Account__c.field-meta.xml
<CustomField>
    <fullName>Related_PRO_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related PRO Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>MINI Accounts</relationshipLabel>
    <relationshipName>MINIAccount</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <description>Counterpart to Serial Number on Lead</description>
    <label>Serial Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Target_Product__c.field-meta.xml
<CustomField>
    <fullName>Target_Product__c</fullName>
    <label>Target Product</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HardwareFulfilment__c/HardwareFulfilment__c.object-meta.xml
<CustomObject>
    <label>Hardware Fulfilment</label>
    <nameField>
        <label>Fulfilment No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hardware Fulfilments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HardwareFulfilment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Hardware Fulfilments</relationshipLabel>
    <relationshipName>HardwareFulfilments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HardwareFulfilment__c/fields/SerialNumber__c.field-meta.xml
<CustomField>
    <fullName>SerialNumber__c</fullName>
    <label>Serial number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/LAC_ID__c.field-meta.xml
<CustomField>
    <fullName>LAC_ID__c</fullName>
    <description>Stakeholder: CDS, BI, MKT, Sales https://jira.orderbird.com/browse/CDS-138</description>
    <inlineHelpText>Enter the ID (3 digits) for relevant Lead Attribution Combo. Careful: entering wrong numbers is possible!</inlineHelpText>
    <label>LAC ID</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/PrimaryLanguage__c.field-meta.xml
<CustomField>
    <fullName>PrimaryLanguage__c</fullName>
    <description>Stakeholder: Sales &amp; CS with MKT</description>
    <inlineHelpText>What language do we use to communicate with this venue? Filled in as soon as known. Updated if necessary!</inlineHelpText>
    <label>Primary Language</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>Russian</fullName>
            </value>
            <value>
                <fullName>Italian</fullName>
            </value>
            <value>
                <fullName>Polish</fullName>
            </value>
            <value>
                <fullName>Chinese</fullName>
            </value>
            <value>
                <fullName>Japanese</fullName>
            </value>
            <value>
                <fullName>Swedish</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Target_Product__c.field-meta.xml
<CustomField>
    <fullName>Target_Product__c</fullName>
    <formula>IF( OR(LAC_ID__c = &quot;180&quot;,LAC_ID__c = &quot;181&quot;), &quot;MINI&quot;, &quot;PRO&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Target Product</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MyObVenue__c/MyObVenue__c.object-meta.xml
<CustomObject>
    <label>MyOb Venue</label>
    <nameField>
        <displayFormat>MyOb-{000000}</displayFormat>
        <label>MyOb Venue</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MyOb Venues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MyObVenue__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>MyOrderbird_Log_ons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MyObVenue__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>MyOrderbird_Log_ons</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/MyObVenue__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created only for Customers that buy a MINI in Shopify</description>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>MyOb Venues</relationshipLabel>
    <relationshipName>MyOb_Venues</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MyObVenue__c/fields/Target_Product__c.field-meta.xml
<CustomField>
    <fullName>Target_Product__c</fullName>
    <formula>Account__r.Target_Product__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Target Product</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/MINI_Eligible__c.field-meta.xml
<CustomField>
    <fullName>MINI_Eligible__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MINI Eligible</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/SubscriptionLineItem__c.field-meta.xml
<CustomField>
    <fullName>SubscriptionLineItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription Line Item</label>
    <referenceTo>SubscriptionLineItem__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/SubscriptionLineItem__c.object-meta.xml
<CustomObject>
    <label>Subscription Line Item</label>
    <nameField>
        <label>Subscription Line Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SubscriptionLineItem__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>SubscriptionLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>Subscription_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>Subscription_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Language.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>German</fullName>
        <default>true</default>
        <label>German</label>
    </customValue>
    <customValue>
        <fullName>English</fullName>
    </customValue>
    <customValue>
        <fullName>French</fullName>
    </customValue>
    <customValue>
        <fullName>Spanish</fullName>
    </customValue>
    <customValue>
        <fullName>Russian</fullName>
    </customValue>
    <customValue>
        <fullName>Italian</fullName>
    </customValue>
    <customValue>
        <fullName>Polish</fullName>
    </customValue>
    <customValue>
        <fullName>Chinese</fullName>
    </customValue>
    <customValue>
        <fullName>Japanese</fullName>
    </customValue>
    <customValue>
        <fullName>Swedish</fullName>
    </customValue>
    <masterLabel>Language</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/MiniConverter.cls
global class MiniConverter implements Queueable, Database.AllowsCallouts {
  global Map<Id, Lead> leads;

  global MiniConverter(Map<Id, Lead> iLeads) {
    leads = iLeads;
  }

  global MiniConverter(Id leadId) {
    Map<Id, Lead> iLeads = new Map<Id, Lead>(
      [
        SELECT Id, Lastname, Serial_Number__c, PrimaryLanguage__c, LAC_ID__c
        FROM Lead
        WHERE id = :leadId
      ]
    );
    leads = iLeads;
  }

  public void execute(QueueableContext context) {
    List<Database.LeadConvert> leadConverts = new List<Database.LeadConvert>();
    LeadStatus convertStatus = [
      SELECT Id, MasterLabel
      FROM LeadStatus
      WHERE MasterLabel = 'Qualified MINI'
      LIMIT 1
    ];

    Map<Id, String> SNLeadMap = new Map<Id, String>();
    Map<String, Id> SNAcctMap = new Map<String, Id>();
    Set<Id> HWFAccts = new Set<Id>();
    for (Lead lead : leads.values()) {
      if (lead.Serial_Number__c != null)
        SNLeadMap.put(lead.Id, lead.Serial_Number__c);
    }
    for (HardwareFulfilment__c hwf : [
      SELECT Id, Account__c, Account__r.Related_MINI_Account__c, SerialNumber__c
      FROM HardwareFulfilment__c
      WHERE SerialNumber__c IN :SNLeadMap.values()
    ]) {
      /*HWFAccts.add(hwf.Account__c);
            SNAcctMap.put(
                hwf.SerialNumber__c, 
                hwf.Account__r.Related_MINI_Account__c == null ?
                	hwf.Account__c : hwf.Account__r.Related_MINI_Account__c
            );*/
    }
    Set<Id> NonMINIAccts = new Set<Id>();
    for (AggregateResult ar : [
      SELECT AccountId AcctId
      FROM Quote
      WHERE
        Quote.Status != 'Expired'
        AND Quote.Status != 'Rejected'
        AND AccountId IN :SNAcctMap.values()
        AND Id IN (
          SELECT QuoteId
          FROM QuoteLineItem
          WHERE Product2.MINI_Eligible__c = FALSE
        )
      GROUP BY AccountId
    ]) {
      NonMINIAccts.add((Id) ar.get('AcctId'));
    }
    for (AggregateResult ar : [
      SELECT Account__c AcctId
      FROM Subscription__c
      WHERE
        Account__c IN :SNAcctMap.values()
        AND Id IN (
          SELECT Subscription__c
          FROM SubscriptionLineItem__c
          WHERE Product__r.MINI_Eligible__c = FALSE
        )
      GROUP BY Account__c
    ]) {
      NonMINIAccts.add((Id) ar.get('AcctId'));
    }

    Id MINIownerId = Test.isRunningTest()
      ? UserInfo.getUserId()
      : [SELECT id FROM User WHERE alias = 'dfall' LIMIT 1].id;

    for (Lead lead : leads.values()) {
      Id AcctId = SNAcctMap.get(lead.Serial_Number__c);
      Database.LeadConvert leadConvert = new Database.LeadConvert();
      leadConvert.setLeadId(lead.Id);
      leadConvert.setAccountId(NonMINIAccts.contains(AcctId) ? null : AcctId);
      leadConvert.setConvertedStatus(convertStatus.MasterLabel);
      leadConvert.setDoNotCreateOpportunity(false);
      leadConvert.setOwnerId(MINIownerId);
      leadConverts.add(leadConvert);
    }
    system.debug(json.serialize(leadConverts));
    Database.LeadConvertResult[] leadConvertResults = Database.convertLead(
      leadConverts,
      false
    );
    system.debug(json.serialize(leadConvertResults));

    Map<Id, Id> NewAcctMap = new Map<Id, Id>();
    Map<Id, MyObVenue__c> LeadIdMapVenue = new Map<Id, MyObVenue__c>();
    List<MyObVenue__c> updateVenues = new List<MyObVenue__c>();
    for (MyObVenue__c v : [
      SELECT id, lead__c, contact__c
      FROM MyObVenue__c
      WHERE lead__c IN :leads.keySet()
    ]) {
      LeadIdMapVenue.put(v.lead__c, v);
    }

    for (Database.LeadConvertResult lcr : leadConvertResults) {
      NewAcctMap.put(lcr.accountid, lcr.leadid);
      String lang = leads.get(lcr.leadid).PrimaryLanguage__c;
      if (
        lcr.success && leads.get(lcr.leadid).LAC_ID__c == '180' // sending registration emails only to this leads
      ) {
        AccountLightningController.sendMyObRegistrationEmail(
          lcr.contactId,
          lang == 'English' || lang == 'French' ? lang : 'German',
          'supportmini@orderbird.com'
        );
      } else if (lcr.success && leads.get(lcr.leadid).LAC_ID__c == '181') {
        MyObVenue__c v = LeadIdMapVenue.get(lcr.leadid);
        v.contact__c = lcr.contactid;
        updateVenues.add(v);
      }
    }
    update updateVenues;

    Map<String, Id> ChildMap = new Map<String, Id>();
    for (Account a : [
      SELECT Id
      FROM Account
      WHERE Id IN :NewAcctMap.keySet()
    ]) {
      if (
        SNAcctMap.keySet()
          .contains(leads.get(NewAcctMap.get(a.Id)).Serial_Number__c) &&
        !HWFAccts.contains(a.Id)
      ) {
        ChildMap.put(leads.get(NewAcctMap.get(a.Id)).Serial_Number__c, a.Id);
      }
    }
    List<Account> updateAccounts = new List<Account>();
    for (HardwareFulfilment__c hwf : [
      SELECT Id, Account__c, SerialNumber__c
      FROM HardwareFulfilment__c
      WHERE SerialNumber__c IN :ChildMap.keySet() AND SerialNumber__c != NULL
    ]) {
      updateAccounts.add(
        new Account(
          Id = hwf.Account__c,
          Related_MINI_Account__c = ChildMap.get(hwf.SerialNumber__c)
        )
      );
      updateAccounts.add(
        new Account(
          Id = ChildMap.get(hwf.SerialNumber__c),
          Related_PRO_Account__c = hwf.Account__c,
          Target_Product__c = 'MINI'
        )
      );
    }
    update updateAccounts;
  }
}