force-app/main/default/objects/Account/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>https://jira.orderbird.com/browse/SFDC-1487</description>
    <inlineHelpText>Primary Contact for all relevant communication. Auto-populated after lead conversion.</inlineHelpText>
    <label>Primary Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Contact.Account.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Account.Id</field>
            <operation>equals</operation>
            <valueField>$Source.ParentId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Primary Contact)</relationshipLabel>
    <relationshipName>PrimaryContactForAcc</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/SF_BillTo_Contact__c.field-meta.xml
<CustomField>
    <fullName>SF_BillTo_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Stakeholder: Sales &amp; Account Management</description>
    <inlineHelpText>This defines the official billing address.</inlineHelpText>
    <label>Billing Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.ParentId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Zuora BillTo Contact)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <formula>Account.Primary_Contact__c = Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>2.0</description>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>Zuora Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/MyObVenue__c/MyObVenue__c.object-meta.xml
<CustomObject>
    <label>MyOb Venue</label>
    <nameField>
        <displayFormat>MyOb-{000000}</displayFormat>
        <label>MyOb Venue</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MyOb Venues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MyObVenue__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>MyOrderbird_Log_ons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MyObVenue__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>MyOrderbird_Log_ons</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/MyObVenue__c/fields/MyOrderbirdId__c.field-meta.xml
<CustomField>
    <fullName>MyOrderbirdId__c</fullName>
    <externalId>true</externalId>
    <label>MyOrderbird Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LAC_ID__c.field-meta.xml
<CustomField>
    <fullName>LAC_ID__c</fullName>
    <description>Stakeholder: CDS, BI, MKT, Sales https://jira.orderbird.com/browse/CDS-138</description>
    <inlineHelpText>Enter the ID (3 digits) for relevant Lead Attribution Combo. Careful: entering wrong numbers is possible!</inlineHelpText>
    <label>LAC ID</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Stakeholder: Sales &amp; CS</description>
    <inlineHelpText>How is the person in charge of the sales talk on the prospect side? This Contact should also include all the relevant contact information (phone, email). Mailings go there. Update if necessary!</inlineHelpText>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Primary Contact)</relationshipLabel>
    <relationshipName>PrimaryContactForOpp</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/EffectiveEndDate__c.field-meta.xml
<CustomField>
    <fullName>EffectiveEndDate__c</fullName>
    <label>Effective End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product2/fields/EffectiveStartDate__c.field-meta.xml
<CustomField>
    <fullName>EffectiveStartDate__c</fullName>
    <label>Effective Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductCategory__c.field-meta.xml
<CustomField>
    <fullName>ProductCategory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Category</label>
    <referenceTo>ProductCategory__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>POS Base License</fullName>
                <default>true</default>
                <label>POS Base License</label>
            </value>
            <value>
                <fullName>POS Add-on License</fullName>
            </value>
            <value>
                <fullName>Hardware</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Discount</fullName>
            </value>
            <value>
                <fullName>Promotion</fullName>
            </value>
            <value>
                <fullName>Other License</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ProductCategory__c/ProductCategory__c.object-meta.xml
<CustomObject>
    <label>Product Category</label>
    <nameField>
        <label>Product Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/SubscriptionLineItem__c.object-meta.xml
<CustomObject>
    <label>Subscription Line Item</label>
    <nameField>
        <label>Subscription Line Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SubscriptionLineItem__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>SubscriptionLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/fields/EffectiveEndDate__c.field-meta.xml
<CustomField>
    <fullName>EffectiveEndDate__c</fullName>
    <label>Effective End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/fields/EffectiveStartDate__c.field-meta.xml
<CustomField>
    <fullName>EffectiveStartDate__c</fullName>
    <label>Effective Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>Subscription_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>Subscription__r.Status__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>Subscription_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/PortalController_test.cls
@isTest public class PortalController_test {

    static TestMethod void test() {
        Account a = new Account(name='test');
        insert a;
        Contact c = new Contact(lastname='test', accountid=a.id, email='test@test.com');
        insert c;
        a.SF_BillTo_Contact__c = c.Id;
        update a;
        MyObVenue__c v = new MyObVenue__c(contact__c=c.Id,myorderbirdid__c='123');
        insert v;
        Invoice__c i = new Invoice__c(name='test', account__c = a.id, status__c = 'posted');
        insert i;
        Opportunity o = new Opportunity(LAC_Id__c = '110', AccountId = a.Id, name='test', CloseDate = date.today(), StageName='Potential');
        insert o;
        Quote q = new Quote(OpportunityId = o.Id, name='test');
        insert q;
        Subscription__c s = new Subscription__c(Account__c = a.id, ZuoraId__c = 'test');
        insert s;
        ProductCategory__c pc = new ProductCategory__c(ProductType__c = 'POS Service+Device', ZuoraId__c = 'test');
        insert pc;
        Product2 p1 = new Product2(ProductCategory__c = pc.id, name='test');
        insert p1;
        insert new SubscriptionLineItem__c(Subscription__c = s.id, product__c = p1.id, EffectiveStartDate__c = date.today(), EffectiveEndDate__c = date.today(), ZuoraId__c = 'test');
        insert new SubscriptionLineItem__c(Subscription__c = s.id, product__c = p1.id, EffectiveStartDate__c = date.today()+1, EffectiveEndDate__c = date.today()+1, ZuoraId__c = 'test1');
        String token = PortalToken.encryptToken('123');
        PortalController.LicenseWrapper pclw = new PortalController.LicenseWrapper(new list<aggregateresult>(), new list<aggregateresult>(), new list<aggregateresult>(), new list<aggregateresult>(), new list<aggregateresult>(), new list<aggregateresult>(), new list<aggregateresult>(), new list<aggregateresult>());
        system.debug(PortalController.getAccountInfo(token));
        system.debug(PortalController.verifyConnection(token, 'test'));
        system.debug(PortalController.getAccountInfo(token));
        system.debug(PortalController.getToken(a.Id));
        system.debug(PortalController.getInvoices(token));
        system.debug(PortalController.getTSE(token));
        system.debug(PortalController.getFinanzamt(token, '12345'));
        Map<String, Object> LetterMap = (Map<String, Object>)JSON.deserializeUntyped(PortalController.createP148Letter(token, '{"Venue":{"Account__r":{"Primary_Contact__r":{}}},"Finanzamt":{}}', true));
        Id LetterId = (String)LetterMap.get('StringValue');
        system.debug(PortalController.downloadP148Letter(token, 'test'));
        system.debug(PortalController.createP148Email(token, 'test'));
        system.debug(PortalController.getP148Key(token, 'test'));
        system.debug(PortalController.getInvoice(token, i.id));
        system.debug(PortalController.getQuotes(token));
        system.debug(PortalController.getQuote(token, q.Id));	
        system.debug(PortalController.getInvoicePDF(token, 'test'));
        system.debug(PortalController.CreateLicenseQuote(token, '[{"Type":"TSE","Frequency":"12","Num":1}]'));
        //system.debug(PortalController.getLicenses(token));
    }

    static TestMethod void test2() {
        Account a = new Account(name='test');
        insert a;
        Contact c = new Contact(lastname='test', accountid=a.id, email='test@test.com');
        insert c;
        a.SF_BillTo_Contact__c = c.Id;
        update a;
        MyObVenue__c v = new MyObVenue__c(contact__c=c.Id,myorderbirdid__c='123');
        insert v;
        Invoice__c i = new Invoice__c(name='test', account__c = a.id, status__c = 'posted');
        insert i;
        Opportunity o = new Opportunity(LAC_Id__c = '110', AccountId = a.Id, name='test', CloseDate = date.today(), StageName='Potential');
        insert o;
        Quote q = new Quote(OpportunityId = o.Id, name='test');
        insert q;
        Subscription__c s = new Subscription__c(Account__c = a.id, ZuoraId__c = 'test');
        insert s;
        ProductCategory__c pc = new ProductCategory__c(ProductType__c = 'POS Service+Device', ZuoraId__c = 'test');
        insert pc;
        Product2 p1 = new Product2(ProductCategory__c = pc.id, name='test');
        insert p1;
        insert new SubscriptionLineItem__c(Subscription__c = s.id, product__c = p1.id, EffectiveStartDate__c = date.today(), EffectiveEndDate__c = date.today(), ZuoraId__c = 'test');
        insert new SubscriptionLineItem__c(Subscription__c = s.id, product__c = p1.id, EffectiveStartDate__c = date.today()+1, EffectiveEndDate__c = date.today()+1, ZuoraId__c = 'test1');
        String token = PortalToken.encryptToken('123');
        system.debug(PortalController.getAccountInfo(token));
        system.debug(PortalController.verifyConnection(token, 'test'));
        system.debug(PortalController.getAccountInfo(token));
        system.debug(PortalController.getToken(a.Id));
        system.debug(PortalController.getTSE(token));
        Map<String, Object> LetterMap = (Map<String, Object>)JSON.deserializeUntyped(PortalController.createP148Letter(token, '{"Venue":{"Account__r":{"Primary_Contact__r":{}}},"Finanzamt":{}}', true));
        Id LetterId = (String)LetterMap.get('StringValue');
        system.debug(PortalController.CreateLicenseQuote(token, '[{"Type":"TSE","Frequency":"12","Num":1}]'));
        system.debug(PortalController.getLicenses(token));
    }
}