force-app/main/default/objects/Account/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <description>Counterpart to Serial Number on Lead</description>
    <label>Serial Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/HardwareFulfilment__c/HardwareFulfilment__c.object-meta.xml
<CustomObject>
    <label>Hardware Fulfilment</label>
    <nameField>
        <label>Fulfilment No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hardware Fulfilments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HardwareFulfilment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Hardware Fulfilments</relationshipLabel>
    <relationshipName>HardwareFulfilments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HardwareFulfilment__c/fields/InternalIDHW__c.field-meta.xml
<CustomField>
    <fullName>InternalIDHW__c</fullName>
    <externalId>true</externalId>
    <label>Internal ID HW</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HardwareFulfilment__c/fields/SerialNumber__c.field-meta.xml
<CustomField>
    <fullName>SerialNumber__c</fullName>
    <label>Serial number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/LAC_ID__c.field-meta.xml
<CustomField>
    <fullName>LAC_ID__c</fullName>
    <description>Stakeholder: CDS, BI, MKT, Sales https://jira.orderbird.com/browse/CDS-138</description>
    <inlineHelpText>Enter the ID (3 digits) for relevant Lead Attribution Combo. Careful: entering wrong numbers is possible!</inlineHelpText>
    <label>LAC ID</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Pending_Autoconversion__c.field-meta.xml
<CustomField>
    <fullName>Pending_Autoconversion__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pending Autoconversion</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/MINI_Eligible__c.field-meta.xml
<CustomField>
    <fullName>MINI_Eligible__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MINI Eligible</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/SubscriptionLineItem__c.object-meta.xml
<CustomObject>
    <label>Subscription Line Item</label>
    <nameField>
        <label>Subscription Line Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SubscriptionLineItem__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>SubscriptionLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>Subscription_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>Subscription_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/MiniConverter_test.cls
@isTest
public class MiniConverter_test {
  static testMethod void test() {
    Contact c = new Contact(LastName = 'Buyer', FirstName = 'Shopify');
    insert c;
    Lead l = new Lead(lastname = 'test', company = 'test', LAC_ID__c = '181');
    insert l;
    system.enqueueJob(new MiniConverter(l.id));
    Map<Id, Lead> leads = new Map<Id, Lead>();
    leads.put(l.Id, l);
    system.enqueueJob(new MiniConverter(leads));
  }

  static testMethod void test2() {
    Account a = new Account(name = 'test');
    insert a;
    HardwareFulfilment__c hwf = new HardwareFulfilment__c(
      InternalIDHW__c = '123',
      Account__c = a.Id,
      SerialNumber__c = '123abc'
    );
    insert hwf;
    Product2 p = new Product2(name = 'test', MINI_Eligible__c = false);
    insert p;
    Subscription__c s = new Subscription__c(
      Account__c = a.Id,
      ZuoraId__c = 'test'
    );
    insert s;
    SubscriptionLineItem__c sli = new SubscriptionLineItem__c(
      Subscription__c = s.Id,
      ZuoraId__c = 'test',
      Product__c = p.Id
    );
    insert sli;
    Lead l = new Lead(
      lastname = 'test',
      company = 'test',
      serial_number__c = '123abc'
    );
    insert l;
    Map<Id, Lead> leads = new Map<Id, Lead>();
    leads.put(l.Id, l);
    system.enqueueJob(new MiniConverter(leads));
  }

  static testMethod void Test3() {
    insert new Lead(lastname = 'test', company = 'test', lac_id__c = '180');
    system.assertEquals(
      [SELECT id, pending_autoconversion__c FROM lead LIMIT 1]
      .pending_autoconversion__c,
      true
    );
  }
}