force-app/main/default/objects/Account/fields/SF_BillTo_Contact__c.field-meta.xml
<CustomField>
    <fullName>SF_BillTo_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Stakeholder: Sales &amp; Account Management</description>
    <inlineHelpText>This defines the official billing address.</inlineHelpText>
    <label>Billing Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.ParentId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Zuora BillTo Contact)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/SF_SoldTo_Contact__c.field-meta.xml
<CustomField>
    <fullName>SF_SoldTo_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Stakeholder: Sales &amp; Account Management</description>
    <inlineHelpText>This contact defines the official shipping address.</inlineHelpText>
    <label>Shipping Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.ParentId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/taxExempted__c.field-meta.xml
<CustomField>
    <fullName>taxExempted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>tax exempted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/VATNumber__c.field-meta.xml
<CustomField>
    <fullName>VATNumber__c</fullName>
    <description>Stakeholder: Finance</description>
    <inlineHelpText>What is the venues value added tax (VAT)  number of this venue? Filled in by Sales. Required for most non-German EU customers</inlineHelpText>
    <label>VAT Number (Raw)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QuoteAccountSync.cls
/**
 * @author keylight
 */
public with sharing class QuoteAccountSync {
    /*@TestVisible private List<zqu__Quote__c> quotes;
    private Map<ID, Account> accounts;

    public QuoteAccountSync(List<zqu__Quote__c> quotes) {
        this.quotes = quotes;
    }

    public List<Account> updateAccounts() {
        Map<ID, Account> accounts = getAccounts();
        Map<Id,Account> updateAccountsMap = new Map<Id,Account>();
        for (zqu__Quote__c quote : this.quotes) {
            if (quote.zqu__BillToContact__c != null || quote.zqu__SoldToContact__c != null) {
                Account account = accounts.get(quote.zqu__Account__c);
                account.SF_BillTo_Contact__c = quote.zqu__BillToContact__c;
                account.SF_SoldTo_Contact__c = quote.zqu__SoldToContact__c;
                updateAccountsMap.put(account.Id, account);
            }
        }
        return updateAccountsMap.values();
    }

    public Map<ID, Account> getAccounts() {
        if(this.accounts == null) {
            List<ID> accountIds = new List<ID>();
            for (zqu__Quote__c quote : this.quotes) {
                accountIds.add(quote.zqu__Account__c);
            }
            this.accounts = new Map<ID, Account>([
                    SELECT Id, SF_BillTo_Contact__c, SF_SoldTo_Contact__c , CurrencyISOCode, VATNumber__c, taxExempted__c
                    FROM Account
                    WHERE Id IN :accountIds]);

            return this.accounts;
        } else {
            return this.accounts;
        }
    }*/
}