force-app/main/default/objects/Account/fields/SF_BillTo_Contact__c.field-meta.xml
<CustomField>
    <fullName>SF_BillTo_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Stakeholder: Sales &amp; Account Management</description>
    <inlineHelpText>This defines the official billing address.</inlineHelpText>
    <label>Billing Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.ParentId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Zuora BillTo Contact)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>2.0</description>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/VAT_ref__c.field-meta.xml
<CustomField>
    <fullName>VAT_ref__c</fullName>
    <label>VAT Adjustment Reference</label>
    <length>23</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>Zuora Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/InvoiceLineItem__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>ILI-{0000000}</displayFormat>
        <label>Invoice Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceLineItem__c/fields/ChargeAmount__c.field-meta.xml
<CustomField>
    <fullName>ChargeAmount__c</fullName>
    <label>Charge Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/fields/SubscriptionLineItem__c.field-meta.xml
<CustomField>
    <fullName>SubscriptionLineItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription Line Item</label>
    <referenceTo>SubscriptionLineItem__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/MyObVenue__c/MyObVenue__c.object-meta.xml
<CustomObject>
    <label>MyOb Venue</label>
    <nameField>
        <displayFormat>MyOb-{000000}</displayFormat>
        <label>MyOb Venue</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MyOb Venues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MyObVenue__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>MyOrderbird_Log_ons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MyObVenue__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>MyOrderbird_Log_ons</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/OBInvoice__c/OBInvoice__c.object-meta.xml
<CustomObject>
    <label>OB Invoice</label>
    <nameField>
        <label>Invoice (New) Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OB Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OBInvoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Invoices_New</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OBInvoiceItem__c/OBInvoiceItem__c.object-meta.xml
<CustomObject>
    <label>OB Invoice Item</label>
    <nameField>
        <displayFormat>OBInvItem-{00000000}</displayFormat>
        <label>Invoice Item (New) Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OB Invoice Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OBInvoiceItem__c/fields/ChargeAmount__c.field-meta.xml
<CustomField>
    <fullName>ChargeAmount__c</fullName>
    <label>Charge Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OBInvoiceItem__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>NetSuite InvItem External ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OBInvoiceItem__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>OBInvoice__c</referenceTo>
    <relationshipName>Invoice_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OBInvoiceItem__c/fields/InvoiceName__c.field-meta.xml
<CustomField>
    <fullName>InvoiceName__c</fullName>
    <label>Invoice Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OBInvoiceItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Invoice_Items_New</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OBInvoiceItem__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>16</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OBInvoiceItem__c/fields/SubscriptionLineItem__c.field-meta.xml
<CustomField>
    <fullName>SubscriptionLineItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription Line Item</label>
    <referenceTo>SubscriptionLineItem__c</referenceTo>
    <relationshipLabel>OB Invoice Items</relationshipLabel>
    <relationshipName>OB_Invoice_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LAC_ID__c.field-meta.xml
<CustomField>
    <fullName>LAC_ID__c</fullName>
    <description>Stakeholder: CDS, BI, MKT, Sales https://jira.orderbird.com/browse/CDS-138</description>
    <inlineHelpText>Enter the ID (3 digits) for relevant Lead Attribution Combo. Careful: entering wrong numbers is possible!</inlineHelpText>
    <label>LAC ID</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductBundle__c/ProductBundle__c.object-meta.xml
<CustomObject>
    <label>Product Bundle</label>
    <nameField>
        <label>Product Bundle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Bundles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ProductBundle__c.field-meta.xml
<CustomField>
    <fullName>ProductBundle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Bundle</label>
    <referenceTo>ProductBundle__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/SubscriptionLineItem__c.field-meta.xml
<CustomField>
    <fullName>SubscriptionLineItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription Line Item</label>
    <referenceTo>SubscriptionLineItem__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/SubscriptionLineItem__c.object-meta.xml
<CustomObject>
    <label>Subscription Line Item</label>
    <nameField>
        <label>Subscription Line Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SubscriptionLineItem__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>SubscriptionLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>Subscription_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>Subscription_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/fields/VAT_ref__c.field-meta.xml
<CustomField>
    <fullName>VAT_ref__c</fullName>
    <label>VAT Adjustment Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/PdfControllerTest.cls
@isTest(seeAllData=true)
public class PdfControllerTest {
	
    @isTest static void test1() {
        Pricebook2 pb = [SELECT Id FROM Pricebook2 WHERE IsStandard = true LIMIT 1];
        Account a = new Account(name='test');
        insert a;
        Opportunity o = new Opportunity(lac_id__c = '1',Pricebook2Id = pb.Id, Name='test', StageName='New', CloseDate=Date.today(), AccountId=a.Id, CurrencyIsoCode='EUR');
        insert o;
        Quote q = new Quote(OpportunityId=o.Id,Name='test',CurrencyIsoCode='EUR', Pricebook2Id = pb.Id);
        insert q;
        PricebookEntry pbe = [SELECT Id, Product2Id FROM PricebookEntry WHERE Pricebook2Id = :pb.Id AND CurrencyIsoCode='EUR' LIMIT 1];
        //ProductBundle__c pbun = [SELECT Id FROM ProductBundle__c LIMIT 1];
        ProductBundle__c pbun = new ProductBundle__c();
        insert new QuoteLineItem(QuoteId = q.Id,PricebookEntryId=pbe.Id, Quantity=1, UnitPrice=10, Product2Id=pbe.Product2Id, ProductBundle__c = pbun.Id);
        insert new QuoteLineItem(QuoteId = q.Id,PricebookEntryId=pbe.Id, Quantity=2, UnitPrice=8.25, Product2Id=pbe.Product2Id);
        QuotePdfController qpdf = new QuotePdfController();
        qpdf.qId = q.Id;
        
    }
    
    @isTest static void test2() {
        Account a = new Account(name='test');
        insert a;
        Pricebook2 pb = [SELECT Id FROM Pricebook2 WHERE IsStandard = true LIMIT 1];
        Invoice__c i = new Invoice__c(Account__c=a.Id,Name='test',CurrencyIsoCode='EUR');
        insert i;
        PricebookEntry pbe = [SELECT Id, Product2Id FROM PricebookEntry WHERE Pricebook2Id = :pb.Id  LIMIT 1];
        Subscription__c s = new Subscription__c(Account__c=a.Id, ZuoraId__c='test');
        insert s;
        SubscriptionLineItem__c sl = new SubscriptionLineItem__c(Subscription__c = s.Id, Product__c=pbe.Product2Id, ZuoraId__c='test_sli');
        insert sl;
        insert new InvoiceLineItem__c(Invoice__c = i.Id,SubscriptionLineItem__c=sl.Id, Quantity__c=1, ChargeAmount__c=0);
        insert new InvoiceLineItem__c(Invoice__c = i.Id,SubscriptionLineItem__c=sl.Id, Quantity__c=2, ChargeAmount__c=0);
        InvoicePdfController ipdf = new InvoicePdfController();
        ipdf.iId = i.Id;
        
    }
    
    @isTest static void test2vat() {
        Account a = new Account(name='test');
        insert a;
        Pricebook2 pb = [SELECT Id FROM Pricebook2 WHERE IsStandard = true LIMIT 1];
        Invoice__c i = new Invoice__c(Account__c=a.Id,Name='test',CurrencyIsoCode='EUR', ZuoraId__c ='inv');
        insert i;
        PricebookEntry pbe = [SELECT Id, Product2Id FROM PricebookEntry WHERE Pricebook2Id = :pb.Id  LIMIT 1];
        Subscription__c s = new Subscription__c(Account__c=a.Id, ZuoraId__c='test');
        insert s;
        SubscriptionLineItem__c sl = new SubscriptionLineItem__c(Subscription__c = s.Id, Product__c=pbe.Product2Id, ZuoraId__c='test_sli');
        insert sl;
        insert new InvoiceLineItem__c(Invoice__c = i.Id,SubscriptionLineItem__c=sl.Id, Quantity__c=1, ChargeAmount__c=0, ZuoraId__c = 'ili1');
        insert new InvoiceLineItem__c(Invoice__c = i.Id,SubscriptionLineItem__c=sl.Id, Quantity__c=2, ChargeAmount__c=0, ZuoraId__c = 'ili2');
        Invoice__c i2 = new Invoice__c(Account__c=a.Id,Name='test',CurrencyIsoCode='EUR');
        insert i2;
        Subscription__c s2 = new Subscription__c(Account__c=a.Id, ZuoraId__c='test2');
        insert s2;
        SubscriptionLineItem__c sl2 = new SubscriptionLineItem__c(Subscription__c = s.Id, Product__c=pbe.Product2Id, ZuoraId__c='test_sli2', vat_ref__c = 'inv|ili1;ili2');
        insert sl2;
        insert new InvoiceLineItem__c(Invoice__c = i2.Id,SubscriptionLineItem__c=sl2.Id, Quantity__c=1, ChargeAmount__c=10);
        insert new InvoiceLineItem__c(Invoice__c = i2.Id,SubscriptionLineItem__c=sl2.Id, Quantity__c=2, ChargeAmount__c=-10);
        InvoicePdfController ipdf = new InvoicePdfController();
        ipdf.iId = i2.Id;
        
    }
    
    @isTest static void test2ob() {
        Account a = new Account(name='test', CurrencyIsoCode = 'EUR');
        insert a;
        Pricebook2 pb = [SELECT Id FROM Pricebook2 WHERE IsStandard = true LIMIT 1];
        //OBInvoice__c i = new OBInvoice__c(Account__c=a.Id,Name='test',CurrencyIsoCode='EUR',ExternalId__c='123');
        //insert i;
        PricebookEntry pbe = [SELECT Id, Product2Id FROM PricebookEntry WHERE Pricebook2Id = :pb.Id  LIMIT 1];
        Subscription__c s = new Subscription__c(Account__c=a.Id, ZuoraId__c='test');
        insert s;
        SubscriptionLineItem__c sl = new SubscriptionLineItem__c(Subscription__c = s.Id, Product__c=pbe.Product2Id, ZuoraId__c='test_sli');
        insert sl;
        insert new OBInvoiceItem__c(InvoiceName__c = '123', SubscriptionLineItem__c=sl.Id, Quantity__c=1, ChargeAmount__c=0);
        insert new OBInvoiceItem__c(InvoiceName__c = '123', SubscriptionLineItem__c=sl.Id, Quantity__c=2, ChargeAmount__c=0);
        obInvoicePdfController ipdf = new obInvoicePdfController();
        ipdf.iId = [SELECT Id FROM ObInvoice__c LIMIT 1].Id;
        
    }
    
    @isTest static void test3() {
        Account a = new Account(name='test');
        insert a;
        AccountLightningController.updateAddressBuilder(a.Id, 'Shipping','test');
        AccountLightningController.updateAddressBuilder(a.Id, 'Billing','test');
        AccountLightningController.updateAddressBuilder(a.Id, 'Venue','test');
        String s = AccountLightningController.getAddressBuilder(a.Id, 'Shipping');
        s = AccountLightningController.getAddressBuilder(a.Id, 'Billing');
        s = AccountLightningController.getAddressBuilder(a.Id, 'Venue');
        s = AccountLightningController.getAccountContacts(a.Id);
        system.debug(json.serialize(AccountLightningController.getRelatedDocuments(a.Id)));
        AccountLightningController.RelatedDoc rd = new AccountLightningController.RelatedDoc('t','e','s','t',datetime.now());
    }
    
    @isTest static void test4() {
        AccountLightningController.getVATVerify('DE812639372');
        Account a = new Account(name='test');
        insert a;
        Contact c = new Contact(lastname='test',accountid=a.Id,email='test@test.com');
        insert c;
        a.SF_BillTo_Contact__c = c.id;
        update a;
        AccountLightningController.saveVAT(a.Id, true, '{"vatID":"test","name":"test","address":"at-3124 test"}');
        AccountLightningController.sendMyObRegistrationEmail(c.Id, 'German');
        MyObVenue__c v = new MyObVenue__c(Contact__c=c.Id);
        insert v;
        system.debug(AccountLightningController.matchContacts(v.Id));
        AccountLightningController.confirmObVenue(v.Id);
        system.debug(json.serialize(AccountLightningController.getObWarning(a.Id)));
        system.debug(AccountLightningController.matchContacts(v.Id));
    }
    
    @isTest static void test5() {
        system.debug(json.serialize(AccountLightningController.getMyObVenues('test')));
    }
}