force-app/main/default/objects/Account/fields/Target_Product__c.field-meta.xml
<CustomField>
    <fullName>Target_Product__c</fullName>
    <label>Target Product</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MyObVenue__c/MyObVenue__c.object-meta.xml
<CustomObject>
    <label>MyOb Venue</label>
    <nameField>
        <displayFormat>MyOb-{000000}</displayFormat>
        <label>MyOb Venue</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MyOb Venues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MyObVenue__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>MyOrderbird_Log_ons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MyObVenue__c/fields/MyOrderbirdId__c.field-meta.xml
<CustomField>
    <fullName>MyOrderbirdId__c</fullName>
    <externalId>true</externalId>
    <label>MyOrderbird Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/MyObVenue__c/fields/Target_Product__c.field-meta.xml
<CustomField>
    <fullName>Target_Product__c</fullName>
    <formula>Account__r.Target_Product__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Target Product</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MyObVenue__c/fields/TSE_Charges__c.field-meta.xml
<CustomField>
    <fullName>TSE_Charges__c</fullName>
    <label>TSE Charge(s)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MyObVenue__c/fields/TSE_Revoke__c.field-meta.xml
<CustomField>
    <fullName>TSE_Revoke__c</fullName>
    <label>TSE Revoke</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MyObVenue__c/fields/Wizard_Complete__c.field-meta.xml
<CustomField>
    <fullName>Wizard_Complete__c</fullName>
    <label>Wizard Complete</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OppCategory__c.field-meta.xml
<CustomField>
    <fullName>OppCategory__c</fullName>
    <description>https://jira.orderbird.com/browse/CDS-1827
This field is created to be used as a dependant picklist for the opportunity type.
It is a read only except for System admin</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Business</fullName>
            </value>
            <value>
                <fullName>Account Management</fullName>
            </value>
            <value>
                <fullName>MINI by orderbird</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_type_1__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_type_1__c</fullName>
    <description>AccM solution CDS-1831 and CDS-1827</description>
    <label>Sub-Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>OppCategory__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>New Business</fullName>
            </value>
            <value>
                <fullName>orderbird pay</fullName>
            </value>
            <value>
                <fullName>Compensation</fullName>
            </value>
            <value>
                <fullName>POS Add on products</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>Upselling</fullName>
            </value>
            <value>
                <fullName>pay onboarding</fullName>
            </value>
            <value>
                <fullName>METRO Cockpit</fullName>
            </value>
            <value>
                <fullName>MINI registration</fullName>
            </value>
            <value>
                <fullName>GM - Table Reservation</fullName>
            </value>
            <value>
                <fullName>GM - Ordering System</fullName>
            </value>
            <value>
                <fullName>GM - Bundle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/PaymentMethod__c.object-meta.xml
<CustomObject>
    <label>Payment Method</label>
    <nameField>
        <label>Payment Method Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentMethod__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payment Methods</relationshipLabel>
    <relationshipName>Payment_Methods</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <externalId>true</externalId>
    <label>Key</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <externalId>true</externalId>
    <label>Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/EffectiveStartDate__c.field-meta.xml
<CustomField>
    <fullName>EffectiveStartDate__c</fullName>
    <label>Effective Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Price_EUR__c.field-meta.xml
<CustomField>
    <fullName>Price_EUR__c</fullName>
    <label>Price (EUR)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Quote/fields/InvoiceOwner__c.field-meta.xml
<CustomField>
    <fullName>InvoiceOwner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Alternate Invoice Owner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoice Owner Quotes</relationshipLabel>
    <relationshipName>InvoiceOwnerQuotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/SubscriptionLineItem__c.field-meta.xml
<CustomField>
    <fullName>SubscriptionLineItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription Line Item</label>
    <referenceTo>SubscriptionLineItem__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/InvoiceOwner__c.field-meta.xml
<CustomField>
    <fullName>InvoiceOwner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Owner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions (Invoice Owner)</relationshipLabel>
    <relationshipName>InvOwnSubscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/TermType__c.field-meta.xml
<CustomField>
    <fullName>TermType__c</fullName>
    <label>Term Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/SubscriptionLineItem__c.object-meta.xml
<CustomObject>
    <label>Subscription Line Item</label>
    <nameField>
        <label>Subscription Line Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SubscriptionLineItem__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>SubscriptionLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/fields/EffectiveStartDate__c.field-meta.xml
<CustomField>
    <fullName>EffectiveStartDate__c</fullName>
    <label>Effective Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/fields/ESD_Matches_SubTSD__c.field-meta.xml
<CustomField>
    <fullName>ESD_Matches_SubTSD__c</fullName>
    <formula>MONTH(EffectiveStartDate__c) = MONTH(Subscription__r.TermStartDate__c)
&amp;&amp;
DAY(EffectiveStartDate__c) = DAY(Subscription__r.TermStartDate__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ESD Matches SubTSD</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/fields/IsCurrent__c.field-meta.xml
<CustomField>
    <fullName>IsCurrent__c</fullName>
    <formula>CASE(
	Subscription__r.Status__c,
	&quot;Active&quot;,
	IF(
		(
			PrecedingSLI__r.Quantity__c &lt;&gt; Quantity__c
			|| PrecedingSLI__r.Price__c &lt;&gt; Price__c
		) &amp;&amp; PrecedingSLI__r.Subscription__r.AmendmentEffectiveDate__c &gt; TODAY(),
		0,
		IF(
			NOT(CONTAINS(Product__r.Name, &apos;TSE&apos;)) &amp;&amp; (
			EffectiveStartDate__c &gt; TODAY() || (
				ISBLANK(PrecedingSLI__c) &amp;&amp; Subscription__r.PrecedingSubscription__r.AmendmentEffectiveDate__c &gt; TODAY()
			)),
			0,
			IF(
				Subscription__r.TermType__c == &quot;TERMED&quot; &amp;&amp; 
				Subscription__r.TermEndDate__c &lt; TODAY(), 
				0, 
				1
			)
		)
	),
	&quot;Expired&quot;,
	IF(
		(
			SupercedingSLI__r.Quantity__c &lt;&gt; Quantity__c
			|| SupercedingSLI__r.Price__c &lt;&gt; Price__c
		) &amp;&amp; Subscription__r.AmendmentEffectiveDate__c &gt; TODAY(),
		1,
		IF(
			ISBLANK(SupercedingSLI__c) &amp;&amp; Subscription__r.AmendmentEffectiveDate__c &gt; TODAY(),
			1,
			0
		)
	),
	IF(
		EffectiveStartDate__c &lt;= TODAY() &amp;&amp; EffectiveEndDate__c &gt;= TODAY(),
		1,
		0
	)
) == 1</formula>
    <label>Is Current</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>Subscription_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>Subscription__r.Status__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/fields/Status_Active_Service__c.field-meta.xml
<CustomField>
    <fullName>Status_Active_Service__c</fullName>
    <formula>IF(
IsCurrent__c
&amp;&amp;
NOT(CONTAINS(Product__r.Name,&quot;subsidy&quot;))
&amp;&amp; (
 Product__r.ProductCategory__r.ProductType__c  = &quot;POS Service&quot;
||
 Product__r.ProductCategory__r.ProductType__c  = &quot;POS Service+Device&quot;
),1,0)</formula>
    <label>Status Active Service</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>Subscription_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/TSE_Settings__c/TSE_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>TSE Settings</label>
</CustomObject>

force-app/main/default/objects/TSE_Settings__c/fields/SubscriptionStartDate__c.field-meta.xml
<CustomField>
    <fullName>SubscriptionStartDate__c</fullName>
    <label>Subscription Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/TSESubscribeBatch.cls
global class TSESubscribeBatch implements Schedulable {
    
    global static Integer DaysToRenewalCutoff = 31;
    global static Boolean DoProrate = false;
    global static TSE_Settings__c Settings = TSE_Settings__c.getInstance([SELECT Id FROM Profile where Name = 'System Administrator' LIMIT 1].Id);
    global static Date SubStartDefault = Settings.SubscriptionStartDate__c == null ? Date.today() : Settings.SubscriptionStartDate__c;
    
    global void execute(SchedulableContext sc) {
        doTSESub();
    }
    
    @future(callout=true)
    global static void doTSESub() {
        try {
            MyObVenue__c venue = [
                SELECT Id, Account__c, Account__r.CurrencyIsoCode, Account__r.ZuoraId__c, TSE_Charges__c, MyOrderbirdId__c, Wizard_Complete__c
                FROM MyObVenue__c 
                WHERE Wizard_Complete__c >= :Date.newInstance(2020,7,29) AND TSE_Revoke__c = null AND TSE_Charges__c = null AND Account__r.Target_Product__c != 'MINI'
                ORDER BY Wizard_Complete__c
                LIMIT 1
            ];
            
            Date SubStart = (venue.Wizard_Complete__c < DateTime.newInstance(2020,5,11) || venue.Wizard_Complete__c > DateTime.newInstance(2020,7,28)) ? Date.newInstance(venue.Wizard_Complete__c.year(), venue.Wizard_Complete__c.month(), venue.Wizard_Complete__c.day()) : SubStartDefault;
                
            List<String> LinkedCharges = new List<String>();
            
            String AccountId = venue.Account__c;
            String AccountCurr = venue.Account__r.CurrencyIsoCode;
            List<MyObVenue__c> OtherVenues = [SELECT Id, TSE_Charges__c FROM MyObVenue__c WHERE Account__c = :AccountId AND TSE_Charges__c != null];
            for (MyObVenue__c OtherVenue : OtherVenues) {
                LinkedCharges.addAll(OtherVenue.TSE_Charges__c.split(','));
            }
            if ( (!LinkedCharges.contains('NEED') && !LinkedCharges.contains('ERROR')) || venue.Account__r.ZuoraId__c == null ) {
                
                List<SubscriptionLineItem__c> UnlinkedCharges = [
                    SELECT Id, Name 
                    FROM SubscriptionLineItem__c 
                    WHERE Name NOT IN :LinkedCharges 
                    AND Subscription__r.Account__c = :AccountId
                    AND Product__r.Name LIKE '%tse%' 
                    AND (NOT Product__r.Name LIKE '%discount%') 
                    AND IsCurrent__C = TRUE
                ];
                
                if (UnlinkedCharges.size() > 0) {
                    venue.TSE_Charges__c = UnlinkedCharges[0].Name;
                } else {
                    
                    List<SubscriptionLineItem__c> ServiceLicenses = [
                        SELECT Id, ESD_Matches_SubTSD__c, EffectiveStartDate__c, Subscription__r.Account__c, Subscription__r.Account__r.CurrencyIsoCode, Subscription__r.InvoiceOwner__c,
                        Subscription__r.TermType__c, Subscription__r.Status__c, Subscription__r.ZuoraId__c, Subscription__r.Account__r.ZuoraId__c
                        FROM SubscriptionLineItem__c 
                        WHERE Status_Active_Service__c = 1 
                        AND Product__r.Model__C in ('perunit', 'flatfee') 
                        AND Subscription__r.Account__c = :AccountId
                        ORDER BY Product__r.Price_EUR__c DESC, EffectiveStartDate__c
                    ];
                    
                    String tsec;
                    if ((!DoProrate || Test.isRunningTest()) && ServiceLicenses.size() == 0) { tsec = SimpleNoProrate(AccountId, AccountCurr, SubStart); } else {
                        if (ServiceLicenses[0].ESD_Matches_SubTSD__c){ tsec = SimpleProrate(ServiceLicenses[0], SubStart); } else { tsec = ComplexProrate(ServiceLicenses[0], SubStart); }
                    }
                    venue.TSE_Charges__c = tsec;
                    
                }
                
            } else { venue.TSE_Charges__c = 'ERROR'; }
            update venue;
        } catch(exception e) {system.debug(e.getMessage());}
    }
    
    public static Boolean IsRenewalDateTooSoon(Date d, Date SubStart) {
        return SubStart.daysBetween(RenewalDate(d, SubStart)) < DaysToRenewalCutoff;
    }
    
    public static Date RenewalDate(Date d, Date SubStart) {
        Date RenewalDate = Date.newInstance(SubStart.year()-1, d.month(), d.day());
        while (RenewalDate < SubStart) { RenewalDate = Date.newInstance(RenewalDate.year()+1, d.month(), d.day()); }
        return RenewalDate;
    }
    
    public static String SimpleNoProrate(Id AccountId, String AccountCurr, Date SubStart) { //simple without proration
        list<PricebookEntry> pbes = [SELECT Id, key__c, Name, Pricebook2Id, Product2Id, CurrencyIsoCode, UnitPrice, IsActive, UseStandardPrice FROM PricebookEntry];
        map<string, PricebookEntry> pbeMap = new map<string, PricebookEntry>();
        for (PricebookEntry pbe : pbes) { pbeMap.put(pbe.key__c, pbe); }
        Opportunity newOpp = new Opportunity(CurrencyIsoCode=AccountCurr,AccountId=AccountId,name='TSE Autosubscribe',stagename='Potential',closedate=date.today().addDays(14),oppcategory__c='Account Management',opportunity_type_1__c='TSE Auto-subscribe'); 
        insert newOpp;
        Quote newQuote = new Quote(
            name='TSE Auto-subscribe Quote',
            Pricebook2Id = [SELECT Id From Pricebook2 WHERE Key__c = 'Main' LIMIT 1].Id,
            Tax = 0,
            AutoAcceptPriority__c = 50,
            ContractEffectiveDate__c = SubStart,
            InvoiceDate__c = SubStart,
            InvoiceTargetDate__c = Date.today(),
            POS_Start_Date__c = SubStart,
            ExpirationDate = date.today().addDays(30),
            Pay_by_Instalment__c = false,
            PaymentMethod__c = 'Bank Transfer',
            WireFirstPayment__c = false,
            PayPalLink__c = false,
            InvoiceOwner__c = AccountId,
            Contains_Recurring_Items__c = true,
            CurrencyIsoCode = AccountCurr,
            opportunityid = newOpp.id
        );
        insert newQuote;
        List<Product2> prods = [SELECT Id, ZuoraId__c FROM Product2 WHERE UniqueSysRef__c IN ('TSE', 'TSE_fee')];
        for (Product2 prod : prods) {
            insert new QuoteLineItem(
                QuoteId = newQuote.Id,
                Product2Id = prod.Id,
                Quantity = 1,
                PricebookEntryId = pbeMap.get(AccountCurr + ':' + prod.ZuoraId__c).Id,
                UnitPrice = pbeMap.get(AccountCurr + ':' + prod.ZuoraId__c).UnitPrice
            );
        }
        return 'NEED';
    }
    
    public static String SimpleProrate(SubscriptionLineItem__c SLI, Date SubStart) { //simple with proration
        if (IsRenewalDateTooSoon(SLI.EffectiveStartDate__c, SubStart)) { return ComplexProrate(SLI, SubStart); } else { return PerformSP(SLI, SubStart); }
    }

    public static String ComplexProrate(SubscriptionLineItem__c SLI, Date SubStart) { //complicated proration
        if (EvalSub(SLI)) { return ExecCP(SLI, SubStart); } return SimpleNoProrate(SLI.Subscription__r.Account__c, SLI.Subscription__r.Account__r.CurrencyIsoCode, SubStart);
    }

    public static String PerformSP(SubscriptionLineItem__c SLI, Date SubStart) {
        if (EvalSub(SLI)) { return ExecSP(SLI, SubStart); } return SimpleNoProrate(SLI.Subscription__r.Account__c, SLI.Subscription__r.Account__r.CurrencyIsoCode, SubStart);
    }
    
    public static Boolean EvalSub(SubscriptionLineItem__c SLI) {
        return (SLI.Subscription__r.TermType__c == 'Evergreen' && SLI.Subscription__r.Status__c == 'Active' && SLI.Subscription__r.Account__c == SLI.Subscription__r.InvoiceOwner__c);
    }
    
    public static String ExecSP(SubscriptionLineItem__c SLI, Date SubStart) {
        if (ZuoraSyncController.BillSimpleTSE(SubStart, SLI.Subscription__r.ZuoraId__c, SLI.Subscription__r.Account__r.ZuoraId__c)) { return 'NEED'; } else { return SimpleNoProrate(SLI.Subscription__r.Account__c, SLI.Subscription__r.Account__r.CurrencyIsoCode, SubStart); }
    }
    
    public static String ExecCP(SubscriptionLineItem__c SLI, Date SubStart	) {
        if (ZuoraSyncController.BillComplexTSE(SubStart, SLI.Subscription__r.ZuoraId__c, SLI.Subscription__r.Account__r.ZuoraId__c, RenewalDate(SLI.EffectiveStartDate__c, SubStart), IsRenewalDateTooSoon(SLI.EffectiveStartDate__c, SubStart))) { return 'NEED'; } else { return SimpleNoProrate(SLI.Subscription__r.Account__c, SLI.Subscription__r.Account__r.CurrencyIsoCode, SubStart); }
    }
        
}