force-app/main/default/objects/Account/fields/Target_Product__c.field-meta.xml
<CustomField>
    <fullName>Target_Product__c</fullName>
    <label>Target Product</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>2.0</description>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>Zuora Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/InvoiceLineItem__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>ILI-{0000000}</displayFormat>
        <label>Invoice Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceLineItem__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/fields/ServiceStartDate__c.field-meta.xml
<CustomField>
    <fullName>ServiceStartDate__c</fullName>
    <label>Service Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/fields/SubscriptionLineItem__c.field-meta.xml
<CustomField>
    <fullName>SubscriptionLineItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription Line Item</label>
    <referenceTo>SubscriptionLineItem__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/MyObVenue__c/MyObVenue__c.object-meta.xml
<CustomObject>
    <label>MyOb Venue</label>
    <nameField>
        <displayFormat>MyOb-{000000}</displayFormat>
        <label>MyOb Venue</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MyOb Venues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MyObVenue__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>MyOrderbird_Log_ons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MyObVenue__c/fields/ChurnPrediction__c.field-meta.xml
<CustomField>
    <fullName>ChurnPrediction__c</fullName>
    <label>Churn Prediction</label>
    <precision>18</precision>
    <scale>17</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MyObVenue__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>MyOrderbird_Log_ons</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/MyObVenue__c/fields/LastOpenShiftTimestamp__c.field-meta.xml
<CustomField>
    <fullName>LastOpenShiftTimestamp__c</fullName>
    <label>Last Open Shift Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MyObVenue__c/fields/Target_Product__c.field-meta.xml
<CustomField>
    <fullName>Target_Product__c</fullName>
    <formula>Account__r.Target_Product__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Target Product</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <externalId>true</externalId>
    <label>Key</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <externalId>true</externalId>
    <label>Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/DownshiftsTo__c.field-meta.xml
<CustomField>
    <fullName>DownshiftsTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Downshifts To</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Products (Downshifts To)</relationshipLabel>
    <relationshipName>DSProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Refund__c/Refund__c.object-meta.xml
<CustomObject>
    <label>Refund</label>
    <nameField>
        <label>Refund Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Refunds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/SubscriptionLineItem__c.object-meta.xml
<CustomObject>
    <label>Subscription Line Item</label>
    <nameField>
        <label>Subscription Line Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SubscriptionLineItem__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>SubscriptionLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>Subscription_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>Subscription__r.Status__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>Subscription_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/FailedPaymentBatch_test.cls
@isTest(seeAllData=true) public class FailedPaymentBatch_test {

    static TestMethod void test1() {
        Account a = new Account(name='isRunning Test Account');
        insert a;
        Refund__c ref = new Refund__c(name='test',account__c=a.id,zuoraid__c='test');
        insert ref;
        database.executeBatch(new FailedPaymentBatch());
    }

	static TestMethod void test2() {
        Account a = new Account(name='isRunning Test Account', Target_Product__c='MINI');
        insert a;
        Refund__c ref = new Refund__c(name='test',account__c=a.id,zuoraid__c='test');
        insert ref;
        database.executeBatch(new FailedPaymentBatch());
    }

    static TestMethod void test3() {
        Account a = new Account(name='isRunning Test Account',currencyisocode='EUR');
        insert a;
        Contact c = new Contact(lastname='test', email='test@test.com', accountid=a.id);
        insert c;
        MyObVenue__c v = new MyObVenue__c(Contact__c=c.Id,LastOpenShiftTimestamp__c=datetime.now(),ChurnPrediction__c=0.9);
        insert v;
        Refund__c ref = new Refund__c(name='test',account__c=a.id,zuoraid__c='test');
        insert ref;
        Product2 p1 = new Product2(name='test1',ZuoraId__c='test1');
        insert p1;
        Product2 p = new Product2(name='test',downshiftsto__c=p1.id,ZuoraId__c='test');
        insert p;
        Id Pricebook2Id = [SELECT Id From Pricebook2 WHERE Key__c = 'Main' LIMIT 1].Id;
        PriceBookEntry pbe1 = new PriceBookEntry(Pricebook2Id=Pricebook2Id,Key__c='EUR:test1',UnitPrice=12.34,Product2Id=p1.Id,IsActive=true);
        insert pbe1;
        PriceBookEntry pbe = new PriceBookEntry(Pricebook2Id=Pricebook2Id,Key__c='EUR:test',UnitPrice=12.34,Product2Id=p.Id,IsActive=true);
        insert pbe;
        Subscription__c sub = new Subscription__c(Account__c=a.Id,ZuoraId__c='test',Status__c='Active');
        insert sub;
        SubscriptionLineItem__c sli = new SubscriptionLineItem__c(name='test',Subscription__c=sub.Id,Product__c=p.Id,ZuoraId__c='test');
        insert sli;
        Invoice__c inv = new Invoice__c(name='test',account__c=a.id,zuoraid__c='test',amount__c=12.34,balance__c=12.34);
        insert inv;
        InvoiceLineItem__c ili = new InvoiceLineItem__c(Invoice__c=inv.id, ServiceStartDate__c = date.today().addDays(-10),ZuoraId__c='test',subscriptionlineitem__c=sli.id);
        insert ili;
        database.executeBatch(new FailedPaymentBatch());
    }
    
    static TestMethod void test4() {
        system.schedule('jobName', '0 0 0 * * ?', new FailedPaymentBatch_Scheduler());
    }
}