force-app/main/default/objects/Account/fields/Tax_Exempt_Status_formula__c.field-meta.xml
<CustomField>
    <fullName>Tax_Exempt_Status_formula__c</fullName>
    <formula>IF(ISPICKVAL(Tax_Exempt_Reason__c,&quot;&quot;),&quot;Pending&quot;,IF(ISPICKVAL(Tax_Exempt_Reason__c,&quot;Non Tax Exempt&quot;),&quot;No&quot;,&quot;Yes&quot;))</formula>
    <inlineHelpText>This field is not editable. Please select the Tax Exempt Reason to set the Tax Exempt Status.</inlineHelpText>
    <label>Tax Exempt Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/VATNumber__c.field-meta.xml
<CustomField>
    <fullName>VATNumber__c</fullName>
    <description>Stakeholder: Finance</description>
    <inlineHelpText>What is the venues value added tax (VAT)  number of this venue? Filled in by Sales. Required for most non-German EU customers</inlineHelpText>
    <label>VAT Number (Raw)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/VATNumber_disp__c.field-meta.xml
<CustomField>
    <fullName>VATNumber_disp__c</fullName>
    <formula>IF( NOT( CONTAINS(VATNumber__c, &quot;null&quot;) ), VATNumber__c, null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>VAT Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/VATNumberVerify.cls
public class VATNumberVerify implements Database.Batchable<sObject>{
  
    public final String Query;
    public List<SObject> AcctUpdt;
	public map <Id,SObject> m1;
    
    public VATNumberVerify(){
        Query = 'SELECT Id, vatnumber_disp__c, vatnumber__c ' 
            + 'FROM Account ' 
            + 'WHERE'
            + ' vatnumber_disp__c != null'
            //+ ' createddate =< today' 
            + ' AND (NOT vatnumber_disp__c like \'%NULL%\')' 
            + ' AND Tax_Exempt_Status_formula__c=\'Yes\' ';
            //+ 'LIMIT 10';
    }

    public Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(Query);
    }

    public void execute(Database.BatchableContext BC, List<sObject> scope){
        Integer getVATVerify;
        AcctUpdt = new List <SObject>();
        for(sobject s : scope){
            AcctUpdt.add(s);
            //AcctUpdt.add((Account)s.getSobject('Account__r'));
            String VATNumber = (String)s.get('vatnumber__c');
            //getVATVerify = VIES.isValidVATID(VATNumber);
            //s.put('VATId_Status__c', getVATVerify);
        }
        system.debug(AcctUpdt.size());
        m1 = new Map<Id, SObject>(AcctUpdt);
        system.debug(m1.size()+' *map size');
        
        //update scope;
    }  

    public void finish(Database.BatchableContext BC){
    	
    }
}