force-app/main/default/objects/Account/fields/Venue__c.field-meta.xml
<CustomField>
    <fullName>Venue__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Venue</label>
    <referenceTo>MyObVenue__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MyObVenue__c/MyObVenue__c.object-meta.xml
<CustomObject>
    <label>MyOb Venue</label>
    <nameField>
        <displayFormat>MyOb-{000000}</displayFormat>
        <label>MyOb Venue</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MyOb Venues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MyObVenue__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>MyOrderbird_Log_ons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MyObVenue__c/fields/AssignmentFlag__c.field-meta.xml
<CustomField>
    <fullName>AssignmentFlag__c</fullName>
    <formula>(
ISBLANK(Account__r.Venue__c)
||
AssignmentSort__c &gt; Account__r.Venue__r.AssignmentSort__c
)</formula>
    <label>Assignment Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MyObVenue__c/fields/AssignmentSort__c.field-meta.xml
<CustomField>
    <fullName>AssignmentSort__c</fullName>
    <formula>IF( Inactive__c || ISBLANK( MyOrderbirdId__c ) ,0, 

IF(ISBLANK(Days_Since_Last_Shift_Open__c), 
(CreatedDate - DATETIMEVALUE( &quot;1970-01-01 00:00:00&quot; )),
1000000 + IF (Days_Since_Last_Shift_Open__c = 0, 1000001, 1000000/Days_Since_Last_Shift_Open__c))
)</formula>
    <label>Assignment Sort</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/VenueAssignment.cls
global class VenueAssignment implements Database.Batchable<sObject>{
    
    global final String Query;
    
    global VenueAssignment() {
        Query = 'SELECT Id, Venue__c, (SELECT Id FROM MyOrderbird_Log_ons__r ORDER BY AssignmentSort__c DESC LIMIT 1) FROM Account WHERE Id IN (SELECT Account__c FROM MyObVenue__c WHERE AssignmentFlag__c = TRUE)';
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope){
        for (sObject s : scope) {
            s.put('Venue__c', ((List<MyObVenue__c>)s.getSObjects('MyOrderbird_Log_ons__r'))[0].Id);
        }
        update scope;
    }
    
    global void finish(Database.BatchableContext BC){
    }
    
}