force-app/main/default/objects/Account/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <label>Payment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/NeedsAttention__c.field-meta.xml
<CustomField>
    <fullName>NeedsAttention__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Needs Attention</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SubmitPaymentGateway_test.cls
@isTest public class SubmitPaymentGateway_test {

    static TestMethod void test() {
        Account a = new Account(name='test');
        insert a;
        insert new Payment__c(NeedsAttention__c = true, ZuoraId__c = 'abc', Account__c = a.Id);
        String jobId = System.schedule('test', '0 0 0 3 9 ? 2022', new SubmitPaymentGateway_sched());
    }
    
    static TestMethod void test2() {
        Account a = new Account(name='test');
        insert a;
        insert new Payment__c(NeedsAttention__c = true, ZuoraId__c = 'abc', Account__c = a.Id);
        SubmitPaymentGateway.SubmitPayment();
    }
}