force-app/main/default/objects/Account/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>2.0</description>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/SuppressTriggeredEmail__c.field-meta.xml
<CustomField>
    <fullName>SuppressTriggeredEmail__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Suppress Triggered Email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>Zuora Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/InvoiceLineItem__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>ILI-{0000000}</displayFormat>
        <label>Invoice Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceLineItem__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/fields/SubscriptionLineItem__c.field-meta.xml
<CustomField>
    <fullName>SubscriptionLineItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription Line Item</label>
    <referenceTo>SubscriptionLineItem__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/InvoicePayment__c/InvoicePayment__c.object-meta.xml
<CustomObject>
    <label>Invoice Payment</label>
    <nameField>
        <displayFormat>InvPmt-{000000}</displayFormat>
        <label>Invoice Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoicePayment__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Payments</relationshipLabel>
    <relationshipName>Invoice_Payments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoicePayment__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <label>Payment</label>
    <referenceTo>Payment__c</referenceTo>
    <relationshipLabel>Invoice Payments</relationshipLabel>
    <relationshipName>Invoice_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoiceRefund__c/InvoiceRefund__c.object-meta.xml
<CustomObject>
    <label>Invoice Refund</label>
    <nameField>
        <displayFormat>InvRef-{000000}</displayFormat>
        <label>Invoice Refund Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Refunds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceRefund__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Refunds</relationshipLabel>
    <relationshipName>Invoice_Refunds</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoiceRefund__c/fields/Refund__c.field-meta.xml
<CustomField>
    <fullName>Refund__c</fullName>
    <label>Refund</label>
    <referenceTo>Refund__c</referenceTo>
    <relationshipLabel>Invoice Refunds</relationshipLabel>
    <relationshipName>Invoice_Refunds</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoiceRefund__c/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LAC_Shorthand__c.field-meta.xml
<CustomField>
    <fullName>LAC_Shorthand__c</fullName>
    <description>Stakeholder: CDS, BI, MKT, Sales https://jira.orderbird.com/browse/CDS-138</description>
    <inlineHelpText>Select the relevant Lead Attribution Combo. If it is not on the list use the field LAC ID</inlineHelpText>
    <label>LAC Shorthand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LAC_Shorthands</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/PaymentMethod__c.object-meta.xml
<CustomObject>
    <label>Payment Method</label>
    <nameField>
        <label>Payment Method Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentMethod__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payment Methods</relationshipLabel>
    <relationshipName>Payment_Methods</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/BankTransferAccountNumberMask__c.field-meta.xml
<CustomField>
    <fullName>BankTransferAccountNumberMask__c</fullName>
    <label>Bank Transfer Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <externalId>true</externalId>
    <label>Key</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <externalId>true</externalId>
    <label>Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Quote/fields/PaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethod__c</fullName>
    <inlineHelpText>How is the customer going to pay recurring fees? Bank transfer (orderbird charges, SEPA Mandate / Direct Debit) or Wire transfer (customer wires money)?</inlineHelpText>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bank Transfer</fullName>
                <default>true</default>
                <label>Bank Transfer</label>
            </value>
            <value>
                <fullName>Wire Transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/SubscriptionLineItem__c.field-meta.xml
<CustomField>
    <fullName>SubscriptionLineItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription Line Item</label>
    <referenceTo>SubscriptionLineItem__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Refund__c/Refund__c.object-meta.xml
<CustomObject>
    <label>Refund</label>
    <nameField>
        <label>Refund Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Refunds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Refund__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>Payment__c</referenceTo>
    <relationshipLabel>Refunds</relationshipLabel>
    <relationshipName>Refunds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SLIMap__c/SLIMap__c.object-meta.xml
<CustomObject>
    <label>SLI Mapping</label>
    <nameField>
        <displayFormat>SLIM-{000000}</displayFormat>
        <label>SLI Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SLI Map</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SLIMap__c/fields/RatePlanId__c.field-meta.xml
<CustomField>
    <fullName>RatePlanId__c</fullName>
    <externalId>true</externalId>
    <label>RatePlanId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/SubscriptionLineItem__c.object-meta.xml
<CustomObject>
    <label>Subscription Line Item</label>
    <nameField>
        <label>Subscription Line Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SubscriptionLineItem__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>SubscriptionLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>Subscription__r.Status__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>Subscription_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/globalValueSets/LAC_Shorthands.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Walk-In</fullName>
    </customValue>
    <customValue>
        <fullName>Hotline</fullName>
    </customValue>
    <customValue>
        <fullName>Personal Network</fullName>
    </customValue>
    <customValue>
        <fullName>E-mail</fullName>
    </customValue>
    <customValue>
        <fullName>CRC - Referral of successor</fullName>
    </customValue>
    <customValue>
        <fullName>CRC - E-mail</fullName>
    </customValue>
    <customValue>
        <fullName>CRC - Hotline</fullName>
    </customValue>
    <customValue>
        <fullName>CRC - Webform</fullName>
    </customValue>
    <customValue>
        <fullName>Referral by Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Research - Public Register</fullName>
    </customValue>
    <customValue>
        <fullName>Research - Other</fullName>
    </customValue>
    <customValue>
        <fullName>Chat</fullName>
    </customValue>
    <customValue>
        <fullName>Facebook</fullName>
    </customValue>
    <customValue>
        <fullName>Twitter</fullName>
    </customValue>
    <customValue>
        <fullName>Instagram</fullName>
    </customValue>
    <customValue>
        <fullName>Kassensystemevergleich.de</fullName>
    </customValue>
    <customValue>
        <fullName>Kassen-Vergleich.com</fullName>
    </customValue>
    <customValue>
        <fullName>Companeo</fullName>
    </customValue>
    <customValue>
        <fullName>Facebook Scraper</fullName>
    </customValue>
    <customValue>
        <fullName>Toques de restauration</fullName>
    </customValue>
    <customValue>
        <fullName>Chardasso</fullName>
    </customValue>
    <customValue>
        <fullName>Trade Register Scraper</fullName>
    </customValue>
    <customValue>
        <fullName>TradingTwins</fullName>
    </customValue>
    <customValue>
        <fullName>Outbound Texting</fullName>
    </customValue>
    <customValue>
        <fullName>my.ob Reg</fullName>
    </customValue>
    <customValue>
        <fullName>Neugeschaeft</fullName>
    </customValue>
    <customValue>
        <fullName>ETL-Print</fullName>
    </customValue>
    <customValue>
        <fullName>Cold Call</fullName>
    </customValue>
    <customValue>
        <fullName>Preorder</fullName>
    </customValue>
    <customValue>
        <fullName>Postcard 2020</fullName>
        <isActive>false</isActive>
        <label>Postcard 2020</label>
    </customValue>
    <description>For the convenient use of Lead Attributes: Users can use Keywords instead of IDs</description>
    <masterLabel>LAC Shorthands</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ZuoraSyncController_Test.cls
@isTest
public class ZuoraSyncController_Test {

    @isTest static void test1() {
        Id pricebookId = Test.getStandardPricebookId();
        update new Pricebook2(id=pricebookId, key__c='main',isactive=true);
        ZuoraSyncController.UpsertCatalog(ZuoraSyncController.FetchCatalog());
        //ZuoraSyncController.syncCatalog();
        //ZuoraSyncController.syncCatalog();
        system.debug(JSON.serialize(new ZuoraSyncController.QueryCBAsRequest()));
        system.debug(JSON.serialize(new ZuoraSyncController.QueryCBAsRequest(Date.today())));
        ZObj.FetchCBA f = new ZObj.FetchCBA();
        f.AccountId = '';
        f.AdjustmentDate = Date.today();
        f.Amount = 0;
        f.CancelledOn = Date.today();
        f.Comment = '';
        f.Id = '';
        f.NumberX = '';
        f.SourceTransactionId = '';
        f.SourceTransactionNumber = '';
        f.SourceTransactionType = '';
        f.Status = '';
        f.Type = '';
        ZObj.FetchCBAs fc = new ZObj.FetchCBAs();
        fc.queryLocator = '';
        fc.done = true;
        fc.records = new List<ZObj.FetchCBA>{ f };
    }

    @isTest static void test2() {
        Id pricebookId = Test.getStandardPricebookId();
        update new Pricebook2(id=pricebookId, key__c='main',isactive=true);
        ZuoraSyncController.UpsertCatalog(ZuoraSyncController.FetchCatalog());
        //ZuoraSyncController.syncCatalog();
        Account a = new Account(name='test');
        insert a;
        Opportunity o = new Opportunity(accountid = a.Id, name='test', stagename='new', closedate=date.today(), lac_shorthand__c = 'Walk-In');
        insert o;
        Id pbId = Test.getStandardPricebookId();
        Quote q = new Quote(name='test',opportunityid=o.id, pricebook2Id = pbId);
        insert q;
        Product2 p = [SELECT Id FROM Product2 LIMIT 1];
        PricebookEntry pbe = [SELECT Id FROM PricebookEntry WHERE Pricebook2Id = :pbId and Product2Id = :p.Id LIMIT 1];
        QuoteLineItem qli = new QuoteLineItem(QuoteId = q.Id, Product2Id = p.Id, Quantity = 1, UnitPrice = 1, PricebookEntryId = pbe.Id);
        insert qli;
        String preview = ZuoraSyncController.PreviewAmendment(q.Id);
        ZuoraSyncController.BillSimpleTSE(date.today(), 'test','test');
        ZuoraSyncController.BillComplexTSE(date.today(), 'test','test', Date.today().addMonths(6), false);
        ZuoraSyncController.BillComplexTSE(date.today(), 'test','test', Date.today().addMonths(6), true);
    }
    
    @isTest static void test2b() {
        Id pricebookId = Test.getStandardPricebookId();
        update new Pricebook2(id=pricebookId, key__c='main',isactive=true);
        ZuoraSyncController.UpsertCatalog(ZuoraSyncController.FetchCatalog());
        //ZuoraSyncController.syncCatalog();
        Account a = new Account(name='test');
        insert a;
        Opportunity o = new Opportunity(accountid = a.Id, name='test', stagename='new', closedate=date.today(), lac_shorthand__c = 'Walk-In');
        insert o;
        Id pbId = Test.getStandardPricebookId();
        Quote q = new Quote(name='test',opportunityid=o.id, pricebook2Id = pbId);
        insert q;
        Product2 p = [SELECT Id FROM Product2 LIMIT 1];
        PricebookEntry pbe = [SELECT Id FROM PricebookEntry WHERE Pricebook2Id = :pbId and Product2Id = :p.Id LIMIT 1];
        QuoteLineItem qli = new QuoteLineItem(QuoteId = q.Id, Product2Id = p.Id, Quantity = 1, UnitPrice = 1, PricebookEntryId = pbe.Id);
        insert qli;
        String preview = ZuoraSyncController.PreviewAmendment(q.Id);
        ZuoraSyncController.ProcessQuote(q.Id);
        Opportunity o2 = new Opportunity(accountid = a.Id, name='test2', stagename='new', closedate=date.today(), lac_shorthand__c = 'Walk-In');
        insert o2;
        Quote q2 = new Quote(name='test2',opportunityid=o2.id, pricebook2id = pbId);
        insert q2;
        QuoteLineItem qli2 = new QuoteLineItem(QuoteId = q2.Id, Product2Id = p.Id, Quantity = 3, UnitPrice = 1, PricebookEntryId = pbe.Id);
        QuoteLineItem qli3 = new QuoteLineItem(QuoteId = q2.Id, Product2Id = p.Id, Quantity = -1, UnitPrice = 1, PricebookEntryId = pbe.Id);
        insert qli2;
        insert qli3;
        ZuoraSyncController.ProcessQuote(q2.Id);
        String cancel = ZuoraSyncController.CancelSubscriptions('["test"]',null);
        ZObj.CreatePreviewReq cpr = new ZObj.CreatePreviewReq(q.Id);
    }
    
    @isTest static void test3() {
        ZuoraSyncController.FetchInvoiceCollection();
        ZuoraSyncController.FetchInvoiceCollection('Invoice__c','test');
        ZuoraSyncController.FetchInvoiceCollection('InvoiceLineItem__c','test');
        ZuoraSyncController.InvoiceZObjCollection InvoiceCollection = ZuoraSyncController.FetchInvoiceCollection(Date.today());
        ZuoraSyncController.InvoiceCollectionUpsert(InvoiceCollection);
    }

    @isTest static void test4() {
        ZuoraSyncController.FetchPaymentCollection();
        ZuoraSyncController.FetchPaymentCollection('Payment__c','test');
        ZuoraSyncController.PaymentZObjCollection PaymentCollection = ZuoraSyncController.FetchPaymentCollection(Date.today());
        ZuoraSyncController.PaymentCollectionUpsert(PaymentCollection);
    }

    @isTest static void test5() {
        ZuoraSyncController.FetchInvPmtCollection();
        ZuoraSyncController.FetchInvPmtCollection('InvoicePayment__c','test');
        ZuoraSyncController.InvPmtZObjCollection InvPmtCollection = ZuoraSyncController.FetchInvPmtCollection(Date.today());
        ZuoraSyncController.InvPmtCollectionUpsert(InvPmtCollection);
    }

    @isTest static void test6() {
        ZuoraSyncController.FetchRefundCollection();
        ZuoraSyncController.FetchRefundCollection('Refund__c','test');
        ZuoraSyncController.RefundZObjCollection RefundCollection = ZuoraSyncController.FetchRefundCollection(Date.today());
        ZuoraSyncController.RefundCollectionUpsert(RefundCollection);
    }

    @isTest static void test7() {
        ZuoraSyncController.FetchInvRefCollection();
        ZuoraSyncController.FetchInvRefCollection('InvoiceRefund__c','test');
        ZuoraSyncController.InvRefZObjCollection InvRefCollection = ZuoraSyncController.FetchInvRefCollection(Date.today());
        ZuoraSyncController.InvRefCollectionUpsert(InvRefCollection);
    }
    
    @isTest static void test8() {
        ZuoraSyncController.PaymentZObjCollection PaymentCollection = (ZuoraSyncController.PaymentZObjCollection)JSON.deserialize(
            '{"FetchPayments":[{"done":true,"records":[{"id":"test"}]}],"queryLocators":[{"objectName":"test","queryLocator":"test"}]}', 
            ZuoraSyncController.PaymentZObjCollection.class
        );
        ZuoraSyncController.PaymentCollectionUpsert(PaymentCollection);
    }

    @isTest static void test9() {
        ZuoraSyncController.RefundZObjCollection RefundCollection = (ZuoraSyncController.RefundZObjCollection)JSON.deserialize(
            '{"FetchRefunds":[{"done":true,"records":[{"id":"test"}]}],"queryLocators":[{"objectName":"test","queryLocator":"test"}]}', 
            ZuoraSyncController.RefundZObjCollection.class
        );
        ZuoraSyncController.RefundCollectionUpsert(RefundCollection);
    }
    
    @isTest static void test10() {
        ZObj.FetchPayment FetchPayment = new ZObj.FetchPayment();
        FetchPayment.Amount = 0;
        FetchPayment.AppliedCreditBalanceAmount = 0;
        FetchPayment.AppliedInvoiceAmount = 0;
        FetchPayment.AuthTransactionId = 'test';
        FetchPayment.BankIdentificationNumber = 'test';
        FetchPayment.CancelledOn = DateTime.now();
        FetchPayment.CreatedDate = DateTime.now();
        FetchPayment.CreditBalanceAmount = 0;
        //FetchPayment.CurrencyX = 'EUR';
        FetchPayment.EffectiveDate = DateTime.now();
        FetchPayment.GatewayResponse = 'test';
        FetchPayment.GatewayResponseCode = 'test';
        FetchPayment.GatewayState = 'test';
        FetchPayment.Id = 'test';
        FetchPayment.RefundAmount = 0;
        FetchPayment.SettledOn = DateTime.now();
        FetchPayment.Status = 'test';
        FetchPayment.SubmittedOn = DateTime.now();
        //FetchPayment.Success = true;
        FetchPayment.Type = 'test';
        FetchPayment.UnappliedAmount = 0;
    }

    @isTest static void test11() {
        ZObj.FetchRefund FetchRefund = new ZObj.FetchRefund();
        FetchRefund.Amount = 0;
        FetchRefund.CancelledOn = DateTime.now();
        FetchRefund.CurrencyX = 'EUR';
        FetchRefund.EffectiveDate = DateTime.now();
        FetchRefund.GatewayResponse = 'test';
        FetchRefund.GatewayResponseCode = 'test';
        FetchRefund.GatewayState = 'test';
        FetchRefund.Id = 'test';
        FetchRefund.SettledOn = DateTime.now();
        FetchRefund.Status = 'test';
        FetchRefund.Type = 'test';
    }

    @isTest static void test12() {
        ZObj.AmendmentSet Data = new ZObj.AmendmentSet(
        	null,null,null,null,null,null
        );
        String s = ZuoraSyncController.ExecuteAmendment(Data, true, Date.today());
        s = ZuoraSyncController.ExecuteAmendment(Data, false, Date.today());
    }
    
    @isTest static void test13() {
        Account a = new Account(name='test',ZuoraId__c='test');
        insert a;
        Subscription__c s = new Subscription__c(Account__c=a.Id, ZuoraId__c='test', Status__c='Active');
        insert s;
        ZuoraSyncController.FetchActiveSubscriptions('test');
    }
    
    @isTest static void test14() {
        Account a = new Account(name='test',ZuoraId__c='test');
        insert a;
        Subscription__c s = new Subscription__c(Account__c=a.Id, ZuoraId__c='test', Status__c='Active');
        insert s;
        ZuoraSyncController.InvoiceCollectionUpsert(
        	new ZuoraSyncController.InvCombinedZObjCollection(
                new List<ZObj.FetchInvoice>{
                    (ZObj.FetchInvoice)json.deserialize('{"Id":"test","AccountId":"test","IncludesRecurring":true,"IncludesUsage":true,"IncludesOneTime":true}', ZObj.FetchInvoice.class)
                },
                new List<ZObj.FetchInvoiceItem>{
                    (ZObj.FetchInvoiceItem)json.deserialize('{"Id":"test","InvoiceId":"test","RatePlanChargeId":"test"}', ZObj.FetchInvoiceItem.class)
                },
                new List<ZuoraSyncController.QueryLocator>()
            ),
            true
        );
    }
    
    @isTest static void test15() {
        ZuoraSyncController.AccountZObjCollection a = ZuoraSyncController.FetchAccountCollection();
        a = ZuoraSyncController.FetchAccountCollection(Date.today());
        a = ZuoraSyncController.FetchAccountCollection('Account', 'QueryLocator');
    }
    
    @isTest static void test16() {
        Account a = new Account(name='test',ZuoraId__c='test');
        insert a;
        insert new PaymentMethod__c(Account__c=a.Id,ZuoraId__c='test',name='test',BankTransferAccountNumberMask__c='xyz');
        ZuoraSyncController.AccountCollectionUpsert(
        	new ZuoraSyncController.AccountZObjCollection(
                new List<ZObj.FetchAccount>{
                    (ZObj.FetchAccount)json.deserialize(
                        '{"AutoPay":true,"Id":"test","DefaultPaymentMethodId":"test"}', 
                        ZObj.FetchAccount.class
                    )
                },
                new List<ZuoraSyncController.QueryLocator>()
            )
        );
    }

    @isTest static void test17() {
        Account a = new Account(name='test',ZuoraId__c='test');
        insert a;
        ZuoraSyncController.InvoiceCollectionUpsert(
        	new ZuoraSyncController.InvoiceZObjCollection(
                new List<ZObj.FetchInvoice>{
                    (ZObj.FetchInvoice)json.deserialize(
                        '{"Id":"test","AccountId":"test","IncludesOneTime":true,"IncludesRecurring":true,"IncludesUsage":true}', 
                        ZObj.FetchInvoice.class
                    )
                },
                new List<ZuoraSyncController.QueryLocator>()
            )
        );
    }

    @isTest static void test18() {
        ZuoraSyncController.InvItemZObjCollection a = ZuoraSyncController.FetchInvItemCollection();
        a = ZuoraSyncController.FetchInvItemCollection(Date.today());
        a = ZuoraSyncController.FetchInvItemCollection('InvoiceLineItem__c', 'QueryLocator');
    }
    
    @isTest static void test19() {
        Account a = new Account(name='test',ZuoraId__c='test');
        insert a;
        Invoice__c i = new Invoice__c(ZuoraId__c='test',Account__c=a.Id,SuppressTriggeredEmail__c=true);
        insert i;
        Subscription__c s = new Subscription__c(ZuoraId__c='test',Account__c=a.Id);
        insert s;
        SubscriptionLineItem__c sl = new SubscriptionLineItem__c(ZuoraId__c='test',Subscription__c=s.Id);
        insert sl;
        ZuoraSyncController.InvItemCollectionUpsert(
        	new ZuoraSyncController.InvItemZObjCollection(
                new List<ZObj.FetchInvoiceItem>{
                    (ZObj.FetchInvoiceItem)json.deserialize(
                        '{"Id":"test","InvoiceId":"test","SubscriptionId":"test","RatePlanChargeId":"test"}', 
                        ZObj.FetchInvoiceItem.class
                    )
                },
                new List<ZuoraSyncController.QueryLocator>()
            )
        );
    }

    @isTest static void test20() {
        ZuoraSyncController.SubscriptionZObjCollection a = ZuoraSyncController.FetchSubscriptionCollection();
        a = ZuoraSyncController.FetchSubscriptionCollection(Date.today());
        a = ZuoraSyncController.FetchSubscriptionCollection('Subscription__c', 'QueryLocator');
    }
    
    @isTest static void test21() {
        Account a = new Account(name='test',ZuoraId__c='test');
        insert a;
        ZuoraSyncController.SubscriptionCollectionUpsert(
        	new ZuoraSyncController.SubscriptionZObjCollection(
                new List<ZObj.FetchSubscription>{
                    (ZObj.FetchSubscription)json.deserialize(
                        '{"Id":"test","AccountId":"test","AutoRenew":true,"IsInvoiceSeparate":true}', 
                        ZObj.FetchSubscription.class
                    )
                },
                new List<ZuoraSyncController.QueryLocator>()
            )
        );
    }

    @isTest static void test22() {
        ZuoraSyncController.SLIMapZObjCollection a = ZuoraSyncController.FetchSLIMapCollection();
        a = ZuoraSyncController.FetchSLIMapCollection(Date.today());
        a = ZuoraSyncController.FetchSLIMapCollection('SLIMap__c', 'QueryLocator');
    }
    
    @isTest static void test23() {
        ZuoraSyncController.SLIMapCollectionUpsert(
        	new ZuoraSyncController.SLIMapZObjCollection(
                new List<ZObj.FetchSLIMapping>{
                    (ZObj.FetchSLIMapping)json.deserialize(
                        '{"Id":"test","SubscriptionId":"test"}', 
                        ZObj.FetchSLIMapping.class
                    )
                },
                new List<ZuoraSyncController.QueryLocator>()
            )
        );
    }

    /*@isTest static void test24() {
        ZuoraSyncController.SubItemZObjCollection a = ZuoraSyncController.FetchSubItemCollection();
        a = ZuoraSyncController.FetchSubItemCollection(Date.today());
        a = ZuoraSyncController.FetchSubItemCollection('SubscriptionLineItem__c', 'QueryLocator');
    }*/
    
    @isTest static void test25() {
        Account a = new Account(name='test',ZuoraId__c='test');
        insert a;
        Subscription__c s = new Subscription__c(ZuoraId__c='test',Account__c=a.Id);
        insert s;
        Product2 p = new Product2(ZuoraId__c='test',name='test');
        insert p;
        SLIMap__c m = new SLIMap__c(RatePlanId__c='test', SubscriptionId__c='test');
        insert m;
        /*ZuoraSyncController.SubItemCollectionUpsert(
        	new ZuoraSyncController.SubItemZObjCollection(
                new List<ZObj.FetchSubItem>{
                    (ZObj.FetchSubItem)json.deserialize(
                        '{"Id":"test","SubscriptionId":"test","RatePlanId":"test","ProductRatePlanChargeId":"test"}', 
                        ZObj.FetchSubItem.class
                    )
                },
                new List<ZuoraSyncController.QueryLocator>()
            )
        );*/
    }

    @isTest static void test26() {
        Account a = new Account(name='test',ZuoraId__c='test');
        insert a;
        ZuoraSyncController.PaymentCollectionUpsert(
        	new ZuoraSyncController.PaymentZObjCollection(
                new List<ZObj.FetchPayment>{
                    (ZObj.FetchPayment)json.deserialize(
                        '{"Id":"test","AccountId":"test"}', 
                        ZObj.FetchPayment.class
                    )
                },
                new List<ZuoraSyncController.QueryLocator>()
            )
        );
    }

    @isTest static void test27() {
        Account a = new Account(name='test',ZuoraId__c='test');
        insert a;
        Invoice__c i = new Invoice__c(ZuoraId__c='test',Account__c=a.Id,SuppressTriggeredEmail__c=true);
        insert i;
        Payment__c p = new Payment__c(ZuoraId__c='test',Account__c=a.Id);
        insert p;
        ZuoraSyncController.InvPmtCollectionUpsert(
        	new ZuoraSyncController.InvPmtZObjCollection(
                new List<ZObj.FetchInvPmt>{
                    (ZObj.FetchInvPmt)json.deserialize(
                        '{"Id":"test","InvoiceId":"test","PaymentId":"test"}', 
                        ZObj.FetchInvPmt.class
                    )
                },
                new List<ZuoraSyncController.QueryLocator>()
            )
        );
    }

    @isTest static void test28() {
        Account a = new Account(name='test',ZuoraId__c='test');
        insert a;
        Invoice__c i = new Invoice__c(ZuoraId__c='test',Account__c=a.Id,SuppressTriggeredEmail__c=true);
        insert i;
        Refund__c r = new Refund__c(ZuoraId__c='test',Account__c=a.Id);
        insert r;
        ZuoraSyncController.InvRefCollectionUpsert(
        	new ZuoraSyncController.InvRefZObjCollection(
                new List<ZObj.FetchInvRef>{
                    (ZObj.FetchInvRef)json.deserialize(
                        '{"Id":"test","InvoiceId":"test","RefundId":"test"}', 
                        ZObj.FetchInvRef.class
                    )
                },
                new List<ZuoraSyncController.QueryLocator>()
            )
        );
    }

    @isTest static void test29() {
        Account a = new Account(name='test',ZuoraId__c='test');
        insert a;
        ZuoraSyncController.RefundCollectionUpsert(
        	new ZuoraSyncController.RefundZObjCollection(
                new List<ZObj.FetchRefund>{
                    (ZObj.FetchRefund)json.deserialize(
                        '{"Id":"test","AccountId":"test"}', 
                        ZObj.FetchRefund.class
                    )
                },
                new List<ZuoraSyncController.QueryLocator>()
            )
        );
    }

    @isTest static void test30() {
        ZuoraSyncController.PmtMtdZObjCollection a = ZuoraSyncController.FetchPmtMtdCollection();
        a = ZuoraSyncController.FetchPmtMtdCollection(Date.today());
        a = ZuoraSyncController.FetchPmtMtdCollection('PaymentMethod__c', 'QueryLocator');
    }
    
    @isTest static void test31() {
        Account a = new Account(name='test',ZuoraId__c='test');
        insert a;
        ZuoraSyncController.PmtMtdCollectionUpsert(
        	new ZuoraSyncController.PmtMtdZObjCollection(
                new List<ZObj.FetchPmtMtd>{
                    (ZObj.FetchPmtMtd)json.deserialize(
                        '{"Id":"test","AccountId":"test","Active":true,"BankTransferAccountNumberMask":"abc"}', 
                        ZObj.FetchPmtMtd.class
                    )
                },
                new List<ZuoraSyncController.QueryLocator>()
            )
        );
    }
    
    @isTest static void test32() {
        ZObj.Amendment zA = new ZObj.Amendment(
            new ZObj.AmendmentPair(
                new QuoteLineItem(),
                new SubscriptionLineItem__c()
            ),
            new Map<String, Decimal>(),
            'test'
        );
        zA = new ZObj.Amendment(
            new QuoteLineItem(),
            'test'
        );
        zA = new ZObj.Amendment(
            new QuoteLineItem(),
            'test',
            new Map<String, Decimal>()
        );
    }

    @isTest static void test33() {
        ZObj.AmendItem zA = new ZObj.AmendItem(
            'test',
            new QuoteLineItem()
        );
        zA = new ZObj.AmendItem(
            new SubscriptionLineItem__c(),
            new QuoteLineItem()
        );
        zA = new ZObj.AmendItem(
            new SubscriptionLineItem__c(),
            new QuoteLineItem(),
            1
        );
    }
    
    @isTest static void test34() {
        test.startTest();
 		SchedFetch_Account SchedFetch_Account = new SchedFetch_Account();
        String sch = '0 0 0 * * ?';
        system.schedule('Test check', sch, SchedFetch_Account);
        test.stopTest();
    }

    @isTest static void test35() {
        test.startTest();
 		SchedFetch_Invoice SchedFetch_Invoice = new SchedFetch_Invoice();
        String sch = '0 0 0 * * ?';
        system.schedule('Test check', sch, SchedFetch_Invoice);
        test.stopTest();
    }

    @isTest static void test36() {
        test.startTest();
 		SchedFetch_InvoiceLineItem SchedFetch_InvoiceLineItem = new SchedFetch_InvoiceLineItem();
        String sch = '0 0 0 * * ?';
        system.schedule('Test check', sch, SchedFetch_InvoiceLineItem);
        test.stopTest();
    }

    @isTest static void test37() {
        test.startTest();
 		SchedFetch_InvoicePayment SchedFetch_InvoicePayment = new SchedFetch_InvoicePayment();
        String sch = '0 0 0 * * ?';
        system.schedule('Test check', sch, SchedFetch_InvoicePayment);
        test.stopTest();
    }

    @isTest static void test38() {
        test.startTest();
 		SchedFetch_InvoiceRefund SchedFetch_InvoiceRefund = new SchedFetch_InvoiceRefund();
        String sch = '0 0 0 * * ?';
        system.schedule('Test check', sch, SchedFetch_InvoiceRefund);
        test.stopTest();
    }

    @isTest static void test39() {
        test.startTest();
 		SchedFetch_Payment SchedFetch_Payment = new SchedFetch_Payment();
        String sch = '0 0 0 * * ?';
        system.schedule('Test check', sch, SchedFetch_Payment);
        test.stopTest();
    }

    @isTest static void test40() {
        test.startTest();
 		SchedFetch_PaymentMethod SchedFetch_PaymentMethod = new SchedFetch_PaymentMethod();
        String sch = '0 0 0 * * ?';
        system.schedule('Test check', sch, SchedFetch_PaymentMethod);
        test.stopTest();
    }

    @isTest static void test41() {
        test.startTest();
 		SchedFetch_Refund SchedFetch_Refund = new SchedFetch_Refund();
        String sch = '0 0 0 * * ?';
        system.schedule('Test check', sch, SchedFetch_Refund);
        test.stopTest();
    }

    @isTest static void test42() {
        test.startTest();
 		SchedFetch_SLIMap SchedFetch_SLIMap = new SchedFetch_SLIMap();
        String sch = '0 0 0 * * ?';
        system.schedule('Test check', sch, SchedFetch_SLIMap);
        test.stopTest();
    }

    @isTest static void test43() {
        test.startTest();
 		SchedFetch_Subscription SchedFetch_Subscription = new SchedFetch_Subscription();
        String sch = '0 0 0 * * ?';
        system.schedule('Test check', sch, SchedFetch_Subscription);
        test.stopTest();
    }

    /*@isTest static void test44() {
        test.startTest();
 		SchedFetch_SubscriptionLineItem SchedFetch_SubscriptionLineItem = new SchedFetch_SubscriptionLineItem();
        String sch = '0 0 0 * * ?';
        system.schedule('Test check', sch, SchedFetch_SubscriptionLineItem);
        test.stopTest();
    }*/

    @isTest static void test45() {
        test.startTest();
 		SchedClear_SLIMap SchedClear_SLIMap = new SchedClear_SLIMap();
        String sch = '0 0 0 * * ?';
        system.schedule('Test check', sch, SchedClear_SLIMap);
        test.stopTest();
    }
    
    @isTest static void test46() {
        test.startTest();
        System.enqueueJob(new EnqueueQueryMoreZuora());
        test.stopTest();
    }

    @isTest static void test47() {
        Contact c = new Contact(lastname='test',email='test@test.com');
        insert c;
        Account a = new Account(name='test',ZuoraId__c='test',SF_BillTo_Contact__c=c.Id);
        insert a;
        Invoice__c i = new Invoice__c(ZuoraId__c='test',Account__c=a.Id,SuppressTriggeredEmail__c=true);
        insert i;
        test.startTest();
        System.enqueueJob(new InvoicePDFSender(new List<Invoice__c>{i}));
        test.stopTest();
    }
    
    @isTest static void test48() {
        test.startTest();
        System.enqueueJob(new EnqueueAccountInvoiceSend('test'));
        test.stopTest();
    }
    
    @isTest static void test49() {
        ZuoraSyncController.CBAZObjCollection a = ZuoraSyncController.FetchCBACollection();
        a = ZuoraSyncController.FetchCBACollection(Date.today());
        a = ZuoraSyncController.FetchCBACollection('PaymentMethod__c', 'QueryLocator');
    }
    
    @isTest static void test50() {
        Account a = new Account(name='test',ZuoraId__c='test');
        insert a;
        ZuoraSyncController.CBACollectionUpsert(
            new ZuoraSyncController.CBAZObjCollection(
                new List<ZObj.FetchCBA>{
                    (ZObj.FetchCBA)json.deserialize(
                        '{"Id":"test","AccountId":"test"}', 
                        ZObj.FetchCBA.class
                    )
                        },
                new List<ZuoraSyncController.QueryLocator>()
            )
        );
    }
    
    @isTest static void test51() {
        ZObj.RevokeSubReq rsr = new ZObj.RevokeSubReq(Date.today(), Date.today());
        
    }
    
    @isTest static void test52() {
        ZuoraSyncController.CreateBillRunsForPrepayers(new List<ZObj.CreateBillRun> { new ZObj.CreateBillRun('test',Date.today()) });
    }
    
    @isTest static void test53() {
        ZuoraSyncController.UpdateBillingBatches(new List<ZObj.BatchChange>{new ZObj.BatchChange('test','test')});
    }
    
    @isTest static void test54() {
        ZuoraSyncController.InstalmentPaymentRun(new List<ZObj.CreatePayment>{new ZObj.CreatePayment('test','test','test',12.34)});
    }
    
}