force-app/main/default/objects/Account/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/MyObVenue__c/MyObVenue__c.object-meta.xml
<CustomObject>
    <label>MyOb Venue</label>
    <nameField>
        <displayFormat>MyOb-{000000}</displayFormat>
        <label>MyOb Venue</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MyOb Venues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MyObVenue__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>MyOrderbird_Log_ons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MyObVenue__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>MyOrderbird_Log_ons</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/MyObVenue__c/fields/Wizard_Complete__c.field-meta.xml
<CustomField>
    <fullName>Wizard_Complete__c</fullName>
    <label>Wizard Complete</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/InvoiceOwner__c.field-meta.xml
<CustomField>
    <fullName>InvoiceOwner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Owner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions (Invoice Owner)</relationshipLabel>
    <relationshipName>InvOwnSubscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/TermType__c.field-meta.xml
<CustomField>
    <fullName>TermType__c</fullName>
    <label>Term Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/SubscriptionLineItem__c.object-meta.xml
<CustomObject>
    <label>Subscription Line Item</label>
    <nameField>
        <label>Subscription Line Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SubscriptionLineItem__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>SubscriptionLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/fields/EffectiveStartDate__c.field-meta.xml
<CustomField>
    <fullName>EffectiveStartDate__c</fullName>
    <label>Effective Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/fields/ESD_Matches_SubTSD__c.field-meta.xml
<CustomField>
    <fullName>ESD_Matches_SubTSD__c</fullName>
    <formula>MONTH(EffectiveStartDate__c) = MONTH(Subscription__r.TermStartDate__c)
&amp;&amp;
DAY(EffectiveStartDate__c) = DAY(Subscription__r.TermStartDate__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ESD Matches SubTSD</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>Subscription__r.Status__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>Subscription_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/TSESubscribeBatch_test.cls
@isTest(seeAllData=true) public class TSESubscribeBatch_test {

    static TestMethod void test() {
        Account a = new Account(name='test', currencyisocode='EUR');
        insert a;
        Contact c = new Contact(lastname='test', accountid=a.id, email='test@test.com');
        insert c;
        insert new MyObVenue__c(Contact__c = c.Id, Wizard_Complete__c = DateTime.now());
        TSESubscribeBatch tsb = new TSESubscribeBatch();
        Boolean b = TSESubscribeBatch.IsRenewalDateTooSoon(Date.today().addDays(1), date.today());
        test.startTest();
 		TSESubscribeBatch dbs = new TSESubscribeBatch();
        String sch = '0 0 23 * * ?';
        system.schedule('Test check', sch, dbs);
        test.stopTest();
    }
    
    static TestMethod void test2() {
        Account a = new Account(name='test', currencyisocode='EUR');
        insert a;
        Contact c = new Contact(lastname='test', accountid=a.id, email='test@test.com');
        insert c;
        insert new MyObVenue__c(Contact__c = c.Id, Wizard_Complete__c = DateTime.now());
        Subscription__c sub = new Subscription__c(Account__c = a.Id, ZuoraId__c = 'test');
        insert sub;
        SubscriptionLineItem__c sli = new SubscriptionLineItem__c(Subscription__c = sub.Id, ZuoraId__c = 'test', EffectiveStartDate__c = Date.newInstance(2018, 3, 4));
        insert sli;
        SubscriptionLineItem__c sliQ = [SELECT Id, ESD_Matches_SubTSD__c, EffectiveStartDate__c, Subscription__r.Account__c, Subscription__r.Account__r.CurrencyIsoCode, Subscription__r.InvoiceOwner__c,
                                        Subscription__r.TermType__c, Subscription__r.Status__c, Subscription__r.ZuoraId__c, Subscription__r.Account__r.ZuoraId__c
                                        FROM SubscriptionLineItem__c WHERE Id = :sli.Id LIMIT 1
                                       ];
        TSESubscribeBatch tsb = new TSESubscribeBatch();
        String s = TSESubscribeBatch.SimpleProrate(sliQ, date.today());
        s = TSESubscribeBatch.ComplexProrate(sliQ, date.today());
        Boolean b = TSESubscribeBatch.EvalSub(sliQ);
        s = TSESubscribeBatch.PerformSP(sliQ, date.today());
        s = TSESubscribeBatch.ExecSP(sliQ, date.today());
    }
}