force-app/main/default/objects/Account/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>2.0</description>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>Zuora Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/InvoicePayment__c/InvoicePayment__c.object-meta.xml
<CustomObject>
    <label>Invoice Payment</label>
    <nameField>
        <displayFormat>InvPmt-{000000}</displayFormat>
        <label>Invoice Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoicePayment__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Payments</relationshipLabel>
    <relationshipName>Invoice_Payments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoicePayment__c/fields/IsQualifyingPayment__c.field-meta.xml
<CustomField>
    <fullName>IsQualifyingPayment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsQualifyingPayment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InvoicePayment__c/fields/IsQualifyingPayment_formula__c.field-meta.xml
<CustomField>
    <fullName>IsQualifyingPayment_formula__c</fullName>
    <formula>Payment__r.Status__c = &apos;Processed&apos; &amp;&amp; (Payment__r.Type__c = &apos;External&apos; || (Payment__r.Type__c = &apos;Electronic&apos; &amp;&amp; Payment__r.GatewayState__c = &apos;Settled&apos;)) &amp;&amp;  Payment__r.RefundAmount__c = 0</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IsQualifyingPayment (formula)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InvoicePayment__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <label>Payment</label>
    <referenceTo>Payment__c</referenceTo>
    <relationshipLabel>Invoice Payments</relationshipLabel>
    <relationshipName>Invoice_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <label>Payment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/IsQualifyingPayment__c.field-meta.xml
<CustomField>
    <fullName>IsQualifyingPayment__c</fullName>
    <formula>Status__c = &apos;Processed&apos; &amp;&amp; (Type__c = &apos;External&apos; || (Type__c = &apos;Electronic&apos; &amp;&amp; GatewayState__c = &apos;Settled&apos;)) &amp;&amp; RefundAmount__c = 0</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IsQualifyingPayment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/InvoicePayment_test.cls
@isTest public class InvoicePayment_test {

    static testMethod void test() {
    
        Account a = new Account(name='test');
        insert a;
        Invoice__c i = new Invoice__c(Account__c = a.Id, ZuoraId__c = 'test');
        insert i;
        Payment__c p = new Payment__c(Account__c = a.Id, ZuoraId__c = 'test');
        insert p;
        InvoicePayment__c ip = new InvoicePayment__c(
            Invoice__c = i.Id, Payment__c = p.Id, ZuoraId__c = 'test', IsQualifyingPayment__c = false
        );
        insert ip;
        ip.IsQualifyingPayment__c = true;
        update ip;
        system.debug(json.serialize([select id, isqualifyingpayment__c, isqualifyingpayment_formula__c from invoicepayment__c]));
        Database.executeBatch(new InvoicePayment_batch());
        String jobId = System.schedule('test', '0 0 0 3 9 ? 2022', new InvoicePayment_scheduler());

    
    }

}