force-app/main/default/objects/Account/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/PrecedingSubscription__c.field-meta.xml
<CustomField>
    <fullName>PrecedingSubscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Preceding Subscription</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>PrecedingSubscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/SubscriptionLineItem__c.object-meta.xml
<CustomObject>
    <label>Subscription Line Item</label>
    <nameField>
        <label>Subscription Line Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SubscriptionLineItem__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>SubscriptionLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/fields/PrecedingSLI__c.field-meta.xml
<CustomField>
    <fullName>PrecedingSLI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Preceding SLI</label>
    <referenceTo>SubscriptionLineItem__c</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>PrecedingSLIs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>Subscription_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/BatchSubscriptionLinkage_Test.cls
@isTest public class BatchSubscriptionLinkage_Test {

    static TestMethod void test1() {
        Account a = new Account(name = 'Test');
        insert a;
        Subscription__c s1 = new Subscription__c(account__c = a.Id, zuoraid__c = 'test1', name='Test', version__c = 1);
        insert s1;
        SubscriptionLineItem__c sli1 = new SubscriptionLineItem__c(subscription__c = s1.Id, name='Test', zuoraid__c = 'test1');
        insert sli1;
        Subscription__c s2 = new Subscription__c(account__c = a.Id, zuoraid__c = 'test2', name='Test', version__c = 2);
        insert s2;
        SubscriptionLineItem__c sli2 = new SubscriptionLineItem__c(subscription__c = s2.Id, name='Test', zuoraid__c = 'test');
        insert sli2;
        database.executeBatch(new BatchSubscriptionLinkage(true));
        database.executeBatch(new BatchSLILinkage(true));
    }
    
    static TestMethod void test2() {
        Account a = new Account(name = 'Test');
        insert a;
        Subscription__c s1 = new Subscription__c(account__c = a.Id, zuoraid__c = 'test1', name='Test', version__c = 1);
        insert s1;
        SubscriptionLineItem__c sli1 = new SubscriptionLineItem__c(subscription__c = s1.Id, name='Test', zuoraid__c = 'test1');
        insert sli1;
        Subscription__c s2 = new Subscription__c(PrecedingSubscription__c = s1.Id, account__c = a.Id, zuoraid__c = 'test2', name='Test', version__c = 2);
        insert s2;
        SubscriptionLineItem__c sli2 = new SubscriptionLineItem__c(precedingsli__c = sli1.id, subscription__c = s2.Id, name='Test', zuoraid__c = 'test');
        insert sli2;
        database.executeBatch(new BatchSubscriptionLinkage(false));
        database.executeBatch(new BatchSLILinkage(false));
    }

    static TestMethod void test3() {
        String jobId = System.schedule('test', '0 0 0 3 9 ? 2022', new BatchSubscriptionLinkage_Sched_P());
    }

    static TestMethod void test4() {
        String jobId = System.schedule('test', '0 0 0 3 9 ? 2022', new BatchSubscriptionLinkage_Sched_S());
    }

    static TestMethod void test5() {
        String jobId = System.schedule('test', '0 0 0 3 9 ? 2022', new BatchSLILinkage_Sched_P());
    }

    static TestMethod void test6() {
        String jobId = System.schedule('test', '0 0 0 3 9 ? 2022', new BatchSLILinkage_Sched_S());
    }

}