force-app/main/default/objects/Account/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>2.0</description>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>Zuora Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/DownloadInvoiceControllerTest.cls
/**
 * Created by keylight
 */
@isTest
public class DownloadInvoiceControllerTest {

	@isTest
	static void testDownloadInvoiceController() {
		Test.setMock(HttpCalloutMock.class, new ZuoraHttpCalloutMock());
		Account a = new Account(name='test');
        insert a;
		Invoice__c invoice = new Invoice__c(ZuoraId__c='2345',Account__c=a.Id);
		insert invoice;

		Test.startTest();
		ApexPages.StandardController standardController = new ApexPages.StandardController(invoice);
		DownloadInvoiceController invoiceController = new DownloadInvoiceController(standardController);
		String result = invoiceController.getDisplay();
		System.assertEquals('Test', result);
		Test.stopTest();
	}
}