force-app/main/default/objects/Account/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>ZuoraId</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>2.0</description>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoiceDate__c.field-meta.xml
<CustomField>
    <fullName>InvoiceDate__c</fullName>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>Zuora Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/NegativeInvoiceAdjuster.cls
global class NegativeInvoiceAdjuster implements Database.Batchable<sObject>, Database.AllowsCallouts{
    
    global String Query;
    
    global NegativeInvoiceAdjuster() {
        Query  = 'SELECT Id, Balance__c, ZuoraId__c, Account__r.ZuoraId__c FROM Invoice__c ';
        Query += 'WHERE Balance__c < 0 AND InvoiceDate__c <= TODAY AND Status__c = \'Posted\'';
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(Query);
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope){
        List<ZObj.CreateCBA> CreateCBAs = new List<ZObj.CreateCBA>();
        for (sObject s : scope) {
            CreateCBAs.add(
                new ZObj.CreateCBA(
                    Math.abs((Decimal)s.get('Balance__c')), (String)s.get('ZuoraId__c'), 'Increase'
                )
            );
        }
        ZuoraSyncController.CreateCreditBalanceAdjustments(new List<List<ZObj.CreateCBA>>{ CreateCBAs });
    }
    
    global void finish(Database.BatchableContext BC){
    }
    
}