force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>2.0</description>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/HasBeenEmailed__c.field-meta.xml
<CustomField>
    <fullName>HasBeenEmailed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Been Emailed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/TaxExemptReason__c.field-meta.xml
<CustomField>
    <fullName>TaxExemptReason__c</fullName>
    <label>Tax Exempt Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/VAT_ref__c.field-meta.xml
<CustomField>
    <fullName>VAT_ref__c</fullName>
    <label>VAT Adjustment Reference</label>
    <length>23</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/VATId__c.field-meta.xml
<CustomField>
    <fullName>VATId__c</fullName>
    <label>VAT Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ZuoraId__c.field-meta.xml
<CustomField>
    <fullName>ZuoraId__c</fullName>
    <externalId>true</externalId>
    <label>Zuora Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/InvoiceUpdater.cls
global class InvoiceUpdater implements Database.Batchable<sObject>, Database.AllowsCallouts{
    
    global String Query;
    
    global InvoiceUpdater() {
        Query  = 'SELECT Id, ZuoraId__c, VATId__c, TaxExemptReason__c, VAT_ref__c FROM Invoice__c WHERE Id IN (SELECT ParentId FROM Invoice__History WHERE Field = \'HasBeenEmailed__c\' AND CreatedDate >= YESTERDAY)';
    }
    
    global InvoiceUpdater(Boolean b) {
        if (b) {
            Query  = 'SELECT Id, ZuoraId__c, VATId__c, TaxExemptReason__c, VAT_ref__c FROM Invoice__c WHERE HasBeenEmailed__c = TRUE AND ZuoraId__c != null AND VATId__c != NULL';
        } else {
            Query  = 'SELECT Id, ZuoraId__c, VATId__c, TaxExemptReason__c, VAT_ref__c FROM Invoice__c WHERE VAT_ref__c != null';
        }
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(Query);
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope){
        List<ZObj.InvoiceVATUpdate> BatchChanges = new List<ZObj.InvoiceVATUpdate>(); for (sObject s : scope) { BatchChanges.add(new ZObj.InvoiceVATUpdate((Invoice__c)s)); } ZuoraSyncController.UpdateInvoiceBatches(BatchChanges);
    }
    
    global void finish(Database.BatchableContext BC){
    }

}