force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>2.0</description>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceLineItem__c/InvoiceLineItem__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>ILI-{0000000}</displayFormat>
        <label>Invoice Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceLineItem__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/fields/SubscriptionLineItem__c.field-meta.xml
<CustomField>
    <fullName>SubscriptionLineItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription Line Item</label>
    <referenceTo>SubscriptionLineItem__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InvoicePayment__c/InvoicePayment__c.object-meta.xml
<CustomObject>
    <label>Invoice Payment</label>
    <nameField>
        <displayFormat>InvPmt-{000000}</displayFormat>
        <label>Invoice Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoicePayment__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Payments</relationshipLabel>
    <relationshipName>Invoice_Payments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoicePayment__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <label>Payment</label>
    <referenceTo>Payment__c</referenceTo>
    <relationshipLabel>Invoice Payments</relationshipLabel>
    <relationshipName>Invoice_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoiceRefund__c/InvoiceRefund__c.object-meta.xml
<CustomObject>
    <label>Invoice Refund</label>
    <nameField>
        <displayFormat>InvRef-{000000}</displayFormat>
        <label>Invoice Refund Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Refunds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceRefund__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Refunds</relationshipLabel>
    <relationshipName>Invoice_Refunds</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoiceRefund__c/fields/Refund__c.field-meta.xml
<CustomField>
    <fullName>Refund__c</fullName>
    <label>Refund</label>
    <referenceTo>Refund__c</referenceTo>
    <relationshipLabel>Invoice Refunds</relationshipLabel>
    <relationshipName>Invoice_Refunds</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <label>Payment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentMethod__c/PaymentMethod__c.object-meta.xml
<CustomObject>
    <label>Payment Method</label>
    <nameField>
        <label>Payment Method Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Refund__c/Refund__c.object-meta.xml
<CustomObject>
    <label>Refund</label>
    <nameField>
        <label>Refund Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Refunds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Refund__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>Payment__c</referenceTo>
    <relationshipLabel>Refunds</relationshipLabel>
    <relationshipName>Refunds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SLIMap__c/SLIMap__c.object-meta.xml
<CustomObject>
    <label>SLI Mapping</label>
    <nameField>
        <displayFormat>SLIM-{000000}</displayFormat>
        <label>SLI Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SLI Map</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SubscriptionLineItem__c/SubscriptionLineItem__c.object-meta.xml
<CustomObject>
    <label>Subscription Line Item</label>
    <nameField>
        <label>Subscription Line Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SubscriptionLineItem__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>Subscription_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ZuoraFetchQueue_test.cls
@isTest
public class ZuoraFetchQueue_test {
    
    @isTest static void Test1() {
        System.enqueueJob(new ZuoraFetchQueue('ProductCatalog'));
        System.enqueueJob(new ZuoraFetchQueue('Account'));
        System.enqueueJob(new ZuoraFetchQueue('Subscription__c'));
        System.enqueueJob(new ZuoraFetchQueue('SLIMap__c'));
    }
    
    @isTest static void Test2() {
        Test.startTest();
        System.enqueueJob(new ZuoraFetchQueue('SubscriptionLineItem__c:0'));
        Test.stopTest();
        System.enqueueJob(new ZuoraFetchQueue('SubscriptionLineItem__c:1'));
        System.enqueueJob(new ZuoraFetchQueue('SubscriptionLineItem__c:2'));
        System.enqueueJob(new ZuoraFetchQueue('Invoice__c'));
    }
    
    @isTest static void Test3() {
        System.enqueueJob(new ZuoraFetchQueue('InvoiceLineItem__c'));
        System.enqueueJob(new ZuoraFetchQueue('Payment__c'));
        System.enqueueJob(new ZuoraFetchQueue('Refund__c'));
        System.enqueueJob(new ZuoraFetchQueue('InvoicePayment__c'));
    }
    
    @isTest static void Test4() {
        System.enqueueJob(new ZuoraFetchQueue('InvoiceRefund__c'));
        System.enqueueJob(new ZuoraFetchQueue('PaymentMethod__c'));
    }
    
    @isTest static void Test5() {
        ZuoraFetchScheduler p = new ZuoraFetchScheduler('ProductCatalog');
        String sch = '0 12 00 * * ?';
        system.schedule('ProductCatalog', sch, p);
    }
    
    @isTest static void Test6() {
        ZuoraFetchScheduler p = new ZuoraFetchScheduler('ProductCatalog');
        String sch = '0 12 00 * * ?';
        system.schedule('ProductCatalog', sch, p);
    }
    
    @isTest static void Test7() {
        ZObj.FetchCatalog cat = new ZObj.FetchCatalog();
        ZObj.FetchCatalogProducts fcp = new ZObj.FetchCatalogProducts();
        ZObj.FetchCatalogProductRatePlans fcprp = new ZObj.FetchCatalogProductRatePlans();
        ZObj.FetchCatalogProductRatePlanCharges fcprpc = new ZObj.FetchCatalogProductRatePlanCharges();
        ZObj.FetchCatalogPricing fcpricing = new ZObj.FetchCatalogPricing();
        fcprpc.pricing = new List<ZObj.FetchCatalogPricing>{fcpricing};
		fcprp.productRatePlanCharges = new List<ZObj.FetchCatalogProductRatePlanCharges>{fcprpc};
        fcp.productRatePlans = new List<ZObj.FetchCatalogProductRatePlans>{fcprp};
        cat.products = new List<ZObj.FetchCatalogProducts>{fcp};
		fcp.id = 'test';
        fcprp.id = 'test';
        fcprpc.id = 'test';
        fcprpc.name = 'test';
        fcprpc.taxable = true;
        System.enqueueJob(new ProdCatUpsert(0, JSON.serialize(cat)));
    }
}