force-app/main/default/objects/CSVReport__c/CSVReport__c.object-meta.xml
<CustomObject>
    <label>CSV Report</label>
    <nameField>
        <label>CSV Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSV Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CSVReport__c/fields/Email_as_XLS__c.field-meta.xml
<CustomField>
    <fullName>Email_as_XLS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Email as XLS</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CSVReport__c/fields/EmailTo__c.field-meta.xml
<CustomField>
    <fullName>EmailTo__c</fullName>
    <label>Scheduled Email Recipient(s)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CSVReportEmailer.cls
public class CSVReportEmailer{
    
    public static void EmailCSVs() {
        
        List<CSVReport__c> CSVRs = [SELECT Id, EmailTo__c, FileName__c, Email_as_XLS__c FROM CSVReport__c WHERE EmailTo__c != null];
        
        Set<String> EmailAddresses = new Set<String>();
        List<Messaging.Email> Emails = new List<Messaging.Email>();
        
        for (CSVReport__c CSVR : CSVRs) {
            for (String EmailAddress : CSVR.EmailTo__c.replace(' ','').split(',')) {
                EmailAddresses.add(EmailAddress);
            }
        }
        
        for (String EmailAddress : EmailAddresses) {
            List<Messaging.Emailfileattachment> fileAttachments = new List<Messaging.Emailfileattachment>();
            for (CSVReport__c CSVR : CSVRs) {
                if (CSVR.EmailTo__c.contains(EmailAddress)) {
                    Messaging.Emailfileattachment efa = new Messaging.Emailfileattachment();
                    efa.setFileName(CSVR.FileName__c + '.csv');
                    String ReportOutput = 'CSV';
                    if (CSVR.Email_as_XLS__c) {
                        ReportOutput = 'XLS';
                        efa.setFileName(CSVR.FileName__c + '.xls');
                    }
                    PageReference pageRef = new PageReference('/apex/' + ReportOutput + 'Report');
                    pageRef.getParameters().put('id', CSVR.Id);
                    Blob csvBlob;
                    if(!test.isRunningTest()) csvBlob = pageRef.getContent();
                    efa.setBody(csvBlob);
                    fileAttachments.add(efa);
                }
            }
            Messaging.SingleEmailMessage em = new Messaging.SingleEmailMessage();
            em.setTreatBodiesAsTemplate(true);
            em.setPlainTextBody('');
            em.setSubject('Scheduled Reports');
            em.setToAddresses(new List<String>{EmailAddress});
            em.setFileAttachments(fileAttachments);
            Emails.add(em);
        }
        
        if (!test.isRunningTest()) Messaging.sendEmail( Emails );
        
    }
    
    @InvocableMethod(label='CSV Email' description='Sends CSV Reports via Email')
    public static void CSVInvocableEmail(List<CSVRequest> requests) {
        List<Messaging.Email> Emails = new List<Messaging.Email>();
        for (CSVRequest req : requests) {
            Set<String> CSVIds = new Set<String>(req.CSVReportIds.replace(' ','').replace(';',',').split(','));
            system.debug(json.serialize(CSVIds));
            List<CSVReport__c> CSVRs = [SELECT Id, EmailTo__c, FileName__c, Email_as_XLS__c FROM CSVReport__c WHERE Id IN :CSVIds];
            List<Messaging.Emailfileattachment> fileAttachments = new List<Messaging.Emailfileattachment>();
            for (CSVReport__c CSVR : CSVRs) {
                Messaging.Emailfileattachment efa = new Messaging.Emailfileattachment();
                efa.setFileName(CSVR.FileName__c + '.csv');
                String ReportOutput = 'CSV';
                if (CSVR.Email_as_XLS__c) {
                    ReportOutput = 'XLS';
                    efa.setFileName(CSVR.FileName__c + '.xls');
                }
                PageReference pageRef = new PageReference('/apex/' + ReportOutput + 'Report');
                pageRef.getParameters().put('id', CSVR.Id);
                if (req.RecordId != null) pageRef.getParameters().put('recordId', req.RecordId);
                Blob csvBlob;
                if(!test.isRunningTest()) csvBlob = pageRef.getContent();
                efa.setBody(csvBlob);
                fileAttachments.add(efa);
            }
            Messaging.SingleEmailMessage em = new Messaging.SingleEmailMessage();
            em.setPlainTextBody('');
            em.setSaveAsActivity(false);
            em.setSubject('Salesforce Automated CSV Generation');
            em.setTargetObjectId(req.UserId);
            em.setFileAttachments(fileAttachments);
            Emails.add(em);
        }
        if (!test.isRunningTest()) Messaging.sendEmail( Emails );
    }
    
    public class CSVRequest {
        
        @InvocableVariable(required=true)
        public Id UserId;
        
        @InvocableVariable(required=true)
        public String CSVReportIds;
        
        @InvocableVariable(required=false)
        public String RecordId;
        
    }
    
}