force-app/main/default/objects/CSVReport__c/CSVReport__c.object-meta.xml
<CustomObject>
    <label>CSV Report</label>
    <nameField>
        <label>CSV Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSV Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CSVReport__c/fields/SOQL_Finish__c.field-meta.xml
<CustomField>
    <fullName>SOQL_Finish__c</fullName>
    <label>SOQL Finish</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CSVReportField__c/CSVReportField__c.object-meta.xml
<CustomObject>
    <label>CSV Report Field</label>
    <nameField>
        <label>Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSV Report Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CSVReportField__c/fields/Aggregation__c.field-meta.xml
<CustomField>
    <fullName>Aggregation__c</fullName>
    <label>Aggregation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GROUP BY</fullName>
                <default>true</default>
                <label>GROUP BY</label>
            </value>
            <value>
                <fullName>SUM</fullName>
            </value>
            <value>
                <fullName>COUNT</fullName>
            </value>
            <value>
                <fullName>COUNT_DISTINCT</fullName>
            </value>
            <value>
                <fullName>AVG</fullName>
            </value>
            <value>
                <fullName>MIN</fullName>
            </value>
            <value>
                <fullName>MAX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CSVReportField__c/fields/CSVReport__c.field-meta.xml
<CustomField>
    <fullName>CSVReport__c</fullName>
    <label>CSV Report</label>
    <referenceTo>CSVReport__c</referenceTo>
    <relationshipLabel>CSV Report Fields</relationshipLabel>
    <relationshipName>CSV_Report_Fields</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CSVReportField__c/fields/Header__c.field-meta.xml
<CustomField>
    <fullName>Header__c</fullName>
    <label>CSV Column Header</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CSVReportField__c/fields/IsDate__c.field-meta.xml
<CustomField>
    <fullName>IsDate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Date Field</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CSVReportField__c/fields/IsInteger__c.field-meta.xml
<CustomField>
    <fullName>IsInteger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Display as Integer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CSVReportEngine.cls
public class CSVReportEngine {
    
    private Final CSVReport__c csvr = [
        SELECT Id, Name, FileName__c, Object__c, Filter__c, SOQL_Finish__c, (SELECT Id, Name, Aggregation__c, Header__c, IsDate__c, IsInteger__c FROM CSV_Report_Fields__r ORDER BY Order__c, CreatedDate) 
        FROM CSVReport__c WHERE Id=:apexpages.currentpage().getparameters().get('id') LIMIT 1
    ];
    
    public String getFileName() {
        return csvr.FileName__c;
    }
    
    public String getColumnHeaders() {
        String ColumnHeaders = '';
        Boolean FirstField = TRUE;
        for (CSVReportField__c csvrf : csvr.CSV_Report_Fields__r) {
            if (FirstField) {
                FirstField = FALSE;
            } else {
                ColumnHeaders += ',';
            }
            ColumnHeaders += csvrf.Header__c;
        }
        return ColumnHeaders;
    }
    
    public List<CSVReportField__c> getFields() {
        return csvr.CSV_Report_Fields__r;
    }
    
    public List<AggregateResult> getReportData() {

        String SelectStmt = '';
        String GroupStmt = '';
        Boolean FirstField = TRUE;
        Boolean FirstGroup = TRUE;
        String SOQLFinish = csvr.SOQL_Finish__c == null ? '' : ' ' + csvr.SOQL_Finish__c;
        for (CSVReportField__c csvrf : csvr.CSV_Report_Fields__r) {
            if (FirstField) {
                FirstField = FALSE;
            } else {
                SelectStmt += ', ';
            }
            if (csvrf.Aggregation__c != 'GROUP BY') {
                SelectStmt += csvrf.Aggregation__c + '(' + csvrf.Name + ') ' + csvrf.Id;
            } else {
                SelectStmt += csvrf.Name + ' ' + csvrf.Id;
                if (FirstGroup) {
                    FirstGroup = FALSE;
                } else {
                    GroupStmt += ', ';
                }
                GroupStmt += csvrf.Name;
            }
        }
        
        return Database.query('SELECT ' + SelectStmt + ' FROM ' + csvr.Object__c + ' WHERE ' + csvr.Filter__c + ' GROUP BY ' + GroupStmt + SOQLFinish);
    }
    
    public String getNewLine() {
        return '\n';
    }
}