force-app/main/default/objects/MyObVenue__c/MyObVenue__c.object-meta.xml
<CustomObject>
    <label>MyOb Venue</label>
    <nameField>
        <displayFormat>MyOb-{000000}</displayFormat>
        <label>MyOb Venue</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MyOb Venues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MyObVenue__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>MyOrderbird_Log_ons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MyObVenue__c/fields/MyOrderbirdId__c.field-meta.xml
<CustomField>
    <fullName>MyOrderbirdId__c</fullName>
    <externalId>true</externalId>
    <label>MyOrderbird Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OppCategory__c.field-meta.xml
<CustomField>
    <fullName>OppCategory__c</fullName>
    <description>https://jira.orderbird.com/browse/CDS-1827
This field is created to be used as a dependant picklist for the opportunity type.
It is a read only except for System admin</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Business</fullName>
            </value>
            <value>
                <fullName>Account Management</fullName>
            </value>
            <value>
                <fullName>MINI by orderbird</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_type_1__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_type_1__c</fullName>
    <description>AccM solution CDS-1831 and CDS-1827</description>
    <label>Sub-Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>OppCategory__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>New Business</fullName>
            </value>
            <value>
                <fullName>orderbird pay</fullName>
            </value>
            <value>
                <fullName>Compensation</fullName>
            </value>
            <value>
                <fullName>POS Add on products</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>Upselling</fullName>
            </value>
            <value>
                <fullName>pay onboarding</fullName>
            </value>
            <value>
                <fullName>METRO Cockpit</fullName>
            </value>
            <value>
                <fullName>MINI registration</fullName>
            </value>
            <value>
                <fullName>GM - Table Reservation</fullName>
            </value>
            <value>
                <fullName>GM - Ordering System</fullName>
            </value>
            <value>
                <fullName>GM - Bundle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Processed__c.field-meta.xml
<CustomField>
    <fullName>Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Processed (temp)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Closed.recordType-meta.xml
<RecordType>
    <fullName>Closed</fullName>
    <active>true</active>
    <businessProcess>SalesProcess</businessProcess>
    <label>Closed</label>
</RecordType>

force-app/main/default/objects/Portal__c/Portal__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Portal</label>
</CustomObject>

force-app/main/default/objects/Pricebook2/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <externalId>true</externalId>
    <label>Key</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <externalId>true</externalId>
    <label>Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Price_EUR__c.field-meta.xml
<CustomField>
    <fullName>Price_EUR__c</fullName>
    <label>Price (EUR)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductCategory__c.field-meta.xml
<CustomField>
    <fullName>ProductCategory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Category</label>
    <referenceTo>ProductCategory__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductGeneration__c.field-meta.xml
<CustomField>
    <fullName>ProductGeneration__c</fullName>
    <label>Product Generation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>V_1</fullName>
                <label>V-1</label>
            </value>
            <value>
                <fullName>V0</fullName>
            </value>
            <value>
                <fullName>V1</fullName>
            </value>
            <value>
                <fullName>v2</fullName>
            </value>
            <value>
                <fullName>POS201609FR</fullName>
            </value>
            <value>
                <fullName>POS201708DEATCHFR (V2)</fullName>
            </value>
            <value>
                <fullName>POS201507DEATCHnewPrice (V1)</fullName>
            </value>
            <value>
                <fullName>POS201507DEATCHoldPrice (V0)</fullName>
            </value>
            <value>
                <fullName>POS201109DEATCH (V-1)</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductCategory__c/ProductCategory__c.object-meta.xml
<CustomObject>
    <label>Product Category</label>
    <nameField>
        <label>Product Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductCategory__c/fields/ProductGeneration__c.field-meta.xml
<CustomField>
    <fullName>ProductGeneration__c</fullName>
    <label>Product Generation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/recordTypes/Closed.recordType-meta.xml
<RecordType>
    <fullName>Closed</fullName>
    <active>true</active>
    <label>Closed</label>
</RecordType>

force-app/main/default/objects/Work_Order__c/Work_Order__c.object-meta.xml
<CustomObject>
    <description>-used to store requests from the control Shift Portal</description>
    <label>Work Order</label>
    <nameField>
        <displayFormat>Work Order-{000000}</displayFormat>
        <label>Work Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Order__c/fields/Token__c.field-meta.xml
<CustomField>
    <fullName>Token__c</fullName>
    <label>Token</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/WorkOrderSerivce.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 08-16-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class WorkOrderSerivce {
    

    public static void startNegativeProcess (List<Work_Order__c> listRecordsToCreate){
       system.debug('lll '+listRecordsToCreate);
       for(Work_Order__c workOder :listRecordsToCreate){
           if(workOder.Message__c !=null){
               List<ParseJson.removeLicenceJson> listMessage = ParseJson.parseRemovingLicence(workOder.Message__c);
               licencesController(workOder.Id, listMessage, 'Negative',null,null);
           }
       }
    }

    public static void startPositiveProcess (List<Work_Order__c> listRecordsToCreate){
        for(Work_Order__c workOder :listRecordsToCreate){
            if(workOder.Message__c !=null){
                licencesController(workOder.Id, null, 'Positive',workOder.Token__c,workOder.Message__c);
            }
        }
    }

    public class addDevicesWrapper{
        public String productId;
        public String StartDate;
        public Integer Quantity;
        public String ProductName;
    }

    public static List<addDevicesWrapper> getProductsForMoreLicences (String productsToAddString){
        List<addDevicesWrapper> listOfDevicesToAdd = new List<addDevicesWrapper>();

        List<String> listOfProductsToAdd = productsToAddString.split('/');
        List<String> requestedProducts = new List<String>();

        List<String> Year3DeviceToAdd = listOfProductsToAdd[0].split(':');
        if(Integer.valueOf(Year3DeviceToAdd[1]) > 0){
            requestedProducts.add('Device license 3 years');

            addDevicesWrapper year3Wrapper = new addDevicesWrapper();
            year3Wrapper.ProductName = 'Device license 3 years';
            year3Wrapper.StartDate = listOfProductsToAdd[2].split(':')[1];
            year3Wrapper.Quantity = Integer.valueOf(Year3DeviceToAdd[1]);
            listOfDevicesToAdd.add(year3Wrapper);
        }

        List<String> MonthlyDeviceToAdd = listOfProductsToAdd[4].split(':');
        if(Integer.valueOf(MonthlyDeviceToAdd[1]) > 0){
            requestedProducts.add('Device license monthly');

            addDevicesWrapper monthlyWrapper = new addDevicesWrapper();
            monthlyWrapper.ProductName = 'Device license monthly';
            monthlyWrapper.StartDate = listOfProductsToAdd[5].split(':')[1];
            monthlyWrapper.Quantity = Integer.valueOf(MonthlyDeviceToAdd[1]);
            listOfDevicesToAdd.add(monthlyWrapper);
        }

        List<String> YearlyDeviceToAdd = listOfProductsToAdd[6].split(':');
        if(Integer.valueOf(YearlyDeviceToAdd[1]) > 0){
            requestedProducts.add('Device license 1 year');

            addDevicesWrapper yearlyWrapper = new addDevicesWrapper();
            yearlyWrapper.ProductName = 'Device license monthly';
            yearlyWrapper.StartDate = listOfProductsToAdd[8].split(':')[1];
            yearlyWrapper.Quantity = Integer.valueOf(YearlyDeviceToAdd[1]);
            listOfDevicesToAdd.add(yearlyWrapper);
        }
        
        for(Product2 currentProduct : [SELECT Id, Name FROM Product2 WHERE ProductCategory__r.ProductGeneration__c = 'G' AND Name IN: requestedProducts]){
            for(addDevicesWrapper currentDevice : listOfDevicesToAdd){
                if(currentDevice.ProductName == currentProduct.Name){
                    currentDevice.productId = currentProduct.Id;
                    break;
                }
            }
       }

       return listOfDevicesToAdd;
    }


    public static void licencesController(String woId, List<ParseJson.removeLicenceJson> removalList, String operationType, String currentToken, String productsToAddString){
        List<String> listAcctId = new List<String>();
        List<String> listProdId = new List<String>();
        List<Opportunity> listOpptyToInsert = new List<Opportunity>();
        List<Quote> listQuoteToInsert = new List<Quote>();
        List<QuoteLineItem> listOfQLIs = new List<QuoteLineItem>();
        List<Work_Order__c> listWoToComplete = new List<Work_Order__c>();
        Boolean opptySuccess = false;
        Boolean quoteSucess = false;
        Boolean processSuccess = false;


        String oppName = '';
        String quoteName = '';

        List<Product2> listOfProds  = new List<Product2>();

        if(removalList != null){
            for(ParseJson.removeLicenceJson param: removalList ){
                listAcctId.add(param.subLineItemAccount);
                listProdId.add(param.subLineItemProduct);
            }
            oppName = 'MYorderbird Cancel Opportunity'+'- '+system.today();
            quoteName = 'MYorderbird Cancel Quote';
        }else{
            String venueId = '';
            PortalToken.TokenWrapper tw = (PortalToken.TokenWrapper)JSON.deserialize(Crypto.decryptWithManagedIV('AES256', Blob.valueOf(Test.isRunningTest() ? '6251655468576D5A7134743777397A24' : Portal__c.getAll().get('PortalKey').Key__c), EncodingUtil.base64decode(currentToken.replace('-','/').replace('_','+'))).toString(), PortalToken.TokenWrapper.class);
            String accountId = [SELECT Id, Account__c FROM MyObVenue__c WHERE MyOrderbirdId__c =: tw.VenueId].Account__c;
            listAcctId.add(accountId);
            oppName = 'MYorderbird New Licence Opportunity'+'- '+system.today();
            quoteName = 'MYorderbird Adding Licence Quote';
        }

        //get products
        if(operationType == 'Positive'){
            getProductsForMoreLicences(productsToAddString);
        }else{
            listOfProds = [Select Id, Price_EUR__c, Name FROM Product2 WHERE Id =: listProdId];
        }
        
        //get the pricebook for the products
        List<PriceBookEntry> listOfPBEntries = [Select Id, Product2Id, Product2.Price_EUR__c FROM PriceBookEntry WHERE Product2Id =:listOfProds];
        Pricebook2 pb = [SELECT Id FROM Pricebook2 WHERE IsStandard = true];
        system.debug('pbentries are ==> ' + listOfPBEntries);
        system.debug('products are == > ' + listOfProds);

        //Possibly need to add Case Creation method here 
        //Possibly need to add Licence and Subscription creation methods here - future plan to remove this

        //Creates Opp, Quote and Line Iteam for Both adding and removing licences

        for(String accId :listAcctId){
            Opportunity newZuoraOpp = new Opportunity();
            newZuoraOpp.AccountId = accId;
            newZuoraOpp.Name = oppName;
            newZuoraOpp.CloseDate = Date.today().addDays(30);
            newZuoraOpp.StageName = 'Closed Won'; //needs to be changed to Potential
            newZuoraOpp.OppCategory__c = 'Account Management';
            newZuoraOpp.Opportunity_type_1__c = 'Cancellation';
            listOpptyToInsert.add(newZuoraOpp);
        }

        Database.SaveResult[] opportunityList = Database.insert(listOpptyToInsert, false);
        for (Database.SaveResult sr : opportunityList) {
            if (sr.isSuccess()) {
                opptySuccess = true;
                System.debug('Successfully inserted Opportunity. Opportunity ID: ' + sr.getId());
                
                Quote newZuroaQuote = new Quote();
                newZuroaQuote.OpportunityId=sr.getId();
                newZuroaQuote.name = quoteName;
                newZuroaQuote.Pricebook2ID = pb.Id;
                listQuoteToInsert.add(newZuroaQuote);
            }
            else {
                // Operation failed, so get all errors                
                for(Database.Error err : sr.getErrors()) {
                    opptySuccess = false;
                    System.debug('The following error has occurred.');                    
                    System.debug(err.getStatusCode() + ': ' + err.getMessage());
                    System.debug('Opportunity fields that affected this error: ' + err.getFields());
                }
            }
        }
        if(opptySuccess == true){
            Database.SaveResult[] quoteList = Database.insert(listQuoteToInsert, false);
            
            for (Database.SaveResult sq : quoteList) {
                if (sq.isSuccess()) {
                    quoteSucess = true;

                    for(PriceBookEntry pbentry : listOfPBEntries){
                        QuoteLineItem qli = new QuoteLineItem();
                        qli.QuoteId = sq.Id;


                       
                        if(operationType == 'Positive'){ //Add 

                        }else{//Remove

                        }

                        listOfQLIs.add(qli);

                        qli.Product2Id = pbentry.Product2Id;
                        if(operationType =='Negative'){
                            qli.UnitPrice = pbentry.Product2.Price_EUR__c;
                        }
                        qli.Quantity = 1;
                        qli.PriceBookEntryId = pbentry.Id;
                        
                        
                    }
                }
                else {
                    // Operation failed, so get all errors                
                    for(Database.Error err : sq.getErrors()) {
                        System.debug('The following error has occurred.');                    
                        System.debug(err.getStatusCode() + ': ' + err.getMessage());
                        System.debug('Qoute fields that affected this error: ' + err.getFields());
                    }
                }
            }
        }
        if(quoteSucess == true){
            Database.SaveResult[] quoteLineItemList = Database.insert(listOfQLIs, false);
            for (Database.SaveResult sqLi : quoteLineItemList) {
                System.debug('Successfully inserted QLI. QLI ID: ' + sqLi.getId());
                processSuccess = true;
            }
        }

        //Should be an addtional task here to do something to the subscription i believe - Talk to team tomorrow

        if(processSuccess == true){
            List<Work_Order__c> workOrderToUpdate =[select id from Work_Order__c where id =:woId];
            for(Work_Order__c od :workOrderToUpdate ){
                od.Processed__c =true;
                listWoToComplete.add(od);
            }
            update listWoToComplete;
        }
    }
}