force-app/main/default/objects/MyObVenue__c/MyObVenue__c.object-meta.xml
<CustomObject>
    <label>MyOb Venue</label>
    <nameField>
        <displayFormat>MyOb-{000000}</displayFormat>
        <label>MyOb Venue</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MyOb Venues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MyObVenue__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>MyOrderbird_Log_ons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MyObVenue__c/fields/TSE_Charges__c.field-meta.xml
<CustomField>
    <fullName>TSE_Charges__c</fullName>
    <label>TSE Charge(s)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/SubscriptionLineItem__c.object-meta.xml
<CustomObject>
    <label>Subscription Line Item</label>
    <nameField>
        <label>Subscription Line Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SubscriptionLineItem__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>SubscriptionLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>Subscription_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SubscriptionLineItem__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>Subscription_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TSEChargeLink.cls
global class TSEChargeLink implements Schedulable {
    
    global void execute(SchedulableContext sc) {
        
        Map<String, Set<String>> AcctMap = new Map<String, Set<String>>();
        Set<String> ExcludeChargeNames = new Set<String>();
        
        List<MyObVenue__c> unlinkedVenues = [
            SELECT Id, Account__c, TSE_Charges__c
            FROM MyObVenue__c 
            WHERE TSE_Charges__c = 'NEED' 
        ];
        
        for (MyObVenue__c unlinkedVenue : unlinkedVenues) { AcctMap.put(unlinkedVenue.Account__c, new Set<String>()); }

        List<MyObVenue__c> linkedVenues = [
            SELECT Id, Account__c, TSE_Charges__c
            FROM MyObVenue__c 
            WHERE TSE_Charges__c != 'NEED' AND TSE_Charges__c != 'ERROR' 
            AND TSE_Charges__c != 'SKIP' AND TSE_Charges__c != null
            AND Account__c IN :AcctMap.keySet()
        ];

        for (MyObVenue__c linkedVenue : linkedVenues) { ExcludeChargeNames.addAll(linkedVenue.TSE_Charges__c.split(',')); }
        
        List<SubscriptionLineItem__c> charges = [
            SELECT Id, Name, Subscription__r.Account__c
            FROM SubscriptionLineItem__c
            WHERE Name NOT IN :ExcludeChargeNames 
                AND Subscription__r.Account__c IN :AcctMap.keySet()
                AND Product__r.Name LIKE '%tse%' 
                AND (NOT Product__r.Name LIKE '%discount%') 
        ];
        
        for (SubscriptionLineItem__c charge : charges) { AcctMap.get(charge.Subscription__r.Account__c).add(charge.Name); }
        
        for (MyObVenue__c unlinkedVenue : unlinkedVenues) {
            if (AcctMap.get(unlinkedVenue.Account__c).size()>0) unlinkedVenue.TSE_Charges__c = AcctMap.get(unlinkedVenue.Account__c).toString().replace('{','').replace('}','');
        }
        
        update unlinkedVenues;
    }

}