force-app/main/default/objects/Lead/fields/LAC_ID__c.field-meta.xml
<CustomField>
    <fullName>LAC_ID__c</fullName>
    <description>Stakeholder: CDS, BI, MKT, Sales https://jira.orderbird.com/browse/CDS-138</description>
    <inlineHelpText>Enter the ID (3 digits) for relevant Lead Attribution Combo. Careful: entering wrong numbers is possible!</inlineHelpText>
    <label>LAC ID</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Send_Template_Folder__c/Send_Template_Folder__c.object-meta.xml
<CustomObject>
    <label>Send Template Folder</label>
    <nameField>
        <label>Send Template Folder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Send Template Folders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SendTemplate__c/SendTemplate__c.object-meta.xml
<CustomObject>
    <label>Send Template</label>
    <nameField>
        <label>Send Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Send Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SendTemplate__c/fields/AdminName__c.field-meta.xml
<CustomField>
    <fullName>AdminName__c</fullName>
    <label>Admin Name</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SendTemplate__c/fields/Folder__c.field-meta.xml
<CustomField>
    <fullName>Folder__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Folder</label>
    <referenceTo>Send_Template_Folder__c</referenceTo>
    <relationshipLabel>Send Templates</relationshipLabel>
    <relationshipName>Send_Templates</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SendTemplate__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/SendTemplate__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Case</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>MyObVenue</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>BigDataAlert__c</fullName>
            </value>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>Joint_Sales__c</fullName>
            </value>
            <value>
                <fullName>HardwareFulfilment__c</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>OBInvoice</fullName>
            </value>
            <value>
                <fullName>P148Letter__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/QuoteLeadController_test.cls
@isTest public class QuoteLeadController_test {

    static TestMethod void test() {
        Send_Template_Folder__c stf = new Send_Template_Folder__c(name='test');
        insert stf;
        SendTemplate__c st = new SendTemplate__c(Subject__c = 'test', Message__c = 'test', folder__c = stf.id, object__c='Lead', adminname__c='QuotePreorder_EN');
        insert st;
        Lead l = new Lead(lastname='test', company='test', email='bart.collins@orderbird.com', lac_id__c = '800');
        insert l;
        QuoteLeadController.GenerateQuoteId(new List<Id>{ l.Id });
    }
}