force-app/main/default/objects/Lead/fields/Reaction_Time__c.field-meta.xml
<CustomField>
    <fullName>Reaction_Time__c</fullName>
    <label>Reaction Time (in sec)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Reaction_Time_disp__c.field-meta.xml
<CustomField>
    <fullName>Reaction_Time_disp__c</fullName>
    <formula>if(isblank(Reaction_Time__c),&quot;&quot;,
if(Reaction_Time__c &gt;= 3600, TEXT(FLOOR(Reaction_Time__c / 3600)) &amp; &quot; Hour&quot; &amp;
if(FLOOR(Reaction_Time__c / 3600) = 1, &quot;&quot;, &quot;s&quot;)
&amp; &quot;, &quot;,&quot;&quot;)
&amp;
if(Reaction_Time__c &gt;= 60, TEXT(FLOOR(MOD(Reaction_Time__c, 3600) / 60)) &amp; &quot; Minute&quot;&amp;
if(FLOOR(MOD(Reaction_Time__c, 3600) / 60) = 1, &quot;&quot;, &quot;s&quot;)
&amp; &quot;, &quot;, &quot;&quot;)
&amp;
TEXT(MOD(Reaction_Time__c, 60)) &amp; &quot; Second&quot;&amp;
if(MOD(Reaction_Time__c, 60) = 1, &quot;&quot;, &quot;s&quot;))</formula>
    <label>Reaction Time</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Response_Time__c.field-meta.xml
<CustomField>
    <fullName>Response_Time__c</fullName>
    <label>Response Time (in sec)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Response_Time_disp__c.field-meta.xml
<CustomField>
    <fullName>Response_Time_disp__c</fullName>
    <formula>if(isblank(Response_Time__c),&quot;&quot;,
if(Response_Time__c &gt;= 3600, TEXT(FLOOR(Response_Time__c / 3600)) &amp; &quot; Hour&quot; &amp; 
if(FLOOR(Response_Time__c / 3600) = 1, &quot;&quot;, &quot;s&quot;) 
&amp; &quot;, &quot;,&quot;&quot;) 
&amp; 
if(Response_Time__c &gt;= 60, TEXT(FLOOR(MOD(Response_Time__c, 3600) / 60)) &amp; &quot; Minute&quot;&amp; 
if(FLOOR(MOD(Response_Time__c, 3600) / 60) = 1, &quot;&quot;, &quot;s&quot;) 
&amp; &quot;, &quot;, &quot;&quot;) 
&amp; 
TEXT(MOD(Response_Time__c, 60)) &amp; &quot; Second&quot;&amp; 
if(MOD(Response_Time__c, 60) = 1, &quot;&quot;, &quot;s&quot;))</formula>
    <label>Response Time</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/First_Activity_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>First_Activity_Date_Time__c</fullName>
    <label>First Activity Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/First_Successful_Activity_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>First_Successful_Activity_Date_Time__c</fullName>
    <label>First Successful Activity Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Reaction_Time__c.field-meta.xml
<CustomField>
    <fullName>Reaction_Time__c</fullName>
    <label>Reaction Time (in Sec)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Reaction_Time_disp__c.field-meta.xml
<CustomField>
    <fullName>Reaction_Time_disp__c</fullName>
    <formula>if(isblank(Reaction_Time__c),&quot;&quot;,
if(Reaction_Time__c &gt;= 3600, TEXT(FLOOR(Reaction_Time__c / 3600)) &amp; &quot; Hour&quot; &amp;
if(FLOOR(Reaction_Time__c / 3600) = 1, &quot;&quot;, &quot;s&quot;)
&amp; &quot;, &quot;,&quot;&quot;)
&amp;
if(Reaction_Time__c &gt;= 60, TEXT(FLOOR(MOD(Reaction_Time__c, 3600) / 60)) &amp; &quot; Minute&quot;&amp;
if(FLOOR(MOD(Reaction_Time__c, 3600) / 60) = 1, &quot;&quot;, &quot;s&quot;)
&amp; &quot;, &quot;, &quot;&quot;)
&amp;
TEXT(MOD(Reaction_Time__c, 60)) &amp; &quot; Second&quot;&amp;
if(MOD(Reaction_Time__c, 60) = 1, &quot;&quot;, &quot;s&quot;))</formula>
    <label>Reaction Time</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Response_Time__c.field-meta.xml
<CustomField>
    <fullName>Response_Time__c</fullName>
    <label>Response Time (in Sec)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Response_Time_disp__c.field-meta.xml
<CustomField>
    <fullName>Response_Time_disp__c</fullName>
    <formula>if(isblank(Response_Time__c),&quot;&quot;,
if(Response_Time__c &gt;= 3600, TEXT(FLOOR(Response_Time__c / 3600)) &amp; &quot; Hour&quot; &amp;
if(FLOOR(Response_Time__c / 3600) = 1, &quot;&quot;, &quot;s&quot;)
&amp; &quot;, &quot;,&quot;&quot;)
&amp;
if(Response_Time__c &gt;= 60, TEXT(FLOOR(MOD(Response_Time__c, 3600) / 60)) &amp; &quot; Minute&quot;&amp;
if(FLOOR(MOD(Response_Time__c, 3600) / 60) = 1, &quot;&quot;, &quot;s&quot;)
&amp; &quot;, &quot;, &quot;&quot;)
&amp;
TEXT(MOD(Response_Time__c, 60)) &amp; &quot; Second&quot;&amp;
if(MOD(Response_Time__c, 60) = 1, &quot;&quot;, &quot;s&quot;))</formula>
    <label>Response Time</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LeadTimeCalculatorTest.cls
@isTest
private class LeadTimeCalculatorTest {
	
    static testMethod void createOpportunity() {
        Lead ld = new Lead(lastname='test',company='test',status='Qualified', CreatedDate=DateTime.newInstance(2017,11,13,12,0,0));
        insert ld;
        List<Lead> leads = new List<Lead>();
        leads.add(ld);
        LeadAutoConvert.convert(leads);
        //Opportunity l = new Opportunity(WhoId=ld.Id,CreatedDate=DateTime.newInstance(2017,11,13,12,0,0), StageName='Test', Name='Test', CloseDate=Date.newInstance(2018,1,1));
        Id oppId = [SELECT ConvertedOpportunityId FROM Lead WHERE Id=:ld.Id LIMIT 1].ConvertedOpportunityId;
        Opportunity l = [SELECT Id, First_Activity_Date_Time__c FROM Opportunity WHERE Id=:oppId LIMIT 1];
        //insert l;
        l.First_Activity_Date_Time__c = DateTime.newInstance(2017,11,13,13,1,1);
        update l;
        //system.assertEquals(3661, [SELECT Reaction_Time__c FROM Opportunity WHERE Id=:l.Id LIMIT 1].Reaction_Time__c);
        //system.assertEquals('1 Hour, 1 Minute, 1 Second', [SELECT Reaction_Time_disp__c FROM Opportunity WHERE Id=:l.Id LIMIT 1].Reaction_Time_disp__c);
    }

    /*static testMethod void createOpportunityOutsideRange() {
        Opportunity l = new Opportunity(CreatedDate=DateTime.newInstance(2017,11,12,12,0,0), StageName='Test', Name='Test', CloseDate=Date.newInstance(2018,1,1));
        insert l;
        l.First_Successful_Activity_Date_Time__c = DateTime.newInstance(2017,11,13,11,2,2);
        update l;
        system.assertEquals(7322, [SELECT Response_Time__c FROM Opportunity WHERE Id=:l.Id LIMIT 1].Response_Time__c);
        system.assertEquals('2 Hours, 2 Minutes, 2 Seconds', [SELECT Response_Time_disp__c FROM Opportunity WHERE Id=:l.Id LIMIT 1].Response_Time_disp__c);
    }
    
    static testMethod void testBatcher() {
        Test.startTest();
        Opportunity l = new Opportunity(CreatedDate=DateTime.newInstance(2017,11,12,12,0,0), StageName='Test', Name='Test', CloseDate=Date.newInstance(2018,1,1));
        insert l;
        l.First_Successful_Activity_Date_Time__c = DateTime.newInstance(2017,11,13,11,2,2);
        update l;
        l.Response_Time__c = null;
        update l;
        system.assertEquals(null, [SELECT Response_Time__c FROM Opportunity WHERE Id=:l.Id LIMIT 1].Response_Time__c);
		LeadTimeCalculator.processBatch([
            SELECT 
                Id, 
                CreatedDate, 
                Response_Time__c, 
                Reaction_Time__c, 
                First_Activity_Date_Time__c, 
                First_Successful_Activity_Date_Time__c 
            FROM Opportunity
        ]);
        Test.stopTest();
        system.assertEquals(7322, [SELECT Response_Time__c FROM Opportunity WHERE Id=:l.Id LIMIT 1].Response_Time__c);
    }*/

}