force-app/main/default/objects/Batch_Object__mdt/Batch_Object__mdt.object-meta.xml
<CustomObject>
    <label>Batch Object</label>
    <pluralLabel>Batch Objects</pluralLabel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/LAC_Shorthand__c.field-meta.xml
<CustomField>
    <fullName>LAC_Shorthand__c</fullName>
    <description>Stakeholder: CDS, BI, MKT, Sales https://jira.orderbird.com/browse/CDS-138</description>
    <inlineHelpText>Select the relevant Lead Attribution Combo. If it is not on the list use the field LAC ID</inlineHelpText>
    <label>LAC Shorthand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LAC_Shorthands</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/LAC_Shorthands.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Walk-In</fullName>
    </customValue>
    <customValue>
        <fullName>Hotline</fullName>
    </customValue>
    <customValue>
        <fullName>Personal Network</fullName>
    </customValue>
    <customValue>
        <fullName>E-mail</fullName>
    </customValue>
    <customValue>
        <fullName>CRC - Referral of successor</fullName>
    </customValue>
    <customValue>
        <fullName>CRC - E-mail</fullName>
    </customValue>
    <customValue>
        <fullName>CRC - Hotline</fullName>
    </customValue>
    <customValue>
        <fullName>CRC - Webform</fullName>
    </customValue>
    <customValue>
        <fullName>Referral by Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Research - Public Register</fullName>
    </customValue>
    <customValue>
        <fullName>Research - Other</fullName>
    </customValue>
    <customValue>
        <fullName>Chat</fullName>
    </customValue>
    <customValue>
        <fullName>Facebook</fullName>
    </customValue>
    <customValue>
        <fullName>Twitter</fullName>
    </customValue>
    <customValue>
        <fullName>Instagram</fullName>
    </customValue>
    <customValue>
        <fullName>Kassensystemevergleich.de</fullName>
    </customValue>
    <customValue>
        <fullName>Kassen-Vergleich.com</fullName>
    </customValue>
    <customValue>
        <fullName>Companeo</fullName>
    </customValue>
    <customValue>
        <fullName>Facebook Scraper</fullName>
    </customValue>
    <customValue>
        <fullName>Toques de restauration</fullName>
    </customValue>
    <customValue>
        <fullName>Chardasso</fullName>
    </customValue>
    <customValue>
        <fullName>Trade Register Scraper</fullName>
    </customValue>
    <customValue>
        <fullName>TradingTwins</fullName>
    </customValue>
    <customValue>
        <fullName>Outbound Texting</fullName>
    </customValue>
    <customValue>
        <fullName>my.ob Reg</fullName>
    </customValue>
    <customValue>
        <fullName>Neugeschaeft</fullName>
    </customValue>
    <customValue>
        <fullName>ETL-Print</fullName>
    </customValue>
    <customValue>
        <fullName>Cold Call</fullName>
    </customValue>
    <customValue>
        <fullName>Preorder</fullName>
    </customValue>
    <customValue>
        <fullName>Postcard 2020</fullName>
        <isActive>false</isActive>
        <label>Postcard 2020</label>
    </customValue>
    <description>For the convenient use of Lead Attributes: Users can use Keywords instead of IDs</description>
    <masterLabel>LAC Shorthands</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DailyBatcher_test.cls
@isTest public class DailyBatcher_test {

    static TestMethod void test() {
        Account a = new Account(name='test');
        insert a;
        Opportunity o = new Opportunity(Name='test', StageName='New', CloseDate=Date.today(), AccountId=a.Id, LAC_Shorthand__c='Walk-In');
        insert o;
        List<Batch_Object__mdt> Objects = [SELECT DeveloperName FROM Batch_Object__mdt];
        for (Batch_Object__mdt Obj : Objects) database.executeBatch(new dailybatcher(Obj.DeveloperName));
        String jobId = System.schedule('test', '0 0 0 3 9 ? 2022', new DailyBatcher_scheduler());
    }
    
}