force-app/main/default/objects/Contact/fields/Addressee__c.field-meta.xml
<CustomField>
    <fullName>Addressee__c</fullName>
    <inlineHelpText>This field can be selected within Address Builder</inlineHelpText>
    <label>OUTDATED Addressee</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Attention__c.field-meta.xml
<CustomField>
    <fullName>Attention__c</fullName>
    <inlineHelpText>This field can be selected within Address Builder</inlineHelpText>
    <label>OUTDATED Attention</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/classes/ZuoraContactUpdateTest.cls
/**
 * @author keylight
 */
@IsTest
private class ZuoraContactUpdateTest {
	@isTest static void constructer_test() {
		Contact c = new Contact();
		String zId = 'test';
		ZuoraContactUpdate cu = new ZuoraContactUpdate(c, zId);
        System.assertEquals(c, cu.contact);
        System.assertEquals(zId, cu.zuoraId);
    }

    @isTest static void should_return_json() {
		Contact c = new Contact(FirstName='Test', LastName='Test2');
		String zId = 'test';
		ZuoraContactUpdate cu = new ZuoraContactUpdate(c, zId);
		String json = cu.toJson();
        System.assertEquals('{"Description":"","FirstName":"Test","LastName":"Test2"}', json.deleteWhitespace());
    }

     @isTest static void run_send() {
     	Test.setMock(HttpCalloutMock.class, new ZuoraHttpCalloutMock());
		Contact c = new Contact(FirstName='Test', LastName='Test2', Addressee__c='Test', Attention__c='Test');
		String zId = 'test';
		ZuoraContactUpdate cu = new ZuoraContactUpdate(c, zId);
		cu.send();
    }
}