force-app/main/default/objects/Contact/fields/Addressee__c.field-meta.xml
<CustomField>
    <fullName>Addressee__c</fullName>
    <inlineHelpText>This field can be selected within Address Builder</inlineHelpText>
    <label>OUTDATED Addressee</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Attention__c.field-meta.xml
<CustomField>
    <fullName>Attention__c</fullName>
    <inlineHelpText>This field can be selected within Address Builder</inlineHelpText>
    <label>OUTDATED Attention</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Zuora_BillTo_Contact__c.field-meta.xml
<CustomField>
    <fullName>Zuora_BillTo_Contact__c</fullName>
    <description>Stakeholder: Account Management &amp; Finance</description>
    <formula>Id  =  Account.SF_BillTo_Contact__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Is this contact the billing contact for its Account? This means that the address in this contact needs to be complete and up to date. Checked automatically, when the contact got selected as billing contact on the Account</inlineHelpText>
    <label>Billing Contact (Zuora)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Zuora_SoldTo_Contact__c.field-meta.xml
<CustomField>
    <fullName>Zuora_SoldTo_Contact__c</fullName>
    <description>Stakeholder: Account Management &amp; Finance</description>
    <formula>Id =  Account.SF_SoldTo_Contact__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Is this contact the shipping contact for its Account? This means that the address in this contact needs to be complete and up to date. Checked automatically, when the contact got selected as shipping contact on the Account</inlineHelpText>
    <label>Shipping Contact (Zuora)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/classes/ZuoraContactUpdateUtil.cls
/**
 * @author keylight
 */
public with sharing class ZuoraContactUpdateUtil {/*
	public static List<ZuoraContactUpdate> getZuoraContactUpdates(Contact oldContact, Contact newContact, List<Zuora__CustomerAccount__c> billingAccounts) {
		List<ZuoraContactUpdate> contactUpdates = new List<ZuoraContactUpdate>();
		if (ZuoraContactUpdateUtil.contactNeedsUpdate(oldContact, newContact)) {
			for (Zuora__CustomerAccount__c billingAccount : billingAccounts) {
	        	if (newContact.Zuora_BillTo_Contact__c && billingAccount.Zuora__Account__c == newContact.AccountId) {
            		contactUpdates.add(new ZuoraContactUpdate(newContact, billingAccount.Zuora__BillToId__c));
	            }
	            if (newContact.Zuora_SoldTo_Contact__c && billingAccount.Zuora__Account__c == newContact.AccountId) {
	            	contactUpdates.add(new ZuoraContactUpdate(newContact, billingAccount.Zuora__SoldToId__c));
	        	}
	        }    
        }
        return contactUpdates;
	}

	@TestVisible
	private static Boolean contactNeedsUpdate(Contact c1, Contact c2) {
        for (String field : contactFields) {
            if (c1.get(field) != c2.get(field)) return true;
        }
        return false;
    }

	private static List<String> contactFields = new List<String>{
	    'Attention__c',
	    'Addressee__c',
	    'Description',
	    'FirstName',
	    'LastName',
	    'MailingStreet',
	    'MailingPostalCode',
	    'MailingCity',
	    'MailingCountry',
	    'Email'
    };*/
}