force-app/main/default/objects/Contact/fields/DoubleOptIn__c.field-meta.xml
<CustomField>
    <fullName>DoubleOptIn__c</fullName>
    <label>Marketing Double Opt-In</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Refused</fullName>
            </value>
            <value>
                <fullName>Verbal Ok</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Lead/fields/DoubleOptIn__c.field-meta.xml
<CustomField>
    <fullName>DoubleOptIn__c</fullName>
    <label>Marketing Double Opt-In</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Refused</fullName>
            </value>
            <value>
                <fullName>Verbal Ok</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/LAC_Shorthand__c.field-meta.xml
<CustomField>
    <fullName>LAC_Shorthand__c</fullName>
    <description>Stakeholder: CDS, BI, MKT, Sales https://jira.orderbird.com/browse/CDS-138</description>
    <inlineHelpText>Select the relevant Lead Attribution Combo. If it is not on the list use the field LAC ID instead</inlineHelpText>
    <label>LAC Shorthand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LAC_Shorthands</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/LAC_Shorthands.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Walk-In</fullName>
    </customValue>
    <customValue>
        <fullName>Hotline</fullName>
    </customValue>
    <customValue>
        <fullName>Personal Network</fullName>
    </customValue>
    <customValue>
        <fullName>E-mail</fullName>
    </customValue>
    <customValue>
        <fullName>CRC - Referral of successor</fullName>
    </customValue>
    <customValue>
        <fullName>CRC - E-mail</fullName>
    </customValue>
    <customValue>
        <fullName>CRC - Hotline</fullName>
    </customValue>
    <customValue>
        <fullName>CRC - Webform</fullName>
    </customValue>
    <customValue>
        <fullName>Referral by Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Research - Public Register</fullName>
    </customValue>
    <customValue>
        <fullName>Research - Other</fullName>
    </customValue>
    <customValue>
        <fullName>Chat</fullName>
    </customValue>
    <customValue>
        <fullName>Facebook</fullName>
    </customValue>
    <customValue>
        <fullName>Twitter</fullName>
    </customValue>
    <customValue>
        <fullName>Instagram</fullName>
    </customValue>
    <customValue>
        <fullName>Kassensystemevergleich.de</fullName>
    </customValue>
    <customValue>
        <fullName>Kassen-Vergleich.com</fullName>
    </customValue>
    <customValue>
        <fullName>Companeo</fullName>
    </customValue>
    <customValue>
        <fullName>Facebook Scraper</fullName>
    </customValue>
    <customValue>
        <fullName>Toques de restauration</fullName>
    </customValue>
    <customValue>
        <fullName>Chardasso</fullName>
    </customValue>
    <customValue>
        <fullName>Trade Register Scraper</fullName>
    </customValue>
    <customValue>
        <fullName>TradingTwins</fullName>
    </customValue>
    <customValue>
        <fullName>Outbound Texting</fullName>
    </customValue>
    <customValue>
        <fullName>my.ob Reg</fullName>
    </customValue>
    <customValue>
        <fullName>Neugeschaeft</fullName>
    </customValue>
    <customValue>
        <fullName>ETL-Print</fullName>
    </customValue>
    <customValue>
        <fullName>Cold Call</fullName>
    </customValue>
    <customValue>
        <fullName>Preorder</fullName>
    </customValue>
    <customValue>
        <fullName>Postcard 2020</fullName>
        <isActive>false</isActive>
        <label>Postcard 2020</label>
    </customValue>
    <description>For the convenient use of Lead Attributes: Users can use Keywords instead of IDs</description>
    <masterLabel>LAC Shorthands</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DOI_Sync_test.cls
@isTest public class DOI_Sync_test {

    Static TestMethod void test1() {
        DOI_Sync_scheduler p = new DOI_Sync_scheduler();
        String sch = '0 12 00 * * ?';
        system.schedule('DOI_Sync', sch, p);
    }
    
    Static TestMethod void test2() {
        insert new Contact(Lastname = 'test', Firstname = 'test', Email = 'test@test.com');
        insert new Lead(Company = 'test', Lastname = 'test', Firstname = 'test', Email = 'test@test.com', DoubleOptIn__c = 'Verbal Ok', CountryCode = 'DE', Phone = '+4915134567890', LAC_Shorthand__c = 'Hotline');
        System.enqueueJob(new DOI_Sync());
    }
}