force-app/main/default/objects/Contact/fields/PartnerID__c.field-meta.xml
<CustomField>
    <fullName>PartnerID__c</fullName>
    <description>Stakholder: PaM</description>
    <externalId>true</externalId>
    <inlineHelpText>What is this contacts ID as an orderbird Partner? Only to be used for partner contacts!</inlineHelpText>
    <label>Partner ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Lead/fields/PartnerID__c.field-meta.xml
<CustomField>
    <fullName>PartnerID__c</fullName>
    <description>Stakeholder: PaM // potential later use: the ID of the Partner who send us the lead; requires workflow to transfer this information into &quot;Partner Contact&quot;</description>
    <inlineHelpText>What is the ID of the Partner who send us this lead? Automatically looks up the contact and populates the according field here on the lead</inlineHelpText>
    <label>Partner ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/ReferralContact__c.field-meta.xml
<CustomField>
    <fullName>ReferralContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Stakeholder: PaM &amp; Sales (CRC)</description>
    <inlineHelpText>Who referred this lead to us? Filled in by leads or sales as soon as known, preferably on creation</inlineHelpText>
    <label>Referral Contact</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 OR 2) AND 3</booleanFilter>
        <filterItems>
            <field>Contact.Ambassador_ID__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>Contact.PartnerID__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>Contact.Email</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <infoMessage>Please make sure to add the Ambassador ID to the Ambassador contact</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Leads (as Ambassador)</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LeadAssignContact.cls
/**
 * @author joern
 * @description Assign a partner contact if partnerID is set in lead (LeadAssignTrigger)
 *
 * @todo refactoring: to fit into LeadHandler behavior
 */
public with sharing class LeadAssignContact {

    @TestVisible
	private Map<String, Lead> leadsWithPartnerID = new Map<String, Lead>();

	public LeadAssignContact(Lead[] leads) {
        if(leads != null) {
		    prepare(leads);
        }
	}

	/**
	 * @description Assign referral contacts based on PartnerId__c field (beforeInsert/Update trigger)
	 */
	public void assign() {
		Set<String> partnerIDs = leadsWithPartnerID.keySet();
		for (Contact c : [SELECT Id, PartnerID__c FROM Contact WHERE PartnerID__c in :partnerIDs]) {
			Lead lead = leadsWithPartnerID.get(c.PartnerID__c);
			lead.ReferralContact__c = c.Id;
		}
	}

	private void prepare(Lead[] leads) {
		for (Lead lead : leads) {
			String partnerID = lead.PartnerID__c;
			if(!String.isBlank(partnerID)) {
				leadsWithPartnerID.put(partnerID, lead);
			}
		}
	}
}