force-app/main/default/objects/Contact/fields/PartnerID__c.field-meta.xml
<CustomField>
    <fullName>PartnerID__c</fullName>
    <description>Stakholder: PaM</description>
    <externalId>true</externalId>
    <inlineHelpText>What is this contacts ID as an orderbird Partner? Only to be used for partner contacts!</inlineHelpText>
    <label>Partner ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Lead/fields/PartnerID__c.field-meta.xml
<CustomField>
    <fullName>PartnerID__c</fullName>
    <description>Stakeholder: PaM // potential later use: the ID of the Partner who send us the lead; requires workflow to transfer this information into &quot;Partner Contact&quot;</description>
    <inlineHelpText>What is the ID of the Partner who send us this lead? Automatically looks up the contact and populates the according field here on the lead</inlineHelpText>
    <label>Partner ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/ReferralContact__c.field-meta.xml
<CustomField>
    <fullName>ReferralContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Stakeholder: PaM &amp; Sales (CRC)</description>
    <inlineHelpText>Who referred this lead to us? Filled in by leads or sales as soon as known, preferably on creation</inlineHelpText>
    <label>Referral Contact</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 OR 2) AND 3</booleanFilter>
        <filterItems>
            <field>Contact.Ambassador_ID__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>Contact.PartnerID__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>Contact.Email</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <infoMessage>Please make sure to add the Ambassador ID to the Ambassador contact</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Leads (as Ambassador)</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LeadAssignContactTest.cls
/**
 * @author joern
 */
@isTest
private class LeadAssignContactTest {
	@isTest static void should_assign_reverral_contact() {
		Contact[] contacts = new List<Contact>{
			new Contact(LastName = 'LastName1', PartnerID__c = '1234'),
			new Contact(LastName = 'LastName2', PartnerID__c = '2345'),
			new Contact(LastName = 'LastName3', PartnerID__c = '3456')
		};
		insert contacts;
		Lead lead1 = new Lead(PartnerID__c = '1234');
		Lead lead2 = new Lead(PartnerID__c = '3456');
		Lead lead3 = new Lead(PartnerID__c = '2345');
		Lead lead4 = new Lead();
		LeadAssignContact lacObj = new LeadAssignContact(new List<Lead>{lead1, lead2, lead3, lead4});
		lacObj.assign();
		System.assertEquals(contacts[0].Id, lead1.ReferralContact__c);
		System.assertEquals(contacts[2].Id, lead2.ReferralContact__c);
		System.assertEquals(contacts[1].Id, lead3.ReferralContact__c);
		System.assertEquals(null, lead4.ReferralContact__c);
	}


	@isTest static void should_not_assign_reverral_contact() {
		Lead lead1 = new Lead(PartnerID__c = '1234');
		Lead lead2 = new Lead();
		Lead lead3 = new Lead(PartnerID__c = '2345');
		LeadAssignContact lacObj = new LeadAssignContact(new List<Lead>{lead1});
		lacObj.assign();
		System.assertEquals(null, lead1.ReferralContact__c);
		System.assertEquals(null, lead2.ReferralContact__c);
		System.assertEquals(null, lead3.ReferralContact__c);
	}

	@isTest static void should_not_throw_exception() {
		LeadAssignContact lacObj = new LeadAssignContact(null);
		lacObj.assign();
        System.assertEquals(lacObj.leadsWithPartnerID.size(), 0);
	}
}