force-app/main/default/objects/SFUrls__c/SFUrls__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>SFUrls</label>
</CustomObject>

force-app/main/default/objects/SFUrls__c/fields/BaseUrl__c.field-meta.xml
<CustomField>
    <fullName>BaseUrl__c</fullName>
    <label>BaseUrl</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SalesforceUrlManager.cls
public class SalesforceUrlManager {
	public static String getSalesforceInstanceUrl() {
		List<SFUrls__c> urls = [SELECT BaseUrl__c FROM SFUrls__c WHERE Name='Salesforce' LIMIT 1];
		return SalesforceUrlManager.getBaseUrl(urls);
    }

    @TestVisible
    private static String getBaseUrl(List<SFUrls__c> urls) {
    	if (urls.isEmpty()) return null;
		SFUrls__c url = urls[0];
        return url.BaseUrl__c;
    }
}