force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>2.0</description>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OBInvoice__c/OBInvoice__c.object-meta.xml
<CustomObject>
    <label>OB Invoice</label>
    <nameField>
        <label>Invoice (New) Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OB Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OBInvoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Invoices_New</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LAC_Shorthand__c.field-meta.xml
<CustomField>
    <fullName>LAC_Shorthand__c</fullName>
    <description>Stakeholder: CDS, BI, MKT, Sales https://jira.orderbird.com/browse/CDS-138</description>
    <inlineHelpText>Select the relevant Lead Attribution Combo. If it is not on the list use the field LAC ID</inlineHelpText>
    <label>LAC Shorthand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LAC_Shorthands</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Send_Template_Folder__c/Send_Template_Folder__c.object-meta.xml
<CustomObject>
    <label>Send Template Folder</label>
    <nameField>
        <label>Send Template Folder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Send Template Folders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SendTemplate__c/SendTemplate__c.object-meta.xml
<CustomObject>
    <label>Send Template</label>
    <nameField>
        <label>Send Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Send Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SendTemplate__c/fields/AdminName__c.field-meta.xml
<CustomField>
    <fullName>AdminName__c</fullName>
    <label>Admin Name</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SendTemplate__c/fields/Folder__c.field-meta.xml
<CustomField>
    <fullName>Folder__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Folder</label>
    <referenceTo>Send_Template_Folder__c</referenceTo>
    <relationshipLabel>Send Templates</relationshipLabel>
    <relationshipName>Send_Templates</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SendTemplate__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/SendTemplate__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Case</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>MyObVenue</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>BigDataAlert__c</fullName>
            </value>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>Joint_Sales__c</fullName>
            </value>
            <value>
                <fullName>HardwareFulfilment__c</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>OBInvoice</fullName>
            </value>
            <value>
                <fullName>P148Letter__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/LAC_Shorthands.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Walk-In</fullName>
    </customValue>
    <customValue>
        <fullName>Hotline</fullName>
    </customValue>
    <customValue>
        <fullName>Personal Network</fullName>
    </customValue>
    <customValue>
        <fullName>E-mail</fullName>
    </customValue>
    <customValue>
        <fullName>CRC - Referral of successor</fullName>
    </customValue>
    <customValue>
        <fullName>CRC - E-mail</fullName>
    </customValue>
    <customValue>
        <fullName>CRC - Hotline</fullName>
    </customValue>
    <customValue>
        <fullName>CRC - Webform</fullName>
    </customValue>
    <customValue>
        <fullName>Referral by Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Research - Public Register</fullName>
    </customValue>
    <customValue>
        <fullName>Research - Other</fullName>
    </customValue>
    <customValue>
        <fullName>Chat</fullName>
    </customValue>
    <customValue>
        <fullName>Facebook</fullName>
    </customValue>
    <customValue>
        <fullName>Twitter</fullName>
    </customValue>
    <customValue>
        <fullName>Instagram</fullName>
    </customValue>
    <customValue>
        <fullName>Kassensystemevergleich.de</fullName>
    </customValue>
    <customValue>
        <fullName>Kassen-Vergleich.com</fullName>
    </customValue>
    <customValue>
        <fullName>Companeo</fullName>
    </customValue>
    <customValue>
        <fullName>Facebook Scraper</fullName>
    </customValue>
    <customValue>
        <fullName>Toques de restauration</fullName>
    </customValue>
    <customValue>
        <fullName>Chardasso</fullName>
    </customValue>
    <customValue>
        <fullName>Trade Register Scraper</fullName>
    </customValue>
    <customValue>
        <fullName>TradingTwins</fullName>
    </customValue>
    <customValue>
        <fullName>Outbound Texting</fullName>
    </customValue>
    <customValue>
        <fullName>my.ob Reg</fullName>
    </customValue>
    <customValue>
        <fullName>Neugeschaeft</fullName>
    </customValue>
    <customValue>
        <fullName>ETL-Print</fullName>
    </customValue>
    <customValue>
        <fullName>Cold Call</fullName>
    </customValue>
    <customValue>
        <fullName>Preorder</fullName>
    </customValue>
    <customValue>
        <fullName>Postcard 2020</fullName>
        <isActive>false</isActive>
        <label>Postcard 2020</label>
    </customValue>
    <description>For the convenient use of Lead Attributes: Users can use Keywords instead of IDs</description>
    <masterLabel>LAC Shorthands</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/EmailSenderTest.cls
@isTest(seeAllData=true) public class EmailSenderTest {

    static TestMethod void test1() {
        EmailMessage EM = [SELECT Id, MessageDate, RelatedToId, CreatedById, Subject, Key__c FROM EmailMessage WHERE RelatedToId != null ORDER BY CreatedDate DESC LIMIT 1];
        Contact c = [SELECT Id FROM Contact ORDER BY CreatedDate LIMIT 1];
        EM.Key__c = EncodingUtil.base64Encode(Blob.valueOf(String.valueOf(Math.random())+','+c.Id));
        update EM;
        EmailSender.notifyOpen(new List<Id>{ EM.Id });
        Messaging.InboundEmail email = new Messaging.InboundEmail();
        Messaging.InboundEnvelope envelope = new Messaging.InboundEnvelope();
        email.plainTextBody = JSON.serialize(new EmailSender.NotifyEmailWrapper(em, c, 'Opportunity'));
        EmailNotifyHandler catcher = new EmailNotifyHandler();
        Messaging.InboundEmailResult result = catcher.handleInboundEmail(email, envelope);
    }
    
    static TestMethod void test2() {
        Account a = new Account(name='test');
        insert a;
        Contact c = new Contact(lastname='test',accountid=a.id,email='test@test.com');
        insert c;
        Opportunity o = new Opportunity(LAC_Shorthand__c='Walk-in',name='test',closedate=date.today(),stagename='New',accountid=a.Id);
        insert o;
        Invoice__c i = new Invoice__c(Account__c=a.Id);
        insert i;
        OBInvoice__c n = new OBInvoice__c(ExternalId__c='x');
        insert n;
        Quote q = new Quote(OpportunityId=o.Id,name='test');
        insert q;
        Case cc = new Case(AccountId = a.Id);
        insert cc;
        EmailSender.sendAsyncEmail(o.Id, JSON.serialize(new List<String>{c.Id}), '[]', 'EmailSubject', 'Email %%!Account.Name%% Text', '[]', null, null, 'German', true);
        EmailSender.sendAsyncEmail(i.Id, JSON.serialize(new List<String>{c.Id}), '[]', 'EmailSubject', 'Email %%!Account__r.Name%% Text', '[]', null, null, 'German', true);
        EmailSender.sendAsyncEmail(n.Id, JSON.serialize(new List<String>{c.Id}), '[]', 'EmailSubject', 'Email %%!Name%% Text', '[]', null, null, 'German', true);
        EmailSender.sendAsyncEmail(q.Id, JSON.serialize(new List<String>{c.Id}), '[]', 'EmailSubject', 'Email %%!Account.Name%% Text', '[]', null, null, 'German', true);
        EmailSender.sendCaseEmail(cc.Id, JSON.serialize(new List<String>{c.Id}), '[]', 'EmailSubject', 'Email %%!Account.Name%% Text', '[]', 'German', true, true);
        system.debug(json.serialize(EmailSender.previewEmail(cc.Id, JSON.serialize(new List<String>{c.Id}), 'EmailSubject', 'Email %%!Account.Name%% Text', 'German')));
    }
    
    static TestMethod void test3() {
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.params.put('id','test');
        RestContext.request = req;
        RestContext.response = res;
        EmailImageAPI.emailOpen();
    }
    
    static TestMethod void test4() {
        Send_Template_Folder__c stf = new Send_Template_Folder__c(name='test');
        insert stf;
        SendTemplate__c st = new SendTemplate__c(folder__c=stf.id,adminname__c='test',subject__c='test',message__c='test',object__c='Opportunity');
        insert st;
        Account a = new Account(name='test');
        insert a;
        Contact c = new Contact(lastname='test',accountid=a.id,email='test@test.com');
        insert c;
        Opportunity o = new Opportunity(LAC_Shorthand__c='Walk-in',name='test',closedate=date.today(),stagename='New',accountid=a.Id);
        insert o;
        EmailAutomater.AutomatedTemplateEmail(new List<EmailAutomater.EmailAutomationRequest>{new EmailAutomater.EmailAutomationRequest(c.Id,o.Id,'test')});
        system.debug(json.serialize(EmailSender.templateSearch('te', null,new List<String>{'Opportunity','German'})));
        system.debug(EmailSender.getAllTemplates('Opportunity'));
    }
    
}