force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/LAC_Shorthand__c.field-meta.xml
<CustomField>
    <fullName>LAC_Shorthand__c</fullName>
    <description>Stakeholder: CDS, BI, MKT, Sales https://jira.orderbird.com/browse/CDS-138</description>
    <inlineHelpText>Select the relevant Lead Attribution Combo. If it is not on the list use the field LAC ID</inlineHelpText>
    <label>LAC Shorthand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LAC_Shorthands</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductBundle__c/ProductBundle__c.object-meta.xml
<CustomObject>
    <label>Product Bundle</label>
    <nameField>
        <label>Product Bundle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Bundles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/LAC_Shorthands.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Walk-In</fullName>
    </customValue>
    <customValue>
        <fullName>Hotline</fullName>
    </customValue>
    <customValue>
        <fullName>Personal Network</fullName>
    </customValue>
    <customValue>
        <fullName>E-mail</fullName>
    </customValue>
    <customValue>
        <fullName>CRC - Referral of successor</fullName>
    </customValue>
    <customValue>
        <fullName>CRC - E-mail</fullName>
    </customValue>
    <customValue>
        <fullName>CRC - Hotline</fullName>
    </customValue>
    <customValue>
        <fullName>CRC - Webform</fullName>
    </customValue>
    <customValue>
        <fullName>Referral by Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Research - Public Register</fullName>
    </customValue>
    <customValue>
        <fullName>Research - Other</fullName>
    </customValue>
    <customValue>
        <fullName>Chat</fullName>
    </customValue>
    <customValue>
        <fullName>Facebook</fullName>
    </customValue>
    <customValue>
        <fullName>Twitter</fullName>
    </customValue>
    <customValue>
        <fullName>Instagram</fullName>
    </customValue>
    <customValue>
        <fullName>Kassensystemevergleich.de</fullName>
    </customValue>
    <customValue>
        <fullName>Kassen-Vergleich.com</fullName>
    </customValue>
    <customValue>
        <fullName>Companeo</fullName>
    </customValue>
    <customValue>
        <fullName>Facebook Scraper</fullName>
    </customValue>
    <customValue>
        <fullName>Toques de restauration</fullName>
    </customValue>
    <customValue>
        <fullName>Chardasso</fullName>
    </customValue>
    <customValue>
        <fullName>Trade Register Scraper</fullName>
    </customValue>
    <customValue>
        <fullName>TradingTwins</fullName>
    </customValue>
    <customValue>
        <fullName>Outbound Texting</fullName>
    </customValue>
    <customValue>
        <fullName>my.ob Reg</fullName>
    </customValue>
    <customValue>
        <fullName>Neugeschaeft</fullName>
    </customValue>
    <customValue>
        <fullName>ETL-Print</fullName>
    </customValue>
    <customValue>
        <fullName>Cold Call</fullName>
    </customValue>
    <customValue>
        <fullName>Preorder</fullName>
    </customValue>
    <customValue>
        <fullName>Postcard 2020</fullName>
        <isActive>false</isActive>
        <label>Postcard 2020</label>
    </customValue>
    <description>For the convenient use of Lead Attributes: Users can use Keywords instead of IDs</description>
    <masterLabel>LAC Shorthands</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/QuoteBuilderTest.cls
@isTest(SeeAllData=true)
public class QuoteBuilderTest {

    @isTest static void test1() {
        Account a = new Account(name='test');
        insert a;
        SubscriptionPickerController.getSubscriptionsFromCase(a.Id);
        Boolean b = NewQuoteController.getAcctMgmtPerm();
    }
    
    @isTest static void test2() {
        Account a = new Account(name='test');
        insert a;
        Opportunity o = new Opportunity(Name='test', StageName='New', CloseDate=Date.today(), AccountId=a.Id, LAC_Shorthand__c='Walk-In');
        insert o;
        NewQuoteController.JItem jitem1 = new NewQuoteController.JItem();
        jitem1.isBundle = false;
        jitem1.isBundleItem = false;
        NewQuoteController.JDetail jdetail1 = new NewQuoteController.JDetail();
        jdetail1.PayByInstalment = false;
        jdetail1.WireFirstPayment = false;
        NewQuoteController.JItemList jitemlist = new NewQuoteController.JItemList();
        jitemlist.Items = new List<NewQuoteController.JItem>{ jitem1 };
        jitemlist.Details = jdetail1;
        map<id, ProductBundle__c> bundlemap = new map<id, ProductBundle__c>();
        for (ProductBundle__c bundle : ((NewQuoteController.JPricingWrapper)JSON.deserialize(NewQuoteController.getPrices('EUR'), NewQuoteController.JPricingWrapper.class)).Bundles){
            bundlemap.put(bundle.id, bundle);
        }
        map<id, PricebookEntry> pricemap = new map<id, PricebookEntry>();
        for (PricebookEntry pm : ((NewQuoteController.JPricingWrapper)JSON.deserialize(NewQuoteController.getPrices('EUR'), NewQuoteController.JPricingWrapper.class)).Pricebook){
            pricemap.put(pm.id, pm);
        }
        NewQuoteController.upsertQuote(
            JSON.serialize(jitemlist),
            JSON.serialize(bundlemap),
            JSON.serialize(pricemap),
            'null',
            o.Id,
            null,
            'EUR'
        );
    }

    @isTest static void test3() {
        Account a = new Account(name='test');
        insert a;
        Opportunity o = new Opportunity(Name='test', StageName='New', CloseDate=Date.today(), AccountId=a.Id, LAC_Shorthand__c='Walk-In');
        insert o;
        Quote q = new Quote(OpportunityId=o.Id,Name='test');
        insert q;
        NewQuoteController.JItem jitem1 = new NewQuoteController.JItem();
        jitem1.isBundle = false;
        jitem1.isBundleItem = false;
        NewQuoteController.JDetail jdetail1 = new NewQuoteController.JDetail();
        jdetail1.PayByInstalment = false;
        jdetail1.WireFirstPayment = false;
        jdetail1.PayPalLink = false;
        NewQuoteController.JItemList jitemlist = new NewQuoteController.JItemList();
        jitemlist.Items = new List<NewQuoteController.JItem>{ jitem1 };
        jitemlist.Details = jdetail1;
        map<id, ProductBundle__c> bundlemap = new map<id, ProductBundle__c>();
        for (ProductBundle__c bundle : ((NewQuoteController.JPricingWrapper)JSON.deserialize(NewQuoteController.getPrices('EUR'), NewQuoteController.JPricingWrapper.class)).Bundles){
            bundlemap.put(bundle.id, bundle);
        }
        map<id, PricebookEntry> pricemap = new map<id, PricebookEntry>();
        for (PricebookEntry pm : ((NewQuoteController.JPricingWrapper)JSON.deserialize(NewQuoteController.getPrices('EUR'), NewQuoteController.JPricingWrapper.class)).Pricebook){
            pricemap.put(pm.id, pm);
        }
        NewQuoteController.upsertQuote(
            JSON.serialize(jitemlist),
            JSON.serialize(bundlemap),
            JSON.serialize(pricemap),
            'null',
            o.Id,
            q.Id,
            'EUR'
        );
    }
    
    @isTest static void test4() {
        Account a = new Account(name='test');
        insert a;
        Opportunity o = new Opportunity(Name='test', StageName='New', CloseDate=Date.today(), AccountId=a.Id, LAC_Shorthand__c='Walk-In');
        insert o;
        Quote q = new Quote(OpportunityId=o.Id,Name='test');
        insert q;
        NewQuoteController.forecastInvoice(q.Id);
        String s = NewQuoteController.getCatalog('EUR', a.Id);
        s = NewQuoteController.getContacts(q.Id, 'Quote');
        s = NewQuoteController.getQuoteLineItems(q.Id);
        s = NewQuoteController.getSubscriptionLineItems(o.Id);
        s = NewQuoteController.getSendTemplates('Quote');
        NewQuoteController.JBundle JBundle = new NewQuoteController.JBundle();
        boolean b = NewQuoteController.getBamboraEligibility(q.ID);
    }
    
    /*@isTest static void pdfemail() {
        Account a = new Account(name='test');
        insert a;
        Contact c = new Contact(AccountId=a.Id, Lastname='test', Email='bart.collins@orderbird.com');
        insert c;
        String ContactIdsString = JSON.serialize(new List<String>{c.Id});
        Opportunity o = new Opportunity(Name='test', StageName='New', CloseDate=Date.today(), AccountId=a.Id, LAC_Shorthand__c='Walk-In');
        insert o;
        Quote q = new Quote(OpportunityId=o.Id,Name='test');
        insert q;
        String OWEAId = [SELECT Id FROM OrgWideEmailAddress][0].Id;
        Boolean b = NewQuoteController.sendPdfEmails(
            String.valueOf(q.Id), 
            ContactIdsString, 
            '[]',
            'Quote',
            'EmailSubject',
            'EmailText',
            '[]',
            OWEAId
        );
    }*/
    
}