force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/MyObVenue__c/MyObVenue__c.object-meta.xml
<CustomObject>
    <label>MyOb Venue</label>
    <nameField>
        <displayFormat>MyOb-{000000}</displayFormat>
        <label>MyOb Venue</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MyOb Venues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MyObVenue__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>MyOrderbird_Log_ons</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/MyObVenue__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created only for Customers that buy a MINI in Shopify</description>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>MyOb Venues</relationshipLabel>
    <relationshipName>MyOb_Venues</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MyObVenue__c/fields/MyOrderbirdId__c.field-meta.xml
<CustomField>
    <fullName>MyOrderbirdId__c</fullName>
    <externalId>true</externalId>
    <label>MyOrderbird Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/CustomerDataAPITest.cls
@isTest
public class CustomerDataAPITest {
  @TestSetup
  static void Data() {
    Account a = new Account(name = 'TestKonto');
    insert a;
    contact c = new Contact(
      FirstName = 'Jose',
      lastname = 'Canseco',
      AccountId = a.id
    );
    insert c;
    Lead l = new Lead(Lastname = 'TestName', Company = 'VenueName');
    insert l;
    MyObVenue__c v = new MyObVenue__c(Contact__c = c.id);
    insert v;
    CryptAES cs = new CryptAES('AES256');
    String Token = cs.encrypt(v.Id);
    v.Token__c = Token;
    update v;
  }
  
  @isTest
  static void testPutCall() {
    Account a = new Account(Name = 'Shopify');
    insert a;
    Contact c = new Contact(Lastname = 'PalceholderName', AccountId = a.id);
    insert c;
    Lead l = new Lead(LastName = 'TestName', Company = 'MINI Venue');
    insert l;
    MyObVenue__c v = new MyObVenue__c(
      Contact__c = c.id,
      Lead__c = l.id,
      myOrderbirdId__c = '12345'
    );
    insert v;
    RestRequest req = new RestRequest();
    RestResponse res = new RestResponse();
    req.requestURI = '/services/apexrest/customerdata';
    req.httpMethod = 'PUT';
    // req.addHeader('Auth', 'bearer 1234');
    req.requestBody = Blob.valueof(
      '{"CustomerName":"testCompany","email":"dummy@test.com","applicationId":"' +
      v.id +
      '"}'
    );
    RestContext.request = req;
    RestContext.response = res;
    CustomerDataAPI.updateCustomerData();
  }
  @isTest
  static void testPostCall() {
    MyObVenue__c v = [SELECT token__c FROM MyObVenue__c WHERE token__c!=null LIMIT 1];
    String token = v.token__c;
    RestRequest req = new RestRequest();
    RestResponse res = new RestResponse();
    req.requestURI = '/services/apexrest/customerdata';
    req.httpMethod = 'POST';
    req.addHeader('Auth', 'bearer 1234');
    req.requestBody = Blob.valueof('{"name":"test","email":"test@test.com","keyToken":"' +
    token +
    '"}'
    );
    RestContext.request = req;
    RestContext.response = res;
    CustomerDataAPI.registerMyObVenue();
  }

  @isTest
  static void testGetCall() {
    Account a = new Account(Name = 'Shopify');
    insert a;
    Contact c = new Contact(Lastname = 'PalceholderName', AccountId = a.id);
    insert c;
    Lead l = new Lead(LastName = 'TestName', Company = 'MINI Venue');
    insert l;
    MyObVenue__c v = new MyObVenue__c(Contact__c = c.id, Lead__c = l.id);
    insert v;
    CryptAES cs = new CryptAES('AES256');
    String Token = cs.encrypt(v.Id);
    v.Token__c = Token;
    update v;
    RestRequest req = new RestRequest();
    RestResponse res = new RestResponse();
    req.requestURI = '/services/apexrest/customerdata';
    req.addHeader('Auth', 'bearer 1234');
    req.httpMethod = 'GET';
    RestContext.request = req;
    RestContext.response = res;
    CustomerDataAPI.getCustomerInfo(); //test Request without parameters

    req.params.put('keyToken', Token);
    RestContext.request = req;
    CustomerDataAPI.getCustomerInfo(); //test Request with parameters

    String body = res.responseBody.toString();
    Map<String, Object> m = (Map<String, Object>) JSON.deserializeUntyped(body);
    System.assertEquals(v.id, m.get('ApplicationId'));

    // change name of test account to test else logic in the ResponseWrapper method of the class
    a.Name = 'NoShopify';
    update a;
    CustomerDataAPI.getCustomerInfo();
  }
}