force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/MyObVenue__c/MyObVenue__c.object-meta.xml
<CustomObject>
    <label>MyOb Venue</label>
    <nameField>
        <displayFormat>MyOb-{000000}</displayFormat>
        <label>MyOb Venue</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MyOb Venues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MyObVenue__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>MyOrderbird_Log_ons</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/MyObVenue__c/fields/MyOrderbirdId__c.field-meta.xml
<CustomField>
    <fullName>MyOrderbirdId__c</fullName>
    <externalId>true</externalId>
    <label>MyOrderbird Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/FiscalizationAPI_test.cls
@isTest public class FiscalizationAPI_test {

    static TestMethod void test() {
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/fiscalize';
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof('{"venueId":"123"}');
        RestContext.request = req;
        RestContext.response = res;
        FiscalizationAPI.RevokeTSE();
        FiscalizationAPI.WizardComplete();
        Account a = new Account(name='test');
        insert a;
        Contact c = new Contact(lastname = 'test', accountId = a.Id);
        insert c;
        insert new MyObVenue__c(contact__c = c.Id, myorderbirdid__c = '123');
        FiscalizationAPI.WizardComplete();
    }
}