force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <label>Payment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/NeedsAttention__c.field-meta.xml
<CustomField>
    <fullName>NeedsAttention__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Needs Attention</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SubmitPaymentGateway.cls
public class SubmitPaymentGateway {
    
    @future(callout=true)
    public static void SubmitPayment() {
        try {
            Payment__c p = [
                SELECT Id, NeedsAttention__c, ZuoraId__c 
                FROM Payment__c 
                WHERE NeedsAttention__c = TRUE AND ZuoraId__c != null 
                LIMIT 1
            ];
            system.debug(ZuoraAPIManager.callZuoraAPI(
                'gateway-settlement/payments/' + p.ZuoraId__c + '/settle',
                'POST',
                '{"settledOn": "'+String.valueOf(DateTime.now())+'"}'
            ));
            p.NeedsAttention__c = false;
            update p;
        } catch(exception e) {}
    }
}